import type { Raw } from '../types';

// 1.1 OSI model (25) · 1.2 Appliances, applications and functions (30)
const q: Raw[] = [
  ["1.1","e","osi",
   "A switch forwards frames by reading their destination MAC addresses. At which OSI layer does it make that decision?",
   "Layer 2 – Data link",
   ["Layer 1 – Physical","Layer 3 – Network","Layer 4 – Transport"],
   "Las direcciones MAC (Media Access Control) y las tramas pertenecen a la capa 2 (enlace de datos). Un switch tradicional decide por MAC, así que trabaja en capa 2.",
   ["La capa 1 solo mueve bits por el cable; no lee direcciones.","La capa 3 decide por dirección IP; eso lo hace un router.","La capa 4 trabaja con puertos TCP/UDP, no con MAC."]],

  ["1.1","e","osi,pdu",
   "When TCP is used, what is the protocol data unit (PDU) called at the Transport layer?",
   "Segment",
   ["Frame","Packet","Bit"],
   "En la capa 4 (transporte) la PDU (Protocol Data Unit) de TCP se llama segmento. Con UDP (User Datagram Protocol) se llama datagrama.",
   ["La trama es la PDU de la capa 2.","El paquete es la PDU de la capa 3.","Los bits son la unidad de la capa 1."]],

  ["1.1","m","osi",
   "Which OSI layer is responsible for data formatting, character encoding and encryption so that two systems can understand each other's data?",
   "Layer 6 – Presentation",
   ["Layer 5 – Session","Layer 7 – Application","Layer 4 – Transport"],
   "La capa 6 (presentación) es la 'traductora': formato, codificación, compresión y cifrado.",
   ["La capa 5 abre, mantiene y cierra sesiones; no cambia el formato de los datos.","La capa 7 es la interfaz del programa con la red (HTTP, DNS…); el cifrado se asocia a la 6.","La capa 4 se ocupa de la entrega (puertos, fiabilidad), no del formato."]],

  ["1.1","m","osi",
   "Which OSI layer establishes, maintains and terminates the dialog between two applications?",
   "Layer 5 – Session",
   ["Layer 4 – Transport","Layer 6 – Presentation","Layer 3 – Network"],
   "'Establecer, mantener y terminar' el diálogo es la frase clave de la capa 5 (sesión).",
   ["La capa 4 gestiona la conexión de transporte (puertos, TCP), pero el diálogo entre aplicaciones es la 5.","La capa 6 cambia el formato de los datos, no controla la sesión.","La capa 3 enruta paquetes y no tiene concepto de conversación."]],

  ["1.1","e","osi,devices",
   "A legacy hub repeats every incoming signal out of all its other ports without reading any address. At which OSI layer does a hub operate?",
   "Layer 1 – Physical",
   ["Layer 2 – Data link","Layer 3 – Network","Layer 7 – Application"],
   "Un hub solo regenera la señal eléctrica: no entiende de tramas ni direcciones. Por eso es un dispositivo de capa 1.",
   ["Un dispositivo de capa 2 (como un switch) leería la MAC y no inundaría todo.","La capa 3 exige leer direcciones IP.","La capa 7 es la de las aplicaciones; un hub no entiende ningún protocolo."]],

  ["1.1","e","osi,devices",
   "A device receives packets and forwards them to other subnets by looking at the destination IP address. At which OSI layer is it operating?",
   "Layer 3 – Network",
   ["Layer 2 – Data link","Layer 4 – Transport","Layer 1 – Physical"],
   "Decidir el camino según la IP de destino es enrutar, y enrutar es capa 3 (red). Es lo que hace un router.",
   ["La capa 2 reenvía por MAC dentro de la misma red local.","La capa 4 usa puertos, no direcciones IP.","La capa 1 no lee ninguna dirección."]],

  ["1.1","m","osi,encapsulation",
   "Which sequence correctly shows encapsulation as data moves DOWN the OSI model on the sending host?",
   "Data → Segment → Packet → Frame → Bits",
   ["Data → Packet → Segment → Frame → Bits","Bits → Frame → Packet → Segment → Data","Data → Frame → Packet → Segment → Bits"],
   "Al bajar, cada capa añade su cabecera: la 4 pone puertos (segmento), la 3 pone IPs (paquete), la 2 pone MACs y el FCS (trama) y la 1 lo convierte en bits.",
   ["Invierte segmento y paquete: la cabecera IP va por fuera de la TCP, no al revés.","Es el orden de desencapsulación (subiendo en el receptor), no el de envío.","Pone la trama antes del paquete; la capa 2 envuelve a la 3, no al revés."]],

  ["1.1","m","osi,encapsulation",
   "Which OSI layer adds a trailer containing a Frame Check Sequence (FCS) to the data it encapsulates?",
   "Data link",
   ["Network","Transport","Physical"],
   "La capa 2 (enlace de datos) es la única que añade algo al final: el trailer con el FCS (Frame Check Sequence), que sirve para detectar tramas dañadas.",
   ["La capa 3 solo añade una cabecera IP, sin trailer.","La capa 4 añade una cabecera con puertos, sin trailer.","La capa 1 transmite bits; no añade cabeceras ni trailers."]],

  ["1.1","e","osi,protocols",
   "At which OSI layer do TCP and UDP operate?",
   "Transport",
   ["Network","Session","Data link"],
   "TCP (Transmission Control Protocol) y UDP (User Datagram Protocol) son los dos protocolos de la capa 4 (transporte).",
   ["En la capa 3 están IP e ICMP.","La capa 5 gestiona sesiones, no el transporte de segmentos.","En la capa 2 están Ethernet y las direcciones MAC."]],

  ["1.1","e","osi,protocols",
   "HTTP, DNS and SMTP are examples of protocols that operate at which OSI layer?",
   "Application",
   ["Presentation","Transport","Network"],
   "Son protocolos que usan directamente los programas (web, resolución de nombres, correo): capa 7 (aplicación).",
   ["La capa 6 trata formato y cifrado, no estos protocolos.","En la capa 4 solo están TCP y UDP, que transportan a estos protocolos.","En la capa 3 están IP e ICMP."]],

  ["1.1","m","osi,load-balancer",
   "A load balancer sends requests for /images/* to one server pool and everything else to another. At which OSI layer is it making that decision?",
   "Layer 7",
   ["Layer 3","Layer 4","Layer 2"],
   "Para ver la ruta /images tiene que leer la petición HTTP, que es contenido de aplicación: capa 7.",
   ["Con capa 3 solo vería la IP de destino, igual para todas las rutas.","Con capa 4 vería el puerto 80/443, idéntico para todas las rutas.","Con capa 2 solo vería direcciones MAC."]],

  ["1.1","m","osi,firewall",
   "A traditional stateful firewall permits or denies traffic based on source/destination IP addresses and port numbers. Which OSI layers does it inspect?",
   "Layers 3 and 4",
   ["Layers 1 and 2","Layers 2 and 3","Layers 5 through 7"],
   "Las direcciones IP son capa 3 y los puertos son capa 4. Un firewall stateful clásico mira esas dos capas (y el estado de la conexión TCP, que también es capa 4).",
   ["Las capas 1 y 2 no contienen IPs ni puertos.","Incluye la 3 pero no la 4, y los puertos son capa 4.","Inspeccionar capas 5–7 es propio de un NGFW o un proxy, no de un firewall stateful clásico."]],

  ["1.1","m","osi,troubleshooting",
   "A new server's switch port is up, the switch has learned the server's MAC address, and the server can ping hosts in its own subnet but not in any other subnet. At which layer is the problem MOST likely?",
   "Layer 3",
   ["Layer 1","Layer 2","Layer 7"],
   "Capa 1 y 2 funcionan (puerto arriba, MAC aprendida, ping local OK). Si solo falla salir de la subred, el problema es de enrutamiento: gateway o ruta, capa 3.",
   ["Con un fallo de capa 1 no funcionaría nada, tampoco el ping local.","Con un fallo de capa 2 fallaría también el ping dentro de la misma subred.","Un fallo de capa 7 afectaría a un servicio concreto, no a toda la conectividad con otras subredes."]],

  ["1.1","h","osi,troubleshooting",
   "A user can ping a web server in another subnet, but a capture shows the user's SYN to TCP 443 never receives a SYN-ACK. What is the highest layer confirmed working, and where is the fault?",
   "Layer 3 confirmed; fault at layer 4",
   ["Layer 2 confirmed; fault at layer 3","Layer 4 confirmed; fault at layer 7","Layer 7 confirmed; fault at layer 6"],
   "El ping entre subredes prueba la capa 3. El SYN sin respuesta significa que el saludo TCP (handshake) no se completa: puerto cerrado, servicio caído o un firewall filtrando. Eso es capa 4.",
   ["Un ping que cruza subredes ya confirma la capa 3, no solo la 2.","La capa 4 no está confirmada: el handshake nunca se completó.","No se intercambió ningún dato de aplicación; nada por encima de la capa 3 está confirmado."]],

  ["1.1","m","osi,troubleshooting",
   "A user reaches a web application, the page loads correctly, but the application rejects the user's valid-looking password. At which OSI layer is this problem?",
   "Layer 7",
   ["Layer 3","Layer 4","Layer 6"],
   "Si la página carga, red y transporte funcionan. La contraseña la evalúa el propio programa: es un problema de capa 7 (aplicación).",
   ["La página carga, así que el enrutamiento (capa 3) funciona.","La conexión TCP (capa 4) se estableció, porque la página cargó.","La capa 6 sería un problema de cifrado o formato; aquí el servidor entendió el mensaje y decidió rechazarlo."]],

  ["1.1","h","osi,troubleshooting",
   "A switch interface shows a steadily increasing number of CRC errors. At which OSI layer are these errors DETECTED?",
   "Layer 2",
   ["Layer 1","Layer 3","Layer 4"],
   "El CRC (Cyclic Redundancy Check) se comprueba contra el FCS del final de la trama, y eso es capa 2. La causa suele ser física (cable, interferencia), pero la detección ocurre en capa 2.",
   ["La capa 1 suele ser la causa, pero no sabe de tramas ni puede comprobar el FCS.","La trama dañada se descarta en capa 2 antes de llegar a la 3.","TCP tiene su propio checksum, pero no valida las tramas Ethernet."]],

  ["1.1","m","osi,protocols",
   "At which OSI layer does ICMP, the protocol used by ping, operate?",
   "Network",
   ["Transport","Application","Data link"],
   "ICMP (Internet Control Message Protocol) va dentro de IP y no usa puertos: es capa 3. Que 'ping' sea un programa no lo hace capa 7.",
   ["ICMP no usa puertos ni cabecera TCP/UDP, así que no es capa 4.","ping es la herramienta; el protocolo que viaja por la red es ICMP, de capa 3.","ICMP trabaja con direcciones IP, no MAC."]],

  ["1.1","e","osi,ports",
   "Which OSI layer uses port numbers to identify the application that should receive the data?",
   "Transport",
   ["Network","Data link","Presentation"],
   "Los números de puerto (80, 443, 3389…) están en la cabecera TCP/UDP, que es capa 4 (transporte).",
   ["La capa 3 identifica equipos con IPs, no aplicaciones.","La capa 2 identifica tarjetas de red con MACs.","La capa 6 cambia el formato de los datos; no usa puertos."]],

  ["1.1","m","osi,tcp",
   "Which OSI layer is responsible for segmentation, flow control and retransmitting lost data?",
   "Transport",
   ["Network","Session","Data link"],
   "La capa 4 parte los datos en segmentos, controla el ritmo con ventanas (flow control) y, con TCP, reenvía lo que se pierde.",
   ["La capa 3 enruta paquetes; no reenvía datos perdidos.","La capa 5 gestiona el diálogo, no la fiabilidad de la entrega.","La capa 2 detecta tramas dañadas con el FCS, pero no las retransmite."]],

  ["1.1","e","osi,troubleshooting",
   "A technician troubleshoots by checking cabling and link lights first, then MAC learning, then IP settings, and finally the application. Which approach is this?",
   "Bottom-to-top",
   ["Top-to-bottom","Divide and conquer","Follow the path"],
   "Empezar en la capa 1 y subir capa a capa hasta la 7 es el enfoque bottom-to-top (de abajo arriba).",
   ["Top-to-bottom empieza por la aplicación y baja.","Divide and conquer empieza en una capa intermedia (normalmente la 3) y decide hacia dónde ir.","Follow the path recorre el camino del tráfico salto a salto, no las capas."]],

  ["1.1","h","osi,addressing",
   "As a packet travels from a PC through three routers to a remote server, which addresses are rewritten at every hop?",
   "The source and destination MAC addresses",
   ["The source and destination IP addresses","The TCP source and destination ports","The application payload"],
   "La IP indica el destino final y no cambia en el camino (salvo NAT). La MAC indica 'quién lo lleva en este tramo', así que cada router pone MACs nuevas.",
   ["Las IPs se mantienen de extremo a extremo (sin NAT).","Los puertos TCP no cambian en los saltos de routers normales.","Los routers no modifican el contenido de la aplicación."]],

  ["1.1","m","osi,devices",
   "A multilayer switch is routing traffic between VLAN 10 and VLAN 20. At which OSI layer is it performing this function?",
   "Layer 3",
   ["Layer 2","Layer 4","Layer 1"],
   "Cada VLAN (Virtual LAN) es una red distinta. Pasar tráfico de una a otra es enrutar, y enrutar es capa 3.",
   ["Dentro de una misma VLAN conmuta en capa 2, pero cruzar VLANs exige capa 3.","No hay ninguna decisión basada en puertos.","La capa 1 no toma decisiones de reenvío."]],

  ["1.1","e","osi",
   "Which OSI layer defines voltage levels, connector pinouts and how bits are signaled on the medium?",
   "Physical",
   ["Data link","Network","Presentation"],
   "La capa 1 (física) define lo tangible: señales, conectores, pines y medios.",
   ["La capa 2 organiza los bits en tramas y usa MAC.","La capa 3 trata direcciones lógicas y enrutamiento.","La capa 6 trata formato y cifrado de los datos."]],

  ["1.1","m","osi,devices",
   "Which of the following devices make forwarding decisions at Layer 2? (Choose TWO)",
   ["Switch","Bridge"],
   ["Router","Hub","Layer 7 load balancer"],
   "Switches y bridges reenvían tramas según la dirección MAC de destino: capa 2.",
   ["El router decide por IP: capa 3.","El hub no decide nada: repite bits (capa 1).","Un balanceador de capa 7 decide por contenido de la aplicación."]],

  ["1.1","h","osi,vpn",
   "At which OSI layer does IPsec protect traffic?",
   "Network",
   ["Data link","Transport","Application"],
   "IPsec (Internet Protocol Security) cifra y autentica paquetes IP, así que trabaja en la capa 3 (red). Por eso protege cualquier tráfico que vaya por encima.",
   ["IPsec no trabaja con tramas ni MACs.","TLS trabaja por encima del transporte; IPsec lo hace por debajo, en IP.","IPsec no depende de la aplicación; protege todo el paquete IP."]],

  ["1.2","e","ids-ips,security",
   "A company wants a device placed inline that detects malicious traffic AND automatically blocks it. Which device should it deploy?",
   "IPS",
   ["IDS","Load balancer","Proxy server"],
   "Un IPS (Intrusion Prevention System) va en línea con el tráfico y puede bloquear. Un IDS (Intrusion Detection System) solo detecta y avisa.",
   ["Un IDS solo alerta; no bloquea.","Un balanceador reparte carga; no busca ataques.","Un proxy intermedia peticiones web; no es un sistema de prevención de intrusiones."]],

  ["1.2","m","ids-ips,security",
   "A sensor connected to a switch's mirror (SPAN) port analyzes a copy of traffic and sends alerts, but cannot stop anything. What is it?",
   "IDS",
   ["IPS","Stateful firewall","Content filter"],
   "Si recibe una copia del tráfico por un puerto espejo (SPAN), no está en el camino real, así que solo puede avisar: es un IDS (Intrusion Detection System).",
   ["Un IPS necesita estar en línea para bloquear.","Un firewall está en el camino del tráfico y aplica reglas.","Un filtro de contenido bloquea webs; tampoco funciona con una copia pasiva."]],

  ["1.2","e","load-balancer",
   "An online store runs its website on six identical servers and wants incoming requests spread across them. Which device does this?",
   "Load balancer",
   ["Proxy server","IDS","Wireless LAN controller"],
   "Un balanceador de carga (load balancer) reparte las peticiones entre varios servidores y deja de enviar a los que fallan.",
   ["Un proxy intermedia peticiones, normalmente de usuarios hacia internet; no reparte entre granjas de servidores.","Un IDS detecta ataques; no reparte tráfico.","Un WLC gestiona puntos de acceso inalámbricos."]],

  ["1.2","m","proxy",
   "Employees' web requests go to a server that caches frequently visited pages and filters blocked sites before forwarding requests to the internet. What is this server?",
   "Forward proxy",
   ["Reverse proxy","Load balancer","NAS"],
   "Un proxy directo (forward proxy) actúa en nombre de los usuarios internos hacia internet: cachea, filtra y oculta a los clientes.",
   ["Un proxy inverso protege a los servidores y recibe peticiones que vienen de internet.","Un balanceador reparte peticiones entre servidores propios.","Un NAS es almacenamiento de archivos."]],

  ["1.2","m","proxy",
   "Internet users connect to a company's public website through a server that hides the real web servers, terminates their connections and forwards requests inward. What is this?",
   "Reverse proxy",
   ["Forward proxy","IDS","VPN headend"],
   "Un proxy inverso (reverse proxy) está delante de los servidores: recibe peticiones de internet y las reenvía a los servidores internos, que quedan ocultos.",
   ["Un proxy directo trabaja para los usuarios internos que salen a internet.","Un IDS solo detecta ataques.","Un VPN headend termina túneles VPN (Virtual Private Network), no publica sitios web."]],

  ["1.2","m","storage",
   "Users need shared folders that they can map as network drives over the existing Ethernet LAN using SMB. Which storage solution fits?",
   "NAS",
   ["SAN","DAS","CDN"],
   "Un NAS (Network Attached Storage) ofrece archivos por la LAN con protocolos como SMB (Server Message Block) o NFS. Es almacenamiento a nivel de archivo.",
   ["Una SAN (Storage Area Network) ofrece bloques, no carpetas compartidas.","El DAS (Direct Attached Storage) va conectado a un solo equipo, no se comparte por la red.","Una CDN (Content Delivery Network) distribuye contenido web por el mundo."]],

  ["1.2","m","storage",
   "Servers in a data center need block-level storage over a dedicated high-speed network using Fibre Channel or iSCSI. Which solution is this?",
   "SAN",
   ["NAS","CDN","Proxy"],
   "Una SAN (Storage Area Network) es una red dedicada que entrega almacenamiento a nivel de bloque; el servidor lo ve como un disco local.",
   ["Un NAS entrega archivos, no bloques.","Una CDN reparte contenido web.","Un proxy intermedia peticiones; no ofrece almacenamiento."]],

  ["1.2","e","wireless,wlc",
   "A company has 80 lightweight access points and wants to configure and monitor them all from one place. Which device is needed?",
   "Wireless LAN controller",
   ["Load balancer","Multilayer switch","IDS"],
   "Un WLC (Wireless LAN Controller) gestiona de forma centralizada muchos APs ligeros (lightweight): configuración, canales, potencia y roaming.",
   ["Un balanceador reparte tráfico entre servidores.","Un switch multicapa enruta y conmuta, pero no gestiona APs.","Un IDS detecta ataques."]],

  ["1.2","m","vpn",
   "What is the main purpose of a VPN headend (VPN concentrator)?",
   "Terminate and manage many remote-access and site-to-site VPN tunnels",
   ["Assign IP addresses automatically to every wireless client on the network","Cache web content for branch offices","Scan email attachments for malware before delivering them to users"],
   "Un VPN headend (concentrador VPN) es el punto central que recibe y gestiona muchos túneles VPN (Virtual Private Network) a la vez.",
   ["Eso lo hace un servidor DHCP.","Eso lo hace un proxy o una CDN.","Eso lo hace un filtro de correo o antimalware."]],

  ["1.2","m","firewall,ngfw",
   "A company needs to allow web browsing but block file-sharing applications, even when they use TCP 443. Which device can do this?",
   "Next-generation firewall (NGFW)",
   ["Stateless packet filter","Layer 2 switch","Hub"],
   "Un NGFW (Next-Generation Firewall) inspecciona hasta la capa 7 y reconoce la aplicación aunque use el mismo puerto que la navegación web.",
   ["Un filtro sin estado solo ve IP y puerto: todo el 443 le parece igual.","Un switch de capa 2 no filtra aplicaciones.","Un hub no filtra nada."]],

  ["1.2","e","cdn",
   "A video company wants users around the world to load its content quickly by serving it from servers close to each user. What should it use?",
   "Content delivery network (CDN)",
   ["Storage area network (SAN)","Virtual private network (VPN)","Intrusion detection system (IDS)"],
   "Una CDN (Content Delivery Network) guarda copias del contenido en servidores repartidos por el mundo y sirve a cada usuario desde el más cercano, bajando la latencia.",
   ["Una SAN es almacenamiento interno de un centro de datos.","Una VPN cifra conexiones; no acerca el contenido al usuario.","Un IDS detecta ataques."]],

  ["1.2","e","qos",
   "Which network function gives VoIP traffic priority over bulk file downloads during congestion?",
   "Quality of Service (QoS)",
   ["Network Address Translation (NAT)","Time to Live (TTL)","Dynamic Host Configuration Protocol (DHCP)"],
   "QoS (Quality of Service) clasifica el tráfico y da prioridad al más sensible, como la voz, cuando hay congestión.",
   ["NAT traduce direcciones; no prioriza.","TTL limita cuántos saltos puede dar un paquete.","DHCP reparte direcciones IP."]],

  ["1.2","m","ttl",
   "What is the purpose of the TTL field in an IPv4 packet?",
   "Prevent packets from looping forever by limiting router hops",
   ["Set how long a client may keep its DHCP-assigned address","Define how long a DNS answer is cached by the client","Encrypt the packet payload for a limited time"],
   "TTL (Time to Live) se reduce en 1 en cada router. Cuando llega a 0 el paquete se descarta, así un bucle de enrutamiento no lo mantiene vivo para siempre. En IPv6 se llama hop limit.",
   ["La duración del préstamo DHCP se llama lease time.","DNS también usa un 'TTL' para su caché, pero el campo TTL de un paquete IPv4 cuenta saltos.","TTL no cifra nada."]],

  ["1.2","m","nfv,virtualization",
   "Instead of buying a hardware firewall, a company runs the firewall as a virtual machine on its existing servers. What is this approach called?",
   "Network functions virtualization (NFV)",
   ["Software-defined WAN (SD-WAN)","Port aggregation","Content delivery network"],
   "NFV (Network Functions Virtualization) convierte funciones de red (firewall, router, balanceador) en software que corre en servidores estándar.",
   ["SD-WAN gestiona enlaces WAN por software, no virtualiza appliances.","La agregación de puertos une varios enlaces físicos en uno lógico.","Una CDN distribuye contenido web."]],

  ["1.2","e","router",
   "Which device is required to allow hosts in 10.1.1.0/24 to communicate with hosts in 10.1.2.0/24?",
   "Router",
   ["Unmanaged switch","Hub","Access point"],
   "Son dos redes distintas. Para pasar de una red a otra hace falta enrutar, y eso lo hace un router (o un switch de capa 3).",
   ["Un switch no gestionable solo reenvía dentro de la misma red.","Un hub solo repite bits.","Un punto de acceso conecta clientes inalámbricos a la misma red."]],

  ["1.2","m","switch,collision-domain",
   "Replacing a hub with a switch mainly improves performance because the switch:",
   "Gives each port its own collision domain",
   ["Gives each port its own broadcast domain","Routes traffic between subnets","Encrypts traffic between ports"],
   "Un switch separa las colisiones por puerto (cada puerto es su propio dominio de colisión), así cada equipo puede transmitir sin chocar con los demás.",
   ["Todos los puertos de un switch (en la misma VLAN) comparten un único dominio de broadcast.","Un switch básico no enruta entre subredes.","Un switch no cifra el tráfico."]],

  ["1.2","m","router,broadcast-domain",
   "Which device separates broadcast domains by default?",
   "Router",
   ["Switch","Hub","Repeater"],
   "Los routers no reenvían broadcasts de una interfaz a otra, así que cada interfaz es un dominio de broadcast separado.",
   ["Un switch reenvía los broadcasts por todos sus puertos de la misma VLAN.","Un hub repite todo, broadcasts incluidos.","Un repetidor también repite todo."]],

  ["1.2","m","firewall",
   "A firewall automatically allows reply traffic for connections that internal users started, without a separate inbound rule. Which feature makes this possible?",
   "Stateful inspection",
   ["Port mirroring","MAC filtering","Content caching"],
   "Un firewall stateful guarda una tabla de las conexiones abiertas y deja pasar las respuestas que corresponden a ellas.",
   ["Port mirroring copia tráfico para analizarlo.","El filtrado MAC decide por dirección física, no por el estado de la conexión.","El caché de contenido es cosa de un proxy o una CDN."]],

  ["1.2","e","vpn",
   "Which of the following BEST describes a VPN?",
   "An encrypted tunnel across an untrusted network",
   ["A switch feature that splits one physical network into several logical ones","A server that assigns IP addresses automatically","A device that caches web pages for users"],
   "Una VPN (Virtual Private Network) crea un túnel cifrado para que el tráfico privado cruce internet sin que otros puedan leerlo.",
   ["Eso describe una VLAN.","Eso describe DHCP.","Eso describe un proxy."]],

  ["1.2","m","load-balancer",
   "Which of the following are functions of a load balancer? (Choose TWO)",
   ["Distributing client requests across multiple servers","Running health checks and removing failed servers from the pool"],
   ["Assigning IP addresses to clients","Translating hostnames to IP addresses","Encrypting data stored on disk"],
   "Un balanceador reparte peticiones y comprueba la salud de los servidores para no enviar tráfico a los que fallan.",
   ["Eso es DHCP.","Eso es DNS.","El cifrado en reposo se hace en el almacenamiento, no en el balanceador."]],

  ["1.2","e","content-filter",
   "A school wants to block students from reaching gambling and adult websites by category. What should it implement?",
   "Content filter",
   ["Load balancer","NAS","Wireless LAN controller"],
   "Un filtro de contenido (content/URL filter), normalmente en un proxy o NGFW, bloquea sitios por categoría o por URL.",
   ["Un balanceador reparte tráfico entre servidores.","Un NAS guarda archivos.","Un WLC gestiona puntos de acceso."]],

  ["1.2","e","wireless,ap",
   "What is the main function of a wireless access point?",
   "Connect wireless clients to the wired network",
   ["Route traffic between different subnets and VLANs","Assign IP addresses to clients","Filter websites by category"],
   "Un punto de acceso (AP) es el puente entre los clientes Wi-Fi y la red cableada.",
   ["Eso lo hace un router.","Eso lo hace un servidor DHCP (aunque algunos equipos domésticos lo integran).","Eso lo hace un filtro de contenido."]],

  ["1.2","m","nfv,virtualization",
   "What is a key benefit of using virtual network appliances instead of physical ones?",
   "Fast to deploy and scale on existing servers",
   ["They never need patches or updates","They do not consume any CPU or memory","They eliminate the need for IP addressing on the host"],
   "Un appliance virtual es software: se despliega, clona o amplía en minutos sobre servidores que ya tienes, sin esperar a comprar hardware.",
   ["El software virtual también necesita parches.","Consume CPU y memoria del servidor que lo aloja.","Sigue necesitando direcciones IP como cualquier equipo."]],

  ["1.2","h","load-balancer,tls",
   "A web farm's servers are overloaded by TLS encryption work. Which device can terminate TLS in front of them so the servers receive unencrypted requests?",
   "Load balancer performing SSL/TLS offloading",
   ["Intrusion detection system on a SPAN port","Layer 2 access switch with VLAN trunking","NAS appliance serving the website files"],
   "Muchos balanceadores hacen 'SSL/TLS offloading': descifran la conexión del cliente y pasan la petición a los servidores, que se ahorran ese trabajo.",
   ["Un IDS en un puerto espejo solo observa una copia; no termina conexiones.","Un switch de capa 2 no entiende TLS.","Un NAS guarda archivos."]],

  ["1.2","h","ids-ips",
   "What is a key risk of deploying an IPS inline rather than an IDS?",
   "A false positive can block legitimate traffic",
   ["It cannot see encrypted or unencrypted traffic at all","It requires no signature updates","It only works on wireless networks"],
   "Como el IPS está en el camino y bloquea, si se equivoca (falso positivo) corta tráfico legítimo. Un IDS en el mismo caso solo generaría una alerta.",
   ["Un IPS en línea ve el tráfico que pasa por él.","Un IPS basado en firmas necesita actualizarlas.","Funciona en redes cableadas e inalámbricas."]],

  ["1.2","h","proxy",
   "Web traffic is intercepted by a proxy without any proxy settings configured on the users' browsers. What type of proxy is this?",
   "Transparent proxy",
   ["Explicit forward proxy","Reverse proxy","SOCKS client"],
   "Un proxy transparente intercepta el tráfico en la red sin que el cliente tenga que configurar nada.",
   ["Un proxy explícito exige configurarlo en el navegador o el sistema.","Un proxy inverso protege servidores, no intercepta a los usuarios internos.","Un cliente SOCKS también requiere configuración en el equipo."]],

  ["1.2","m","ids-ips",
   "An IDS alerts whenever traffic deviates significantly from a learned baseline of normal network behavior. Which detection method is it using?",
   "Anomaly-based (behavior-based) detection",
   ["Signature-based detection with custom rules","Port-based filtering","MAC-based filtering"],
   "La detección por anomalías compara con lo 'normal' aprendido y avisa de lo que se sale de ahí. Puede detectar ataques nuevos, pero da más falsos positivos.",
   ["La detección por firmas compara con patrones de ataques conocidos.","Filtrar por puerto es una regla fija, no aprende comportamiento.","Filtrar por MAC es control de acceso, no detección de intrusiones."]],

  ["1.2","m","ids-ips",
   "What is the main weakness of a purely signature-based IDS?",
   "It misses new attacks with no known signature",
   ["It generates an alert for every packet","It cannot be placed on a SPAN port","It requires physical access to each host it monitors"],
   "Un IDS por firmas solo reconoce ataques que ya están en su base de datos. Un ataque nuevo (zero-day) pasa desapercibido.",
   ["Solo alerta cuando algo coincide con una firma.","Precisamente se suele conectar a un puerto espejo (SPAN).","Un IDS de red analiza tráfico; no necesita acceso físico a cada equipo."]],

  ["1.2","m","cdn",
   "Which of the following are benefits of using a CDN for a public website? (Choose TWO)",
   ["Lower latency for users who are far from the origin server","Reduced load on the origin server"],
   ["Encryption of data stored on the origin's disks","Automatic IP address assignment for visitors","Replacement of the need for DNS"],
   "Una CDN (Content Delivery Network) sirve copias desde servidores cercanos al usuario: menos latencia y menos carga para el servidor original.",
   ["El cifrado en reposo no es función de una CDN.","Las IPs de los visitantes las asigna su propio proveedor o red.","Las CDN dependen precisamente de DNS para dirigir a cada usuario al servidor cercano."]],
];

export default q;
