import type { Raw } from '../types';

// 1.2 (+1) · 1.3 Cloud concepts and connectivity (25) · 1.4 Ports, protocols, services, traffic types (25 + 20 generated)
const q: Raw[] = [
  ["1.2","e","bridge",
   "Which device connects two network segments at Layer 2 and forwards frames between them based on MAC addresses, usually with very few ports?",
   "Bridge",
   ["Router","Hub","Proxy server"],
   "Un bridge (puente) une dos segmentos y decide por MAC, igual que un switch pero con muy pocos puertos. El switch es, en la práctica, un bridge con muchos puertos.",
   ["El router decide por IP y separa redes distintas.","El hub no lee MACs: repite todo.","El proxy trabaja con peticiones de aplicación, no con tramas."]],

  ["1.3","e","cloud,service-models",
   "A company uses a web-based email service. The provider manages everything, and the company only creates user accounts. Which cloud service model is this?",
   "SaaS",
   ["IaaS","PaaS","DaaS"],
   "SaaS (Software as a Service): usas una aplicación terminada por internet y el proveedor gestiona todo lo demás.",
   ["En IaaS alquilas servidores virtuales y gestionas tú el sistema operativo.","En PaaS despliegas tu propio código en una plataforma gestionada.","DaaS (Desktop as a Service) ofrece escritorios virtuales, no una aplicación de correo."]],

  ["1.3","e","cloud,service-models",
   "A company rents virtual machines, storage and virtual networks from a provider and installs and patches its own operating systems. Which service model is this?",
   "IaaS",
   ["SaaS","PaaS","FaaS"],
   "IaaS (Infrastructure as a Service): el proveedor da la infraestructura (VMs, red, almacenamiento) y tú gestionas desde el sistema operativo hacia arriba.",
   ["En SaaS no tocas ningún sistema operativo.","En PaaS el proveedor gestiona el sistema operativo por ti.","FaaS (funciones sin servidor) no te da máquinas virtuales para administrar."]],

  ["1.3","m","cloud,service-models",
   "Developers want to upload their application code and have the provider handle the operating system, runtime and scaling. Which service model fits?",
   "PaaS",
   ["IaaS","SaaS","On-premises hosting"],
   "PaaS (Platform as a Service): tú pones el código y los datos; el proveedor gestiona sistema operativo, runtime y escalado.",
   ["En IaaS tendrían que instalar y parchear el sistema operativo ellos mismos.","SaaS es una aplicación ya hecha, no una plataforma para tu código.","En tu propio centro de datos lo gestionarías todo tú."]],

  ["1.3","m","cloud,shared-responsibility",
   "In an IaaS deployment, who is normally responsible for patching the guest operating system on a virtual machine?",
   "The customer",
   ["The cloud provider","The internet service provider","The hardware manufacturer"],
   "En IaaS el proveedor se encarga del hardware y la virtualización; todo lo que va encima (sistema operativo, aplicaciones, datos) es responsabilidad del cliente.",
   ["El proveedor no toca el sistema operativo de tus VMs en IaaS.","El ISP solo te da la conexión a internet.","El fabricante no gestiona tus VMs."]],

  ["1.3","m","cloud,service-models",
   "Which cloud service model shifts the MOST management responsibility to the provider?",
   "SaaS",
   ["IaaS","PaaS","Hybrid cloud"],
   "En SaaS el cliente solo usa la aplicación y gestiona sus usuarios y datos; todo lo demás lo gestiona el proveedor.",
   ["IaaS deja al cliente el sistema operativo y todo lo de encima.","PaaS deja al cliente el código y los datos.","'Hybrid' es un modelo de despliegue, no de servicio."]],

  ["1.3","e","cloud,deployment-models",
   "Which cloud deployment model runs on infrastructure shared by many unrelated customers and is operated by a third-party provider?",
   "Public cloud",
   ["Private cloud","Hybrid cloud","On-premises data center"],
   "La nube pública es infraestructura de un proveedor (AWS, Azure, Google…) compartida por muchos clientes.",
   ["La nube privada es de uso exclusivo de una organización.","La híbrida combina pública y privada/local.","Un centro de datos local es tuyo, no de un proveedor compartido."]],

  ["1.3","e","cloud,deployment-models",
   "A hospital builds cloud-style infrastructure used only by its own organization for regulatory reasons. Which deployment model is this?",
   "Private cloud",
   ["Public cloud","Community cloud","Multitenant SaaS"],
   "Una nube privada da los beneficios de la nube (autoservicio, virtualización) pero para una sola organización.",
   ["La pública se comparte con otros clientes.","Una nube comunitaria se comparte entre varias organizaciones con intereses comunes.","El SaaS multitenant comparte la aplicación con muchos clientes."]],

  ["1.3","m","cloud,deployment-models",
   "A company keeps its database servers on-premises but runs its web front end in a public cloud, with both connected. Which deployment model is this?",
   "Hybrid cloud",
   ["Private cloud","Public cloud","Community cloud"],
   "Combinar recursos locales o privados con nube pública, conectados entre sí, es una nube híbrida.",
   ["Una nube privada no incluiría la parte pública.","Una nube pública no incluiría los servidores locales.","Una nube comunitaria se comparte entre organizaciones afines; no es la mezcla local más pública."]],

  ["1.3","m","cloud,elasticity",
   "During a holiday sale, a retailer's cloud environment automatically adds web servers as traffic rises and removes them when it drops. Which cloud characteristic is this?",
   "Elasticity",
   ["Multitenancy","Data locality","Fault tolerance"],
   "La elasticidad es crecer y encoger recursos automáticamente según la demanda del momento.",
   ["Multitenancy es compartir infraestructura entre varios clientes.","Data locality trata de dónde se guardan los datos físicamente.","La tolerancia a fallos es seguir funcionando cuando algo se rompe."]],

  ["1.3","m","cloud,scalability",
   "A company expects its user base to triple over three years and needs a design that can grow to handle that load by adding resources. Which characteristic is it evaluating?",
   "Scalability",
   ["Elasticity","Multitenancy","Latency"],
   "La escalabilidad es la capacidad de crecer para soportar más carga. La elasticidad es la versión automática y dinámica (subir y bajar según la demanda).",
   ["La elasticidad pone el foco en ajustarse solo, arriba y abajo, al momento; aquí se habla de crecimiento planificado.","Multitenancy es compartir recursos entre clientes.","La latencia es un retardo, no una capacidad de crecer."]],

  ["1.3","m","cloud,multitenancy",
   "In a public cloud, many customers run workloads on the same physical servers while being logically isolated from each other. What is this called?",
   "Multitenancy",
   ["Elasticity","Hybrid cloud","Direct connect"],
   "Multitenancy (multiinquilino): varios clientes comparten la misma infraestructura física, cada uno aislado lógicamente.",
   ["La elasticidad es crecer y encoger según la demanda.","Híbrido es mezclar nube pública con recursos privados.","Direct connect es un enlace dedicado a la nube."]],

  ["1.3","m","cloud,multitenancy",
   "Which is a common concern with multitenant public cloud environments?",
   "Another tenant's heavy workload can affect performance on shared resources",
   ["Customers must buy and install their own physical servers in the provider's data center","Resources can never be scaled","Virtual networks cannot be isolated at all"],
   "Al compartir hardware, un vecino con mucha carga puede afectar al rendimiento (el llamado 'noisy neighbor'). También preocupa el aislamiento entre clientes.",
   ["En la nube pública no compras servidores físicos.","La nube pública precisamente permite escalar.","Los proveedores aíslan las redes virtuales de cada cliente."]],

  ["1.3","e","cloud,vpc",
   "What is a virtual private cloud (VPC)?",
   "A logically isolated private network defined inside a public cloud",
   ["A physical data center that the customer owns and operates itself","A VPN client installed on laptops","A content delivery network for private files"],
   "Una VPC (Virtual Private Cloud) es tu propia red aislada dentro de la nube pública: tú defines sus subredes, rutas y reglas.",
   ["Una VPC es virtual y está en la nube del proveedor.","Un cliente VPN es un programa en el portátil, no una red en la nube.","Una CDN distribuye contenido; no es una red privada."]],

  ["1.3","m","cloud,gateways",
   "Which cloud component allows resources with public IP addresses in a VPC subnet to send and receive traffic directly with the internet?",
   "Internet gateway",
   ["NAT gateway","Security group","Direct connect circuit"],
   "El internet gateway conecta la VPC con internet en ambos sentidos para los recursos con IP pública.",
   ["Un NAT gateway solo permite salir a internet, no recibir conexiones iniciadas desde fuera.","Un security group filtra tráfico; no da salida a internet.","Direct connect conecta tu red local con la nube, no con internet."]],

  ["1.3","m","cloud,gateways",
   "Database servers in a private VPC subnet must download OS updates from the internet but must NOT be reachable from the internet. Which component should be used?",
   "NAT gateway",
   ["Internet gateway attached directly to the database subnet","Public IP address on each database server","Reverse proxy"],
   "Un NAT gateway deja a las instancias privadas iniciar conexiones hacia internet (por ejemplo, para actualizarse) sin que nadie de fuera pueda iniciar conexiones hacia ellas.",
   ["Dar salida directa por el internet gateway expondría la subred.","Una IP pública haría los servidores accesibles desde internet.","Un proxy inverso publica servicios hacia fuera, justo lo contrario de lo que se quiere."]],

  ["1.3","m","cloud,security-groups",
   "Which cloud control acts as a virtual firewall applied directly to individual instances or their network interfaces?",
   "Security group",
   ["Internet gateway","Route table","Direct connect"],
   "Un security group es un firewall virtual asociado a instancias o interfaces concretas: define qué tráfico entra y sale de ellas.",
   ["El internet gateway da acceso a internet; no filtra.","La tabla de rutas decide el camino, no filtra.","Direct connect es un enlace privado a la nube."]],

  ["1.3","h","cloud,security-lists",
   "A cloud administrator wants one set of allow/deny rules to apply to every instance in a subnet, in addition to per-instance rules. Which control applies at the subnet level?",
   "Network security list (network ACL)",
   ["Security group attached to each instance","NAT gateway","Elastic IP address"],
   "Las listas de seguridad de red (network security lists o network ACLs) se aplican a la subred entera; los security groups se aplican a cada instancia o interfaz.",
   ["El security group se asocia a instancias o interfaces, no a la subred completa.","Un NAT gateway da salida a internet, no filtra por subred.","Una IP elástica es una dirección pública fija; no es un filtro."]],

  ["1.3","h","cloud,security-groups",
   "An administrator adds an inbound rule allowing TCP 443 to a stateful security group. What happens to the web server's responses to those clients?",
   "Allowed automatically; the group is stateful",
   ["They are blocked unless a matching outbound rule is added","They are sent over UDP instead of TCP","They must go through a NAT gateway"],
   "Un security group stateful recuerda las conexiones permitidas y deja salir sus respuestas sin reglas adicionales.",
   ["Eso ocurriría con un filtro sin estado (stateless).","HTTPS usa TCP; la respuesta no cambia de protocolo.","Las respuestas vuelven por el mismo camino de la conexión; el NAT gateway es para salidas iniciadas desde dentro."]],

  ["1.3","m","cloud,connectivity",
   "A company wants a private, dedicated connection from its data center to its cloud provider with consistent bandwidth and latency that does not cross the public internet. What should it order?",
   "Direct connect (dedicated circuit)",
   ["Site-to-site VPN over the internet","Client-to-site VPN","Public IP addresses on every server"],
   "Un direct connect es un circuito privado y dedicado hasta el proveedor de nube: rendimiento más estable y sin pasar por internet.",
   ["Una VPN site-to-site cifra el tráfico, pero sigue viajando por internet, con rendimiento variable.","Una VPN de cliente es para usuarios individuales, no para unir un centro de datos.","Las IPs públicas exponen los servidores a internet."]],

  ["1.3","m","cloud,connectivity",
   "A small company needs to connect its office network to its VPC this week, cheaply and securely, using its existing internet connection. What is the BEST option?",
   "Site-to-site VPN",
   ["Direct connect circuit","Dial-up modem","Unencrypted GRE tunnel"],
   "Una VPN site-to-site se monta rápido sobre la conexión a internet que ya tienes, cifra el tráfico y es barata.",
   ["Un direct connect tarda semanas en instalarse y cuesta más.","Un módem de acceso telefónico es obsoleto y demasiado lento.","GRE (Generic Routing Encapsulation) sin IPsec no cifra nada."]],

  ["1.3","h","cloud,connectivity",
   "Which of the following are advantages of a direct connect circuit over a site-to-site VPN to the cloud? (Choose TWO)",
   ["More consistent bandwidth and latency","Traffic does not travel across the public internet"],
   ["Cheaper and faster to set up","Needs no involvement from the provider or a carrier","Works without any physical installation"],
   "Un direct connect es un enlace dedicado: rendimiento predecible y el tráfico no pasa por internet.",
   ["Suele ser más caro y lento de instalar que una VPN.","Requiere coordinar con el proveedor de nube y con un operador.","Necesita instalar un circuito físico."]],

  ["1.3","h","cloud,isolation",
   "In a multitenant public cloud, what prevents one customer from seeing another customer's network traffic?",
   "Logical isolation of each customer's virtual networks",
   ["Each customer receives its own dedicated physical data center building","All traffic is sent as broadcast","Customers share one flat Layer 2 network"],
   "El proveedor separa lógicamente las redes virtuales de cada cliente (VPC, virtualización de red), aunque compartan el hardware.",
   ["En la nube pública no tienes un centro de datos físico propio.","Los broadcasts no aislarían nada, al contrario.","Una red plana compartida expondría el tráfico entre clientes."]],

  ["1.3","m","cloud,vpc,gateways",
   "A new VPC subnet hosts web servers that must be reachable from the internet. Besides public IP addresses, what must the subnet's route table point to for the default route?",
   "An internet gateway",
   ["A NAT gateway","A security group","A private DNS zone"],
   "Una subred pública necesita una ruta por defecto (0.0.0.0/0) hacia el internet gateway para entrar y salir de internet.",
   ["El NAT gateway es para que subredes privadas salgan, no para recibir conexiones.","Un security group no es un destino de ruta.","Una zona DNS resuelve nombres; no es un camino de red."]],

  ["1.3","m","cloud,nfv",
   "A company deploys a vendor's virtual firewall appliance inside its VPC to inspect traffic between subnets. This is an example of:",
   "Network functions virtualization (NFV)",
   ["Software as a Service (SaaS)","A dedicated direct connect circuit","Multitenancy on the cloud provider's hosts"],
   "Ejecutar un firewall como máquina virtual dentro de la nube es NFV (Network Functions Virtualization): una función de red convertida en software.",
   ["SaaS es una aplicación terminada para usuarios finales.","Direct connect es un enlace privado hacia la nube.","Multitenancy es compartir infraestructura entre clientes."]],

  ["1.4","e","traffic-types",
   "A host sends a packet to one specific destination host. What type of traffic is this?",
   "Unicast",
   ["Broadcast","Multicast","Anycast"],
   "Unicast es de uno a uno: un origen y un único destino.",
   ["Broadcast va a todos los equipos del segmento.","Multicast va a un grupo que se ha suscrito.","Anycast va al más cercano de varios equipos que comparten dirección."]],

  ["1.4","m","traffic-types",
   "A video stream is sent once and delivered only to the hosts that have joined a specific group. Which traffic type is this?",
   "Multicast",
   ["Broadcast","Unicast","Anycast"],
   "Multicast es de uno a muchos, pero solo a quienes se unen al grupo. Ahorra ancho de banda frente a mandar una copia a cada uno.",
   ["Broadcast iría a todos, quieran o no.","Unicast sería una copia por destinatario.","Anycast entrega a un único destino: el más cercano."]],

  ["1.4","e","traffic-types",
   "A frame is sent to every device in the local Layer 2 segment. What type of traffic is this?",
   "Broadcast",
   ["Multicast","Unicast","Anycast"],
   "Broadcast va a todos los equipos del dominio de broadcast (en IPv4, por ejemplo, a 255.255.255.255 o a la dirección de broadcast de la subred).",
   ["Multicast va solo a un grupo suscrito.","Unicast va a un solo destino.","Anycast va al más cercano de varios."]],

  ["1.4","h","traffic-types,anycast",
   "Several DNS servers around the world share the same IP address, and routing delivers each query to the nearest one. What is this called?",
   "Anycast",
   ["Multicast","Broadcast","Unicast"],
   "Con anycast, varios equipos anuncian la misma dirección y el enrutamiento lleva cada paquete al más cercano. Se usa mucho en DNS y CDN.",
   ["Multicast entrega a todos los miembros de un grupo, no a uno solo.","Broadcast entrega a todos los del segmento.","Unicast supone una dirección para un único equipo."]],

  ["1.4","m","traffic-types,ipv6",
   "IPv6 does not support broadcast. Which traffic type does IPv6 use for functions that IPv4 performed with broadcast?",
   "Multicast",
   ["Anycast only","Unicast flooding","Directed broadcast"],
   "IPv6 elimina el broadcast y usa multicast (por ejemplo, para el descubrimiento de vecinos), que solo molesta a los equipos interesados.",
   ["Anycast existe en IPv6, pero no sustituye al broadcast.","La inundación unicast es un comportamiento de los switches, no un reemplazo del broadcast.","El broadcast dirigido es un concepto de IPv4."]],

  ["1.4","m","gre,tunneling",
   "Which protocol encapsulates other protocols inside IP to build a tunnel but provides NO encryption by itself?",
   "GRE",
   ["IPsec ESP","SSH","TLS"],
   "GRE (Generic Routing Encapsulation) crea túneles que pueden llevar muchos protocolos, pero no cifra. Por eso a menudo se combina con IPsec.",
   ["ESP cifra el contenido.","SSH cifra la sesión.","TLS cifra la conexión."]],

  ["1.4","m","ipsec",
   "Which IPsec protocol provides confidentiality by encrypting the payload?",
   "ESP",
   ["AH","GRE","ICMP"],
   "ESP (Encapsulating Security Payload) cifra el contenido y además puede autenticarlo. AH solo autentica.",
   ["AH (Authentication Header) comprueba integridad y origen, pero no cifra.","GRE no cifra.","ICMP es para mensajes de control, no para seguridad."]],

  ["1.4","h","ipsec",
   "Which IPsec protocol provides integrity and origin authentication for packets but does NOT encrypt them?",
   "AH",
   ["ESP","IKE","TLS"],
   "AH (Authentication Header) garantiza que el paquete no fue modificado y de quién viene, pero el contenido viaja legible.",
   ["ESP sí cifra.","IKE (Internet Key Exchange) negocia las claves; no protege paquetes por sí mismo.","TLS no forma parte de IPsec."]],

  ["1.4","e","tcp-udp",
   "Which transport protocol is connection-oriented, uses a three-way handshake and retransmits lost data?",
   "TCP",
   ["UDP","ICMP","GRE"],
   "TCP (Transmission Control Protocol) establece la conexión con un saludo de tres pasos, confirma lo recibido y reenvía lo perdido.",
   ["UDP no establece conexión ni reenvía nada.","ICMP es un protocolo de control de la capa 3.","GRE es un protocolo de túnel."]],

  ["1.4","m","tcp",
   "What is the correct order of the TCP three-way handshake?",
   "SYN → SYN-ACK → ACK",
   ["SYN → ACK → SYN-ACK","ACK → SYN → FIN","SYN → FIN → ACK"],
   "El cliente pide conexión (SYN), el servidor acepta y responde (SYN-ACK) y el cliente confirma (ACK).",
   ["El SYN-ACK lo envía el servidor antes del ACK final.","FIN sirve para cerrar una conexión, no para abrirla.","FIN no forma parte del saludo inicial."]],

  ["1.4","m","udp,voip",
   "Why do real-time applications like VoIP typically use UDP instead of TCP?",
   "UDP has less overhead and does not delay traffic waiting for retransmissions",
   ["UDP guarantees delivery of every packet and retransmits lost audio","UDP encrypts voice traffic","UDP uses a three-way handshake that keeps voice calls stable and ordered"],
   "En una llamada, un paquete que llega tarde no sirve. UDP no espera reenvíos ni confirmaciones, así que añade menos retardo.",
   ["UDP no garantiza la entrega; eso lo hace TCP.","UDP no cifra nada.","El saludo de tres pasos es de TCP."]],

  ["1.4","e","secure-protocols",
   "Which protocol should replace Telnet to provide encrypted remote command-line access?",
   "SSH",
   ["FTP","HTTP","TFTP"],
   "SSH (Secure Shell, TCP 22) da lo mismo que Telnet (una consola remota), pero cifrado.",
   ["FTP transfiere archivos y tampoco cifra.","HTTP es web sin cifrar.","TFTP copia archivos sin autenticación ni cifrado."]],

  ["1.4","e","secure-protocols",
   "A website currently uses HTTP on port 80. Which protocol and port should it move to so traffic is encrypted?",
   "HTTPS on TCP 443",
   ["HTTP on TCP 8080","SFTP on TCP 22","SNMP on UDP 161"],
   "HTTPS (HTTP Secure) usa TLS para cifrar la web y su puerto por defecto es TCP 443.",
   ["8080 es un puerto alternativo para HTTP, que sigue sin cifrar.","SFTP es para transferir archivos, no para servir webs.","SNMP es para monitorizar dispositivos."]],

  ["1.4","m","secure-protocols,ldap",
   "Directory queries currently use LDAP on port 389 in clear text. Which option encrypts them?",
   "LDAPS on TCP 636",
   ["LDAP on UDP 389","SMB on TCP 445","Kerberos on UDP 69"],
   "LDAPS (LDAP over SSL/TLS) cifra las consultas al directorio y usa el puerto 636.",
   ["Cambiar a UDP no añade cifrado.","SMB es para compartir archivos, no para consultar el directorio.","Kerberos no usa el 69 (ese es TFTP) y no sustituye a LDAP."]],

  ["1.4","m","secure-protocols,file-transfer",
   "A company must stop using FTP because credentials travel in clear text. Which replacement encrypts both the login and the files using SSH?",
   "SFTP",
   ["TFTP","SNMP","SMB"],
   "SFTP (SSH File Transfer Protocol) transfiere archivos dentro de una sesión SSH, así que todo va cifrado.",
   ["TFTP es aún menos seguro: no tiene ni autenticación.","SNMP es para monitorizar dispositivos.","SMB sirve para compartir archivos en Windows, pero no es 'FTP sobre SSH'."]],

  ["1.4","m","snmp,secure-protocols",
   "Which SNMP version adds authentication and encryption?",
   "SNMPv3",
   ["SNMPv1","SNMPv2c","SNMPv2 with public community"],
   "SNMPv3 añade usuarios con autenticación y cifrado. Las versiones 1 y 2c solo usan 'community strings' que viajan en claro.",
   ["SNMPv1 manda la community string en texto claro.","SNMPv2c también usa community strings sin cifrar.","La community 'public' es un valor por defecto inseguro."]],

  ["1.4","m","tcp-udp",
   "Which of the following protocols use UDP by default? (Choose TWO)",
   ["DHCP","TFTP"],
   ["SSH","RDP","SMB"],
   "DHCP (67/68) y TFTP (69) usan UDP.",
   ["SSH usa TCP 22.","RDP usa TCP 3389.","SMB usa TCP 445."]],

  ["1.4","m","tcp-udp",
   "Which of the following protocols use TCP by default? (Choose TWO)",
   ["SSH","SMB"],
   ["TFTP","NTP","Syslog"],
   "SSH (22) y SMB (445) usan TCP.",
   ["TFTP usa UDP 69.","NTP usa UDP 123.","Syslog usa normalmente UDP 514."]],

  ["1.4","h","dns",
   "DNS normally answers queries over UDP 53. In which situation does DNS use TCP 53?",
   "Zone transfers and responses too large for UDP",
   ["Every query from a Windows client or domain member","Queries for IPv6 (AAAA) records only","When the client uses DHCP"],
   "DNS usa UDP para las consultas normales y TCP para las transferencias de zona entre servidores y para respuestas grandes.",
   ["Los clientes normales preguntan por UDP.","Los registros IPv6 (AAAA) también se consultan normalmente por UDP.","Usar DHCP no cambia el transporte de DNS."]],

  ["1.4","h","sip,voip",
   "A VoIP system is configured to protect call signaling with TLS. Which port is it MOST likely using?",
   "5061",
   ["5060","3389","1433"],
   "SIP (Session Initiation Protocol) usa 5060 sin cifrar y 5061 cuando va protegido con TLS.",
   ["5060 es SIP sin cifrar.","3389 es RDP.","1433 es SQL Server."]],

  ["1.4","m","snmp",
   "A monitoring server polls switches for statistics and also receives unsolicited alerts from them. Which ports are involved?",
   "UDP 161 for polling and UDP 162 for traps",
   ["UDP 162 for polling and UDP 161 for traps","TCP 22 for polling and TCP 23 for traps","UDP 514 for both"],
   "SNMP usa UDP 161 cuando el gestor pregunta a los equipos (polling) y UDP 162 cuando los equipos envían avisos espontáneos (traps).",
   ["Está al revés.","22 y 23 son SSH y Telnet.","514 es Syslog."]],

  ["1.4","e","ntp",
   "Log entries from different devices cannot be correlated because their clocks differ by several minutes. Which protocol should be configured?",
   "NTP",
   ["SNMP","LDAP","SMTP"],
   "NTP (Network Time Protocol, UDP 123) sincroniza los relojes para que las marcas de tiempo de los logs coincidan.",
   ["SNMP monitoriza, pero no sincroniza relojes.","LDAP consulta directorios.","SMTP envía correo."]],

  ["1.4","e","icmp",
   "Which protocol do the ping and traceroute utilities rely on to report reachability and path information?",
   "ICMP",
   ["UDP 53","TCP 23","ARP"],
   "ping y traceroute usan mensajes ICMP (Internet Control Message Protocol) como Echo Request/Reply y Time Exceeded.",
   ["UDP 53 es DNS.","TCP 23 es Telnet.","ARP resuelve IPs a MACs en la red local; no mide caminos."]],

  ["1.4","m","dhcp,traffic-types",
   "A new laptop has no IP address and sends a DHCP Discover message. What type of traffic is that message?",
   "Broadcast",
   ["Unicast to the DHCP server","Anycast","Multicast to routers"],
   "El cliente aún no sabe dónde está el servidor DHCP, así que su Discover sale en broadcast a toda la red local.",
   ["No puede enviar unicast porque no conoce la IP del servidor.","DHCP en IPv4 no usa anycast.","DHCP para IPv4 no usa multicast."]],

  ["1.4","m","smtps,email",
   "According to the Network+ objectives, which port is associated with SMTPS for sending email securely?",
   "587",
   ["25","110","993"],
   "CompTIA asocia SMTPS (SMTP Secure) al puerto 587, el de envío de correo con cifrado. El 25 es SMTP sin cifrar entre servidores.",
   ["25 es SMTP sin cifrar.","110 es POP3, que sirve para descargar correo, no para enviarlo.","993 es IMAP cifrado, que sirve para leer correo."]],
];

export default q;
