import type { Raw } from '../types';

// 1.3 (+1) · 1.5 Media and transceivers (25) · 1.6 Topologies (20) · 1.7 IPv4 addressing (9 + 36 generated) · 1.8 Modern environments (15)
const q: Raw[] = [
  ["1.3","m","cloud,service-models",
   "A company moves its existing on-premises virtual machines unchanged onto a provider's virtual servers and keeps managing the operating systems itself. Which service model is it using?",
   "IaaS",
   ["SaaS","PaaS","Serverless functions"],
   "Mover VMs tal cual ('lift and shift') y seguir administrando el sistema operativo es IaaS (Infrastructure as a Service).",
   ["En SaaS no administras ningún servidor.","En PaaS el proveedor gestiona el sistema operativo.","Las funciones serverless no son VMs que tú administres."]],

  ["1.5","e","fiber",
   "A company must connect two buildings 8 km apart with a fiber link. Which type of fiber should it use?",
   "Single-mode fiber",
   ["Multimode fiber","Cat 6a twisted pair","Twinaxial DAC cable"],
   "La fibra monomodo (single-mode) tiene un núcleo muy fino y usa láser: llega a muchos kilómetros.",
   ["La multimodo está pensada para distancias cortas, del orden de cientos de metros.","El cobre Cat 6a llega a 100 m.","Un DAC (Direct Attach Copper) solo sirve para unos pocos metros."]],

  ["1.5","m","fiber",
   "Which statement about multimode fiber is correct?",
   "It has a larger core and is used for shorter distances",
   ["It has a smaller core than single-mode and reaches tens of kilometers","It is immune to distance limits","It uses RJ45 connectors"],
   "La multimodo tiene un núcleo más grueso; la luz rebota por varios caminos, lo que limita la distancia a cientos de metros.",
   ["Eso describe a la monomodo.","Toda fibra tiene límites de distancia.","La fibra usa conectores como LC, SC o ST, no RJ45."]],

  ["1.5","e","copper,cabling",
   "Which is the lowest copper cable category that supports 10GBASE-T over the full 100 meters?",
   "Cat 6a",
   ["Cat 5e","Cat 6","Cat 3"],
   "Cat 6a soporta 10 Gbps en los 100 m completos.",
   ["Cat 5e llega a 1 Gbps.","Cat 6 solo soporta 10 Gbps hasta unos 55 m.","Cat 3 es un cable telefónico antiguo."]],

  ["1.5","m","copper,cabling",
   "An existing Cat 6 run of 40 meters must carry 10GBASE-T. What should the technician expect?",
   "Yes; Cat 6 does 10 Gbps up to about 55 m",
   ["It cannot work; Cat 6 is limited to 100 Mbps","It works only if the cable is replaced with shielded Cat 5e","It requires single-mode fiber adapters"],
   "Cat 6 soporta 10 Gbps hasta unos 55 m; con 40 m está dentro del límite.",
   ["Cat 6 soporta al menos 1 Gbps en 100 m y 10 Gbps en distancias cortas.","Cat 5e no soporta 10GBASE-T de forma estándar.","No hace falta fibra para 40 m."]],

  ["1.5","e","copper,cabling",
   "Which cable category is rated for 1 Gbps over 100 meters and is the minimum commonly used for Gigabit Ethernet?",
   "Cat 5e",
   ["Cat 3","Cat 5","Cat 8"],
   "Cat 5e (la 'e' es de enhanced) soporta 1000BASE-T en 100 m.",
   ["Cat 3 es para telefonía y redes muy antiguas.","Cat 5 original está pensado para 100 Mbps.","Cat 8 sirve para 25/40 Gbps en tramos muy cortos: es más de lo necesario."]],

  ["1.5","m","copper,cabling",
   "Which cable category supports 25 or 40 Gbps but only up to about 30 meters, typically between switches and servers in a data center?",
   "Cat 8",
   ["Cat 6a","Cat 5e","Cat 6"],
   "Cat 8 alcanza 25/40 Gbps en distancias de hasta unos 30 m.",
   ["Cat 6a llega a 10 Gbps.","Cat 5e llega a 1 Gbps.","Cat 6 llega a 10 Gbps en tramos cortos."]],

  ["1.5","m","cabling,plenum",
   "Cable must run through the space above a drop ceiling that is used for air circulation. What type of cable is required?",
   "Plenum-rated cable",
   ["PVC (non-plenum) cable","Direct burial cable","Crossover cable"],
   "En espacios por donde circula el aire (plenum) se exige cable plenum: produce poco humo tóxico si hay un incendio.",
   ["El PVC normal suelta humo tóxico al arder y no está permitido en esos espacios.","El cable de enterramiento directo es para exterior bajo tierra.","Crossover describe el orden de los pares, no la protección contra incendios."]],

  ["1.5","m","dac,twinax",
   "A server needs a 10 Gbps link to a top-of-rack switch 3 meters away, as cheaply as possible, using the switch's SFP+ port. What is the BEST choice?",
   "Direct attach copper (DAC) twinaxial cable",
   ["Single-mode fiber with long-range (LR) optics","Cat 3 cable","Coaxial cable with F-type connectors"],
   "Un DAC (Direct Attach Copper) es un cable de cobre twinaxial con los conectores SFP+ ya integrados: barato y perfecto para distancias cortas dentro del rack.",
   ["Las ópticas de largo alcance son caras e innecesarias para 3 m.","Cat 3 no soporta 10 Gbps.","El coaxial con conector F-type es para cable de TV o módems."]],

  ["1.5","m","transceivers",
   "Which transceiver form factor carries four lanes in one module and is commonly used for 40 Gbps or 100 Gbps links?",
   "QSFP",
   ["SFP","RJ45","BNC"],
   "QSFP (Quad Small Form-factor Pluggable) agrupa cuatro canales en un módulo, para 40/100 Gbps.",
   ["El SFP es de un solo canal (1 Gbps; SFP+ 10 Gbps).","RJ45 es un conector de cobre, no un transceptor.","BNC es un conector coaxial antiguo."]],

  ["1.5","h","transceivers,troubleshooting",
   "A new fiber link stays down. One switch has a 10GBASE-SR (multimode) optic and the other a 10GBASE-LR (single-mode) optic. What is the problem?",
   "The transceiver types do not match",
   ["The link needs a crossover cable","The switch ports must be set to half duplex","The fiber must be replaced with Cat 6"],
   "Los dos extremos de un enlace de fibra deben usar el mismo tipo de óptica (SR con SR, LR con LR) y la fibra adecuada. SR es multimodo de corto alcance y LR es monomodo de largo alcance.",
   ["En fibra no existe el cable crossover de Ethernet de cobre.","El duplex no explica que las ópticas no se entiendan.","El problema son los transceptores, no el medio."]],

  ["1.5","e","connectors,fiber",
   "Which small form factor fiber connector is most commonly used on SFP and SFP+ modules?",
   "LC",
   ["ST","BNC","F-type"],
   "LC (Lucent Connector) es pequeño y va en pareja (dúplex); es el típico de los módulos SFP.",
   ["ST es un conector de bayoneta más grande y antiguo.","BNC es coaxial.","F-type es coaxial, de televisión o módem de cable."]],

  ["1.5","h","connectors,fiber",
   "Which fiber connector holds many fibers in a single ferrule and is used for high-speed parallel optics such as 40G/100G?",
   "MPO",
   ["LC","SC","RJ11"],
   "MPO (Multi-fiber Push On) lleva 8, 12 o más fibras en un solo conector, necesario para ópticas paralelas de alta velocidad.",
   ["LC lleva una fibra por conector (en pareja para dúplex).","SC también lleva una sola fibra.","RJ11 es un conector telefónico de cobre."]],

  ["1.5","e","connectors",
   "Which connector is used for analog telephone lines and DSL?",
   "RJ11",
   ["RJ45","LC","BNC"],
   "RJ11 es el conector pequeño de teléfono (2–4 hilos). RJ45 es el de Ethernet (8 hilos).",
   ["RJ45 es para Ethernet.","LC es para fibra.","BNC es para coaxial antiguo."]],

  ["1.5","e","connectors,coax",
   "A cable modem connects to the provider's coaxial line. Which connector is used on that line?",
   "F-type",
   ["BNC","RJ45","ST"],
   "El cable coaxial de TV e internet por cable usa conectores F-type, que van roscados.",
   ["BNC es coaxial de bayoneta, usado en redes antiguas y vídeo.","RJ45 es para par trenzado Ethernet.","ST es para fibra."]],

  ["1.5","m","connectors,coax",
   "Which coaxial connector uses a bayonet twist-lock and was common on older Ethernet and video equipment?",
   "BNC",
   ["F-type","SC","RJ11"],
   "BNC es el conector coaxial de bayoneta: se empuja y se gira para fijarlo.",
   ["F-type se enrosca.","SC es para fibra.","RJ11 es telefónico."]],

  ["1.5","m","connectors,fiber",
   "Which fiber connector has a square body and snaps in with a push-pull motion?",
   "SC",
   ["ST","BNC","MPO"],
   "SC (Subscriber/Standard Connector) es cuadrado y encaja a presión (push-pull).",
   ["ST es redondo, de bayoneta.","BNC es coaxial.","MPO lleva muchas fibras en un conector rectangular."]],

  ["1.5","m","connectors,fiber",
   "Which fiber connector has a round body and locks with a bayonet-style twist?",
   "ST",
   ["SC","LC","F-type"],
   "ST (Straight Tip) es redondo y se fija girándolo, como una bayoneta.",
   ["SC es cuadrado y se empuja.","LC es pequeño con una pestaña de clip.","F-type es coaxial y se enrosca."]],

  ["1.5","m","wireless,satellite",
   "A remote site uses satellite internet. Which characteristic is MOST likely to affect real-time applications?",
   "High latency, especially with geostationary satellites",
   ["Complete immunity to weather","Very short range","Guaranteed lower latency than a terrestrial fiber connection"],
   "Los satélites geoestacionarios están a unos 36 000 km: la señal tarda mucho en ir y volver. Las constelaciones de órbita baja (LEO) reducen ese retardo.",
   ["La lluvia y las tormentas sí afectan a la señal de satélite.","Precisamente cubre grandes distancias.","La fibra tiene mucha menos latencia que el satélite geoestacionario."]],

  ["1.5","m","wireless,cellular",
   "A branch office wants a backup WAN link that needs no new cabling if the primary fiber line fails. What is a good option?",
   "Cellular (4G/5G) router",
   ["Additional Cat 6a patch cables","A second hub","A plenum-rated fiber run"],
   "Un router celular (4G/5G) da un enlace de respaldo inalámbrico sin instalar cableado nuevo.",
   ["Los latiguillos no conectan la sede con internet.","Un hub no proporciona un enlace WAN.","Una nueva fibra requiere obra y probablemente comparte la misma ruta física."]],

  ["1.5","e","coax",
   "Cable internet service is typically delivered to a home over which medium?",
   "Coaxial cable",
   ["Multimode fiber patch cords","Cat 3 telephone wire only","Twinaxial DAC"],
   "El internet por cable (DOCSIS) llega por cable coaxial, el mismo de la televisión.",
   ["La multimodo se usa dentro de edificios y centros de datos.","El cable telefónico se usa para DSL, no para cable.","El DAC es para distancias de pocos metros dentro de un rack."]],

  ["1.5","e","ethernet,standards",
   "Which IEEE standard family defines wired Ethernet?",
   "802.3",
   ["802.11","802.1X","802.15"],
   "IEEE 802.3 es la familia de Ethernet cableado (10BASE-T, 1000BASE-T, 10GBASE-SR…).",
   ["802.11 es Wi-Fi.","802.1X es control de acceso por puerto.","802.15 es para redes personales como Bluetooth."]],

  ["1.5","m","transceivers,storage",
   "A storage team orders transceivers for a SAN that uses a protocol other than Ethernet. Which protocol are they MOST likely using?",
   "Fibre Channel",
   ["802.11","DOCSIS","Bluetooth"],
   "Muchas SAN (Storage Area Network) usan Fibre Channel, que tiene sus propios transceptores (también en formato SFP).",
   ["802.11 es Wi-Fi.","DOCSIS es internet por cable coaxial.","Bluetooth es una red personal inalámbrica."]],

  ["1.5","e","fiber,emi",
   "A cable run must pass next to large electric motors that create strong electromagnetic interference. Which medium is BEST?",
   "Fiber optic",
   ["Unshielded twisted pair","Coaxial cable","Cat 5e UTP"],
   "La fibra transmite luz, no electricidad, así que la EMI (Electromagnetic Interference) no la afecta.",
   ["El UTP (Unshielded Twisted Pair) es muy sensible a la interferencia.","El coaxial está blindado, pero sigue siendo cobre.","Cat 5e UTP es cobre sin blindaje."]],

  ["1.5","m","fiber,copper",
   "Which of the following are advantages of fiber optic cable over copper twisted pair? (Choose TWO)",
   ["Supports much longer distances","Immune to electromagnetic interference"],
   ["Cheaper and easier to terminate","Can deliver PoE to phones","Uses standard RJ45 connectors"],
   "La fibra llega mucho más lejos y no le afecta la EMI.",
   ["Terminar fibra es más caro y delicado que el cobre.","PoE (Power over Ethernet) necesita cobre.","La fibra usa LC, SC, ST o MPO, no RJ45."]],

  ["1.5","h","fiber,standards",
   "What does 10GBASE-SR describe?",
   "10 Gbps Ethernet over multimode fiber for short distances",
   ["10 Gbps Ethernet over single-mode fiber for long distances","10 Gbps Ethernet over Cat 6a copper","10 Mbps Ethernet over coaxial cable"],
   "10GBASE-SR (Short Reach) es 10 Gbps sobre fibra multimodo, del orden de cientos de metros.",
   ["Eso es 10GBASE-LR (Long Reach).","Eso es 10GBASE-T.","10 Mbps sobre coaxial es un estándar muy antiguo (10BASE2/10BASE5)."]],

  ["1.6","e","topologies",
   "Every device in an office connects to a single central switch. Which physical topology is this?",
   "Star",
   ["Bus","Ring","Full mesh"],
   "En estrella todos los equipos van a un punto central (el switch).",
   ["En bus todos comparten un único cable.","En anillo cada equipo se une al siguiente formando un círculo.","En malla completa todos se conectan con todos."]],

  ["1.6","m","topologies,mesh",
   "Which topology connects every site directly to every other site, giving the highest redundancy?",
   "Full mesh",
   ["Hub-and-spoke","Star","Point-to-point"],
   "En malla completa (full mesh) cada nodo tiene un enlace con todos los demás: si cae uno, hay caminos alternativos.",
   ["En hub-and-spoke todo pasa por un centro.","En estrella todo depende de un equipo central.","Punto a punto une solo dos extremos."]],

  ["1.6","h","topologies,mesh",
   "How many links are needed to connect six sites in a full mesh?",
   "15",
   ["6","12","30"],
   "Fórmula: n × (n − 1) / 2 = 6 × 5 / 2 = 15 enlaces.",
   ["6 es el número de sitios, no de enlaces.","12 no sale de la fórmula.","30 es n × (n − 1), contando cada enlace dos veces."]],

  ["1.6","m","topologies,mesh",
   "A WAN design connects the three most critical sites to each other, while smaller branches connect only to the nearest critical site. Which topology is this?",
   "Partial mesh",
   ["Full mesh","Bus","Ring"],
   "Una malla parcial conecta directamente solo algunos nodos (los críticos): redundancia donde importa, a menor coste.",
   ["En malla completa todos los sitios estarían conectados con todos.","En bus todos comparten un único medio.","En anillo cada sitio se uniría solo con dos vecinos."]],

  ["1.6","e","topologies,wan",
   "Twenty branch offices each connect only to headquarters, and branch-to-branch traffic passes through headquarters. Which topology is this?",
   "Hub-and-spoke",
   ["Full mesh","Spine and leaf","Point-to-point"],
   "Hub-and-spoke: el centro (hub, la sede) conecta con cada rama (spoke). Es el equivalente WAN de la estrella.",
   ["En malla completa las sucursales se conectarían entre sí.","Spine and leaf es un diseño de centro de datos.","Punto a punto es un único enlace entre dos sitios."]],

  ["1.6","e","topologies,wan",
   "A company leases a dedicated circuit that connects only its two offices. Which topology is this?",
   "Point-to-point",
   ["Hub-and-spoke","Mesh","Star"],
   "Un enlace dedicado entre exactamente dos extremos es una topología punto a punto.",
   ["Hub-and-spoke implica un centro con varias ramas.","Una malla implica varios enlaces entre varios sitios.","Una estrella implica muchos equipos alrededor de un centro."]],

  ["1.6","m","spine-leaf,data-center",
   "In a spine-and-leaf data center design, how are the switches connected?",
   "Every leaf switch connects to every spine switch",
   ["Every leaf connects to every other leaf","Spine switches connect directly to servers","Each leaf connects to only one spine"],
   "En spine and leaf cada leaf (hoja) se conecta a todos los spines (columna). Así cualquier servidor está a la misma distancia de cualquier otro.",
   ["Las leafs no se conectan entre sí.","Los servidores se conectan a las leafs, no a los spines.","Con un solo spine por leaf se perderían la redundancia y el reparto de carga."]],

  ["1.6","m","spine-leaf,data-center",
   "In a spine-and-leaf architecture, where do the servers connect?",
   "To the leaf switches",
   ["To the spine switches","Directly to the core router","To each other in a ring"],
   "Las leafs son los switches de acceso (a menudo top-of-rack) donde se conectan los servidores; los spines solo interconectan leafs.",
   ["Los spines no reciben servidores.","El router de core no es parte del diseño spine and leaf.","Los servidores no forman anillos entre sí."]],

  ["1.6","h","spine-leaf,data-center",
   "Why is spine-and-leaf well suited to modern data centers?",
   "Predictable, low latency for east-west traffic",
   ["It removes the need for any redundant links","It forces all traffic through a single core switch","It is designed mainly for wireless clients"],
   "Cualquier servidor llega a cualquier otro en el mismo número de saltos (leaf → spine → leaf), ideal para el mucho tráfico este-oeste de hoy.",
   ["Precisamente se basa en múltiples enlaces redundantes.","No hay un único core; hay varios spines.","Es un diseño para servidores de centro de datos, no para Wi-Fi."]],

  ["1.6","e","three-tier",
   "In the three-tier hierarchical model, which layer do end-user devices and access points connect to?",
   "Access layer",
   ["Core layer","Distribution layer","Spine layer"],
   "La capa de acceso es donde se enchufan PCs, teléfonos, impresoras y APs.",
   ["El core es la columna vertebral de alta velocidad; no recibe usuarios.","La distribución agrega los switches de acceso y aplica políticas.","Spine pertenece a otro diseño (spine and leaf)."]],

  ["1.6","m","three-tier",
   "Which layer of the three-tier model provides fast, highly available transport between distribution blocks with minimal policy processing?",
   "Core layer",
   ["Access layer","Distribution layer","Leaf layer"],
   "El core es la columna vertebral: mueve tráfico muy rápido y con redundancia, sin filtrados pesados.",
   ["El acceso conecta dispositivos finales.","La distribución aplica políticas y enruta entre VLANs.","Leaf pertenece a spine and leaf."]],

  ["1.6","m","three-tier",
   "In the three-tier model, which layer typically aggregates access switches and applies policies such as routing between VLANs and ACLs?",
   "Distribution layer",
   ["Core layer","Access layer","Physical layer"],
   "La capa de distribución agrega los switches de acceso y aplica políticas: enrutamiento entre VLANs, ACLs, QoS.",
   ["El core debe ser lo más simple y rápido posible.","El acceso solo conecta a los usuarios.","La capa física es del modelo OSI, no del diseño jerárquico."]],

  ["1.6","m","collapsed-core",
   "A medium-sized campus combines the core and distribution functions into one pair of switches to save cost. What is this design called?",
   "Collapsed core",
   ["Spine and leaf","Full mesh","Hub-and-spoke"],
   "Collapsed core junta las capas de core y distribución en los mismos equipos: queda un diseño de dos niveles, más barato para redes medianas.",
   ["Spine and leaf es un diseño de centro de datos.","Full mesh conecta todos con todos.","Hub-and-spoke es un diseño WAN con un centro."]],

  ["1.6","m","traffic-flows",
   "Traffic between a web server and a database server inside the same data center is described as:",
   "East-west traffic",
   ["North-south traffic","Broadcast traffic","WAN traffic"],
   "Este-oeste es el tráfico lateral dentro del centro de datos, de servidor a servidor.",
   ["Norte-sur es tráfico que entra o sale del centro de datos.","Broadcast es un tipo de entrega, no una dirección de flujo.","No sale a la WAN."]],

  ["1.6","m","traffic-flows",
   "Traffic from internet users entering the data center to reach a public website is described as:",
   "North-south traffic",
   ["East-west traffic","Multicast traffic","Loopback traffic"],
   "Norte-sur es el tráfico que cruza el borde del centro de datos, hacia dentro o hacia fuera.",
   ["Este-oeste es interno, de servidor a servidor.","Multicast es un tipo de entrega, no una dirección de flujo.","Loopback es tráfico de un equipo consigo mismo."]],

  ["1.6","m","topologies,mesh",
   "What is the main disadvantage of a full mesh topology?",
   "High cost and complexity from the many links",
   ["No redundancy if any one link fails","A single point of failure in the center","Only two devices can be connected"],
   "El número de enlaces crece muy rápido (n × (n − 1) / 2), así que una malla completa es cara y compleja.",
   ["Es la topología con más redundancia.","No tiene un centro único.","Conecta a muchos nodos, no solo a dos."]],

  ["1.6","e","topologies,star",
   "In a star topology, what is the single point of failure?",
   "The central switch",
   ["Each end device","The patch cables between end devices","There is none"],
   "Si cae el switch central, todos los equipos que dependen de él pierden la conexión.",
   ["Si cae un equipo final, solo lo afecta a él.","En estrella los equipos no se conectan entre sí.","Sí lo hay: el centro."]],

  ["1.6","m","topologies,wan",
   "What is a drawback of hub-and-spoke WAN designs?",
   "The hub is a single point of failure",
   ["Every branch needs a link to every other branch","It is the most expensive WAN topology","It cannot carry encrypted traffic"],
   "Todo pasa por el hub: si cae, las sucursales quedan aisladas, y el tráfico entre sucursales da un rodeo.",
   ["Eso describe la malla completa.","La malla completa suele ser más cara.","Puede llevar tráfico cifrado (VPNs) sin problema."]],

  ["1.6","h","spine-leaf",
   "Which of the following are characteristics of a spine-and-leaf architecture? (Choose TWO)",
   ["Every leaf switch connects to every spine switch","Any two servers on different leafs are the same number of hops apart"],
   ["Leaf switches connect to each other in a ring","Servers connect directly to spine switches","It depends on STP blocking half of the uplinks"],
   "Cada leaf se conecta a todos los spines, y cualquier par de servidores en leafs distintas está a leaf → spine → leaf.",
   ["Las leafs no se interconectan entre sí.","Los servidores se conectan a las leafs.","Normalmente se usa enrutamiento con varios caminos activos (ECMP), no STP bloqueando enlaces."]],

  ["1.7","e","ipv4,private",
   "Which of the following is an RFC 1918 private IPv4 address?",
   "172.20.14.9",
   ["172.32.14.9","8.8.4.4","11.0.0.5"],
   "Los rangos privados son 10.0.0.0/8, 172.16.0.0/12 (de 172.16 a 172.31) y 192.168.0.0/16. 172.20 está dentro del segundo.",
   ["172.32 queda fuera del rango (acaba en 172.31).","8.8.4.4 es una dirección pública (DNS de Google).","11.x es público; el rango privado es solo 10.x."]],

  ["1.7","e","ipv4,apipa",
   "Which address range does APIPA use?",
   "169.254.0.0/16",
   ["127.0.0.0/8","192.168.0.0/16","224.0.0.0/4"],
   "APIPA (Automatic Private IP Addressing) usa 169.254.x.x: el equipo se la pone a sí mismo cuando no consigue respuesta de ningún servidor DHCP.",
   ["127.0.0.0/8 es loopback.","192.168.0.0/16 es un rango privado RFC 1918.","224.0.0.0/4 es multicast (clase D)."]],

  ["1.7","e","ipv4,loopback",
   "What is the purpose of the 127.0.0.1 address?",
   "Loopback, to test the host's own TCP/IP stack",
   ["It is the default gateway on every network","It is the broadcast address for all networks","It is reserved for DHCP servers"],
   "127.0.0.1 es la dirección de loopback: el equipo hablando consigo mismo. Hacer ping a 127.0.0.1 prueba la pila TCP/IP local.",
   ["El gateway es la dirección del router de cada red.","El broadcast limitado es 255.255.255.255.","No está reservada para DHCP."]],

  ["1.7","m","ipv4,classes",
   "An IPv4 address has a first octet of 150. Under classful addressing, which class is it?",
   "Class B",
   ["Class A","Class C","Class D"],
   "Clase A: 1–126 · Clase B: 128–191 · Clase C: 192–223 · Clase D (multicast): 224–239. 150 está en la B.",
   ["La clase A llega hasta 126.","La clase C empieza en 192.","La clase D es multicast (224–239)."]],

  ["1.7","m","ipv4,classes,multicast",
   "Which first-octet range belongs to Class D, used for multicast?",
   "224–239",
   ["192–223","128–191","240–255"],
   "La clase D (224.0.0.0 a 239.255.255.255) está reservada para multicast.",
   ["192–223 es la clase C.","128–191 es la clase B.","240–255 es la clase E, experimental."]],

  ["1.7","e","ipv4,gateway",
   "What is the role of the default gateway configured on a host?",
   "It is the router that forwards traffic to other networks",
   ["It assigns IP addresses to the host when it boots","It translates hostnames into IP addresses for the host","It is the address of the local switch"],
   "Cuando el destino no está en su subred, el equipo manda el tráfico al gateway (el router), que lo lleva fuera.",
   ["Eso lo hace DHCP.","Eso lo hace DNS.","El switch de capa 2 no necesita IP para reenviar tramas y no es el gateway."]],

  ["1.7","m","ipv4,vlsm",
   "What is the main benefit of variable length subnet masking (VLSM)?",
   "Subnets sized to need, wasting fewer addresses",
   ["Every subnet must use the same mask","It removes the need for a default gateway on each subnet","It converts IPv4 addresses into IPv6"],
   "Con VLSM (Variable Length Subnet Mask) cada subred usa la máscara que necesita: por ejemplo, /30 para un enlace entre routers y /24 para una oficina.",
   ["Eso es justo lo contrario de VLSM.","Las subredes siguen necesitando gateway para salir.","VLSM no tiene nada que ver con IPv6."]],

  ["1.7","m","ipv4,nat",
   "Why do most organizations use private IPv4 addresses internally with NAT at the edge?",
   "To conserve scarce public IPv4 addresses",
   ["Because private addresses are faster","Because NAT encrypts all traffic","Because routers cannot forward public addresses"],
   "Las direcciones IPv4 públicas escasean. Con direcciones privadas dentro y NAT (Network Address Translation) en el borde, muchos equipos salen con pocas IPs públicas.",
   ["La velocidad no depende de que la IP sea privada o pública.","NAT traduce direcciones; no cifra.","Los routers de internet reenvían direcciones públicas; son las privadas las que no se enrutan en internet."]],

  ["1.7","h","ipv4,private",
   "Which of the following addresses are NOT routable on the public internet? (Choose TWO)",
   ["10.44.2.1","192.168.100.20"],
   ["8.8.8.8","172.32.10.5","64.233.160.4"],
   "10.x y 192.168.x son rangos privados RFC 1918 y no se enrutan en internet.",
   ["8.8.8.8 es pública.","172.32.x está justo fuera del rango privado 172.16–172.31, así que es pública.","64.233.160.4 es una dirección pública."]],

  ["1.8","m","sdn",
   "What is the key idea behind software-defined networking (SDN)?",
   "Separating the control plane from the data plane",
   ["Replacing all switches with hubs","Running every network device without any software","Using only static routes"],
   "SDN (Software-Defined Networking) saca la 'inteligencia' (plano de control) a un controlador central, y los equipos se dedican a reenviar (plano de datos).",
   ["Los hubs no tienen nada que ver con SDN.","SDN es precisamente software.","SDN no obliga a usar rutas estáticas."]],

  ["1.8","m","sd-wan",
   "A company wants branch routers to choose between MPLS, broadband and LTE links per application, based on real-time link quality. Which technology provides this?",
   "SD-WAN",
   ["VXLAN","Spanning Tree Protocol","NAT64"],
   "SD-WAN (Software-Defined WAN) es consciente de las aplicaciones y elige el mejor enlace para cada una según su calidad. Además, le da igual el tipo de transporte.",
   ["VXLAN extiende redes de capa 2 sobre capa 3.","STP evita bucles en capa 2.","NAT64 traduce entre IPv6 e IPv4."]],

  ["1.8","m","sd-wan",
   "A new SD-WAN appliance is shipped to a branch, plugged in by non-technical staff, and automatically downloads its configuration from the central controller. What is this feature called?",
   "Zero-touch provisioning",
   ["Configuration drift","Port mirroring","Split tunneling"],
   "Zero-touch provisioning: el equipo se configura solo desde el controlador, sin que nadie técnico esté en la sucursal.",
   ["La desviación de configuración es un problema, no una función.","Port mirroring copia tráfico para analizarlo.","Split tunneling es un modo de VPN."]],

  ["1.8","h","vxlan",
   "What does VXLAN do?",
   "Tunnels Layer 2 frames over a Layer 3 network (UDP)",
   ["Encrypts Wi-Fi traffic between access points and the wireless controller","Replaces DHCP in data centers","Assigns IPv6 addresses automatically to hosts in each data center"],
   "VXLAN (Virtual Extensible LAN) mete tramas de capa 2 dentro de paquetes UDP/IP para extender segmentos de capa 2 sobre una red enrutada. Usa un identificador de 24 bits (unos 16 millones de segmentos).",
   ["VXLAN no cifra el Wi-Fi.","No asigna direcciones.","La autoconfiguración de IPv6 es SLAAC, no VXLAN."]],

  ["1.8","m","vxlan,dci",
   "Two data centers need virtual machines to keep the same Layer 2 segment when they move between sites over a routed link. Which technology is commonly used?",
   "VXLAN",
   ["STP","PoE","SNMP"],
   "VXLAN se usa para la interconexión de centros de datos (DCI, Data Center Interconnect): extiende el segmento de capa 2 por encima de la red enrutada.",
   ["STP evita bucles; no extiende segmentos entre sitios.","PoE da electricidad por el cable.","SNMP monitoriza dispositivos."]],

  ["1.8","e","zero-trust",
   "Which statement BEST describes a zero trust architecture?",
   "Nothing is trusted by default; every request is verified",
   ["Devices inside the corporate LAN are trusted automatically","Only external users need to authenticate","Firewalls are no longer needed"],
   "Zero Trust: 'nunca confíes, verifica siempre'. Estar dentro de la red no da confianza automática; cada acceso se autentica y autoriza con el mínimo privilegio.",
   ["Confiar por estar dentro es justo el modelo antiguo que Zero Trust elimina.","Todos se verifican, internos y externos.","Zero Trust no elimina los firewalls; añade verificación continua."]],

  ["1.8","m","sase",
   "Which model combines SD-WAN networking with cloud-delivered security services such as secure web gateway and zero trust network access?",
   "SASE",
   ["VXLAN","IaC","NAT64"],
   "SASE (Secure Access Service Edge) une SD-WAN con servicios de seguridad prestados desde la nube.",
   ["VXLAN extiende capa 2 sobre capa 3.","IaC es gestionar infraestructura como código.","NAT64 traduce IPv6 a IPv4."]],

  ["1.8","h","sse,sase",
   "How does SSE differ from SASE?",
   "SSE is the cloud security part of SASE, without SD-WAN",
   ["SSE is the SD-WAN networking part of SASE, without any security","SSE is an older name for VLANs","SSE only works on-premises"],
   "SSE (Security Service Edge) es la parte de seguridad de SASE (pasarela web segura, ZTNA, CASB…) sin la parte de red SD-WAN.",
   ["Es al revés: SSE es la seguridad sin SD-WAN.","No tiene nada que ver con las VLANs.","SSE se entrega desde la nube."]],

  ["1.8","e","iac,automation",
   "What is infrastructure as code (IaC)?",
   "Defining infrastructure in files that tools deploy",
   ["Writing and running application code directly on network switches","Physically labeling every cable","Configuring each device by hand through its graphical interface only"],
   "IaC (Infrastructure as Code): la infraestructura se describe en archivos (plantillas, playbooks) que se aplican automáticamente. El resultado es repetible y versionable.",
   ["No se trata de programar aplicaciones en los switches.","Etiquetar cables es documentación física.","IaC reemplaza precisamente la configuración manual por interfaz gráfica."]],

  ["1.8","m","iac,configuration-drift",
   "Over months, engineers make manual one-off changes to servers, so they no longer match their approved templates. What is this called?",
   "Configuration drift",
   ["Elasticity","Zero-touch provisioning","Anycast"],
   "La desviación de configuración (configuration drift) aparece cuando los equipos se alejan poco a poco de su configuración aprobada por cambios manuales. IaC la evita reaplicando la plantilla.",
   ["La elasticidad es escalar automáticamente.","Zero-touch provisioning es autoconfigurar equipos nuevos.","Anycast es un tipo de entrega de tráfico."]],

  ["1.8","e","iac,version-control",
   "Why should IaC templates and network configurations be stored in a version control system?",
   "To track changes and roll back",
   ["To make the files run faster on devices","To encrypt all network traffic","To avoid needing any separate backups of the devices"],
   "El control de versiones guarda el historial de cambios: quién cambió qué, cuándo y por qué. Permite comparar versiones, trabajar en ramas y volver atrás.",
   ["No cambia la velocidad de ejecución.","No cifra el tráfico de red.","Ayuda mucho, pero no sustituye las copias de seguridad."]],

  ["1.8","m","ipv6,transition",
   "A network runs IPv4 and IPv6 at the same time on the same interfaces so hosts can use either protocol. What is this called?",
   "Dual stack",
   ["NAT64","Tunneling","Anycast"],
   "Dual stack: cada equipo tiene direcciones IPv4 e IPv6 a la vez y usa la que corresponda según el destino.",
   ["NAT64 traduce entre protocolos, no los ejecuta a la vez.","Tunneling encapsula un protocolo dentro del otro.","Anycast es un tipo de entrega de tráfico."]],

  ["1.8","h","ipv6,transition",
   "IPv6-only clients must reach services that only have IPv4 addresses. Which technology translates between them?",
   "NAT64",
   ["Dual stack","VXLAN","SLAAC"],
   "NAT64 traduce el tráfico de clientes IPv6 hacia servidores IPv4 (normalmente junto con DNS64).",
   ["Con dual stack los clientes necesitarían también IPv4.","VXLAN extiende capa 2; no traduce protocolos.","SLAAC autoconfigura direcciones IPv6; no traduce."]],

  ["1.8","m","ipv6,transition",
   "Two IPv6 islands must communicate across an ISP that only supports IPv4. Which approach carries IPv6 packets inside IPv4?",
   "Tunneling",
   ["Dual stack","NAT64","DHCP relay"],
   "Un túnel encapsula los paquetes IPv6 dentro de IPv4 para cruzar la red que solo entiende IPv4.",
   ["Dual stack exige que toda la red soporte los dos protocolos.","NAT64 traduce entre clientes y servidores, no une islas IPv6.","El relay DHCP reenvía peticiones DHCP a otra subred."]],

  ["1.8","e","ipv6",
   "What is the main reason IPv6 was developed?",
   "The IPv4 address space was running out",
   ["IPv4 cannot carry TCP traffic","IPv4 does not work over fiber","IPv6 removes the need for routing"],
   "IPv4 tiene unos 4300 millones de direcciones (32 bits) y se agotaron. IPv6 usa 128 bits, un espacio prácticamente ilimitado.",
   ["IPv4 transporta TCP sin problema.","IPv4 funciona sobre cualquier medio.","IPv6 sigue necesitando enrutamiento."]],
];

export default q;
