import type { Raw } from '../types';

// 1.6 (+1) · 2.1 Routing technologies (55)
const q: Raw[] = [
  ["1.6","e","topologies",
   "A campus uses a star topology in each building, and the buildings are joined to each other in a partial mesh. What is the overall topology called?",
   "Hybrid",
   ["Bus","Ring","Point-to-point"],
   "Cuando se combinan varias topologías (aquí estrella y malla parcial), el conjunto se llama topología híbrida.",
   ["En bus todo compartiría un único cable.","En anillo cada nodo se une solo a dos vecinos.","Punto a punto es un único enlace entre dos extremos."]],

  ["2.1","e","routing,static",
   "What is a static route?",
   "A route that an administrator enters manually on the router",
   ["A route learned automatically from OSPF neighbors in the area","A route that changes every few seconds","A route assigned by DHCP"],
   "Una ruta estática la escribe a mano el administrador y no cambia sola.",
   ["Las rutas aprendidas por OSPF son dinámicas.","Una ruta estática no cambia hasta que alguien la modifica.","DHCP entrega un gateway a los hosts, pero no crea rutas en los routers."]],

  ["2.1","m","routing,static",
   "Which is an advantage of static routing compared with dynamic routing?",
   "No routing protocol overhead and completely predictable paths",
   ["Automatic rerouting around failed links","Easier to manage in very large networks","Routes are learned from neighbors automatically, with no typing"],
   "Las rutas estáticas no consumen CPU ni ancho de banda en intercambiar información, y el camino es siempre el que definiste.",
   ["Eso es una ventaja del enrutamiento dinámico.","En redes grandes las rutas estáticas son difíciles de mantener.","Aprender de los vecinos es lo que hace el enrutamiento dinámico."]],

  ["2.1","e","routing,static",
   "What is the main disadvantage of static routes in a large network?",
   "They do not adapt when a link fails and are hard to maintain",
   ["They use too much bandwidth for updates","They cannot be used for a default route to the internet or ISP","They require OSPF to be enabled on every router"],
   "Si un enlace cae, la ruta estática sigue apuntando al camino roto hasta que alguien la cambia a mano. Con cientos de redes, mantenerlas es inviable.",
   ["Las estáticas no envían actualizaciones.","La ruta por defecto suele ser precisamente estática.","Las estáticas funcionan sin ningún protocolo de enrutamiento."]],

  ["2.1","e","routing,default-route",
   "What does the route 0.0.0.0/0 represent in a routing table?",
   "The default route, the last-resort match",
   ["The loopback network of the router","An invalid route that is always ignored","The broadcast address of the network"],
   "0.0.0.0/0 coincide con cualquier destino: es la ruta por defecto, la última opción cuando ninguna otra encaja.",
   ["Loopback es 127.0.0.0/8.","Es una ruta válida y muy usada.","El broadcast es otra cosa; 0.0.0.0/0 es 'cualquier red'."]],

  ["2.1","m","routing,default-route",
   "A branch office has a single WAN link to headquarters. What is the simplest way to route all non-local traffic to HQ?",
   "Configure a static default route pointing to the HQ router",
   ["Run BGP with the headquarters router","Configure a static route for every remote subnet at headquarters","Disable routing on the branch router"],
   "Con una sola salida no hay nada que decidir: una ruta por defecto estática manda todo lo que no es local hacia la sede.",
   ["BGP es excesivo para una red con una sola salida.","Funcionaría, pero es mucho más trabajo y más propenso a errores.","Sin enrutamiento la sucursal no podría salir de su red."]],

  ["2.1","e","routing,dynamic",
   "What is the main advantage of dynamic routing protocols?",
   "Routers learn routes and adapt to changes automatically",
   ["They never use CPU or memory","They are always more secure than static routes in any network","They require no configuration at all"],
   "Los protocolos dinámicos intercambian información entre routers y recalculan caminos solos cuando algo falla.",
   ["Consumen CPU, memoria y algo de ancho de banda.","No son más seguros por defecto; hay que protegerlos (por ejemplo, con autenticación).","Hay que configurarlos, aunque mucho menos que ruta por ruta."]],

  ["2.1","e","routing,ospf",
   "OSPF is best described as which type of routing protocol?",
   "Link-state",
   ["Distance-vector","Path-vector","Exterior gateway protocol"],
   "OSPF (Open Shortest Path First) es de estado de enlace: cada router conoce el mapa completo del área y calcula el mejor camino.",
   ["Los de vector distancia solo saben lo que les cuentan sus vecinos.","Path-vector es BGP.","OSPF es un protocolo interior (IGP), no exterior."]],

  ["2.1","m","routing,ospf",
   "Which metric does OSPF use to choose the best path?",
   "Cost, based on bandwidth",
   ["Hop count only","Administrative distance","The router's MAC address on the link"],
   "OSPF usa el coste: cuanto más ancho de banda tiene un enlace, menor es su coste. Gana el camino con menor coste total.",
   ["Contar saltos es propio de RIP.","La distancia administrativa compara fuentes de rutas, no caminos dentro de OSPF.","La MAC no interviene en la métrica."]],

  ["2.1","m","routing,ospf",
   "In a multi-area OSPF design, which area must all other areas connect to?",
   "Area 0 (the backbone area)",
   ["Area 1","The area with the most routers","Any area, as long as it is numbered"],
   "El área 0 es el backbone de OSPF: todas las demás áreas deben conectarse a ella.",
   ["El área 1 no tiene ningún papel especial.","El tamaño no convierte un área en backbone.","Las áreas no pueden conectarse al azar; el área 0 es obligatoria."]],

  ["2.1","m","routing,eigrp",
   "Which routing protocol was developed by Cisco and is described as an advanced distance-vector (hybrid) protocol?",
   "EIGRP",
   ["OSPF","BGP","RIP"],
   "EIGRP (Enhanced Interior Gateway Routing Protocol) nació en Cisco y combina ideas del vector distancia con mecanismos de convergencia rápida.",
   ["OSPF es un estándar abierto de estado de enlace.","BGP es path-vector y exterior.","RIP es un vector distancia básico y antiguo."]],

  ["2.1","e","routing,bgp",
   "Which routing protocol is used to exchange routes between autonomous systems, such as between ISPs on the internet?",
   "BGP",
   ["OSPF","EIGRP","STP"],
   "BGP (Border Gateway Protocol) es el protocolo exterior que une los sistemas autónomos: es el enrutamiento de internet.",
   ["OSPF es un protocolo interior.","EIGRP es un protocolo interior.","STP evita bucles en capa 2; no enruta."]],

  ["2.1","h","routing,bgp",
   "BGP is classified as which type of routing protocol?",
   "Path-vector",
   ["Link-state","Distance-vector with hop count","First hop redundancy protocol"],
   "BGP es de vector de ruta (path-vector): anuncia la lista de sistemas autónomos que hay que atravesar, y eso le permite evitar bucles y aplicar políticas.",
   ["Link-state es OSPF.","Contar saltos es propio de RIP.","Los FHRP (como VRRP o HSRP) dan redundancia al gateway."]],

  ["2.1","m","routing,bgp",
   "An enterprise connects to two different ISPs and wants to exchange routes with both to control inbound and outbound paths. Which protocol does it need?",
   "BGP",
   ["OSPF","EIGRP","VRRP"],
   "Para intercambiar rutas con varios ISP (multihoming) se usa BGP, el protocolo entre sistemas autónomos.",
   ["OSPF es para dentro de tu organización.","EIGRP es para dentro de tu organización.","VRRP da redundancia al gateway; no intercambia rutas."]],

  ["2.1","m","routing,igp",
   "Which of the following are interior gateway protocols used inside one organization's network? (Choose TWO)",
   ["OSPF","EIGRP"],
   ["BGP","ARP","NAT"],
   "OSPF y EIGRP son IGPs (Interior Gateway Protocols): enrutan dentro de un mismo sistema autónomo.",
   ["BGP es el protocolo exterior entre sistemas autónomos.","ARP resuelve IP a MAC; no es enrutamiento.","NAT traduce direcciones; no es un protocolo de enrutamiento."]],

  ["2.1","h","routing,route-selection",
   "A router has two routes: 10.0.0.0/8 via Router A and 10.1.1.0/24 via Router B. Where does it send a packet destined for 10.1.1.50?",
   "Router B, because /24 is the longest prefix match",
   ["Router A, because /8 covers more addresses than a /24","Both routers equally","Router A, because it was learned first"],
   "La primera regla del router es la coincidencia de prefijo más largo: gana la ruta más específica que contiene el destino, aquí la /24.",
   ["Cubrir más direcciones no la hace preferida; es menos específica.","Solo reparte carga entre rutas iguales (mismo prefijo y métrica).","El orden en que se aprendieron no importa."]],

  ["2.1","h","routing,administrative-distance",
   "A router learns the exact same prefix from EIGRP (internal) and from OSPF. Using Cisco default values, which route is installed?",
   "EIGRP, because its AD (90) is lower than OSPF's (110)",
   ["The OSPF route, because link-state is always preferred","Both, with equal preference","Whichever has the lower metric, compared directly between protocols"],
   "Con el mismo prefijo, el router compara la distancia administrativa (AD): cuanto menor, más confianza. EIGRP interno tiene 90 y OSPF 110.",
   ["No hay preferencia automática por link-state; decide la AD.","Solo se instala la de menor AD.","Las métricas de protocolos distintos no se pueden comparar entre sí."]],

  ["2.1","m","routing,administrative-distance",
   "What does administrative distance represent?",
   "How trustworthy a route's source is; lower values are preferred",
   ["The physical distance to the destination network, in kilometers","The number of hops to the destination","The bandwidth of the outgoing interface"],
   "La distancia administrativa mide cuánto se fía el router de cada fuente de rutas (conectada, estática, OSPF…). Se usa para elegir entre fuentes distintas para el mismo prefijo.",
   ["No es una distancia física.","Los saltos son una métrica (como en RIP), no la AD.","El ancho de banda influye en métricas como la de OSPF, no en la AD."]],

  ["2.1","m","routing,administrative-distance",
   "Using Cisco defaults, what are the administrative distances of a directly connected network and a static route?",
   "0 and 1",
   ["1 and 0","90 and 110","110 and 120"],
   "Una red directamente conectada tiene AD 0 (máxima confianza) y una ruta estática tiene AD 1.",
   ["Está al revés.","90 y 110 son EIGRP interno y OSPF.","110 y 120 son OSPF y RIP."]],

  ["2.1","h","routing,floating-static",
   "An administrator configures a backup static route with an administrative distance of 200 so it is used only if the primary dynamic route disappears. What is this called?",
   "Floating static route",
   ["Default gateway","Virtual IP","Summary route"],
   "Una ruta estática flotante tiene una AD más alta a propósito: queda 'flotando' sin usarse hasta que la ruta principal desaparece.",
   ["El default gateway es la configuración de los hosts.","La VIP (Virtual IP) es de los protocolos de redundancia del gateway.","Una ruta resumen agrupa varias redes en un prefijo."]],

  ["2.1","m","routing,metric",
   "When does a router use the routing metric to choose between routes?",
   "With several routes to one prefix from the same protocol",
   ["When routes to a prefix come from different routing protocols","When the prefixes have different lengths","Only for static routes"],
   "La métrica decide dentro de un mismo protocolo. Entre protocolos distintos decide la distancia administrativa, y antes de todo, el prefijo más largo.",
   ["Entre protocolos distintos decide la AD.","Con prefijos distintos gana el más largo.","Las rutas estáticas normalmente no tienen métrica que comparar."]],

  ["2.1","m","routing,ospf,metric",
   "OSPF learns two paths to 172.16.8.0/24: one with cost 20 and one with cost 45. Which does it use?",
   "The path with cost 20",
   ["The path with cost 45","Both paths equally","Neither, because the costs differ"],
   "En OSPF gana el camino con menor coste total.",
   ["Un coste mayor es peor.","Solo reparte carga cuando los costes son iguales.","Con costes distintos elige el menor; no descarta ambos."]],

  ["2.1","h","routing,ecmp",
   "OSPF finds two paths to the same prefix with identical cost. What does the router typically do?",
   "Install both and load-balance traffic across them",
   ["Choose the path learned first and ignore the other","Drop traffic to that prefix","Flag a routing loop and shut the interfaces"],
   "Con coste idéntico, el router puede instalar ambas rutas y repartir el tráfico (ECMP, Equal-Cost Multi-Path).",
   ["No hace falta descartar una si son igual de buenas.","No hay motivo para descartar el tráfico.","Dos caminos iguales no son un bucle."]],

  ["2.1","m","routing,routing-table",
   "A router receives a packet for a destination that matches no route, and it has no default route. What happens?",
   "It drops the packet and may send ICMP destination unreachable",
   ["It floods the packet out of every interface","It sends the packet back to the source","It forwards the packet to the nearest switch and lets it decide"],
   "Sin ninguna ruta que coincida (ni ruta por defecto), el router no sabe adónde enviarlo: lo descarta y suele avisar con ICMP.",
   ["Los routers no inundan paquetes como hace un switch con las tramas.","No lo devuelve; como mucho envía un aviso ICMP.","No existe esa lógica en un router."]],

  ["2.1","e","nat",
   "What does NAT do?",
   "Translates IP addresses, typically private to public",
   ["Assigns IP addresses to clients","Resolves hostnames to IP addresses for internal clients","Encrypts traffic between sites"],
   "NAT (Network Address Translation) cambia las direcciones IP de los paquetes al pasar por el router o firewall, normalmente de privadas a públicas.",
   ["Eso es DHCP.","Eso es DNS.","Eso es una VPN."]],

  ["2.1","m","nat,pat",
   "Two hundred internal hosts share one public IPv4 address to browse the internet. The router keeps them apart using source port numbers. What is this called?",
   "PAT (NAT overload)",
   ["Static NAT","Dynamic NAT with a large pool","Port mirroring"],
   "PAT (Port Address Translation) permite que muchos equipos compartan una sola IP pública, diferenciando las conexiones por puerto.",
   ["Static NAT es uno a uno.","NAT dinámico usa un grupo de IPs públicas, una por conexión activa.","Port mirroring copia tráfico para analizarlo."]],

  ["2.1","m","nat,static-nat",
   "A mail server with a private address must always be reachable from the internet at the same dedicated public IP. Which NAT type fits?",
   "Static NAT (one-to-one)",
   ["PAT","Dynamic NAT","APIPA"],
   "Static NAT asocia de forma fija una IP privada con una IP pública, así el servidor siempre es accesible en la misma dirección.",
   ["PAT comparte una IP entre muchos equipos, sobre todo para salir.","NAT dinámico no garantiza siempre la misma IP pública.","APIPA es autoasignación de 169.254.x.x."]],

  ["2.1","m","nat,port-forwarding",
   "A small office wants inbound connections to its public IP on TCP 443 sent to an internal web server at 192.168.1.20. What should be configured?",
   "Port forwarding (static PAT)",
   ["A default route pointing to 192.168.1.20","DHCP reservation for the router","An additional VLAN"],
   "Port forwarding reenvía las conexiones que llegan a un puerto de la IP pública hacia un equipo interno concreto.",
   ["Una ruta por defecto no traduce direcciones públicas a privadas.","Una reserva DHCP fija una IP interna, pero no abre la entrada desde internet.","Una VLAN separa redes; no publica servicios."]],

  ["2.1","e","nat,pat",
   "A home router lets ten devices share the single public IP address from the ISP. Which feature is doing this?",
   "PAT",
   ["Static NAT","STP","FHRP"],
   "Los routers domésticos usan PAT (NAT con sobrecarga): todos salen con la misma IP pública y se distinguen por puerto.",
   ["Static NAT es una IP pública por cada IP privada.","STP evita bucles en switches.","FHRP da redundancia al gateway."]],

  ["2.1","m","nat,dynamic-nat",
   "A router maps internal hosts to addresses taken from a pool of public IPs on a first-come, first-served basis. Which NAT type is this?",
   "Dynamic NAT",
   ["Static NAT","PAT with a single address","Port forwarding"],
   "NAT dinámico asigna a cada equipo interno una IP pública libre del grupo mientras dura su conexión.",
   ["Static NAT es una asociación fija.","PAT con una sola dirección diferencia por puerto, no por un grupo de IPs.","Port forwarding publica un servicio interno hacia fuera."]],

  ["2.1","e","nat",
   "After passing through the company's NAT router, what source IP address do internet servers see for an internal PC?",
   "The router's public IP address",
   ["The PC's private IP address","The PC's MAC address","The loopback address 127.0.0.1"],
   "NAT sustituye la IP privada por la pública del router, así que desde fuera solo se ve la IP pública.",
   ["La IP privada queda oculta tras el NAT.","Las MACs no cruzan los routers.","Loopback nunca sale de un equipo."]],

  ["2.1","e","fhrp",
   "What is the purpose of a first hop redundancy protocol (FHRP)?",
   "Provide a backup default gateway for hosts",
   ["Exchange routes between different ISPs on the internet","Prevent Layer 2 loops","Assign IP addresses to hosts"],
   "Un FHRP (First Hop Redundancy Protocol) hace que dos o más routers compartan el papel de gateway: si uno cae, otro sigue atendiendo.",
   ["Eso lo hace BGP.","Eso lo hace STP.","Eso lo hace DHCP."]],

  ["2.1","m","fhrp,vip",
   "In an FHRP deployment, what address do hosts use as their default gateway?",
   "A virtual IP address shared by the participating routers",
   ["The physical IP of whichever router each host prefers to use","The broadcast address of the subnet","The IP address of the DNS server"],
   "Los routers comparten una VIP (Virtual IP). Los hosts apuntan a esa VIP, y el router activo la atiende.",
   ["Si apuntaran a la IP física de un router, perderían conexión cuando cayera.","El broadcast no puede ser un gateway.","El DNS resuelve nombres; no es el gateway."]],

  ["2.1","m","fhrp",
   "Which of the following is a first hop redundancy protocol?",
   "VRRP",
   ["OSPF","BGP","STP"],
   "VRRP (Virtual Router Redundancy Protocol) es un FHRP de estándar abierto. HSRP es la versión propietaria de Cisco.",
   ["OSPF es un protocolo de enrutamiento.","BGP es un protocolo de enrutamiento exterior.","STP evita bucles en capa 2."]],

  ["2.1","h","fhrp",
   "What is the key difference between HSRP and VRRP?",
   "HSRP is Cisco proprietary, while VRRP is an open standard",
   ["HSRP routes between ISPs, while VRRP prevents Layer 2 loops","VRRP only works with IPv6","HSRP encrypts traffic, while VRRP does not"],
   "Los dos hacen lo mismo (gateway redundante con VIP). HSRP (Hot Standby Router Protocol) es de Cisco; VRRP es un estándar abierto.",
   ["Ninguno enruta entre ISPs ni evita bucles.","VRRP funciona con IPv4 e IPv6.","Ninguno cifra tráfico."]],

  ["2.1","m","fhrp",
   "Two routers run an FHRP. The active router loses power. What must be changed on the hosts to keep them online?",
   "Nothing; the standby router takes over the virtual IP",
   ["Every host needs a new default gateway configured","Hosts must renew DHCP to get a new gateway","The switch must be rebooted"],
   "El router en espera asume la VIP y su MAC virtual. Los hosts siguen usando el mismo gateway y no notan el cambio.",
   ["Esa es justo la ventaja del FHRP: no hay que tocar los hosts.","No hace falta renovar DHCP.","El switch no necesita reiniciarse."]],

  ["2.1","m","subinterfaces",
   "What is a router subinterface?",
   "A logical interface carved out of a physical one",
   ["A second physical port added to the router chassis","A backup power supply","A loopback used only for testing"],
   "Una subinterfaz divide una interfaz física en varias lógicas; cada una suele atender una VLAN con su propia IP.",
   ["Es lógica, no un puerto físico adicional.","No tiene nada que ver con la alimentación.","Las loopbacks son interfaces virtuales distintas."]],

  ["2.1","m","subinterfaces,inter-vlan",
   "A router has one physical link to a switch and routes between VLANs 10, 20 and 30 using 802.1Q-tagged subinterfaces. What is this design called?",
   "Router-on-a-stick",
   ["Spine and leaf","Collapsed core","Hub-and-spoke"],
   "Router-on-a-stick: un solo enlace trunk al switch, con una subinterfaz etiquetada por VLAN, para enrutar entre ellas.",
   ["Spine and leaf es un diseño de centro de datos.","Collapsed core junta core y distribución.","Hub-and-spoke es un diseño WAN."]],

  ["2.1","h","subinterfaces,trunking",
   "For router-on-a-stick to work, how must the switch port connected to the router be configured?",
   "As an 802.1Q trunk",
   ["As an access port in VLAN 1","As a mirror (SPAN) port for the router","Administratively down"],
   "El enlace hacia el router debe ser trunk 802.1Q para llevar las tramas de varias VLANs etiquetadas.",
   ["Un puerto de acceso lleva una sola VLAN.","Un puerto espejo solo copia tráfico.","Apagado no pasaría nada."]],

  ["2.1","m","routing,link-state",
   "What is a key difference between link-state and distance-vector routing protocols?",
   "Link-state routers map the whole topology; distance-vector trust neighbors",
   ["Distance-vector protocols always converge faster than link-state ones","Link-state protocols do not use metrics","Distance-vector protocols are only used between ISPs on the internet"],
   "En estado de enlace cada router conoce todo el mapa y calcula por sí mismo. En vector distancia solo sabe 'a qué distancia está cada red según mi vecino'.",
   ["Normalmente convergen más rápido los de estado de enlace.","Los de estado de enlace usan métrica (por ejemplo, el coste en OSPF).","El de internet es BGP, que es path-vector."]],

  ["2.1","m","routing,convergence",
   "In routing, what does convergence mean?",
   "All routers agree on an updated view of the network",
   ["Two VLANs have been merged into one","The router has rebooted","Traffic from several links is combined into one link with LACP"],
   "La convergencia es el momento en que todos los routers ya se han enterado de un cambio y sus tablas vuelven a ser coherentes.",
   ["Juntar VLANs no es convergencia.","Reiniciar no es converger.","LACP agrega enlaces; no es convergencia de enrutamiento."]],

  ["2.1","h","routing,ospf",
   "Why does OSPF generally converge faster than a basic distance-vector protocol such as RIP?",
   "It floods changes immediately and each router recalculates itself",
   ["It waits for periodic full routing-table updates every 30 seconds","It uses hop count as its only metric","It only runs on a single router"],
   "OSPF anuncia los cambios al momento y cada router recalcula con el algoritmo SPF. RIP espera sus actualizaciones periódicas.",
   ["Eso describe a RIP, que es lento.","Contar saltos es RIP.","OSPF corre en todos los routers del área."]],

  ["2.1","m","routing,autonomous-system",
   "What is an autonomous system (AS) in routing?",
   "Networks under one administrative control and routing policy",
   ["A router that configures its routing table without an administrator","A switch that runs STP automatically","A group of wireless access points"],
   "Un sistema autónomo es el conjunto de redes de una misma organización (un ISP, una gran empresa) con su propia política. BGP intercambia rutas entre ellos.",
   ["No es un tipo de router.","No tiene relación con STP.","No tiene que ver con Wi-Fi."]],

  ["2.1","e","routing,next-hop",
   "In a routing table entry, what is the next hop?",
   "The IP address of the next router on the path",
   ["The final destination host","The MAC address of the source","The number of routers left to the destination"],
   "El siguiente salto (next hop) es el router vecino al que se entrega el paquete para que siga su camino.",
   ["El destino final es la dirección de destino, no el siguiente salto.","La MAC de origen no está en la tabla de rutas.","Eso sería un recuento de saltos, no el siguiente salto."]],

  ["2.1","m","routing,administrative-distance",
   "Using Cisco defaults, what is the administrative distance of OSPF?",
   "110",
   ["90","120","1"],
   "OSPF tiene AD 110 por defecto. EIGRP interno 90, RIP 120 y las rutas estáticas 1.",
   ["90 es EIGRP interno.","120 es RIP.","1 es una ruta estática."]],

  ["2.1","m","routing,dynamic",
   "Which of the following are advantages of dynamic routing over static routing? (Choose TWO)",
   ["Automatic rerouting when a link fails","Scales better as the network grows"],
   ["Uses no router CPU or memory","More secure by default","Requires no configuration"],
   "El enrutamiento dinámico se adapta solo a los fallos y escala a redes grandes sin mantener cada ruta a mano.",
   ["Sí consume recursos del router.","No es más seguro por defecto.","Hay que configurarlo."]],

  ["2.1","h","nat,ipsec",
   "Why can NAT cause problems for IPsec using Authentication Header (AH)?",
   "NAT changes the IP header that AH protects, so the check fails",
   ["NAT encrypts the payload a second time, which AH then cannot read","AH only works over UDP 53","NAT removes the TCP header"],
   "AH verifica que la cabecera IP no cambie. Como NAT cambia la IP, la comprobación falla. Por eso con NAT se usa ESP con NAT traversal.",
   ["NAT no cifra nada.","AH no usa UDP 53 (ese es DNS).","NAT no elimina la cabecera TCP."]],

  ["2.1","h","routing,ospf",
   "How do OSPF routers learn the full topology of their area?",
   "They flood LSAs and build the same link-state database",
   ["They copy the routing table of the nearest switch at startup","They ask the DHCP server","They receive the topology from BGP only"],
   "Los routers OSPF se intercambian LSAs (Link-State Advertisements). Todos los del área acaban con la misma base de datos de estado de enlace.",
   ["Los switches de capa 2 no tienen tablas de enrutamiento que copiar.","DHCP no da información de topología.","BGP no se usa dentro de un área OSPF."]],

  ["2.1","h","routing,ospf",
   "Which algorithm does OSPF use to calculate the shortest path tree?",
   "Dijkstra's shortest path first (SPF)",
   ["Bellman-Ford","Spanning tree algorithm (STA) from switches","Round robin"],
   "OSPF usa el algoritmo SPF de Dijkstra sobre su base de datos de estado de enlace.",
   ["Bellman-Ford lo usan protocolos de vector distancia como RIP.","El algoritmo de spanning tree es de STP, en capa 2.","Round robin es una técnica de reparto, no de cálculo de caminos."]],

  ["2.1","m","routing,route-selection",
   "A router has routes to 10.20.0.0/16, 10.20.30.0/24 and 10.20.30.0/27. Which route is used for a packet to 10.20.30.12?",
   "10.20.30.0/27",
   ["10.20.0.0/16","10.20.30.0/24","The default route"],
   "Las tres contienen el destino. Gana la más específica (prefijo más largo): /27, que va de .0 a .31.",
   ["/16 coincide, pero es menos específica.","/24 coincide, pero /27 es más específica.","La ruta por defecto solo se usa si no coincide ninguna otra."]],

  ["2.1","h","routing,floating-static",
   "A router has a static default route to ISP A (AD 1) and a floating static default route to ISP B (AD 200). The link to ISP A goes down. What happens?",
   "The route to ISP B is installed and traffic fails over to it",
   ["Both routes stay unused","Traffic is load-balanced across both ISPs permanently from now on","The router starts running BGP automatically"],
   "Cuando la ruta principal desaparece, la flotante (AD 200) es la única que queda y entra en la tabla: el tráfico pasa por el ISP B.",
   ["La flotante existe precisamente para este caso.","Con AD distintas no hay reparto de carga.","Un router no activa BGP por su cuenta."]],

  ["2.1","m","routing,distance-vector",
   "Which type of routing protocol traditionally sends its routing table to directly connected neighbors at regular intervals?",
   "Distance-vector",
   ["Link-state","Path-vector","First hop redundancy"],
   "Los protocolos de vector distancia clásicos (como RIP) envían periódicamente su tabla a los vecinos.",
   ["Los de estado de enlace anuncian cambios, no la tabla completa cada poco tiempo.","Path-vector es BGP, que envía actualizaciones incrementales.","Los FHRP no intercambian tablas de rutas."]],

  ["2.1","m","inter-vlan,svi",
   "Instead of router-on-a-stick, a multilayer switch routes between VLANs internally. What does it use as each VLAN's gateway?",
   "A switched virtual interface (SVI) per VLAN",
   ["A separate physical router per VLAN","A dedicated hub connected to each VLAN","The DNS server address"],
   "Una SVI (Switched Virtual Interface) es una interfaz virtual del switch con la IP de gateway de cada VLAN, y enruta entre ellas por dentro.",
   ["No hace falta un router físico por VLAN.","Un hub no enruta.","El DNS no es el gateway."]],

  ["2.1","m","routing,routing-table",
   "In a Cisco routing table, what does an entry marked with 'C' indicate?",
   "A directly connected network",
   ["A route learned from BGP","A static route","A default route learned by DHCP"],
   "'C' significa connected: la red está directamente conectada a una interfaz del router (AD 0).",
   ["BGP se marca con 'B'.","Las rutas estáticas se marcan con 'S'.","DHCP no genera entradas marcadas con 'C'."]],

  ["2.1","h","routing,eigrp",
   "By default, which values does EIGRP use to calculate its metric?",
   "Bandwidth and delay",
   ["Hop count only","Administrative distance and MAC address","Jitter and packet loss"],
   "Por defecto, EIGRP calcula su métrica con el ancho de banda mínimo del camino y el retardo acumulado.",
   ["Contar saltos es propio de RIP.","La AD no forma parte de la métrica, y la MAC no interviene.","EIGRP no mide jitter ni pérdida por defecto."]],

  ["2.1","h","routing,administrative-distance",
   "What happens to a route with an administrative distance of 255?",
   "It is considered unusable and is never installed in the routing table",
   ["It is always preferred over all other routes","It is used only for default routes","It is shared with all neighbors but never used by the local router"],
   "AD 255 significa 'no me fío nada': la ruta nunca entra en la tabla.",
   ["Cuanto menor es la AD, más se prefiere; 255 es la peor.","No tiene relación con las rutas por defecto.","No se usa en absoluto."]],
];

export default q;
