import type { Raw } from '../types';

// 2.2 Switching technologies and features (60)
const q: Raw[] = [
  ["2.2","e","vlan",
   "What does a VLAN do on a switch?",
   "Creates separate logical networks on one switch",
   ["Encrypts traffic between switch ports","Combines several links into one faster link","Assigns IP addresses to hosts"],
   "Una VLAN (Virtual LAN) crea redes lógicas separadas dentro del mismo switch. Cada VLAN es su propio dominio de broadcast.",
   ["Las VLAN separan tráfico, pero no lo cifran.","Eso es agregación de enlaces (LACP).","Eso lo hace DHCP."]],

  ["2.2","m","vlan",
   "Which of the following are benefits of using VLANs? (Choose TWO)",
   ["Smaller broadcast domains","Segmentation of departments for security"],
   ["Automatic encryption of all frames","Removal of the need for IP addressing","Unlimited bandwidth per port"],
   "Las VLAN reducen el alcance de los broadcasts y separan grupos (por ejemplo, contabilidad e invitados) para controlar quién habla con quién.",
   ["No cifran tramas.","Cada VLAN sigue necesitando su propio direccionamiento IP.","No cambian la velocidad de los puertos."]],

  ["2.2","e","vlan,inter-vlan",
   "Two PCs are on the same switch but in VLAN 10 and VLAN 20. What is required for them to communicate?",
   "A router or Layer 3 switch",
   ["Nothing; they share the same switch","A hub between the ports","A longer patch cable"],
   "Cada VLAN es una red distinta. Para pasar de una a otra hace falta enrutar: un router o un switch de capa 3.",
   ["Compartir switch no basta: las VLAN los separan precisamente.","Un hub no enruta.","El cable no tiene nada que ver."]],

  ["2.2","e","vlan,access-port",
   "How does an access port handle VLANs?",
   "It carries one VLAN, untagged",
   ["It carries many VLANs with 802.1Q tags","It carries no VLAN traffic","It only carries management traffic"],
   "Un puerto de acceso pertenece a una sola VLAN y envía las tramas sin etiqueta. Es el puerto típico de un PC o una impresora.",
   ["Eso describe un puerto trunk.","Sí lleva tráfico, el de su VLAN.","Puede llevar cualquier tipo de tráfico de su VLAN."]],

  ["2.2","e","vlan,trunk",
   "Which type of switch port carries traffic for multiple VLANs between switches?",
   "Trunk port",
   ["Access port","Mirror port","Console port"],
   "Un trunk lleva el tráfico de muchas VLAN por un mismo enlace, marcando cada trama con su etiqueta 802.1Q.",
   ["Un puerto de acceso lleva una sola VLAN.","Un puerto espejo copia tráfico para analizarlo.","El puerto de consola sirve para administrar el equipo."]],

  ["2.2","m","vlan,802.1q",
   "What does 802.1Q do to a frame on a trunk link?",
   "Inserts a 4-byte tag that includes the VLAN ID",
   ["Encrypts the frame with AES","Replaces the destination MAC address with the VLAN's MAC","Adds an IP header"],
   "802.1Q mete una etiqueta de 4 bytes en la trama con el número de VLAN, así el switch del otro lado sabe a qué VLAN pertenece.",
   ["No cifra nada.","No cambia la MAC de destino.","La cabecera IP la pone la capa 3, no 802.1Q."]],

  ["2.2","h","vlan,802.1q",
   "The VLAN ID field in an 802.1Q tag is 12 bits long. About how many usable VLAN IDs does that allow?",
   "4094",
   ["256","1024","65535"],
   "12 bits dan 4096 valores; se reservan el 0 y el 4095, así que quedan 4094 VLAN utilizables (1–4094).",
   ["256 serían 8 bits.","1024 serían 10 bits.","65535 serían 16 bits."]],

  ["2.2","m","vlan,native-vlan",
   "On an 802.1Q trunk, what is the native VLAN?",
   "The VLAN whose frames are sent across the trunk untagged",
   ["The VLAN used only for voice traffic","The VLAN with the highest ID","The VLAN reserved for wireless clients and their access points"],
   "La VLAN nativa es la que viaja sin etiqueta por el trunk. Por defecto suele ser la VLAN 1.",
   ["Eso es la voice VLAN.","El número de VLAN no la hace nativa.","No tiene nada que ver con Wi-Fi."]],

  ["2.2","h","vlan,native-vlan,troubleshooting",
   "Two switches are joined by a trunk. One side uses native VLAN 1 and the other uses native VLAN 99. What is the likely result?",
   "Untagged traffic ends up in the wrong VLAN on the other side",
   ["The trunk runs faster","All VLANs are automatically merged","Nothing, because native VLANs never need to match on both ends"],
   "Una trama sin etiqueta que sale en la VLAN 1 se interpreta como VLAN 99 al otro lado: el tráfico se 'cuela' entre VLANs. La VLAN nativa debe coincidir en ambos extremos.",
   ["No afecta a la velocidad.","No se fusionan todas; solo se mezcla el tráfico sin etiqueta.","Sí deben coincidir."]],

  ["2.2","m","vlan,native-vlan,security",
   "Why is it a security best practice to change the native VLAN from VLAN 1 to an unused VLAN?",
   "It reduces the risk of VLAN hopping",
   ["It doubles trunk bandwidth","It enables jumbo frames","It removes the need for STP"],
   "Si la VLAN nativa no es una VLAN de usuarios, se complica el ataque de doble etiqueta (VLAN hopping), que aprovecha el tráfico sin etiqueta.",
   ["No cambia el ancho de banda.","Las jumbo frames son otra configuración.","STP sigue siendo necesario."]],

  ["2.2","m","vlan,voice-vlan",
   "An IP phone and a PC share one switch port. The phone's traffic goes in VLAN 50 and the PC's in VLAN 10. Which feature makes this possible?",
   "Voice VLAN",
   ["Native VLAN mismatch","Port mirroring","Link aggregation"],
   "La voice VLAN hace que el teléfono etiquete su tráfico en una VLAN de voz, mientras el PC conectado detrás del teléfono sigue en la VLAN de datos.",
   ["Una discrepancia de VLAN nativa es un error, no una función.","Port mirroring copia tráfico.","La agregación une varios enlaces."]],

  ["2.2","m","vlan,voice-vlan,qos",
   "What is a main benefit of placing IP phones in a dedicated voice VLAN?",
   "Voice can be prioritized with QoS, separate from data",
   ["Phones no longer need power","Calls are encrypted automatically between phones on that VLAN","The phones get public IP addresses from the ISP"],
   "Separar la voz en su propia VLAN facilita aplicarle prioridad (QoS) y protegerla del tráfico de datos.",
   ["La electricidad llega por PoE, no por la VLAN.","La VLAN no cifra nada.","Las IPs públicas no tienen relación con esto."]],

  ["2.2","m","vlan,vlan-database",
   "A technician assigns a port to VLAN 30, but the port does not pass traffic. The switch shows VLAN 30 does not exist. What must be done?",
   "Create VLAN 30 in the VLAN database",
   ["Change the port to an 802.1Q trunk","Enable jumbo frames","Replace the patch cable with a new one"],
   "La VLAN tiene que existir en la base de datos de VLANs del switch antes de que los puertos asignados a ella funcionen.",
   ["Un puerto de acceso para un PC no necesita ser trunk.","Las jumbo frames no tienen que ver.","El cable no es el problema: la VLAN no existe."]],

  ["2.2","m","svi",
   "What is a switched virtual interface (SVI)?",
   "A virtual Layer 3 interface for a VLAN, with an IP",
   ["A physical port reserved for uplinks to the core switch layer","A cable that connects two switches","A backup power supply"],
   "Una SVI (Switched Virtual Interface) es una interfaz virtual asociada a una VLAN, con IP. Sirve para administrar el switch o para enrutar entre VLANs.",
   ["No es un puerto físico.","No es un cable.","No tiene que ver con la alimentación."]],

  ["2.2","m","svi,management",
   "An administrator wants to SSH into a Layer 2 switch from the management network. What must be configured on the switch?",
   "An SVI with an IP in the management VLAN, plus a gateway",
   ["An IP address configured on every access port of the switch","A trunk configured to every user PC","Jumbo frames"],
   "Un switch de capa 2 se administra por IP a través de una SVI en la VLAN de gestión; con un gateway, se alcanza también desde otras redes.",
   ["Los puertos de acceso no llevan IP.","Los PCs no necesitan trunks.","Las jumbo frames no tienen que ver con la administración."]],

  ["2.2","e","link-aggregation",
   "What does link aggregation do?",
   "Bundles several physical links into one logical link",
   ["Divides one link into several VLANs","Blocks redundant links to prevent Layer 2 loops","Converts copper links to fiber"],
   "La agregación de enlaces junta varios cables físicos como si fueran uno lógico: suma capacidad y, si cae uno, siguen los demás.",
   ["Eso es trunking con VLANs.","Eso es lo que hace STP.","No cambia el medio físico."]],

  ["2.2","m","link-aggregation,lacp",
   "Which protocol negotiates link aggregation between two switches?",
   "LACP",
   ["STP","VRRP","ARP"],
   "LACP (Link Aggregation Control Protocol, IEEE 802.3ad/802.1AX) negocia y supervisa los grupos de enlaces agregados.",
   ["STP evita bucles.","VRRP da redundancia al gateway.","ARP resuelve IP a MAC."]],

  ["2.2","h","link-aggregation,lacp",
   "Which condition is required for ports to join the same link aggregation group?",
   "They must have matching speed and duplex settings",
   ["They must be in different VLANs","One must be copper and the other fiber","They must connect to different switches that are not stacked"],
   "Los puertos de un mismo grupo deben coincidir en velocidad, dúplex y configuración de VLAN; si no, no se agregan.",
   ["Deben tener la misma configuración de VLAN.","Normalmente deben ser del mismo tipo y velocidad.","Sin un stack o tecnología multichasis, los miembros van al mismo switch."]],

  ["2.2","m","link-aggregation",
   "One cable in a four-link aggregated bundle is accidentally unplugged. What happens?",
   "Traffic continues on the remaining links",
   ["The whole bundle goes down until the cable is replaced","A broadcast storm starts","All VLANs are deleted"],
   "Esa es la redundancia de la agregación: los enlaces que quedan siguen funcionando, con menos capacidad.",
   ["El grupo sigue activo mientras quede algún miembro.","La agregación no crea bucles.","Las VLANs no se ven afectadas."]],

  ["2.2","h","link-aggregation",
   "Four 1 Gbps links are aggregated. A single large file transfer between two servers still tops out at about 1 Gbps. Why?",
   "Traffic is balanced per flow, so one flow uses one link",
   ["LACP limits every bundle to the speed of 1 Gbps in total","The bundle is not working at all","Duplex is set to full"],
   "La agregación reparte flujos, no trozos de un mismo flujo: una sola conversación va por un solo cable. Varias conversaciones sí aprovechan los 4 Gbps.",
   ["LACP no impone ese límite.","Funciona; simplemente un flujo usa un miembro.","Full duplex es lo correcto."]],

  ["2.2","m","duplex,troubleshooting",
   "A link is very slow and shows late collisions and CRC errors. One side is set to full duplex and the other to half duplex. What is the problem?",
   "Duplex mismatch",
   ["Native VLAN mismatch","Jumbo frame mismatch","STP root election"],
   "Una discrepancia de dúplex (duplex mismatch) provoca colisiones tardías, errores CRC y un rendimiento muy bajo, aunque el enlace aparezca activo.",
   ["Un problema de VLAN nativa mezcla tráfico entre VLANs, no causa colisiones.","Un problema de jumbo frames provoca descartes de tramas grandes.","La elección de root no produce colisiones."]],

  ["2.2","m","duplex,speed",
   "What is the recommended practice for speed and duplex settings on both ends of a link?",
   "Configure both ends the same way",
   ["Set one side to auto and hard-code the other","Always use half duplex","Set different speeds so traffic can be prioritized"],
   "Si un lado negocia y el otro está fijado a mano, la negociación falla y suele acabar en half duplex. Los dos extremos deben configurarse igual.",
   ["Esa combinación provoca justo el problema de dúplex.","Half duplex rinde peor; hoy se usa full.","Con velocidades distintas el enlace no funciona."]],

  ["2.2","e","duplex",
   "What is the difference between half duplex and full duplex?",
   "Full duplex sends and receives at once; half does one at a time",
   ["Half duplex is twice as fast as full duplex on copper cabling","Full duplex only works on wireless","Half duplex encrypts traffic"],
   "Full duplex permite enviar y recibir a la vez. Half duplex alterna entre enviar y recibir, como un walkie-talkie.",
   ["Es al revés: full duplex rinde más.","Full duplex es lo normal en Ethernet cableado.","El dúplex no tiene que ver con el cifrado."]],

  ["2.2","e","stp",
   "What is the main purpose of the Spanning Tree Protocol (STP)?",
   "Prevent Layer 2 loops between switches",
   ["Route traffic between VLANs","Assign VLANs to ports automatically","Encrypt traffic between switches"],
   "STP detecta caminos redundantes en capa 2 y bloquea los necesarios para que no haya bucles, sin perder la redundancia.",
   ["Enrutar entre VLANs es capa 3.","STP no asigna VLANs.","STP no cifra."]],

  ["2.2","m","stp,broadcast-storm",
   "Two switches are connected with two cables and STP is disabled. What is the MOST likely result?",
   "A broadcast storm that can bring the network down",
   ["Double the bandwidth automatically","Faster DHCP responses","Nothing, because switches ignore redundant links automatically"],
   "Sin STP, los broadcasts dan vueltas sin fin por el bucle y se multiplican (tormenta de broadcast), saturando la red y la CPU de los switches.",
   ["Para sumar ancho de banda hay que usar agregación, no dos cables sueltos.","DHCP empeoraría con la tormenta.","Sin STP los switches no detectan el bucle."]],

  ["2.2","h","stp,root-bridge",
   "How is the STP root bridge elected?",
   "Lowest bridge ID (priority, then MAC) wins",
   ["The switch with the most ports wins","The switch with the highest IP address wins","The first switch powered on always wins"],
   "El Bridge ID es la prioridad más la MAC. Gana el más bajo: primero se compara la prioridad y, si empatan, la MAC más baja.",
   ["El número de puertos no influye.","Las IPs no participan en STP.","El orden de encendido no decide."]],

  ["2.2","h","stp,root-bridge",
   "What is the default STP bridge priority on most switches?",
   "32768",
   ["0","4096","65535"],
   "La prioridad por defecto es 32768. Para asegurarte de qué switch será root, se baja su prioridad (por ejemplo, a 4096 o 0).",
   ["0 es la prioridad más baja posible; se configura a mano para forzar el root.","4096 es un valor que se suele configurar, no el de fábrica.","65535 no es un valor por defecto de STP."]],

  ["2.2","m","stp,port-states",
   "In classic STP, which port state forwards user frames and learns MAC addresses?",
   "Forwarding",
   ["Blocking","Listening","Learning"],
   "Solo en el estado forwarding el puerto reenvía tráfico de usuario (y sigue aprendiendo MACs).",
   ["Blocking no reenvía ni aprende.","Listening no reenvía ni aprende MACs.","Learning aprende MACs, pero todavía no reenvía."]],

  ["2.2","m","stp,port-states",
   "Which classic STP state learns MAC addresses but does NOT yet forward user frames?",
   "Learning",
   ["Forwarding","Blocking","Disabled"],
   "En learning el switch va llenando su tabla MAC para no inundar cuando empiece a reenviar, pero aún no pasa tráfico de usuario.",
   ["Forwarding ya reenvía.","Blocking no aprende MACs.","Disabled está apagado administrativamente."]],

  ["2.2","h","stp,port-roles",
   "On a non-root switch, what is the root port?",
   "The port with the lowest-cost path toward the root bridge",
   ["The port connected to the most hosts on the local switch","A port that is permanently blocked","The port with the highest MAC address"],
   "Cada switch que no es root elige un root port: su camino de menor coste hacia el root bridge.",
   ["El número de hosts no cuenta.","Un puerto bloqueado es alternate o blocked, no root port.","La MAC del puerto no decide el rol."]],

  ["2.2","h","stp,port-roles",
   "A switch has two uplinks toward the root bridge: one 10 Gbps and one 1 Gbps. With default STP costs, which becomes the root port?",
   "The 10 Gbps uplink, because it has the lower path cost",
   ["The 1 Gbps uplink, because slower links are safer and preferred","Both become root ports","Neither; both are blocked"],
   "El coste de STP baja cuanto más rápido es el enlace. El root port es el camino de menor coste, así que gana el de 10 Gbps; el otro queda bloqueado.",
   ["Más lento significa más coste, no más seguridad.","Solo hay un root port por switch.","Uno de los dos debe quedar activo para llegar al root."]],

  ["2.2","m","stp,rstp",
   "What is the main improvement of Rapid Spanning Tree Protocol (RSTP, 802.1w) over classic STP?",
   "Much faster convergence after topology changes",
   ["It removes the need for a root bridge in the topology","It aggregates links into bundles","It routes between VLANs"],
   "RSTP converge en segundos (o menos) en lugar de los 30–50 segundos del STP clásico.",
   ["RSTP sigue eligiendo un root bridge.","Eso es LACP.","Eso es capa 3."]],

  ["2.2","m","stp,portfast",
   "A PC connected to an access port waits about 30 seconds after boot before the port passes traffic, which breaks DHCP. Which feature fixes this for end-device ports?",
   "PortFast (edge port)",
   ["BPDU flooding","Native VLAN 1","Half duplex"],
   "PortFast lleva un puerto de equipo final directamente a forwarding, sin pasar por listening y learning.",
   ["Inundar BPDUs no existe como solución y sería peligroso.","La VLAN nativa no afecta al tiempo de arranque del puerto.","Half duplex solo empeoraría el rendimiento."]],

  ["2.2","h","stp,bpdu-guard",
   "A user plugs a small switch into a PortFast office port, and the port immediately goes into an error-disabled state. Which feature caused this?",
   "BPDU guard",
   ["Jumbo frames","LACP","Voice VLAN"],
   "BPDU guard apaga (err-disabled) un puerto edge si recibe BPDUs de STP, porque eso indica que alguien conectó un switch donde solo debería haber un equipo final.",
   ["Las jumbo frames no apagan puertos.","LACP negocia agregación de enlaces.","La voice VLAN separa el tráfico de voz."]],

  ["2.2","h","stp,convergence",
   "Roughly how long can classic 802.1D STP take to move a port from blocking to forwarding?",
   "30 to 50 seconds",
   ["Less than 1 millisecond","Exactly 1 second","About 10 minutes"],
   "Con los temporizadores por defecto, el STP clásico tarda entre 30 y 50 segundos. Por eso se crearon RSTP y PortFast.",
   ["Eso se acercaría a RSTP en el mejor caso, no al STP clásico.","No hay un valor fijo de 1 segundo.","No tarda tanto."]],

  ["2.2","e","mtu",
   "What is the standard Ethernet MTU for the payload of a frame?",
   "1500 bytes",
   ["576 bytes","9000 bytes","64 bytes"],
   "La MTU (Maximum Transmission Unit) estándar de Ethernet es 1500 bytes de carga útil.",
   ["576 es el mínimo que IPv4 garantiza que se puede reensamblar, no la MTU de Ethernet.","9000 es el tamaño típico de las jumbo frames.","64 bytes es el tamaño mínimo de una trama Ethernet."]],

  ["2.2","m","mtu,jumbo-frames",
   "A storage network using iSCSI is configured with an MTU of about 9000 bytes. What are these called?",
   "Jumbo frames",
   ["Runts","Giants caused by errors","Broadcast frames"],
   "Las jumbo frames son tramas de más de 1500 bytes (típicamente 9000). Se usan en redes de almacenamiento y de servidores.",
   ["Un runt es una trama más pequeña de lo mínimo, normalmente por un error.","Un giant es una trama más grande de lo permitido en un puerto que no admite jumbo frames.","Broadcast describe a quién va la trama, no su tamaño."]],

  ["2.2","m","mtu,jumbo-frames",
   "What is the main benefit of jumbo frames on a storage or server network?",
   "Less per-frame overhead for large transfers",
   ["Stronger encryption of storage traffic","Automatic loop prevention between switches","Longer cable distances"],
   "Con tramas más grandes se envían menos tramas para los mismos datos: menos cabeceras y menos trabajo de CPU.",
   ["No cifran nada.","No evitan bucles.","No cambian las distancias máximas del cable."]],

  ["2.2","h","mtu,jumbo-frames,troubleshooting",
   "Jumbo frames were enabled on the servers and storage array but not on the switch between them. Small pings work, but large transfers fail. Why?",
   "The switch drops frames above its MTU",
   ["Jumbo frames only work on wireless networks, not on switches","The switch is running STP","Small pings use a different VLAN"],
   "Todo el camino debe soportar la MTU grande. El switch descarta las tramas que superan su MTU (las ve como giants), mientras que las pequeñas pasan sin problema.",
   ["Las jumbo frames son cosa de redes cableadas.","STP no descarta tramas por tamaño.","El tamaño, no la VLAN, explica el síntoma."]],

  ["2.2","e","mac-table",
   "How does a switch build its MAC address table?",
   "It records each frame's source MAC and incoming port",
   ["By asking the DHCP server","By reading destination IP addresses","From a list typed in by the administrator for every host"],
   "El switch aprende mirando la MAC de origen de cada trama que recibe: 'esta MAC está detrás de este puerto'.",
   ["DHCP no informa al switch de las MACs.","Las IPs son capa 3; el switch de capa 2 no las usa para esto.","Se pueden añadir entradas estáticas, pero normalmente aprende solo."]],

  ["2.2","m","mac-table",
   "A switch receives a frame whose destination MAC address is not in its MAC table. What does it do?",
   "Floods it out all ports in the VLAN except the incoming one",
   ["Drops the frame","Sends it back to the sender","Forwards it only to the default gateway, which decides where it goes"],
   "Si no sabe dónde está el destino (unicast desconocido), lo inunda por todos los puertos de esa VLAN, menos el de entrada. Cuando el destino responda, aprenderá su puerto.",
   ["No lo descarta; lo inunda.","No lo devuelve.","Un switch de capa 2 no piensa en gateways."]],

  ["2.2","e","broadcast",
   "What does a switch do with a broadcast frame?",
   "Forwards it out every other port in the same VLAN",
   ["Forwards it only to the router","Drops it immediately","Sends it out every port on every VLAN on the switch"],
   "Un broadcast va a todos los puertos de la misma VLAN (menos el de entrada). No cruza a otras VLANs.",
   ["El switch no lo limita al router.","No lo descarta.","Las VLANs separan los broadcasts."]],

  ["2.2","m","collision-domain,broadcast-domain",
   "On a switch with 24 ports, all in VLAN 1, how many collision domains and broadcast domains are there?",
   "24 collision domains and 1 broadcast domain",
   ["1 collision domain and 24 broadcast domains","24 collision domains and 24 broadcast domains","1 collision domain and 1 broadcast domain"],
   "Cada puerto de un switch es su propio dominio de colisión (24). Todos en la misma VLAN comparten un único dominio de broadcast (1).",
   ["Está al revés.","Los broadcasts sí llegan a todos los puertos de la VLAN.","Eso describiría un hub."]],

  ["2.2","e","arp",
   "What does ARP do on an IPv4 network?",
   "Finds the MAC address for a known local IP address",
   ["Finds the IP address for a hostname","Assigns IP addresses to hosts","Chooses the best route to a remote network for the host"],
   "ARP (Address Resolution Protocol) pregunta '¿quién tiene esta IP?' y la respuesta trae la MAC, necesaria para enviar la trama en la red local.",
   ["Eso es DNS.","Eso es DHCP.","Eso es el enrutamiento."]],

  ["2.2","m","arp",
   "How are ARP requests and replies normally sent?",
   "The request is a broadcast and the reply is a unicast",
   ["Both the request and the reply are broadcasts","Both are multicasts","The request is a unicast and the reply is a broadcast to all"],
   "El que pregunta no conoce la MAC de destino, así que pregunta en broadcast. El que tiene la IP responde directamente (unicast).",
   ["La respuesta va solo a quien preguntó.","IPv4 ARP no usa multicast.","Está al revés."]],

  ["2.2","m","vlan,troubleshooting",
   "A PC was moved to a different wall jack and now receives an IP address from the wrong subnet. What is the MOST likely cause?",
   "The new port is in a different VLAN",
   ["The PC's MAC address changed with the jack","STP is disabled","The cable is a different color"],
   "Cada VLAN tiene su propio rango DHCP. Si el nuevo puerto está en otra VLAN, el PC recibe una IP de esa otra subred.",
   ["La MAC de la tarjeta no cambia al cambiar de enchufe.","STP no decide qué IP recibes.","El color del cable no importa."]],

  ["2.2","h","vlan,trunk,troubleshooting",
   "Users in VLAN 40 on switch B cannot reach anything, while VLANs 10–30 work over the same trunk to switch A. VLAN 40 exists on both switches. What should be checked first?",
   "Whether VLAN 40 is in the trunk's allowed VLAN list",
   ["The duplex setting of the users' PCs","The DNS server address","Whether the users' patch cables are Cat 6 or better"],
   "Un trunk solo lleva las VLAN permitidas en su lista. Si la 40 no está, su tráfico no cruza, aunque exista en ambos switches.",
   ["El dúplex de los PCs no bloquearía solo a una VLAN.","DNS no impide llegar a 'nada'.","El tipo de cable no afecta a una sola VLAN."]],

  ["2.2","m","vlan,access-port",
   "Frames sent from a switch access port to a normal PC are:",
   "Untagged",
   ["Tagged with 802.1Q","Encrypted","Sent as broadcasts"],
   "Los puertos de acceso quitan cualquier etiqueta: el PC recibe tramas Ethernet normales, sin 802.1Q.",
   ["Las etiquetas se usan en los trunks.","No se cifran.","Solo los broadcasts van a todos; el resto es unicast."]],

  ["2.2","h","vlan,trunk",
   "Which of the following should match on both ends of an 802.1Q trunk for it to work correctly? (Choose TWO)",
   ["Native VLAN","Allowed VLANs"],
   ["Switch hostname","Management IP address","Number of access ports"],
   "Ambos extremos deben coincidir en la VLAN nativa y en qué VLANs se permiten; si no, el tráfico se pierde o se mezcla.",
   ["El nombre del switch no influye en el trunk.","Cada switch tiene su propia IP de gestión.","El número de puertos de acceso no importa."]],

  ["2.2","e","vlan",
   "By default, which VLAN are all ports assigned to on most switches?",
   "VLAN 1",
   ["VLAN 0","VLAN 100","VLAN 4095"],
   "De fábrica todos los puertos están en la VLAN 1, que además es la nativa y la de gestión por defecto.",
   ["La VLAN 0 está reservada.","La VLAN 100 no tiene ningún papel por defecto.","La 4095 está reservada."]],

  ["2.2","h","mtu,fragmentation",
   "A router must forward an IPv4 packet that is larger than the MTU of the outgoing link, and the packet has the Don't Fragment bit set. What happens?",
   "It drops the packet and sends ICMP 'fragmentation needed'",
   ["The router fragments it anyway","The router increases the link MTU automatically to fit the packet","The router converts it to IPv6"],
   "Con el bit DF (Don't Fragment) activo, el router no puede trocear el paquete: lo descarta y avisa con ICMP. Esa es la base del descubrimiento de la MTU del camino.",
   ["DF prohíbe precisamente fragmentar.","La MTU del enlace no cambia sola.","No convierte protocolos."]],

  ["2.2","e","switching",
   "What is the key difference between a Layer 2 switch and a Layer 3 switch?",
   "A Layer 3 switch can also route using IP addresses",
   ["A Layer 2 switch always has more ports than a Layer 3 one","A Layer 3 switch cannot use VLANs","A Layer 2 switch reads IP addresses"],
   "El switch de capa 3 hace lo mismo que uno de capa 2 y además enruta por IP, por ejemplo entre VLANs.",
   ["El número de puertos no define la capa.","Los switches de capa 3 usan VLANs.","Un switch de capa 2 decide por MAC, no por IP."]],

  ["2.2","m","vlan,802.1q",
   "Switches from two different vendors must share VLANs over a trunk. Which trunking standard should be used?",
   "IEEE 802.1Q",
   ["ISL","802.11ac","802.3af"],
   "802.1Q es el estándar abierto de etiquetado de VLANs; todos los fabricantes lo soportan.",
   ["ISL era propietario de Cisco y está obsoleto.","802.11ac es Wi-Fi.","802.3af es PoE."]],

  ["2.2","m","speed,troubleshooting",
   "A technician hard-codes a switch port to 1 Gbps, but the connected device's port is fixed at 100 Mbps. What is the MOST likely result?",
   "The link does not come up",
   ["The link runs at 1 Gbps anyway","The link automatically aggregates","The device receives an APIPA address but full speed"],
   "Si las velocidades fijadas no coinciden, los extremos no se entienden y el enlace no se levanta.",
   ["No puede funcionar a una velocidad que el otro lado no soporta.","La agregación no tiene nada que ver.","Sin enlace no hay DHCP ni ninguna comunicación."]],

  ["2.2","h","stp,loop,troubleshooting",
   "Users report the network is almost unusable. Switch logs show MAC addresses rapidly moving between ports and CPU at 100%. What is the MOST likely cause?",
   "A Layer 2 switching loop",
   ["A DNS server outage","An expired DHCP lease","A duplex mismatch on one PC"],
   "MACs que saltan de un puerto a otro ('MAC flapping'), CPU al máximo y la red colapsada son síntomas clásicos de un bucle de capa 2 con tormenta de broadcast.",
   ["Un fallo de DNS no hace saltar MACs entre puertos.","Una concesión DHCP caducada afecta a un solo equipo.","Un problema de dúplex en un PC no colapsa toda la red."]],

  ["2.2","e","vlan,access-port",
   "A switch port is configured as an access port in VLAN 20. Which subnet will a DHCP client on that port receive an address from?",
   "The subnet associated with VLAN 20",
   ["The subnet of VLAN 1","A public IP subnet","The subnet of whatever VLAN the switch uses for management"],
   "Cada VLAN tiene su propia subred. Un cliente en un puerto de la VLAN 20 recibe una IP del rango de la VLAN 20.",
   ["La VLAN 1 es otra red distinta.","Las IPs públicas no se reparten así en una LAN.","La VLAN de gestión no tiene relación con el puerto del usuario."]],

  ["2.2","h","vlan,voice-vlan",
   "An access port has data VLAN 10 and voice VLAN 50. An IP phone is connected with a PC plugged into the phone. How does the traffic cross the port?",
   "The phone tags voice for VLAN 50; the PC is untagged in VLAN 10",
   ["Both devices send untagged traffic in VLAN 50","Both devices tag their traffic for VLAN 10","The PC tags its traffic for VLAN 50 and the phone uses VLAN 10"],
   "Con voice VLAN, el teléfono etiqueta su tráfico con la VLAN de voz y el PC envía tramas sin etiqueta, que el switch coloca en la VLAN de datos.",
   ["El PC no va a la VLAN de voz.","La voz va a su propia VLAN.","El PC normalmente no etiqueta nada."]],

  ["2.2","h","lacp",
   "Which LACP mode combination will form a link aggregation group?",
   "Active on one side and passive on the other",
   ["Passive on both sides","Off on both sides","Passive on one side and off on the other side"],
   "En modo active el switch inicia la negociación LACP; en passive solo responde. Hace falta al menos un lado en active.",
   ["Con los dos en passive, nadie empieza la negociación.","Off desactiva LACP.","Un lado apagado nunca negocia."]],

  ["2.2","m","lacp",
   "Why is LACP generally preferred over configuring a static link aggregation group?",
   "LACP negotiates and detects misconfigured member links",
   ["LACP doubles the speed of each cable","LACP removes the need for matching settings on both switches","Static groups cannot carry VLANs"],
   "LACP comprueba que el otro extremo también forma parte del grupo y saca los enlaces mal configurados. Un grupo estático no verifica nada y puede crear problemas.",
   ["No cambia la velocidad de cada cable.","Siguen haciendo falta velocidad y dúplex iguales.","Los grupos estáticos también pueden llevar VLANs."]],

  ["2.2","h","svi",
   "On many switches, a VLAN's SVI shows as down even though it is configured with an IP address. What is a common reason?",
   "No active port is in that VLAN, including trunks",
   ["The SVI needs a MAC address typed in manually by the admin","STP is running","Jumbo frames are disabled"],
   "La SVI de una VLAN solo se levanta si hay al menos un puerto activo en esa VLAN (de acceso o un trunk que la lleve).",
   ["La SVI usa una MAC del propio switch.","STP es normal y no apaga las SVIs.","Las jumbo frames no afectan al estado de la SVI."]],
];

export default q;
