import type { Raw } from '../types';

// 2.3 Wireless devices and technologies (60) · 2.4 Physical installations (25)
const q: Raw[] = [
  ["2.3","e","wireless,802.11",
   "Which frequency band does 802.11a use?",
   "5 GHz",
   ["2.4 GHz","6 GHz","900 MHz"],
   "802.11a trabaja en 5 GHz y llega a 54 Mbps.",
   ["2.4 GHz es de 802.11b/g.","6 GHz llegó con Wi-Fi 6E.","900 MHz no se usa en estos estándares Wi-Fi."]],

  ["2.3","e","wireless,802.11",
   "Which 802.11 standard operates only at 2.4 GHz with a maximum of 11 Mbps?",
   "802.11b",
   ["802.11a","802.11g","802.11n"],
   "802.11b es de los primeros estándares: 2.4 GHz y hasta 11 Mbps.",
   ["802.11a es 5 GHz a 54 Mbps.","802.11g es 2.4 GHz a 54 Mbps.","802.11n llega a 600 Mbps en 2.4 y 5 GHz."]],

  ["2.3","e","wireless,802.11",
   "Which 802.11 standard uses 2.4 GHz and supports up to 54 Mbps?",
   "802.11g",
   ["802.11b","802.11a","802.11ac"],
   "802.11g subió la velocidad a 54 Mbps manteniéndose en 2.4 GHz.",
   ["802.11b solo llega a 11 Mbps.","802.11a da 54 Mbps, pero en 5 GHz.","802.11ac es de 5 GHz y mucho más rápido."]],

  ["2.3","m","wireless,802.11",
   "Which standard, also called Wi-Fi 4, was the first to support both 2.4 GHz and 5 GHz and introduced MIMO?",
   "802.11n",
   ["802.11g","802.11ac","802.11ax"],
   "802.11n (Wi-Fi 4) funciona en 2.4 y 5 GHz y usa MIMO (Multiple Input Multiple Output): varias antenas a la vez.",
   ["802.11g es solo 2.4 GHz y sin MIMO.","802.11ac (Wi-Fi 5) es solo 5 GHz y llegó después.","802.11ax (Wi-Fi 6) es posterior."]],

  ["2.3","m","wireless,802.11",
   "Which band does 802.11ac (Wi-Fi 5) use for its high-throughput operation?",
   "5 GHz only",
   ["2.4 GHz only","2.4 GHz and 6 GHz","6 GHz only"],
   "802.11ac trabaja solo en 5 GHz. Los APs 'dual band' usan 802.11n o anteriores para su radio de 2.4 GHz.",
   ["2.4 GHz no forma parte de 802.11ac.","6 GHz llegó con Wi-Fi 6E.","6 GHz es de Wi-Fi 6E."]],

  ["2.3","m","wireless,802.11,6ghz",
   "What does Wi-Fi 6E add compared with Wi-Fi 6?",
   "Support for the 6 GHz band",
   ["Support for the 900 MHz band","WEP encryption","A maximum of 11 Mbps"],
   "Wi-Fi 6E es 802.11ax extendido a la banda de 6 GHz: muchos canales nuevos y limpios.",
   ["900 MHz no tiene relación con Wi-Fi 6E.","WEP es un cifrado obsoleto.","11 Mbps es la velocidad de 802.11b."]],

  ["2.3","h","wireless,802.11,mu-mimo",
   "Which 802.11 standard introduced downlink MU-MIMO, letting an AP send to several clients at the same time?",
   "802.11ac",
   ["802.11b","802.11g","802.11a"],
   "802.11ac (Wi-Fi 5, en su segunda generación o 'wave 2') introdujo MU-MIMO (Multi-User MIMO) de bajada. 802.11ax lo amplió.",
   ["802.11b no tenía MIMO.","802.11g no tenía MIMO.","802.11a no tenía MIMO."]],

  ["2.3","h","wireless,802.11",
   "What is the maximum theoretical data rate of 802.11n?",
   "600 Mbps",
   ["54 Mbps","11 Mbps","9.6 Gbps"],
   "802.11n llega a 600 Mbps teóricos con 4 flujos espaciales y canales de 40 MHz.",
   ["54 Mbps es de 802.11a/g.","11 Mbps es de 802.11b.","9.6 Gbps es el máximo teórico de 802.11ax."]],

  ["2.3","e","wireless,channels",
   "In the 2.4 GHz band in North America, which set of channels does NOT overlap?",
   "1, 6 and 11",
   ["1, 2 and 3","3, 7 and 12","2, 5 and 9"],
   "En 2.4 GHz los canales se pisan entre sí. Solo 1, 6 y 11 están lo bastante separados para no solaparse.",
   ["Son canales vecinos que se solapan casi del todo.","Esos canales se solapan parcialmente.","Esos canales se solapan parcialmente."]],

  ["2.3","m","wireless,bands",
   "Compared with 5 GHz, what is an advantage of the 2.4 GHz band?",
   "Better range and better penetration through walls",
   ["Many more non-overlapping channels","Less interference from microwaves and Bluetooth","Higher maximum throughput"],
   "Las frecuencias más bajas llegan más lejos y atraviesan mejor paredes y obstáculos.",
   ["5 GHz tiene muchos más canales sin solapamiento.","2.4 GHz sufre más interferencias de microondas y Bluetooth.","5 GHz permite mayor velocidad."]],

  ["2.3","e","wireless,bands",
   "A user's laptop gets fast speeds near the AP on 5 GHz, but the signal drops quickly in rooms further away. Why?",
   "5 GHz has a shorter range than 2.4 GHz",
   ["5 GHz does not support encryption","5 GHz only works outdoors","The laptop is using 802.11b"],
   "Cuanto más alta la frecuencia, menos alcance y peor penetración: 5 GHz se debilita antes que 2.4 GHz.",
   ["5 GHz soporta cifrado igual que 2.4.","5 GHz funciona perfectamente en interiores.","802.11b no usa 5 GHz."]],

  ["2.3","m","wireless,6ghz",
   "Why is the 6 GHz band attractive for new Wi-Fi deployments?",
   "Many wide, uncongested channels for Wi-Fi 6E and newer",
   ["It has the longest range of any Wi-Fi band through walls","Every older client can already use it","It needs no encryption"],
   "6 GHz aporta mucho espectro nuevo con canales anchos y sin congestión, pero solo lo usan dispositivos Wi-Fi 6E o posteriores.",
   ["Tiene aún menos alcance que 5 GHz.","Los equipos antiguos no pueden usarla.","En 6 GHz se exige WPA3."]],

  ["2.3","m","wireless,channel-width",
   "What is the trade-off of using 80 MHz or 160 MHz channel widths?",
   "More throughput, but fewer non-overlapping channels",
   ["Longer range for each AP, with lower throughput","Stronger encryption with less speed","No effect on channel availability"],
   "Un canal más ancho transporta más datos, pero ocupa más espectro, así que quedan menos canales libres y aumentan las interferencias entre APs.",
   ["El ancho de canal no aumenta el alcance.","El ancho no tiene que ver con el cifrado.","Sí reduce los canales disponibles."]],

  ["2.3","h","wireless,channel-width",
   "A stadium deploys many APs close together in the 5 GHz band. Which channel width is usually BEST to reduce interference between them?",
   "20 MHz",
   ["80 MHz","160 MHz","Channel bonding of all available channels"],
   "En alta densidad conviene tener muchos canales distintos. Con 20 MHz hay más canales sin solapamiento para repartir entre los APs.",
   ["80 MHz deja muy pocos canales distintos.","160 MHz deja todavía menos.","Unir todos los canales provocaría interferencias entre APs."]],

  ["2.3","m","wireless,channel-bonding",
   "What is channel bonding in Wi-Fi?",
   "Combining adjacent channels into a wider one",
   ["Encrypting each channel separately","Assigning each client its own SSID","Joining an AP to a switch with LACP"],
   "Channel bonding junta canales contiguos de 20 MHz en uno de 40, 80 o 160 MHz para ir más rápido.",
   ["No tiene que ver con el cifrado.","El SSID no se asigna por cliente.","LACP es agregación de enlaces cableados."]],

  ["2.3","m","wireless,band-steering",
   "Which feature encourages dual-band clients to connect on 5 GHz instead of the more crowded 2.4 GHz band?",
   "Band steering",
   ["Channel bonding","MAC filtering","Captive portal"],
   "Band steering empuja a los clientes que soportan las dos bandas hacia 5 GHz (o 6 GHz), donde hay menos congestión.",
   ["Channel bonding ensancha canales.","El filtrado MAC decide quién entra, no en qué banda.","Un portal cautivo muestra una página de acceso."]],

  ["2.3","m","wireless,regulatory",
   "Why might an AP configured in one country not be allowed to use the same channels and power levels in another country?",
   "Allowed channels and power differ by country",
   ["SSIDs must be registered in each country","WPA3 is illegal in some countries","Access points only work in their country of manufacture"],
   "Cada país regula qué canales y qué potencia se pueden usar. Por eso los APs se configuran con el código de país correcto.",
   ["Los SSID no se registran en ningún organismo.","WPA3 no está prohibido por regulación de canales.","Un AP funciona en cualquier país si respeta sus normas."]],

  ["2.3","h","wireless,802.11h,dfs",
   "Which amendment adds Dynamic Frequency Selection (DFS) and Transmit Power Control (TPC) so Wi-Fi in the 5 GHz band avoids interfering with radar?",
   "802.11h",
   ["802.11b","802.3af","802.1X"],
   "802.11h añade DFS (cambiar de canal si detecta radar) y TPC (ajustar la potencia de transmisión).",
   ["802.11b es un estándar antiguo de 2.4 GHz.","802.3af es PoE.","802.1X es control de acceso."]],

  ["2.3","h","wireless,dfs",
   "An AP on a 5 GHz DFS channel suddenly changes channels, briefly disconnecting clients. What is the MOST likely reason?",
   "It detected radar and had to leave the channel",
   ["A client used the wrong password","The SSID was hidden","The AP ran out of IP addresses for its clients"],
   "En canales DFS el AP debe abandonar el canal si detecta radar, y eso provoca breves cortes.",
   ["Una contraseña errónea solo afecta a ese cliente.","Ocultar el SSID no cambia el canal.","La falta de IPs es un problema de DHCP, no de canal."]],

  ["2.3","e","wireless,ssid",
   "What is an SSID?",
   "The name that identifies a wireless network",
   ["The MAC address of a client","The encryption key of the network","The channel number used by the AP"],
   "El SSID (Service Set Identifier) es el nombre visible de la red Wi-Fi.",
   ["La MAC del cliente no es el SSID.","La clave es otra cosa.","El canal es otro parámetro."]],

  ["2.3","m","wireless,bssid",
   "What is a BSSID?",
   "The MAC address of a specific AP radio serving an SSID",
   ["The name of the wireless network","A list of all SSIDs broadcast in a building or on a campus","The IP address of the wireless controller"],
   "El BSSID (Basic Service Set Identifier) es la MAC del radio concreto de un AP. Varios APs con el mismo SSID tienen BSSIDs distintos.",
   ["Eso es el SSID.","No es una lista.","No es una dirección IP."]],

  ["2.3","m","wireless,essid,roaming",
   "Several APs across a building broadcast the same network name and security settings so users can roam between them. What is this group called?",
   "Extended service set (ESS)",
   ["Basic service set with one AP","Ad hoc network between the clients","Independent basic service set (IBSS)"],
   "Un ESS (Extended Service Set) son varios APs con el mismo SSID (ESSID), que permiten moverse por el edificio sin reconectar a mano.",
   ["Un BSS básico es un solo AP.","Ad hoc no usa APs.","Un IBSS es el nombre técnico de una red ad hoc."]],

  ["2.3","m","wireless,ssid,security",
   "A manager suggests hiding the SSID to secure the wireless network. Why is this weak on its own?",
   "Clients reveal the SSID, and tools can capture it",
   ["Hidden SSIDs disable encryption","Clients can never connect to hidden SSIDs","It makes the network visible to more people"],
   "Ocultar el SSID solo evita que salga en la lista; los clientes siguen anunciándolo al conectar y cualquier analizador lo descubre. La seguridad real viene de WPA2/WPA3.",
   ["Ocultar el SSID no toca el cifrado.","Se pueden conectar escribiendo el nombre a mano.","Al revés: lo hace menos visible, pero no más seguro."]],

  ["2.3","e","wireless,modes",
   "In which wireless mode do clients connect through an access point to reach the wired network?",
   "Infrastructure mode",
   ["Ad hoc mode","Monitor mode","Point-to-point bridge mode"],
   "En modo infraestructura los clientes se conectan a un AP, que los une a la red cableada. Es el modo normal en empresas y hogares.",
   ["En ad hoc los equipos se conectan entre sí, sin AP.","Monitor mode es para capturar tráfico.","Un puente punto a punto une dos redes, no clientes."]],

  ["2.3","e","wireless,modes",
   "Two laptops connect directly to each other wirelessly to share files, with no access point. What mode is this?",
   "Ad hoc",
   ["Infrastructure","Mesh backhaul","Extended service set"],
   "Ad hoc es una red inalámbrica directa entre equipos, sin AP.",
   ["Infraestructura usa un AP.","Mesh une APs entre sí.","Un ESS son varios APs con el mismo SSID."]],

  ["2.3","m","wireless,mesh",
   "A large outdoor venue uses APs that connect to each other wirelessly, with only a few wired to the network. If one AP fails, traffic finds another path. What is this design?",
   "Wireless mesh",
   ["Ad hoc","Point-to-point","Autonomous single AP"],
   "En una malla inalámbrica los APs se enlazan entre sí por radio y buscan caminos alternativos si uno falla.",
   ["Ad hoc une clientes directamente, sin APs.","Punto a punto une solo dos extremos.","Un único AP autónomo no forma una malla."]],

  ["2.3","m","wireless,point-to-point",
   "Two buildings 500 meters apart need a wireless link between their networks. What is the BEST approach?",
   "Point-to-point bridge with directional antennas",
   ["Omnidirectional APs in each lobby","An ad hoc network between two laptops","A captive portal on each building's AP"],
   "Un enlace punto a punto con antenas direccionales concentra la señal entre los dos edificios y llega lejos.",
   ["Las omnidireccionales reparten la señal en todas direcciones y no alcanzan esa distancia.","Ad hoc entre portátiles no une dos redes.","Un portal cautivo es para invitados."]],

  ["2.3","h","wireless,wpa3",
   "What is a key security improvement of WPA3-Personal over WPA2-Personal?",
   "SAE makes offline dictionary attacks much harder",
   ["It returns to WEP encryption","It removes the need for any passphrase at all on the network","It uses TKIP instead of AES"],
   "WPA3-Personal usa SAE (Simultaneous Authentication of Equals). Capturar el saludo ya no permite probar contraseñas sin conexión, como pasaba con WPA2-PSK.",
   ["WEP es inseguro y obsoleto.","Sigue usando una contraseña.","TKIP es antiguo; WPA3 usa AES."]],

  ["2.3","m","wireless,wpa2",
   "Which encryption does WPA2 use?",
   "AES with CCMP",
   ["RC4 as in WEP","TKIP only","No encryption"],
   "WPA2 usa AES (Advanced Encryption Standard) con CCMP. TKIP era el parche temporal de WPA.",
   ["RC4 era de WEP, que está roto.","TKIP es de WPA y está obsoleto.","WPA2 sí cifra."]],

  ["2.3","e","wireless,wep",
   "A legacy scanner only supports WEP. Why should WEP not be used?",
   "WEP is easily cracked and considered insecure",
   ["WEP only works on 6 GHz","WEP requires a RADIUS server","WEP is faster than any other security option available"],
   "WEP (Wired Equivalent Privacy) se rompe en minutos. Hay que usar WPA2 o WPA3, o poner el equipo antiguo en una red aislada.",
   ["WEP es de la época de 2.4 GHz.","WEP no usa RADIUS.","La velocidad no compensa la falta de seguridad."]],

  ["2.3","m","wireless,authentication",
   "What is the main difference between WPA2-Personal and WPA2-Enterprise?",
   "Personal uses a shared passphrase; Enterprise uses 802.1X per user",
   ["Personal uses AES encryption; Enterprise still uses WEP keys","Enterprise has no encryption","Personal needs certificates on every client"],
   "Personal (PSK, Pre-Shared Key): todos comparten la misma clave. Enterprise: cada usuario entra con sus credenciales mediante 802.1X y un servidor RADIUS.",
   ["Ambos usan AES.","Enterprise cifra igual o mejor.","Los certificados en los clientes son de EAP-TLS, en Enterprise."]],

  ["2.3","m","wireless,authentication,radius",
   "Which server is typically required to deploy WPA2-Enterprise or WPA3-Enterprise?",
   "RADIUS server",
   ["TFTP server","NTP server only","DNS server only"],
   "El modo Enterprise usa 802.1X, y el AP consulta a un servidor RADIUS (Remote Authentication Dial-In User Service) para validar a cada usuario.",
   ["TFTP transfiere archivos.","NTP sincroniza la hora.","DNS resuelve nombres."]],

  ["2.3","h","wireless,authentication",
   "An employee who knows the office Wi-Fi passphrase leaves the company. Why would WPA2-Enterprise make this easier to handle than WPA2-Personal?",
   "Enterprise lets you disable one account instead of changing a shared key",
   ["Enterprise networks do not use passwords","Personal mode automatically detects and blocks former employees' devices","Enterprise mode blocks all laptops"],
   "Con credenciales individuales basta con desactivar la cuenta de esa persona. Con una clave compartida hay que cambiarla y reconfigurar todos los equipos.",
   ["Enterprise usa credenciales o certificados por usuario.","El modo Personal no sabe quién es cada uno.","Enterprise no bloquea portátiles en general."]],

  ["2.3","e","wireless,guest,captive-portal",
   "A hotel wants guests to accept terms of use on a web page before getting internet access. What should it implement?",
   "Captive portal",
   ["WPA2-Enterprise with certificates","MAC filtering","Hidden SSID"],
   "Un portal cautivo redirige al usuario a una página web (condiciones, registro, código) antes de dejarle navegar.",
   ["Los certificados son demasiado complejos para invitados de hotel.","El filtrado MAC no muestra ninguna página.","Ocultar el SSID no muestra términos."]],

  ["2.3","m","wireless,guest",
   "What is the MOST important network design goal for a guest wireless network?",
   "Isolate guests from internal networks; internet only",
   ["Give guests access to internal file servers and printers","Use the same VLAN as employees","Disable all encryption for convenience"],
   "La red de invitados debe ir separada (VLAN y reglas propias) y dar solo salida a internet.",
   ["Los invitados no deben acceder a recursos internos.","Compartir VLAN con los empleados rompe el aislamiento.","Quitar el cifrado expone el tráfico."]],

  ["2.3","m","wireless,client-isolation",
   "Which feature prevents wireless clients on the same guest SSID from communicating with each other?",
   "Client isolation",
   ["Band steering","Channel bonding","Roaming"],
   "El aislamiento de clientes impide que los dispositivos de una misma red se vean entre sí, algo útil en redes de invitados.",
   ["Band steering elige la banda.","Channel bonding ensancha el canal.","Roaming es moverse entre APs."]],

  ["2.3","e","wireless,antennas",
   "Which type of antenna radiates signal in all horizontal directions and is common on ceiling-mounted office APs?",
   "Omnidirectional",
   ["Yagi","Parabolic dish","Patch panel"],
   "Una antena omnidireccional cubre 360° en horizontal: perfecta para un AP en el centro de una sala.",
   ["La Yagi es direccional.","La parabólica es muy direccional, para enlaces largos.","Un patch panel es cableado, no una antena."]],

  ["2.3","e","wireless,antennas",
   "Which type of antenna focuses signal in one direction for long-distance links?",
   "Directional (e.g. Yagi)",
   ["Omnidirectional (360°)","Dipole on a laptop","Any antenna with no gain (0 dBi)"],
   "Las antenas direccionales concentran la energía hacia un punto, así ganan alcance en esa dirección.",
   ["La omnidireccional reparte la señal alrededor.","La dipolo de un portátil es omnidireccional.","Sin ganancia no se concentra la señal."]],

  ["2.3","m","wireless,antennas",
   "A warehouse has long, narrow aisles between tall metal shelves. Which antenna choice BEST covers each aisle?",
   "Directional antennas aimed down the aisles",
   ["Omnidirectional antennas at maximum power in one corner","No antennas, only wired connections","Hidden SSIDs"],
   "Las antenas direccionales orientadas a lo largo del pasillo meten la señal donde se necesita, sin desperdiciarla contra las estanterías.",
   ["Una omnidireccional en una esquina deja pasillos sin cobertura.","Los lectores móviles necesitan Wi-Fi.","Ocultar el SSID no mejora la cobertura."]],

  ["2.3","m","wireless,autonomous-ap",
   "What is a disadvantage of autonomous (standalone) APs in a large deployment?",
   "Each AP must be configured and managed individually",
   ["They require a wireless LAN controller to forward any traffic","They cannot broadcast an SSID","They only support ad hoc mode"],
   "Un AP autónomo lleva toda su configuración dentro. Con decenas de APs, gestionarlos uno a uno es lento y propenso a errores.",
   ["Esa es la característica de los APs ligeros.","Emiten SSID con normalidad.","Funcionan en modo infraestructura."]],

  ["2.3","e","wireless,lightweight-ap",
   "Lightweight APs are different from autonomous APs because they:",
   "Are managed centrally by a wireless LAN controller",
   ["Do not need any network connection","Store their full configuration only locally on each AP","Cannot support multiple SSIDs"],
   "Los APs ligeros (lightweight) dependen de un WLC (Wireless LAN Controller) que les da la configuración y los gestiona en conjunto.",
   ["Sí necesitan red para hablar con el controlador.","Eso describe a los autónomos.","Pueden emitir varios SSID."]],

  ["2.3","m","wireless,roaming",
   "For users to roam smoothly between APs without reconnecting manually, what must the APs share?",
   "The same SSID and security",
   ["The same channel on every AP in the building","The same MAC address","Different SSIDs for each floor"],
   "Para moverse sin cortes, los APs deben anunciar el mismo SSID con la misma seguridad. Los canales, en cambio, deben ser distintos entre APs vecinos.",
   ["Usar el mismo canal en APs vecinos provoca interferencias.","Cada AP tiene su propia MAC (BSSID).","SSIDs distintos obligarían a cambiar de red a mano."]],

  ["2.3","m","wireless,interference",
   "Two neighboring APs in the 2.4 GHz band are set to channels 1 and 3. What problem does this cause?",
   "Adjacent channel interference",
   ["No problem; any two different channels are fine","The APs merge into one","WPA3 stops working"],
   "Los canales 1 y 3 se solapan en 2.4 GHz: cada AP es ruido para el otro. Se deben usar 1, 6 y 11.",
   ["En 2.4 GHz, que dos canales sean distintos no basta: además no deben solaparse.","Los APs no se fusionan.","El cifrado no depende del canal."]],

  ["2.3","h","wireless,interference",
   "Two nearby APs are both configured on channel 36. What happens?",
   "Co-channel interference (shared airtime)",
   ["They automatically double the bandwidth","Clients cannot see either SSID","Nothing, because 5 GHz channels never interfere"],
   "Dos APs cercanos en el mismo canal compiten por el medio: se turnan para transmitir y el rendimiento baja.",
   ["No suman ancho de banda.","Los SSID se siguen viendo.","Los canales de 5 GHz también interfieren si se repiten cerca."]],

  ["2.3","m","wireless,bands",
   "Which of the following are advantages of the 5 GHz band over 2.4 GHz? (Choose TWO)",
   ["More non-overlapping channels","Less interference from microwaves and Bluetooth"],
   ["Longer range","Better penetration through walls","Supported by 802.11b clients"],
   "5 GHz tiene muchos más canales sin solapamiento y está menos saturado por otros aparatos.",
   ["Tiene menos alcance.","Atraviesa peor las paredes.","802.11b solo usa 2.4 GHz."]],

  ["2.3","h","wireless,wpa3",
   "Which of the following are features of WPA3? (Choose TWO)",
   ["SAE for personal-mode authentication","A 192-bit security mode for enterprise networks"],
   ["TKIP encryption","WEP backward compatibility","Open networks with no authentication by design"],
   "WPA3 trae SAE en modo Personal y un modo Enterprise de 192 bits para entornos exigentes.",
   ["TKIP es de WPA, antiguo.","WPA3 no es compatible con WEP.","WPA3 no se define por redes sin autenticación."]],

  ["2.3","h","wireless,eap",
   "Which EAP method requires certificates on both the authentication server and every client?",
   "EAP-TLS",
   ["PEAP","EAP-MD5","PSK"],
   "EAP-TLS es el más seguro: servidor y clientes se autentican con certificados.",
   ["PEAP solo necesita certificado en el servidor; el usuario entra con usuario y contraseña.","EAP-MD5 no usa certificados y es débil.","PSK no es un método EAP; es una clave compartida."]],

  ["2.3","h","wireless,eap",
   "Which EAP method creates a TLS tunnel using only a server certificate and then authenticates the user with a username and password inside it?",
   "PEAP",
   ["EAP-TLS","WPA2-PSK","WEP"],
   "PEAP (Protected EAP) protege el usuario y la contraseña dentro de un túnel TLS; solo el servidor necesita certificado.",
   ["EAP-TLS exige certificados en los clientes.","PSK no usa usuarios individuales.","WEP es un cifrado obsoleto, no un método EAP."]],

  ["2.3","h","wireless,802.1x",
   "In 802.1X authentication on a wireless network, what role does the access point play?",
   "Authenticator",
   ["Supplicant","Authentication server","Certificate authority"],
   "En 802.1X el cliente es el suplicante, el AP (o switch) es el autenticador que pasa los mensajes, y el RADIUS es el servidor de autenticación.",
   ["El suplicante es el cliente.","El servidor de autenticación es el RADIUS.","La autoridad de certificación emite certificados; no participa como rol de 802.1X."]],

  ["2.3","e","wireless,interference",
   "Users' Wi-Fi drops every time someone uses the break-room microwave. Which band are they MOST likely using?",
   "2.4 GHz",
   ["5 GHz","6 GHz","60 GHz"],
   "Los microondas funcionan cerca de 2.4 GHz e interfieren esa banda. Bluetooth y muchos teléfonos inalámbricos también la usan.",
   ["5 GHz no se ve afectada por el microondas.","6 GHz tampoco.","60 GHz no se usa en redes Wi-Fi de oficina normales."]],

  ["2.3","m","wireless,mimo",
   "How does MIMO increase wireless throughput?",
   "It sends several spatial streams with multiple antennas",
   ["It encrypts traffic twice","It switches to 2.4 GHz automatically when more clients join","It reduces the number of clients allowed"],
   "MIMO (Multiple Input Multiple Output) usa varias antenas para enviar varios flujos a la vez por el mismo canal.",
   ["No tiene que ver con el cifrado.","No cambia de banda.","No limita clientes."]],

  ["2.3","e","wireless,802.11",
   "Which Wi-Fi generation name corresponds to 802.11ac?",
   "Wi-Fi 5",
   ["Wi-Fi 4","Wi-Fi 6","Wi-Fi 6E"],
   "802.11n = Wi-Fi 4, 802.11ac = Wi-Fi 5, 802.11ax = Wi-Fi 6 (y 6E en 6 GHz).",
   ["Wi-Fi 4 es 802.11n.","Wi-Fi 6 es 802.11ax.","Wi-Fi 6E es 802.11ax en 6 GHz."]],

  ["2.3","h","wireless,mesh",
   "In a wireless mesh, why can throughput drop for clients several hops away from the wired AP?",
   "Each wireless backhaul hop uses airtime",
   ["Mesh networks do not support encryption","Clients must use ad hoc mode","Each hop changes the SSID"],
   "Cada salto por radio entre APs gasta tiempo de aire para retransmitir el tráfico, así que cuantos más saltos, menos capacidad queda.",
   ["Las mallas pueden cifrar.","Los clientes siguen en modo infraestructura.","El SSID es el mismo en toda la malla."]],

  ["2.3","m","wireless,wpa2,psk",
   "A company uses WPA2-Personal with a short, common passphrase. What is the main risk?",
   "It can be cracked offline from a captured handshake",
   ["Clients cannot connect at 5 GHz with a passphrase this short","The AP overheats","DHCP stops working for wireless clients"],
   "Con WPA2-PSK, si alguien captura el saludo de conexión, puede probar contraseñas sin conexión. Una clave corta y común cae rápido.",
   ["La frecuencia no depende de la contraseña.","La contraseña no calienta el AP.","DHCP no tiene relación con la clave Wi-Fi."]],

  ["2.3","e","wireless,channels",
   "Which of the following channels is in the 5 GHz band?",
   "36",
   ["1","6","11"],
   "Los canales de 5 GHz empiezan en el 36 (36, 40, 44, 48…). 1, 6 y 11 son de 2.4 GHz.",
   ["El 1 es de 2.4 GHz.","El 6 es de 2.4 GHz.","El 11 es de 2.4 GHz."]],

  ["2.3","h","wireless,antennas",
   "Antenna gain is usually expressed in which unit?",
   "dBi",
   ["Mbps","MHz","Watts per port"],
   "La ganancia de una antena se mide en dBi (decibelios respecto a una antena isotrópica ideal).",
   ["Mbps es velocidad de datos.","MHz es frecuencia o ancho de canal.","Los vatios miden potencia, no ganancia de antena."]],

  ["2.3","m","wireless,beacons",
   "Which frames do access points send periodically to advertise their SSID and capabilities?",
   "Beacon frames",
   ["ARP requests","BPDUs","DHCP offers"],
   "Los APs envían tramas beacon varias veces por segundo anunciando el SSID, la seguridad y las velocidades soportadas.",
   ["ARP resuelve IP a MAC.","Las BPDUs son de STP.","Las ofertas DHCP asignan IPs."]],

  ["2.3","m","wireless,802.11ax",
   "Why is 802.11ax especially useful in dense environments such as airports and lecture halls?",
   "It improves efficiency with many clients, using OFDMA",
   ["It has a longer range than any other standard","It only allows one client per AP","It disables encryption to reduce overhead"],
   "802.11ax (Wi-Fi 6) está pensado para muchos clientes a la vez: con OFDMA reparte el canal entre varios en cada transmisión.",
   ["Su ventaja es la eficiencia, no el alcance.","Permite muchos clientes.","No desactiva el cifrado."]],

  ["2.3","h","wireless,channel-width",
   "Why are 40 MHz channels generally discouraged in the 2.4 GHz band?",
   "Only one non-overlapping 40 MHz channel fits in the band",
   ["2.4 GHz does not allow encryption on wide channels","40 MHz channels require 6 GHz clients","They reduce range to a few centimeters"],
   "El espectro de 2.4 GHz es tan estrecho que un canal de 40 MHz ocupa casi toda la banda y choca con todo lo que haya cerca.",
   ["El cifrado no depende del ancho de canal.","40 MHz existe también en 2.4 y 5 GHz.","El alcance no cambia de esa forma."]],

  ["2.4","e","physical,mdf",
   "What is the MDF in a building's cabling design?",
   "The main distribution frame for the building",
   ["A small closet serving only one floor of the building","A type of multi-fiber connector","The main firewall rule set"],
   "El MDF (Main Distribution Frame) es la sala o armario principal: ahí llegan el proveedor y los enlaces troncales hacia los IDF.",
   ["Eso es un IDF.","No es un conector.","No es un conjunto de reglas."]],

  ["2.4","e","physical,idf",
   "What is an IDF?",
   "A distribution frame that serves one floor or area",
   ["The main demarcation point where the ISP's circuit enters","A wireless controller","A backup generator for one floor"],
   "Un IDF (Intermediate Distribution Frame) es un armario secundario, por ejemplo uno por planta, que conecta a los usuarios de esa zona y sube al MDF.",
   ["La demarcación del proveedor suele estar en el MDF.","No es un controlador inalámbrico.","No es un generador."]],

  ["2.4","m","physical,racks",
   "How tall is one rack unit (1U)?",
   "1.75 inches (44.45 mm)",
   ["1 inch","3.5 inches","19 inches"],
   "1U mide 1,75 pulgadas (44,45 mm). Un equipo de 2U ocupa 3,5 pulgadas.",
   ["Es más de 1 pulgada.","3,5 pulgadas son 2U.","19 pulgadas es el ancho estándar del rack."]],

  ["2.4","e","physical,racks",
   "What is the height of a common full-size equipment rack?",
   "42U",
   ["12U","19U","100U"],
   "Un rack completo típico tiene 42U de altura.",
   ["12U es un rack pequeño de pared.","19 pulgadas es el ancho, no la altura en U.","100U no es un tamaño estándar."]],

  ["2.4","m","physical,airflow",
   "A data center uses hot and cold aisles. Why does it matter whether a switch uses port-side intake or port-side exhaust airflow?",
   "Its airflow must match the hot/cold aisle orientation",
   ["It determines the switch's VLAN numbering and trunk layout","It changes the switch's power voltage","It decides which ports support PoE"],
   "Según hacia dónde miren los puertos al montarlo, el flujo de aire del switch debe coincidir con el diseño: aire frío por la entrada y calor hacia el pasillo caliente.",
   ["El flujo de aire no afecta a las VLANs.","No cambia el voltaje.","No decide qué puertos dan PoE."]],

  ["2.4","m","physical,airflow",
   "In a hot aisle/cold aisle layout, which way should the equipment air intakes face?",
   "Toward the cold aisle",
   ["Toward the hot aisle","Toward the ceiling","It does not matter"],
   "Los equipos toman aire del pasillo frío y expulsan el calor al pasillo caliente. Si se monta al revés, se recalientan.",
   ["Tomar aire del pasillo caliente recalienta los equipos.","El diseño es por pasillos, no hacia el techo.","Sí importa, y mucho."]],

  ["2.4","e","physical,patch-panel",
   "What is the purpose of a patch panel?",
   "Terminate horizontal cabling for easy patching",
   ["Provide battery backup","Route traffic between VLANs in the telecom closet","Convert copper to wireless"],
   "El patch panel recibe los cables fijos que van a las rosetas; con latiguillos cortos se conecta cada puerto al switch sin tocar el cableado fijo.",
   ["Eso es un UPS.","Eso es un router o un switch de capa 3.","Eso es un AP."]],

  ["2.4","m","physical,fiber-distribution",
   "Where are incoming fiber runs typically terminated and organized in a rack before being patched to switches?",
   "Fiber distribution panel",
   ["Copper patch panel","PDU","UPS"],
   "El panel de distribución de fibra (fiber distribution panel) recibe, protege y organiza las fibras, que luego se conectan con latiguillos.",
   ["El patch panel de cobre es para par trenzado.","La PDU distribuye electricidad.","El UPS da respaldo eléctrico."]],

  ["2.4","e","physical,ups",
   "What is the main purpose of a UPS in a network rack?",
   "Battery power during short outages, plus power conditioning",
   ["Distribute network traffic evenly between racks in the room","Cool the equipment","Replace the building generator for several days"],
   "Un UPS (Uninterruptible Power Supply) mantiene los equipos encendidos con batería durante cortes breves y filtra picos y caídas de tensión.",
   ["Eso lo hace un switch.","Eso es la climatización.","La batería dura minutos, no días."]],

  ["2.4","m","physical,ups",
   "A UPS can run the rack for 10 minutes, and power outages sometimes last hours. What should be configured so servers are not damaged?",
   "Graceful shutdown triggered by the UPS",
   ["Disable the UPS alarms","Remove the UPS to save power","Plug everything into a single power strip"],
   "El UPS puede avisar a los servidores para que se apaguen de forma ordenada antes de que se agote la batería.",
   ["Quitar las alarmas no evita el apagado brusco.","Sin UPS el corte sería inmediato.","Una regleta no da respaldo."]],

  ["2.4","e","physical,pdu",
   "Which device distributes electrical power to the equipment inside a rack?",
   "PDU",
   ["UPS only","Patch panel","KVM switch"],
   "La PDU (Power Distribution Unit) es la 'regleta' profesional del rack; muchas permiten medir consumo o encender y apagar tomas en remoto.",
   ["El UPS da respaldo; la distribución a cada equipo la hace la PDU.","El patch panel es de datos.","Un KVM comparte teclado, vídeo y ratón entre servidores."]],

  ["2.4","m","physical,power-load",
   "When planning a rack, why must the total power load of all devices be calculated?",
   "So it stays within the PDU and circuit capacity",
   ["To choose the VLAN numbers for the rack's switches","To decide the SSID","To set the switch duplex"],
   "Si la suma del consumo supera lo que aguanta la PDU o el circuito, salta la protección y cae todo el rack. Se planifica con margen.",
   ["El consumo no tiene que ver con las VLANs.","Tampoco con el SSID.","Tampoco con el dúplex."]],

  ["2.4","m","physical,redundant-power",
   "Servers with dual power supplies should be connected how for the best redundancy?",
   "Each supply to a different PDU and circuit",
   ["Both supplies to the same power strip","One supply connected and the other left unplugged","Both supplies to the same UPS outlet"],
   "Con alimentación A/B, si cae un circuito o una PDU, el servidor sigue funcionando con la otra fuente.",
   ["Si falla esa regleta, caen las dos fuentes.","Desconectar una fuente elimina la redundancia.","Un único enchufe sigue siendo un único punto de fallo."]],

  ["2.4","h","physical,voltage",
   "Why do many data centers power racks at 208 V or 230 V instead of 120 V?",
   "Same power with less current, so more equipment per circuit",
   ["Network switches only work at 208 V or higher voltages today","Higher voltage increases Wi-Fi range","It removes the need for grounding"],
   "Potencia = voltaje × corriente. Con más voltaje, la misma potencia requiere menos corriente, lo que permite cargar más cada circuito y perder menos en calor.",
   ["La mayoría de equipos admite varios voltajes.","El voltaje no afecta al Wi-Fi.","La toma de tierra sigue siendo obligatoria."]],

  ["2.4","m","physical,generator",
   "What is the typical role of a UPS when a building also has a backup generator?",
   "Bridge the gap until the generator starts",
   ["Replace the generator completely","Cool the generator","Provide network connectivity to the generator"],
   "El generador tarda un poco en arrancar. El UPS cubre ese hueco para que los equipos no se apaguen.",
   ["El UPS no tiene autonomía para horas.","No refrigera nada.","No da red."]],

  ["2.4","m","physical,environmental",
   "What problems can very low and very high humidity cause in a network room?",
   "Low: static discharge; high: condensation and corrosion",
   ["Low humidity improves Wi-Fi; high humidity improves cooling a lot","Humidity has no effect on electronics","High humidity prevents static discharge and has no downside"],
   "Aire muy seco favorece las descargas de electricidad estática; aire muy húmedo puede condensar agua y corroer los componentes.",
   ["No mejora nada de eso.","La humedad sí afecta a la electrónica.","La humedad alta tiene el problema de la condensación."]],

  ["2.4","h","physical,environmental",
   "According to common data center guidance (ASHRAE), what is the recommended inlet air temperature range for IT equipment?",
   "About 18–27 °C (64–81 °F)",
   ["About 0–5 °C (32–41 °F)","About 35–45 °C (95–113 °F)","Any temperature, as long as humidity is controlled"],
   "La recomendación habitual para el aire de entrada es de unos 18 a 27 °C.",
   ["Tan frío es innecesario y favorece la condensación.","Tan caliente pone en riesgo los equipos.","La temperatura sí importa, aunque se controle la humedad."]],

  ["2.4","m","physical,fire-suppression",
   "Why do many data centers use clean-agent fire suppression instead of standard water sprinklers?",
   "They put out fires without water damage to equipment",
   ["Clean agents are always free","Water sprinklers are illegal indoors","Clean agents cool the room during normal operation"],
   "Los agentes limpios (gases como FM-200) apagan el fuego sin mojar ni dañar los equipos.",
   ["Son sistemas caros.","Los rociadores de agua son legales y comunes.","No sirven de refrigeración normal."]],

  ["2.4","h","physical,fire-suppression",
   "Which sprinkler system keeps its pipes dry until a detection event occurs, reducing the risk of accidental water discharge on equipment?",
   "Pre-action",
   ["Wet pipe","Deluge with always-open heads","Garden hose system"],
   "En un sistema pre-action las tuberías están secas y solo se llenan tras una primera detección, lo que evita descargas accidentales.",
   ["En wet pipe las tuberías siempre tienen agua.","El diluvio (deluge) descarga en todas las boquillas a la vez; no es el que protege contra descargas accidentales.","No es un sistema real de protección."]],

  ["2.4","e","physical,security",
   "What is the purpose of lockable racks or cabinets in a shared equipment room?",
   "Prevent unauthorized physical access",
   ["Improve Wi-Fi coverage","Increase switch throughput","Replace the need for passwords"],
   "Cerrar racks y armarios evita que cualquiera con acceso a la sala manipule, desconecte o robe equipos.",
   ["No afecta al Wi-Fi.","No cambia el rendimiento.","Las contraseñas siguen siendo necesarias."]],

  ["2.4","e","physical,cable-management",
   "Why is proper cable management inside a rack important besides appearance?",
   "Better airflow and easier troubleshooting",
   ["It increases fiber speeds","It removes the need for labeling cables at each end","It provides power redundancy"],
   "Cables ordenados no tapan las entradas y salidas de aire y permiten seguir cada conexión rápidamente.",
   ["No cambia la velocidad de la fibra.","Hay que etiquetar igualmente.","No da redundancia eléctrica."]],

  ["2.4","e","physical,environmental",
   "Which tool alerts administrators when a network closet becomes too hot or too humid?",
   "Environmental sensors",
   ["A cable tester","A patch panel","A toner probe"],
   "Los sensores ambientales miden temperatura y humedad y generan alertas antes de que los equipos sufran.",
   ["El cable tester comprueba cables.","El patch panel es cableado.","El toner localiza cables."]],

  ["2.4","m","physical,grounding",
   "Why must equipment racks be properly grounded?",
   "To protect people and gear from electrical faults",
   ["To increase network bandwidth on the copper links in the rack","To enable VLAN tagging on the uplinks","To reduce DNS latency"],
   "Una buena toma de tierra desvía de forma segura las corrientes de fallo y la electricidad estática.",
   ["No cambia el ancho de banda.","No tiene relación con las VLANs.","No tiene relación con DNS."]],

  ["2.4","m","physical,racks",
   "Which type of rack is BEST for mounting long, heavy servers that need support at both the front and the rear?",
   "Four-post rack",
   ["Two-post relay rack","Wall-mounted 6U bracket","Open shelf with no rails"],
   "Un rack de cuatro postes sujeta el equipo por delante y por detrás, necesario para servidores largos y pesados.",
   ["Un rack de dos postes es para equipos ligeros y poco profundos, como patch panels o switches.","Un soporte de pared de 6U es para equipos pequeños.","Una estantería sin raíles no sujeta bien los servidores."]],

  ["2.4","m","physical,airflow",
   "Why should blanking panels be installed in empty rack spaces?",
   "To stop hot air from recirculating to the front",
   ["To add extra network ports to the rack for future growth","To provide battery backup","To label the rack units"],
   "Los paneles ciegos tapan los huecos para que el aire caliente de detrás no vuelva al frente y se mezcle con el aire frío.",
   ["No añaden puertos.","No dan batería.","No sirven para etiquetar."]],
];

export default q;
