import type { Raw } from '../types';

// 2.3 (+1) · 3.1 Organizational processes and procedures (40) · 3.2 Network monitoring (40)
const q: Raw[] = [
  ["2.3","e","wireless,wpa3",
   "A company is deploying a brand-new wireless network and every client supports the latest security standard. Which should it choose?",
   "WPA3",
   ["WEP","WPA with TKIP","Open network with MAC filtering"],
   "WPA3 es el estándar más actual y seguro para Wi-Fi.",
   ["WEP está roto.","WPA con TKIP es antiguo y débil.","Una red abierta no cifra, y el filtrado MAC se burla fácilmente."]],

  ["3.1","e","documentation,diagrams",
   "Which type of network diagram shows the actual devices, their locations, ports and cable runs?",
   "Physical diagram",
   ["Logical diagram","Heat map","Flow chart of the change process"],
   "El diagrama físico muestra lo tangible: qué equipo hay, dónde está y qué cable va a qué puerto.",
   ["El lógico muestra subredes, VLANs y rutas, no cables.","Un mapa de calor muestra la cobertura Wi-Fi.","Un flujo de cambios no es un diagrama de red."]],

  ["3.1","e","documentation,diagrams",
   "Which diagram shows IP subnets, VLANs and how traffic is routed, without focusing on physical cable paths?",
   "Logical diagram",
   ["Physical diagram","Rack diagram","Cable map"],
   "El diagrama lógico muestra cómo 'piensa' la red: subredes, VLANs, routers y flujos.",
   ["El físico muestra equipos y cables.","El de rack muestra qué equipo hay en cada U.","El mapa de cables muestra conexiones físicas puerto a puerto."]],

  ["3.1","m","documentation,diagrams",
   "A Layer 1 network diagram primarily documents:",
   "Physical cables, ports and media types",
   ["IP subnets and the routing between them","VLAN assignments and trunks","Application dependencies between servers"],
   "La capa 1 es la física: el diagrama de capa 1 muestra cables, puertos y medios.",
   ["Eso es un diagrama de capa 3.","Eso es un diagrama de capa 2.","Eso queda por encima del modelo de red."]],

  ["3.1","m","documentation,diagrams",
   "Which diagram would BEST show VLANs, trunk links and spanning tree roles between switches?",
   "Layer 2 diagram",
   ["Layer 1 diagram","Layer 3 diagram","Rack diagram"],
   "VLANs, trunks y STP son conceptos de capa 2, así que van en el diagrama de capa 2.",
   ["El de capa 1 muestra cables.","El de capa 3 muestra subredes y enrutamiento.","El de rack muestra la posición física de los equipos."]],

  ["3.1","m","documentation,diagrams",
   "A Layer 3 diagram is MOST useful for understanding:",
   "IP subnets, gateways and routing between networks",
   ["Which patch panel port connects to which jack","Which switch ports are trunks","Where each server sits in the rack"],
   "El diagrama de capa 3 muestra direccionamiento IP y enrutamiento: subredes, gateways y routers.",
   ["Eso es un mapa de cables.","Eso es capa 2.","Eso es un diagrama de rack."]],

  ["3.1","e","documentation,rack",
   "Which document shows exactly which device is installed in each rack unit of a cabinet?",
   "Rack diagram",
   ["Logical diagram","IP address plan","SLA"],
   "El diagrama de rack (rack elevation) indica qué equipo ocupa cada U, en cada rack.",
   ["El lógico no muestra posiciones físicas.","El plan de IPs no dice dónde está cada equipo.","El SLA es un acuerdo de servicio."]],

  ["3.1","e","documentation,cable-map",
   "A technician needs to know which switch port serves wall jack 3-114. Which documentation should they check?",
   "Cable map",
   ["Wireless heat map","Service level agreement","Change request log"],
   "El mapa de cables relaciona cada roseta con su puerto del patch panel y del switch.",
   ["Un mapa de calor muestra la cobertura Wi-Fi.","El SLA define niveles de servicio.","El registro de cambios no mapea rosetas."]],

  ["3.1","m","documentation,asset-inventory",
   "Which information is typically recorded in a network asset inventory?",
   "Models, serials, versions, licenses, warranties",
   ["User passwords for each device","Packet captures from each switch port","Daily bandwidth charts for each link only"],
   "El inventario de activos registra qué tienes: hardware, software, licencias y garantías.",
   ["Las contraseñas nunca van en un inventario.","Las capturas de paquetes son datos de diagnóstico.","Las gráficas de tráfico son monitorización, no inventario."]],

  ["3.1","m","documentation,warranty",
   "A switch fails. Which inventory detail tells the technician whether the vendor will replace it at no cost?",
   "Warranty and support contract",
   ["The switch's VLAN list","The switch's MAC table","The rack's total power draw in watts"],
   "La información de garantía y soporte indica si el fabricante cubre la sustitución (RMA) y en qué plazo.",
   ["Las VLANs no dicen nada de la garantía.","La tabla MAC es un dato de funcionamiento.","El consumo eléctrico no tiene relación."]],

  ["3.1","m","documentation,licensing",
   "Why should software licenses be tracked in the asset inventory?",
   "To stay compliant and renew on time",
   ["To speed up the network after renewal","To encrypt configuration files","To assign VLANs automatically"],
   "Llevar el control de las licencias evita usar software sin licencia y que caduque una sin darse cuenta.",
   ["No afecta a la velocidad.","No cifra nada.","No asigna VLANs."]],

  ["3.1","e","ipam",
   "What does an IPAM system do?",
   "Plans and tracks IP address allocation",
   ["Encrypts IP packets between subnets","Replaces all routers with a central server","Measures Wi-Fi coverage"],
   "IPAM (IP Address Management) lleva el control de qué direcciones y subredes están asignadas y a quién.",
   ["No cifra.","No sustituye routers.","La cobertura Wi-Fi se mide con un site survey."]],

  ["3.1","m","ipam",
   "Why is IPAM often integrated with DHCP and DNS?",
   "So addresses and name records stay accurate",
   ["So DHCP can be disabled on every subnet","So DNS no longer needs records","So every host gets a public IP"],
   "Integrado con DHCP y DNS, el IPAM ve en tiempo real qué IPs se usan y a qué nombres corresponden.",
   ["DHCP sigue siendo necesario.","DNS sigue usando registros.","No tiene nada que ver con las IPs públicas."]],

  ["3.1","e","sla",
   "What does a service level agreement (SLA) define?",
   "The expected service level, such as uptime, and penalties",
   ["The IP addressing scheme for the provider's network","The rack layout at the provider's data center","The switch firmware version"],
   "Un SLA (Service Level Agreement) fija compromisos medibles: disponibilidad, tiempos de respuesta y penalizaciones.",
   ["El direccionamiento va en el plan de IPs o en el IPAM.","El rack va en el diagrama de rack.","El firmware va en el inventario."]],

  ["3.1","h","sla,availability",
   "An SLA promises 99.99% availability. About how much downtime does that allow per year?",
   "About 52 minutes",
   ["About 5 minutes","About 8.8 hours","About 3.6 days"],
   "Un año tiene 525 600 minutos. El 0,01 % no disponible es 525 600 × 0,0001 ≈ 52,6 minutos.",
   ["5 minutos es 99,999 % (cinco nueves).","8,8 horas es 99,9 %.","3,6 días es 99 %."]],

  ["3.1","e","wireless-survey",
   "Before installing access points in a new office, what should be performed to measure RF coverage and interference?",
   "Wireless site survey",
   ["Port scan","Tabletop exercise","Configuration backup"],
   "Un site survey inalámbrico mide la señal, la cobertura y las interferencias para decidir dónde poner los APs.",
   ["Un escaneo de puertos busca servicios abiertos.","Un tabletop es un ejercicio de desastres.","Un backup de configuración no mide RF."]],

  ["3.1","e","wireless-survey,heat-map",
   "Which visual output of a wireless survey shows signal strength across a floor plan using colors?",
   "Heat map",
   ["Rack diagram","Logical diagram","Syslog report"],
   "Un mapa de calor pinta sobre el plano la intensidad de la señal con colores: se ven a simple vista las zonas débiles.",
   ["El de rack muestra equipos.","El lógico muestra subredes.","Syslog son registros de texto."]],

  ["3.1","h","wireless-survey",
   "What is the difference between a predictive wireless survey and an on-site survey?",
   "Predictive is modeled in software; on-site measures real signals",
   ["A predictive survey requires installing every AP first","An on-site survey never uses any measuring equipment","There is no difference; both are just names for a heat map"],
   "El predictivo simula la cobertura con planos y datos de materiales; el presencial mide la señal real recorriendo el lugar.",
   ["El predictivo se hace antes de instalar.","El presencial usa analizadores y APs de prueba.","Sí son distintos."]],

  ["3.1","m","lifecycle,eol",
   "A vendor announces end-of-life (EOL) for a switch model. What does this usually mean?",
   "The product will no longer be sold or manufactured",
   ["The switch stops working immediately","Support and security patches end on that same day for everyone","The switch becomes faster"],
   "EOL (End of Life) indica que el producto deja de fabricarse y venderse. Suele anunciarse junto con la fecha en que terminará el soporte.",
   ["El equipo sigue funcionando.","El soporte suele seguir un tiempo más, hasta la fecha EOS.","No mejora nada."]],

  ["3.1","m","lifecycle,eos",
   "Why is running network devices past their end-of-support (EOS) date a security risk?",
   "No more patches, so new vulnerabilities stay unfixed",
   ["The devices stop routing traffic on that date","They automatically delete their configuration","They can no longer be monitored"],
   "Tras el EOS (End of Support) no salen más parches: cualquier vulnerabilidad nueva se queda abierta para siempre.",
   ["Siguen enrutando.","No borran su configuración.","Se pueden seguir monitorizando."]],

  ["3.1","m","lifecycle",
   "The core switches will reach end of support in 12 months. What is the BEST action?",
   "Plan and budget their replacement now",
   ["Wait until they fail and then replace them","Disable their logging to save resources","Remove them from the inventory"],
   "Se planifica la sustitución con tiempo para no quedarse con equipos críticos sin parches ni soporte.",
   ["Esperar al fallo provoca una caída sin plan.","Quitar los logs no resuelve nada.","Sacarlos del inventario oculta el riesgo."]],

  ["3.1","m","patch-management",
   "A critical firmware patch is released for the company's firewalls. What should happen before installing it in production?",
   "Test it first, then schedule it via change management",
   ["Install it on all firewalls immediately at noon","Ignore it until the next hardware refresh","Post it on the company intranet for users to install"],
   "Los parches se prueban antes y se aplican en una ventana aprobada, con plan de marcha atrás.",
   ["Instalarlo en todo a la vez en horario laboral arriesga una caída general.","Ignorar un parche crítico deja la vulnerabilidad abierta.","Publicarlo no lo instala."]],

  ["3.1","m","patch-management,firmware",
   "When should firmware upgrades on production switches normally be performed?",
   "In an approved maintenance window",
   ["During peak business hours","Whenever a user complains","Only after the switch fails and must be replaced"],
   "Actualizar firmware suele implicar reiniciar el equipo; se hace en la ventana de mantenimiento acordada para minimizar el impacto.",
   ["En hora punta afectaría a todos.","Las quejas no son un calendario de cambios.","Esperar al fallo es reactivo y arriesgado."]],

  ["3.1","m","lifecycle,decommissioning",
   "A router is being decommissioned. Which steps should be included? ",
   "Wipe it, then update inventory, IPAM, DNS and monitoring",
   ["Unplug it and leave it in the rack","Sell it with its configuration intact so the buyer can reuse it","Only change its hostname so it is not confused"],
   "Al retirar un equipo se borran sus datos y configuración (que pueden tener contraseñas y rutas) y se actualiza toda la documentación.",
   ["Dejarlo sin más confunde la documentación y el inventario.","Venderlo con la configuración expone información sensible.","Cambiar el nombre no es desmantelarlo."]],

  ["3.1","e","change-management",
   "Which of the following BEST describes a formal change management process?",
   "Changes are reviewed, approved, scheduled and documented",
   ["Any technician can change production at any time","Changes are made first and approved later","Only hardware changes need approval; software is free"],
   "La gestión de cambios pide, revisa, aprueba, programa y documenta cada cambio, con un plan de marcha atrás.",
   ["Eso es precisamente lo que el proceso evita.","La aprobación va antes, salvo emergencias documentadas.","Los cambios de configuración también requieren aprobación."]],

  ["3.1","m","change-management,rollback",
   "Why must every change request include a rollback plan?",
   "To quickly restore the working state if the change fails",
   ["So the change runs faster during the window","So no testing is needed before the change","So the change is automatically approved"],
   "El plan de marcha atrás (rollback) dice exactamente cómo volver a lo que funcionaba si el cambio sale mal.",
   ["No acelera el cambio.","No sustituye a las pruebas.","No garantiza la aprobación."]],

  ["3.1","m","change-management",
   "A technician changed a firewall rule on a Friday afternoon without approval, causing an outage. Which process was bypassed?",
   "Change management",
   ["Asset inventory","Wireless site survey","Log aggregation"],
   "Saltarse la solicitud y la aprobación del cambio es no seguir la gestión de cambios.",
   ["El inventario registra activos.","El site survey mide la cobertura Wi-Fi.","La agregación de logs reúne registros."]],

  ["3.1","m","change-management,tracking",
   "Why are change requests tracked in a ticketing or request system?",
   "To record who requested, approved and did each change",
   ["To speed up routing protocols","To encrypt device configurations","To assign new IP addresses to the changed devices automatically"],
   "Un sistema de tickets deja la trazabilidad completa de cada cambio: quién, qué, cuándo y por qué.",
   ["No afecta al enrutamiento.","No cifra configuraciones.","No asigna IPs."]],

  ["3.1","m","configuration-management,baseline",
   "What is a baseline (golden) configuration?",
   "The approved standard configuration for a device type",
   ["The configuration of the oldest device","A configuration with all ports disabled","A backup made automatically after every failure"],
   "La configuración base (golden) es la plantilla aprobada. Los equipos se comparan con ella y se restauran desde ella.",
   ["La antigüedad no la convierte en referencia.","No se trata de apagar puertos.","No es un backup tras un fallo, sino el estándar aprobado."]],

  ["3.1","e","configuration-management,backup",
   "Where should switch and router configuration backups be stored?",
   "On a secure system separate from the devices themselves",
   ["Only in the device's own flash memory","Printed and taped to the rack","In a public cloud folder shared with everyone in the company"],
   "Si el equipo muere, su memoria muere con él. Las copias de configuración se guardan fuera, en un sistema seguro.",
   ["Si el equipo falla, la copia se pierde con él.","En papel no se puede restaurar rápido, y expone información.","Compartido con todos expone contraseñas y la topología."]],

  ["3.1","h","configuration-management,drift",
   "An automated job compares each switch's current production configuration with the approved baseline every night. What is it detecting?",
   "Configuration drift",
   ["Wireless interference near the switch","Duplex mismatches on user PCs","Expired DHCP leases on the switch"],
   "Comparar la configuración actual con la base aprobada detecta desviaciones (drift): cambios no autorizados o que nadie documentó.",
   ["La interferencia se mide con análisis de RF.","El dúplex de los PCs no está en la configuración base de los switches.","Los préstamos DHCP no se comparan con una base."]],

  ["3.1","e","documentation",
   "A technician adds a new switch to a closet. What should they do with the network documentation afterward?",
   "Update the diagrams, cable maps and inventory",
   ["Nothing; documentation is only created once","Delete the old diagrams and start new ones later","Wait for the yearly audit to document everything"],
   "La documentación solo sirve si está al día: cada cambio debe reflejarse en diagramas, mapas e inventario.",
   ["La documentación desactualizada engaña al siguiente técnico.","Hay que actualizar, no borrar.","Un año sin actualizar la deja inservible."]],

  ["3.1","m","documentation,asset-inventory",
   "Which of the following belong in a hardware asset inventory? (Choose TWO)",
   ["Serial numbers","Warranty expiration dates"],
   ["User passwords","Live packet captures","Personal phone numbers of visitors"],
   "El inventario identifica cada equipo (número de serie) y su cobertura (garantía).",
   ["Las contraseñas no se guardan en el inventario.","Las capturas son datos de diagnóstico.","No son datos de los activos."]],

  ["3.1","m","change-management",
   "Which of the following should be part of a network change request? (Choose TWO)",
   ["A rollback plan","The scheduled maintenance window"],
   ["The administrator's personal password","A list of every user's email","The color of the patch cables"],
   "Una solicitud de cambio incluye qué se hará, cuándo (ventana), el impacto y cómo volver atrás.",
   ["Las contraseñas no van en la solicitud.","No hace falta la lista de correos.","El color de los cables no es relevante para la aprobación."]],

  ["3.1","e","documentation,labeling",
   "What is the recommended practice for labeling network cables?",
   "Label both ends with one documented scheme",
   ["Label only the switch end of each cable","Use a different scheme in each closet","Avoid labels to reduce clutter in the rack"],
   "Etiquetar los dos extremos con un esquema coherente permite seguir cualquier cable sin tener que rastrearlo.",
   ["Con un solo extremo etiquetado no sabes dónde acaba.","Esquemas distintos confunden.","Sin etiquetas el troubleshooting se alarga mucho."]],

  ["3.1","e","change-management,maintenance-window",
   "What is a maintenance window?",
   "A pre-approved time for changes with minimal impact",
   ["The period after a device fails, until it is repaired","The time a UPS can run on battery","The interval between SNMP polls"],
   "La ventana de mantenimiento es el horario acordado (por ejemplo, domingo de madrugada) para hacer cambios que pueden causar cortes.",
   ["No se refiere a un fallo.","Eso es la autonomía del UPS.","Eso es el intervalo de sondeo."]],

  ["3.1","m","change-management,emergency",
   "A critical vulnerability is being actively exploited and a fix must be applied immediately, outside the normal approval cycle. How should this be handled?",
   "Use the emergency change process and review it afterward",
   ["Skip documentation entirely because it is an emergency","Wait for the next monthly change meeting","Apply it quietly without telling anyone about it"],
   "Los cambios de emergencia tienen su propio procedimiento rápido, pero se documentan y revisan después.",
   ["La emergencia no exime de documentar.","Esperar un mes deja el ataque en curso.","Hacerlo a escondidas rompe la trazabilidad."]],

  ["3.1","m","software-management,firmware",
   "Why should switches of the same model generally run the same approved firmware version?",
   "They behave predictably and are easier to support",
   ["It doubles their throughput on every port","It removes the need for configuration backups","It lets them share one IP address"],
   "Con la misma versión todos se comportan igual, los bugs conocidos son los mismos y aplicar parches es más sencillo.",
   ["No cambia el rendimiento de esa forma.","Los backups siguen siendo necesarios.","Cada switch sigue necesitando su propia IP."]],

  ["3.1","m","configuration-management,baseline",
   "A failed access switch is replaced with a new unit of the same model. What is the fastest way to configure it correctly?",
   "Apply the saved baseline/backup configuration for that switch",
   ["Configure every port manually from memory, one by one, on site","Copy the configuration of the core router","Leave it on factory defaults"],
   "Con la copia guardada (o la configuración base más sus datos específicos), el switch nuevo queda como el anterior en minutos.",
   ["De memoria se cometen errores y se tarda mucho.","La configuración de un router no sirve para un switch de acceso.","Con la configuración de fábrica no tendría VLANs ni seguridad."]],

  ["3.1","m","documentation,security",
   "Which information should NOT be included in network diagrams shared with the operations team?",
   "Device passwords and pre-shared keys",
   ["Device hostnames","Subnet addresses","Interconnections between switches and routers"],
   "Los diagramas se comparten y se imprimen; las contraseñas y claves van en un gestor de secretos, nunca en un diagrama.",
   ["Los nombres de host son necesarios.","Las subredes son parte del diagrama lógico.","Las interconexiones son la esencia del diagrama."]],

  ["3.1","e","patch-management",
   "What is the main reason to apply a vendor security patch to a network device?",
   "To fix a known vulnerability or bug",
   ["To change its IP address","To increase its warranty period","To rename its interfaces"],
   "Los parches corrigen fallos y vulnerabilidades conocidas.",
   ["La IP se cambia en la configuración.","Los parches no amplían la garantía.","No renombran interfaces."]],

  ["3.2","e","snmp",
   "In SNMP, what is the role of the manager (NMS)?",
   "It polls agents on devices for data and receives their traps",
   ["It runs on every switch and answers the queries sent to it","It encrypts all network traffic","It assigns IP addresses to agents"],
   "El gestor (NMS, Network Management System) pregunta a los agentes de los equipos y recibe sus avisos (traps).",
   ["Eso es el agente.","SNMP no cifra el tráfico de red.","SNMP no asigna IPs."]],

  ["3.2","m","snmp,mib",
   "What is an SNMP MIB?",
   "A database defining the objects SNMP can read or set",
   ["A type of firewall rule for SNMP traffic","The encryption key for SNMPv3","A log file of SNMP events stored on the central syslog server"],
   "La MIB (Management Information Base) es el 'catálogo' de datos que un equipo expone por SNMP: contadores, estados, temperaturas…",
   ["No es una regla de firewall.","No es una clave.","No es un archivo de logs."]],

  ["3.2","h","snmp,oid",
   "In SNMP, what uniquely identifies a specific value, such as the inbound octet counter of one interface?",
   "An OID (object identifier)",
   ["A community string","A VLAN ID","A BSSID"],
   "Cada dato de la MIB tiene un OID (Object Identifier), una secuencia numérica jerárquica única.",
   ["La community string es como una contraseña.","La VLAN ID identifica una VLAN.","El BSSID identifica un radio Wi-Fi."]],

  ["3.2","m","snmp,community-strings",
   "What is the security weakness of SNMPv2c community strings?",
   "They are sent in clear text",
   ["They are encrypted with weak keys","They expire every hour and must be reset","They can only be numbers"],
   "Las community strings funcionan como una contraseña, pero viajan sin cifrar: quien capture el tráfico las ve.",
   ["No se cifran en absoluto.","No caducan.","Pueden ser texto."]],

  ["3.2","m","snmp,security",
   "A newly deployed switch still has the default SNMP read community 'public'. What is the risk?",
   "Anyone who reaches the switch can read its details",
   ["The switch will stop forwarding frames","SNMP traps will be encrypted","The switch cannot be pinged by the monitoring server"],
   "Los valores por defecto ('public' y 'private') son lo primero que prueba un atacante: le permiten leer información sensible del equipo.",
   ["Seguiría reenviando tramas.","Con 'public' nada va cifrado.","No afecta al ping."]],

  ["3.2","h","snmp,snmpv3",
   "Policy requires that monitoring credentials and data never travel in clear text. How should SNMP be configured?",
   "SNMPv3 with authentication and privacy (authPriv)",
   ["SNMPv2c with a long, complex community string","SNMPv1 on a non-standard port","SNMPv2c with traps disabled"],
   "Solo SNMPv3 con authPriv autentica a los usuarios y cifra los datos.",
   ["Una community larga sigue viajando en claro.","Cambiar de puerto no cifra nada.","Quitar los traps no cifra el sondeo."]],

  ["3.2","m","netflow,flow-data",
   "Which monitoring data shows who talked to whom, on which ports and how much, without storing full packet contents?",
   "Flow data (NetFlow or IPFIX)",
   ["Full packet capture","Syslog messages from the firewall","Wireless heat maps"],
   "Los datos de flujo resumen cada conversación: IPs, puertos, protocolo, bytes y duración, sin guardar el contenido.",
   ["La captura completa guarda todo el contenido.","Syslog son mensajes de eventos de los equipos.","Un mapa de calor muestra cobertura Wi-Fi."]],

  ["3.2","m","netflow,packet-capture",
   "What is the key difference between flow data and a packet capture?",
   "Flow data is metadata; a capture has full packets",
   ["Flow data includes every byte of every packet","Packet captures only record counts","They are the same thing with different vendor names"],
   "El flujo es un resumen (quién, a quién, cuánto). La captura guarda cada paquete completo: ideal para análisis a fondo, pero ocupa muchísimo.",
   ["El flujo no guarda el contenido.","La captura guarda los paquetes completos.","Son distintos."]],

  ["3.2","e","packet-capture",
   "An application fails with a strange protocol error. Which data would let an engineer examine every field of the exchanged packets?",
   "A packet capture",
   ["An SNMP interface counter","An SLA document","A rack diagram"],
   "Una captura de paquetes muestra cada paquete con todas sus cabeceras y su contenido.",
   ["Los contadores SNMP solo dan totales.","El SLA es un acuerdo.","El diagrama de rack es documentación física."]],

  ["3.2","e","port-mirroring",
   "How can a network analyzer or IDS receive a copy of traffic passing through a switch port without being inline?",
   "Configure port mirroring (SPAN)",
   ["Enable jumbo frames on the analyzer port","Assign it to the native VLAN","Enable PortFast on the analyzer port"],
   "Port mirroring (SPAN) copia el tráfico de uno o varios puertos hacia el puerto donde está el analizador.",
   ["Las jumbo frames cambian el tamaño de trama.","La VLAN nativa no copia tráfico.","PortFast acelera el arranque del puerto."]],

  ["3.2","e","baseline",
   "What is a network performance baseline?",
   "A record of normal performance for later comparison",
   ["The minimum cable category allowed","The first configuration of a device","The slowest link in the network at peak time"],
   "La línea base (baseline) es cómo se comporta la red normalmente. Sin ella no sabes si algo es anormal.",
   ["No es una categoría de cable.","Eso sería la configuración inicial.","No es un enlace concreto."]],

  ["3.2","m","baseline,anomaly",
   "A monitoring system alerts when WAN utilization is 3 times higher than usual for that time of day. What is this based on?",
   "Baseline anomaly alerting",
   ["A static DHCP reservation","A tabletop exercise with the WAN team","A cable certification"],
   "Comparar lo actual con lo normal para esa hora (la línea base) y avisar de las desviaciones es alertar por anomalía.",
   ["Una reserva DHCP no mide tráfico.","Un tabletop es un ejercicio de desastres.","La certificación de cable prueba el medio físico."]],

  ["3.2","e","syslog",
   "Which protocol sends log messages from network devices to a central collector?",
   "Syslog",
   ["SMTP","TFTP","NTP"],
   "Syslog (normalmente UDP 514) envía los mensajes de registro de los equipos a un servidor central.",
   ["SMTP envía correo.","TFTP transfiere archivos.","NTP sincroniza la hora."]],

  ["3.2","m","syslog,severity",
   "In syslog severity levels, which number is the MOST severe?",
   "0 (Emergency)",
   ["7 (Debug)","4 (Warning)","6 (Informational)"],
   "La escala va de 0 (Emergency, lo más grave) a 7 (Debug, lo menos grave).",
   ["7 es lo menos grave.","4 es un aviso intermedio.","6 es informativo."]],

  ["3.2","h","syslog,severity",
   "Which syslog severity level number corresponds to Warning?",
   "4",
   ["0","2","7"],
   "0 Emergency · 1 Alert · 2 Critical · 3 Error · 4 Warning · 5 Notice · 6 Informational · 7 Debug.",
   ["0 es Emergency.","2 es Critical.","7 es Debug."]],

  ["3.2","m","siem",
   "What does a SIEM do?",
   "Correlates logs from many sources and alerts",
   ["Assigns VLANs to switch ports","Provides wireless coverage for security cameras","Replaces the need for a firewall"],
   "Un SIEM (Security Information and Event Management) reúne logs de todo tipo, los correlaciona y avisa de patrones de ataque.",
   ["No asigna VLANs.","No da cobertura Wi-Fi.","No sustituye al firewall."]],

  ["3.2","e","log-aggregation",
   "What is a main benefit of sending all device logs to a central log aggregation system?",
   "Events from all devices are searchable in one place",
   ["Devices stop generating logs","Logs are deleted faster from each device to free local storage","Each device needs more storage"],
   "Centralizar los logs permite buscar, correlacionar y conservarlos en un solo sitio, en lugar de ir equipo por equipo.",
   ["Los equipos siguen generando logs.","La centralización sirve para conservarlos mejor, no para borrarlos.","Al contrario: los equipos no tienen que guardar tanto."]],

  ["3.2","m","api-integration",
   "A monitoring platform pulls statistics directly from a cloud-managed wireless controller over HTTPS using JSON. What method is it using?",
   "API integration",
   ["SNMPv1 polling","Console port access","Port mirroring"],
   "Los controladores y servicios en la nube exponen APIs (normalmente REST sobre HTTPS con JSON) que las herramientas de monitorización consultan.",
   ["SNMPv1 no usa HTTPS ni JSON.","La consola es acceso local por cable.","Port mirroring copia tráfico."]],

  ["3.2","e","network-discovery",
   "Which monitoring function scans the network to find devices and build an inventory or topology map?",
   "Network discovery",
   ["Configuration backup","SLA reporting","Captive portal"],
   "El descubrimiento de red recorre las subredes (con ping, SNMP, LLDP…) para encontrar equipos y ver cómo se conectan.",
   ["El backup guarda configuraciones.","El informe de SLA mide cumplimiento.","El portal cautivo es para invitados Wi-Fi."]],

  ["3.2","m","network-discovery",
   "Why would an organization run network discovery on a schedule rather than only ad hoc?",
   "To detect new or rogue devices automatically",
   ["To reduce the number of VLANs","To encrypt all traffic between discovered devices","To avoid documenting devices"],
   "El descubrimiento programado encuentra por sí solo lo que aparece nuevo, incluidos equipos no autorizados.",
   ["No cambia las VLANs.","No cifra.","Al contrario: ayuda a mantener la documentación."]],

  ["3.2","m","traffic-analysis",
   "The WAN link is saturated every afternoon. Which monitoring approach BEST identifies the hosts and applications consuming the bandwidth?",
   "Traffic analysis using flow data",
   ["Availability monitoring with ping","Configuration monitoring","A rack diagram review"],
   "El análisis de tráfico con flujos (NetFlow/IPFIX) muestra los 'top talkers': qué equipos y aplicaciones gastan más.",
   ["El ping solo dice si algo responde.","La monitorización de configuración vigila cambios de configuración.","Un diagrama de rack no muestra tráfico."]],

  ["3.2","e","performance-monitoring",
   "Which metrics are typical in network performance monitoring?",
   "Latency, utilization, CPU and memory",
   ["Cable color and rack number","User job titles and departments","Warranty dates and serial numbers"],
   "La monitorización de rendimiento mide cómo funciona la red: latencia, uso de enlaces, CPU, memoria y errores.",
   ["Eso es documentación física.","No son métricas de red.","Eso es inventario."]],

  ["3.2","e","availability-monitoring",
   "Which type of monitoring alerts the team as soon as a server or switch stops responding?",
   "Availability (uptime) monitoring",
   ["Configuration monitoring of each device","Asset inventory","Traffic shaping"],
   "La monitorización de disponibilidad comprueba periódicamente si el equipo responde (ping, puertos, servicios) y avisa si deja de hacerlo.",
   ["La de configuración vigila cambios, no caídas.","El inventario no alerta de caídas.","El traffic shaping controla el ancho de banda."]],

  ["3.2","m","configuration-monitoring",
   "A monitoring tool sends an alert whenever a router's running configuration changes. What is this?",
   "Configuration monitoring",
   ["Availability monitoring","Flow analysis","Heat mapping"],
   "La monitorización de configuración detecta y avisa de cualquier cambio de configuración, autorizado o no.",
   ["La de disponibilidad mira si el equipo responde.","El análisis de flujos mira el tráfico.","El mapa de calor es para Wi-Fi."]],

  ["3.2","m","thresholds",
   "An administrator wants an alert when a WAN interface stays above 85% utilization for 10 minutes. What should be configured?",
   "A threshold-based alert",
   ["A DHCP reservation for the router","A new VLAN for the WAN link","A longer patch cable"],
   "Se define un umbral (85 % durante 10 minutos) y el sistema avisa cuando se supera.",
   ["DHCP no mide tráfico.","Una VLAN no genera alertas.","El cable no tiene nada que ver."]],

  ["3.2","m","netflow",
   "Which of the following are provided by flow data such as NetFlow? (Choose TWO)",
   ["Source and destination IP addresses","Port numbers and byte counts per conversation"],
   ["The full text of emails","User passwords typed into websites","The physical location of each cable"],
   "Los flujos registran quién habla con quién (IPs), por qué puerto y cuánto (bytes y paquetes).",
   ["El flujo no guarda contenido.","El flujo no guarda contenido.","El flujo no sabe nada de cables."]],

  ["3.2","m","snmp,snmpv3",
   "Which of the following security features are provided by SNMPv3? (Choose TWO)",
   ["User-based authentication","Encryption of SNMP messages"],
   ["Clear-text community strings","Automatic VLAN assignment","Built-in packet capture"],
   "SNMPv3 añade autenticación por usuario y cifrado de los mensajes.",
   ["Las community strings en claro son de v1/v2c.","SNMP no asigna VLANs.","SNMP no captura paquetes."]],

  ["3.2","e","sensors",
   "How can a network team be alerted when a switch's internal temperature gets too high?",
   "Poll its temperature sensor via SNMP or API",
   ["Check the cable map for that closet","Run a port scan against the switch","Look at the DHCP lease table"],
   "Los equipos exponen sus sensores (temperatura, ventiladores, fuentes) por SNMP o por API, y el sistema de monitorización avisa.",
   ["El mapa de cables no mide temperatura.","Un escaneo de puertos busca servicios abiertos.","DHCP no sabe de temperaturas."]],

  ["3.2","m","log-retention",
   "Why do many organizations define how long logs must be retained?",
   "For compliance and to investigate past incidents",
   ["To make the network faster by freeing disk space","To avoid time synchronization","To assign longer DHCP leases"],
   "Muchas normativas exigen conservar logs durante un tiempo, y además son clave para investigar incidentes pasados.",
   ["No mejora la velocidad.","Hace falta NTP igualmente.","No tiene relación con DHCP."]],

  ["3.2","m","alerting",
   "Engineers ignore the monitoring system because it sends hundreds of low-value alerts per day. What should be done?",
   "Tune thresholds so only meaningful events alert",
   ["Disable all monitoring until it is quieter","Send every alert to every employee","Double the polling frequency"],
   "Demasiadas alertas provocan 'fatiga de alertas'. Hay que ajustar umbrales y prioridades para que cada aviso importe.",
   ["Quitar la monitorización deja la red a ciegas.","Mandarlo a todos lo empeora.","Sondear más a menudo genera aún más ruido."]],

  ["3.2","h","tap,port-mirroring",
   "Why might an engineer use a hardware network TAP instead of a switch SPAN port for monitoring?",
   "It copies all traffic passively, even errored frames",
   ["A TAP encrypts the copied traffic","A TAP assigns IP addresses to the monitored hosts","A TAP blocks malicious traffic inline"],
   "Un TAP copia físicamente todo lo que pasa por el cable, incluidos los errores, sin depender del switch. Un SPAN puede perder tráfico si el switch va cargado.",
   ["No cifra.","No asigna direcciones.","Es pasivo; no bloquea como un IPS."]],

  ["3.2","m","snmp,interface-counters",
   "Which SNMP-polled data helps detect a failing cable before users complain?",
   "Rising interface error counters",
   ["The device hostname and uptime","The rack unit number","The SSID name of the closet AP"],
   "Si los contadores de errores (CRC) o descartes de una interfaz suben de forma sostenida, suele haber un problema físico o de saturación.",
   ["El nombre de host no cambia con los fallos.","El número de U no es un dato de salud.","El SSID no tiene nada que ver con un cable."]],

  ["3.2","e","syslog",
   "Which information does a typical syslog message include?",
   "Timestamp, source, severity and message",
   ["The full packet payload","The user's password in clear text","The switch's serial number only"],
   "Un mensaje syslog lleva fecha y hora, qué equipo lo envía, la gravedad y la descripción del evento.",
   ["No incluye paquetes completos.","Nunca debería incluir contraseñas.","No es solo el número de serie."]],

  ["3.2","m","siem,correlation",
   "A SIEM alerts because the same account failed to log in on 15 different servers within two minutes. What capability made this possible?",
   "Correlation across log sources",
   ["Port mirroring to the SIEM","DHCP snooping on access switches","Channel bonding"],
   "Cada servidor por separado solo ve un fallo; el SIEM junta los logs de todos y detecta el patrón.",
   ["Port mirroring copia tráfico.","DHCP snooping bloquea servidores DHCP falsos.","Channel bonding es de Wi-Fi."]],

  ["3.2","m","packet-capture,privacy",
   "Why must packet captures be stored and handled carefully?",
   "They may contain credentials or personal data",
   ["They damage network cards if opened twice","They always contain viruses","They slow down every switch permanently"],
   "Una captura guarda el contenido de los paquetes; si hay tráfico sin cifrar, puede contener contraseñas o datos personales.",
   ["No dañan las tarjetas.","No contienen virus por definición.","No ralentizan los switches de forma permanente."]],

  ["3.2","h","snmp,security",
   "Why should SNMP read-write (set) access be disabled unless it is truly needed?",
   "An attacker could change the configuration remotely",
   ["Read-write access prevents the NMS from polling the device","It causes duplex mismatches","It disables syslog on the device"],
   "Con acceso de escritura (SET) se puede modificar la configuración del equipo. Si no hace falta, se deja solo lectura (y con SNMPv3).",
   ["No impide el sondeo.","No tiene relación con el dúplex.","No desactiva syslog."]],

  ["3.2","m","network-discovery,lldp",
   "Which protocols can a network discovery tool use to learn how switches and routers are connected to each other? ",
   "LLDP or CDP neighbor information",
   ["DHCP lease tables only","Wi-Fi beacons only","SMTP messages between the switches"],
   "LLDP (Link Layer Discovery Protocol) y CDP (Cisco Discovery Protocol) informan de qué vecino hay en cada puerto; así se dibuja la topología.",
   ["Los préstamos DHCP no dicen qué conecta con qué.","Los beacons Wi-Fi solo anuncian SSIDs.","SMTP es correo."]],

  ["3.2","m","network-discovery,security",
   "A scheduled discovery scan finds a device with an unknown MAC address on a conference-room port. Why is this valuable?",
   "It can reveal unauthorized or rogue devices on the network",
   ["It automatically increases bandwidth for the devices it finds","It removes the device from DHCP","It replaces the need for 802.1X"],
   "Descubrir equipos desconocidos ayuda a detectar dispositivos no autorizados.",
   ["No aumenta el ancho de banda.","No lo saca de DHCP por sí solo.","No sustituye al control de acceso."]],

  ["3.2","m","syslog,debug",
   "Why should debug-level (severity 7) logging normally not be left enabled on production devices?",
   "Huge log volume that hurts performance and hides events",
   ["It disables routing while enabled","It encrypts all logs so they cannot be read by the administrators","It deletes older logs immediately"],
   "El nivel debug registra muchísimo detalle: llena los logs, carga la CPU y esconde lo importante. Se activa solo durante un diagnóstico.",
   ["No desactiva el enrutamiento.","No cifra nada.","No borra logs por sí mismo."]],

  ["3.2","m","netflow,collector",
   "Routers export flow records. Which component receives, stores and analyzes them?",
   "Flow collector",
   ["DHCP server","Wireless controller","Patch panel"],
   "El colector de flujos (flow collector) recibe lo que exportan los routers y switches, y permite analizarlo.",
   ["DHCP asigna IPs.","El WLC gestiona APs.","El patch panel es cableado pasivo."]],
];

export default q;
