import type { Raw } from '../types';

// 3.3 Disaster recovery concepts (35) · 3.4 IPv4 and IPv6 network services (45)
const q: Raw[] = [
  ["3.3","m","dr,rpo",
   "A company backs up its database every 6 hours. Which statement about its recovery point objective (RPO) is correct?",
   "In the worst case it could lose up to about 6 hours of data",
   ["It can be back online within 6 hours","Its hardware fails on average every 6 hours, as shown by the MTBF","It must test backups every 6 hours"],
   "El RPO (Recovery Point Objective) mide cuántos datos puedes perder. Con copias cada 6 horas, el peor caso es perder casi 6 horas de datos.",
   ["Eso sería un RTO (tiempo para volver a funcionar).","Eso sería el MTBF.","La frecuencia de las pruebas no es el RPO."]],

  ["3.3","e","dr,rto",
   "What does the recovery time objective (RTO) define?",
   "The maximum acceptable time to restore a service",
   ["The maximum amount of data that can be lost","The average time between hardware failures of critical systems","The time needed to install a new cable"],
   "El RTO (Recovery Time Objective) es cuánto tiempo puede estar caído un servicio antes de que el impacto sea inaceptable.",
   ["Eso es el RPO.","Eso es el MTBF.","No se refiere a instalar cables."]],

  ["3.3","e","dr,mttr",
   "What does MTTR measure?",
   "The average time to repair a failure",
   ["The average time between failures","The maximum data loss allowed in hours","The time a UPS can run on battery"],
   "El MTTR (Mean Time To Repair) es cuánto se tarda de media en reparar algo que ha fallado.",
   ["Eso es el MTBF.","Eso es el RPO.","Eso es la autonomía del UPS."]],

  ["3.3","e","dr,mtbf",
   "What does MTBF measure?",
   "The average time a component operates between failures",
   ["The average time it takes to repair a failed component","The maximum downtime allowed","The number of backups per day"],
   "El MTBF (Mean Time Between Failures) mide la fiabilidad: cuánto funciona algo de media antes de fallar.",
   ["Eso es el MTTR.","Eso es el RTO.","No es una métrica de backups."]],

  ["3.3","m","dr,mtbf",
   "Two switch models are identical except for MTBF: model A is 200,000 hours and model B is 80,000 hours. Which is expected to be more reliable?",
   "Model A, because higher MTBF means fewer failures",
   ["Model B, because a lower MTBF is better","Both are equally reliable since specs match","MTBF does not relate to reliability"],
   "Cuanto mayor es el MTBF, más tiempo pasa de media entre fallos: el modelo A es más fiable.",
   ["Un MTBF bajo significa fallos más frecuentes.","Los valores son distintos.","El MTBF es precisamente una medida de fiabilidad."]],

  ["3.3","m","dr,sites",
   "A trading platform has an RTO of 15 minutes. Which type of disaster recovery site does it need?",
   "Hot site",
   ["Cold site","Warm site","No DR site; restore from tape at headquarters"],
   "Con un RTO de minutos hace falta un hot site: equipado, con datos replicados y listo para asumir la carga casi al momento.",
   ["Un cold site tarda días o semanas en ponerse en marcha.","Un warm site tarda horas o días.","Restaurar desde cinta tarda demasiado."]],

  ["3.3","e","dr,sites",
   "What does a cold site typically provide?",
   "Space, power and cooling, but no ready equipment",
   ["Fully running servers with real-time data replication","A second internet link at headquarters from another provider","Only a list of employee phone numbers"],
   "Un cold site es un local preparado (electricidad, climatización, espacio), pero hay que llevar y montar los equipos y restaurar los datos. Es barato y lento.",
   ["Eso es un hot site.","Un enlace extra en la sede no es un sitio de recuperación.","Una lista de teléfonos no es un sitio."]],

  ["3.3","m","dr,sites",
   "Which disaster recovery site has some equipment and connectivity in place but needs recent data restored and configuration before it can take over?",
   "Warm site",
   ["Hot site","Cold site","Colocation of the production site"],
   "Un warm site está a medio camino: tiene equipos y conectividad, pero hay que restaurar datos y ajustar la configuración. Tarda horas o días.",
   ["El hot site ya tiene los datos al día.","El cold site no tiene equipos.","Estar en el mismo sitio que producción no protege frente a un desastre en ese sitio."]],

  ["3.3","e","dr,sites",
   "Which disaster recovery site can take over almost immediately because it has equipment running and data continuously replicated?",
   "Hot site",
   ["Cold site","Warm site","Backup tape vault"],
   "El hot site está listo para funcionar: equipos en marcha y datos replicados.",
   ["El cold site es solo el espacio.","El warm site necesita restaurar datos.","Un almacén de cintas guarda copias, no ejecuta servicios."]],

  ["3.3","e","dr,sites,cost",
   "Which disaster recovery site is usually the MOST expensive to maintain?",
   "Hot site",
   ["Cold site","Warm site","All cost exactly the same"],
   "Mantener equipos duplicados en marcha y datos replicados cuesta mucho. El cold site es el más barato.",
   ["El cold site es el más barato.","El warm site es intermedio.","Los costes son muy distintos."]],

  ["3.3","m","dr,cloud-site",
   "A company uses a cloud provider to spin up replicas of its servers only when a disaster is declared. What is a main advantage of this cloud DR site?",
   "Fast recovery without owning a second facility",
   ["It requires no internet connectivity at all","It guarantees zero data loss in every case","It eliminates the need to test the DR plan"],
   "Un sitio de recuperación en la nube evita pagar un segundo centro de datos: se paga sobre todo cuando se usa.",
   ["Depende de la conectividad.","La pérdida de datos depende de cómo se replique.","Hay que probarlo igualmente."]],

  ["3.3","m","ha,active-active",
   "Two firewalls both process traffic at the same time and share the load. If one fails, the other carries everything. What is this configuration?",
   "Active-active",
   ["Active-passive","Cold standby","Single point of failure"],
   "En activo-activo los dos equipos trabajan a la vez y se reparten la carga.",
   ["En activo-pasivo uno espera sin tráfico.","En cold standby el equipo ni siquiera está encendido.","Es justo lo contrario de un punto único de fallo."]],

  ["3.3","m","ha,active-passive",
   "One router handles all traffic while a second router waits and takes over only if the first fails. What is this configuration?",
   "Active-passive",
   ["Active-active","Load balancing across both","Hot aisle containment"],
   "En activo-pasivo el equipo pasivo está preparado pero no mueve tráfico hasta que el activo falla.",
   ["En activo-activo ambos trabajan a la vez.","Repartir la carga sería activo-activo.","La contención de pasillo caliente es climatización."]],

  ["3.3","h","ha,active-active",
   "Two load-balanced servers in an active-active pair each run at 70% CPU. What is the risk if one fails?",
   "The survivor cannot handle 140% of the load, so service will degrade",
   ["None, because active-active always has spare capacity","The failed server's load is dropped silently with no effect","The survivor will automatically double its CPU"],
   "En activo-activo cada nodo debe poder soportar solo la carga total. Al 70 % cada uno, el superviviente tendría que asumir un 140 %.",
   ["El activo-activo no garantiza capacidad de sobra; hay que planificarla.","Los usuarios lo notarían.","El hardware no crece solo."]],

  ["3.3","e","dr,testing,tabletop",
   "Team members meet in a conference room and talk through how they would respond to a simulated data center flood, without touching any systems. What is this?",
   "Tabletop exercise",
   ["Full failover test","Penetration test","Validation test on production"],
   "Un tabletop es un ejercicio de mesa: se recorre el plan hablando, sin tocar sistemas. Es barato y detecta huecos en el plan.",
   ["Una prueba de conmutación real mueve servicios.","Un pentest busca vulnerabilidades.","Una prueba de validación ejecuta el procedimiento de verdad."]],

  ["3.3","m","dr,testing,validation",
   "Which type of DR test actually fails services over to the recovery site to confirm they work?",
   "Validation test (failover test)",
   ["Tabletop exercise","Asset inventory review of the DR site","Heat map survey"],
   "Una prueba de validación ejecuta el plan de verdad: se conmuta y se comprueba que todo funciona en el sitio de recuperación.",
   ["El tabletop solo se habla.","Revisar el inventario no prueba la recuperación.","Un mapa de calor mide cobertura Wi-Fi."]],

  ["3.3","e","dr,testing",
   "Why should disaster recovery plans be tested regularly?",
   "To confirm it works and find gaps early",
   ["Testing is only required by law once","To increase the RPO for every system","To avoid documenting the plan"],
   "Un plan que nunca se prueba suele fallar el día que se necesita. Las pruebas revelan pasos que faltan o datos obsoletos.",
   ["Las pruebas deben ser periódicas.","El objetivo es cumplir el RPO, no aumentarlo.","El plan debe estar documentado."]],

  ["3.3","m","dr,mttr",
   "How can an organization reduce MTTR for failed access switches?",
   "Keep configured spares and current config backups",
   ["Buy switches with a lower MTBF","Disable monitoring alerts on access switches to reduce noise","Extend the maintenance window"],
   "Con repuestos a mano y la configuración guardada, cambiar un switch roto lleva minutos: baja el tiempo medio de reparación.",
   ["Un MTBF menor significa más fallos.","Sin alertas tardas más en enterarte.","La ventana de mantenimiento no afecta a las reparaciones urgentes."]],

  ["3.3","h","dr,rpo,replication",
   "A business requires an RPO of zero for its financial transactions. What does this typically require?",
   "Synchronous replication to a second site",
   ["Weekly full backups to tape","Nightly incremental backups","A tabletop exercise every quarter"],
   "RPO cero significa no perder ni una transacción: cada escritura debe confirmarse en los dos sitios a la vez (replicación síncrona).",
   ["Una copia semanal puede perder una semana.","Una copia nocturna puede perder un día.","Un ejercicio no protege los datos."]],

  ["3.3","h","ha,rto",
   "Which of the following would reduce the RTO for a critical application? (Choose TWO)",
   ["A hot standby environment","Automated failover"],
   ["Moving backups to a cold site","Longer backup intervals","Removing redundant power supplies"],
   "Un entorno en espera caliente y la conmutación automática acortan el tiempo que el servicio está caído.",
   ["Un cold site alarga la recuperación.","Hacer copias con menos frecuencia afecta al RPO, y en contra.","Quitar redundancia aumenta el riesgo de caída."]],

  ["3.3","m","dr,testing,tabletop",
   "Which of the following describe a tabletop exercise? (Choose TWO)",
   ["It is discussion-based","It does not disrupt production systems"],
   ["It requires failing over all servers","It replaces the need for a DR plan","It is performed only by the hardware vendor"],
   "Un tabletop se hace hablando, sin tocar los sistemas en producción.",
   ["Eso es una prueba de conmutación.","Precisamente sirve para revisar el plan.","Lo hace el propio equipo, no el fabricante."]],

  ["3.3","m","backup",
   "Which backup type takes the longest to create but is the simplest and fastest to restore from?",
   "Full backup",
   ["Incremental backup","Differential backup","Snapshot of a single file"],
   "La copia completa copia todo cada vez (lenta de crear), pero para restaurar basta con ella sola.",
   ["La incremental es rápida de crear, pero para restaurar necesitas la completa y todas las incrementales.","La diferencial necesita la completa más la última diferencial.","Un snapshot de un archivo no es una copia completa del sistema."]],

  ["3.3","e","backup,offsite",
   "Why should a copy of backups be stored offsite or in the cloud?",
   "So one site disaster cannot destroy data and backups",
   ["To make backups faster to create","Because onsite backups are illegal in most countries","To avoid encrypting the backups"],
   "Si las copias están en el mismo edificio, un incendio o una inundación se lleva datos y copias a la vez.",
   ["Offsite suele ser más lento, no más rápido.","Las copias locales son legales y útiles.","Las copias externas también deben cifrarse."]],

  ["3.3","e","ha,availability",
   "What does 'five nines' of availability mean?",
   "99.999% uptime, about 5 minutes down per year",
   ["The network has five redundant links","99.9% uptime, about 9 hours down per year","Five backups per day stored in five places"],
   "Cinco nueves = 99,999 % de disponibilidad: unos 5,26 minutos de caída al año.",
   ["No se refiere al número de enlaces.","99,9 % son tres nueves (unas 8,8 horas al año).","No tiene que ver con backups."]],

  ["3.3","m","ha,spof",
   "A small office connects all its departments through one core switch with a single power supply. What is this switch?",
   "A single point of failure",
   ["An active-active cluster","A hot site","A redundant design"],
   "Si ese switch (o su única fuente) falla, cae todo: es un punto único de fallo.",
   ["Un clúster necesita al menos dos equipos.","Un hot site es un sitio de recuperación.","No hay nada redundante."]],

  ["3.3","m","ha,redundancy",
   "Which change BEST improves the availability of a core switch that has one power supply?",
   "Add a second PSU on a different circuit",
   ["Replace its patch cables with longer ones","Change its hostname to mark it as critical","Disable SNMP on it to reduce CPU load"],
   "Una segunda fuente conectada a otro circuito elimina ese punto de fallo eléctrico.",
   ["Los cables más largos no aportan redundancia.","El nombre no afecta a la disponibilidad.","Quitar SNMP no aumenta la disponibilidad."]],

  ["3.3","m","dr,sites",
   "Why should a disaster recovery site be located a significant distance from the primary site?",
   "So one regional event cannot hit both sites",
   ["To reduce latency between the two sites","To share the same power grid","Because nearby sites are not allowed to have networks"],
   "La distancia geográfica evita que el mismo desastre regional afecte a los dos sitios.",
   ["La distancia aumenta la latencia; es un compromiso.","Compartir red eléctrica es justo el riesgo que se quiere evitar.","No existe esa prohibición."]],

  ["3.3","h","dr,failback",
   "After a disaster, services ran at the DR site for two weeks. Moving them back to the repaired primary site is called:",
   "Failback",
   ["Failover","Tabletop","Snapshot"],
   "Failover es pasar al sitio de recuperación; failback es volver al sitio principal cuando ya está reparado.",
   ["Failover es el paso inicial al sitio de recuperación.","El tabletop es un ejercicio de mesa.","Un snapshot es una copia puntual."]],

  ["3.3","h","dr,bia",
   "Which activity determines how critical each business process is and helps set its RTO and RPO values?",
   "Business impact analysis",
   ["Wireless site survey","Port scanning","Cable certification"],
   "El análisis de impacto en el negocio (BIA, Business Impact Analysis) mide cuánto cuesta cada hora de parada o de datos perdidos, y de ahí salen el RTO y el RPO.",
   ["El site survey mide la cobertura Wi-Fi.","El escaneo de puertos busca servicios.","La certificación prueba cables."]],

  ["3.3","m","dr,plan",
   "Which content should be included in a disaster recovery plan?",
   "Roles, contacts, procedures and restore order",
   ["Only the list of hardware vendors","User passwords for every system","The office seating chart for all employees"],
   "Un plan de recuperación dice quién hace qué, cómo contactar a cada persona, los pasos a seguir y en qué orden se levanta cada sistema.",
   ["Los proveedores son solo una parte.","Las contraseñas nunca van en el plan.","La distribución de mesas no ayuda a recuperar."]],

  ["3.3","h","dr,mttr,rto",
   "What is the relationship between RTO and MTTR?",
   "RTO is the recovery target; MTTR, the real average, should stay below it",
   ["They are two names for the same value, used by different teams","MTTR is the maximum data loss allowed","RTO measures time between failures; MTTR measures repair time"],
   "El RTO es el objetivo (lo máximo aceptable); el MTTR es lo que realmente tardas de media. Si el MTTR supera al RTO, no cumples.",
   ["No son lo mismo.","La pérdida de datos es el RPO.","El tiempo entre fallos es el MTBF."]],

  ["3.3","h","dr,replication",
   "A company replicates data to its DR site asynchronously every few minutes. What does this mean for its RPO?",
   "Recent data may be lost, so the RPO is above zero",
   ["No data can ever be lost","The RTO becomes zero because data is copied to the DR site","Backups are no longer needed"],
   "Con replicación asíncrona, lo escrito desde la última copia puede perderse: el RPO es de unos minutos, no cero.",
   ["Eso solo lo garantiza la replicación síncrona.","La replicación no hace el RTO cero.","Las copias siguen siendo necesarias, por ejemplo contra borrados o ransomware."]],

  ["3.3","m","ha,clustering",
   "Several web servers behind a load balancer keep a website available when one server fails. Which concept does this provide?",
   "High availability",
   ["Cold site recovery","Single point of failure","Configuration drift"],
   "Varios servidores con un balanceador delante mantienen el servicio aunque uno falle: alta disponibilidad.",
   ["Un cold site es para desastres y es lento.","Es justo lo contrario.","La desviación de configuración es otro problema."]],

  ["3.3","m","ha,nic-teaming",
   "A server has two network cards connected to two different switches and configured to work as one logical interface. What does this provide?",
   "NIC teaming",
   ["Hot site","Tabletop exercise","A VLAN trunk"],
   "El NIC teaming une varias tarjetas en una lógica: si falla una tarjeta o un switch, el servidor sigue conectado.",
   ["Un hot site es otro centro de datos.","El tabletop es un ejercicio de mesa.","No es un trunk hacia internet."]],

  ["3.3","m","dr,mtbf",
   "A vendor's datasheet lists a component's expected reliability as an average number of operating hours before failure. Which metric is this?",
   "MTBF",
   ["MTTR","RPO","RTO"],
   "El número de horas medias de funcionamiento antes de un fallo es el MTBF (Mean Time Between Failures).",
   ["El MTTR mide el tiempo de reparación.","El RPO es la pérdida de datos aceptable.","El RTO es el tiempo de recuperación aceptable."]],

  ["3.4","m","dhcp,dora",
   "What is the correct order of the DHCP lease process?",
   "Discover → Offer → Request → Acknowledge",
   ["Request → Offer → Discover → Acknowledge","Offer → Discover → Acknowledge → Request","Discover → Request → Offer → Acknowledge"],
   "DORA: el cliente busca (Discover), el servidor ofrece (Offer), el cliente pide esa oferta (Request) y el servidor confirma (Acknowledge).",
   ["El cliente no puede pedir antes de descubrir un servidor.","El servidor no ofrece nada sin que el cliente pregunte.","La oferta llega antes de la petición."]],

  ["3.4","e","dhcp,scope",
   "What is a DHCP scope?",
   "The addresses and settings DHCP hands out for a subnet",
   ["The physical range of a wireless AP","The number of routers in a network","A list of blocked websites that applies to all DHCP clients"],
   "El scope (ámbito) es el conjunto de direcciones y opciones (gateway, DNS…) que el servidor DHCP reparte en una subred.",
   ["La cobertura del AP no es un scope DHCP.","No cuenta routers.","No es un filtro web."]],

  ["3.4","e","dhcp,reservation",
   "A network printer must always receive the same IP address from DHCP. What should be configured?",
   "A DHCP reservation for its MAC",
   ["A shorter lease time for printers","A new VLAN for printers","An exclusion for the whole scope"],
   "Una reserva asocia la MAC de la impresora a una IP concreta: siempre recibe la misma.",
   ["Un préstamo más corto no garantiza la misma IP.","Una VLAN no fija direcciones.","Excluir todo el rango dejaría sin IPs a los demás."]],

  ["3.4","m","dhcp,exclusion",
   "Addresses 10.1.1.1 through 10.1.1.20 are statically assigned to servers inside a DHCP scope. What prevents DHCP from handing them out?",
   "A DHCP exclusion range",
   ["A DHCP reservation for each client","A longer lease time","A second DNS server"],
   "Una exclusión le dice al servidor DHCP que no reparta esas direcciones del rango, porque ya se usan de forma estática.",
   ["Las reservas son para clientes DHCP concretos, no para evitar IPs estáticas.","El tiempo de préstamo no evita conflictos.","DNS no controla la asignación de IPs."]],

  ["3.4","e","dhcp,lease",
   "What is a DHCP lease time?",
   "How long a client may keep its address before renewing",
   ["How long a DNS record is cached","How long a switch keeps MAC addresses","The time a UPS can run on battery after a power outage starts"],
   "El préstamo (lease) indica cuánto tiempo puede usar el cliente esa IP antes de renovarla.",
   ["La caché DNS usa su propio TTL.","El envejecimiento de la tabla MAC es otra cosa.","Eso es la autonomía del UPS."]],

  ["3.4","m","dhcp,lease",
   "A coffee shop's guest Wi-Fi runs out of IP addresses because thousands of visitors pass through each day. What change helps MOST?",
   "Shorten the DHCP lease time",
   ["Lengthen the lease time to one month","Disable DHCP on the guest SSID","Use static IPs for every guest"],
   "Con préstamos cortos, las IPs de quienes ya se fueron vuelven pronto al conjunto disponible.",
   ["Un mes retendría las IPs de gente que ya no está.","Sin DHCP nadie tendría IP.","Configurar IPs estáticas a los invitados es inviable."]],

  ["3.4","h","dhcp,options",
   "Besides an IP address and subnet mask, which DHCP options are most commonly delivered to clients?",
   "Default gateway (3) and DNS servers (6)",
   ["SSID and Wi-Fi password for the client","The switch's STP priority","The client's MAC address"],
   "Las opciones más comunes son el router o gateway (opción 3) y los servidores DNS (opción 6).",
   ["La configuración Wi-Fi no se reparte por DHCP.","La prioridad STP es del switch.","El cliente ya conoce su propia MAC."]],

  ["3.4","m","dhcp,relay",
   "Clients in several VLANs must get addresses from one central DHCP server in the data center. What must be configured on each VLAN's router interface?",
   "A DHCP relay (IP helper)",
   ["A static route to every client","A second DHCP server in every VLAN","Port mirroring to the DHCP server"],
   "El DHCP relay (IP helper) recoge el broadcast del cliente y lo reenvía en unicast al servidor central.",
   ["Las rutas estáticas no reenvían broadcasts.","Funcionaría, pero es justo lo que se quiere evitar.","Port mirroring solo copia tráfico."]],

  ["3.4","m","dhcp,relay",
   "Why is a DHCP relay needed when the DHCP server is on a different subnet from the clients?",
   "Discover is a broadcast, and routers block broadcasts",
   ["DHCP only works over TCP port 67","Clients already know the server's IP address from DNS lookups","DHCP requires IPv6 to cross routers"],
   "El Discover sale en broadcast y los routers no reenvían broadcasts entre redes. El relay hace de puente.",
   ["DHCP usa UDP (67/68).","El cliente no sabe dónde está el servidor.","DHCP para IPv4 no necesita IPv6."]],

  ["3.4","h","dhcp,redundancy",
   "Two DHCP servers serve the same subnet for redundancy. How should their scopes be configured to avoid duplicate address assignments?",
   "Split the range into non-overlapping parts",
   ["Give both servers the identical range","Disable leases on one server permanently","Use the same server name for both"],
   "Si cada servidor reparte una parte distinta del rango (por ejemplo 80/20), nunca asignan la misma IP a dos clientes.",
   ["Rangos idénticos provocan IPs duplicadas (salvo con un failover coordinado).","Sin préstamos, ese servidor no sirve.","El nombre no evita duplicados."]],

  ["3.4","h","dhcp,lease",
   "When does a DHCP client normally first try to renew its lease with the server that assigned it?",
   "At 50% of the lease time",
   ["Only after the lease fully expires","At 5% of the lease time","Every time it sends an ARP request"],
   "El cliente intenta renovar al 50 % del préstamo (T1). Si no puede, lo intenta con cualquier servidor al 87,5 % (T2).",
   ["Esperar al final dejaría al cliente sin IP.","No es tan pronto.","ARP no tiene relación con la renovación."]],

  ["3.4","h","dhcpv6",
   "What is the difference between stateful and stateless DHCPv6?",
   "Stateful assigns addresses; stateless gives only options like DNS",
   ["Stateless assigns addresses; stateful gives only options like DNS","Both assign IPv4 addresses to dual-stack hosts","Stateful DHCPv6 is used only on wireless networks"],
   "El DHCPv6 con estado (stateful) asigna direcciones y lleva el control de quién tiene cada una. El sin estado (stateless) solo da información extra, como DNS; la dirección la crea el host con SLAAC.",
   ["Está al revés.","DHCPv6 es para IPv6.","No depende de si la red es inalámbrica."]],

  ["3.4","m","slaac,ipv6",
   "How does an IPv6 host configure its own global address using SLAAC?",
   "Prefix from router advertisements plus its own interface ID",
   ["It asks a DHCPv4 server for a prefix","It copies the router's address","It uses a 169.254.x.x address from APIPA until a router replies"],
   "Con SLAAC (Stateless Address Autoconfiguration), el router anuncia el prefijo y el host completa la dirección con su propio identificador de interfaz.",
   ["DHCPv4 es para IPv4.","Dos equipos no pueden tener la misma dirección.","169.254 es APIPA, de IPv4."]],

  ["3.4","h","slaac,eui-64",
   "With SLAAC using EUI-64, what is the interface ID based on?",
   "The host's MAC, expanded to 64 bits",
   ["The router's hostname in hexadecimal","A random number chosen by DHCP","The subnet mask of the IPv4 address"],
   "EUI-64 construye el identificador de interfaz a partir de la MAC (48 bits), insertando FFFE en el medio y cambiando un bit. Muchos sistemas usan hoy identificadores aleatorios por privacidad.",
   ["El nombre del router no interviene.","En SLAAC no participa DHCP.","IPv6 no usa máscaras de subred como IPv4."]],

  ["3.4","e","dhcp,dora",
   "Which DHCP message does a server send in response to a client's Discover?",
   "Offer",
   ["Acknowledge","Request","Release"],
   "Tras el Discover, el servidor responde con una Offer que propone una dirección IP.",
   ["El Acknowledge confirma al final.","El Request lo envía el cliente.","El Release lo envía el cliente al liberar su IP."]],

  ["3.4","m","dhcp,conflict",
   "A user sets a static IP on a PC that is inside the DHCP scope, and later another device gets the same IP from DHCP. How should this be prevented?",
   "Reserve or exclude that address in DHCP",
   ["Increase the lease time for all clients","Add a second default gateway","Disable ARP on the PC"],
   "Una reserva (o una exclusión) evita que el servidor reparta una IP que ya usa un equipo.",
   ["El tiempo de préstamo no evita el conflicto.","Un segundo gateway no cambia la asignación.","ARP es necesario para que la red funcione."]],

  ["3.4","h","dhcp",
   "What source IP address does a DHCP client use when sending its initial Discover message?",
   "0.0.0.0",
   ["255.255.255.255","127.0.0.1","The default gateway's address"],
   "El cliente aún no tiene IP, así que usa 0.0.0.0 como origen y envía a 255.255.255.255 como destino.",
   ["255.255.255.255 es el destino (broadcast), no el origen.","127.0.0.1 es loopback y nunca sale del equipo.","Todavía no conoce el gateway."]],

  ["3.4","e","dhcp,options",
   "Which settings can a DHCP server provide to clients in addition to their IP address? (Choose TWO)",
   ["Default gateway","DNS server addresses"],
   ["The client's own MAC address","The switch's VLAN database","The Wi-Fi passphrase"],
   "DHCP entrega, además de la IP y la máscara, el gateway y los servidores DNS, entre otras opciones.",
   ["El cliente ya conoce su MAC.","La base de datos de VLANs es del switch.","La clave Wi-Fi hay que conocerla antes de conectarse."]],

  ["3.4","e","dns,records",
   "Which DNS record maps a hostname to an IPv4 address?",
   "A",
   ["AAAA","MX","PTR"],
   "El registro A relaciona un nombre con una IPv4.",
   ["AAAA es para IPv6.","MX indica los servidores de correo.","PTR resuelve una IP a un nombre (búsqueda inversa)."]],

  ["3.4","e","dns,records",
   "Which DNS record maps a hostname to an IPv6 address?",
   "AAAA",
   ["A","CNAME","NS"],
   "AAAA ('cuádruple A') relaciona un nombre con una dirección IPv6.",
   ["A es para IPv4.","CNAME es un alias hacia otro nombre.","NS indica los servidores de nombres de la zona."]],

  ["3.4","e","dns,records",
   "Which DNS record makes 'www.example.com' an alias of 'webhost.example.com'?",
   "CNAME",
   ["A","MX","TXT"],
   "Un CNAME (Canonical Name) es un alias: apunta a otro nombre, no a una IP.",
   ["A apunta directamente a una IP.","MX es para correo.","TXT guarda texto."]],

  ["3.4","e","dns,records",
   "Which DNS record tells other mail servers where to deliver email for a domain?",
   "MX",
   ["PTR","AAAA","CNAME"],
   "El registro MX (Mail Exchanger) indica qué servidores reciben el correo del dominio.",
   ["PTR es para búsqueda inversa.","AAAA es IPv6.","CNAME es un alias."]],

  ["3.4","m","dns,records,reverse",
   "Which DNS record is used for reverse lookups, resolving an IP address to a hostname?",
   "PTR",
   ["A","MX","NS"],
   "El registro PTR (Pointer) vive en la zona inversa y traduce una IP a un nombre.",
   ["A traduce un nombre a una IPv4.","MX es para correo.","NS indica los servidores de nombres."]],

  ["3.4","m","dns,records",
   "Which DNS record type stores free-form text and is often used for domain ownership verification and email anti-spoofing policies such as SPF?",
   "TXT",
   ["PTR","CNAME","AAAA"],
   "Los registros TXT guardan texto: se usan para verificar la propiedad del dominio y para políticas de correo como SPF.",
   ["PTR es para búsqueda inversa.","CNAME es un alias.","AAAA es IPv6."]],

  ["3.4","m","dns,records",
   "Which DNS record identifies the authoritative name servers for a zone?",
   "NS",
   ["MX","A","TXT"],
   "Los registros NS (Name Server) indican qué servidores son los autoritativos de una zona.",
   ["MX es para correo.","A es un nombre a IPv4.","TXT es texto libre."]],

  ["3.4","m","dns,zones",
   "What is the difference between a forward lookup zone and a reverse lookup zone?",
   "Forward: name to IP; reverse: IP to name",
   ["Forward is for IPv4; reverse is for IPv6","Reverse zones are only used by DHCP","No difference; both hold A records"],
   "La zona directa responde '¿qué IP tiene este nombre?'; la inversa responde '¿qué nombre tiene esta IP?'.",
   ["Ambas zonas existen para IPv4 e IPv6.","Las usan clientes y herramientas, no solo DHCP.","Sí son distintas."]],

  ["3.4","m","dns,authoritative",
   "nslookup returns a 'non-authoritative answer'. What does this mean?",
   "It came from a cache, not the zone's own server",
   ["The answer is definitely wrong","The domain does not exist in public DNS","DNSSEC validation failed for the record"],
   "Una respuesta no autoritativa viene de la caché de un resolver, no del servidor responsable de la zona. Suele ser correcta.",
   ["No significa que sea errónea.","Si no existiera, daría un error de 'no existe' (NXDOMAIN).","No tiene que ver con DNSSEC."]],

  ["3.4","m","dns,zones",
   "What is a secondary DNS zone?",
   "A read-only copy received by zone transfer",
   ["A zone that can only hold MX records","The zone used only for IPv6 AAAA records","A zone that must be edited on every server manually"],
   "La zona secundaria es una copia de solo lectura que se actualiza desde la primaria con transferencias de zona. Da redundancia.",
   ["Puede contener cualquier tipo de registro.","No es exclusiva de IPv6.","Se actualiza sola desde la primaria."]],

  ["3.4","m","dns,recursive",
   "What does a recursive DNS resolver do for a client?",
   "It queries other servers until it gets the answer",
   ["It only answers for the zones it owns and hosts locally","It assigns IP addresses to clients","It blocks all external queries"],
   "El resolver recursivo hace todo el trabajo: pregunta a la raíz, al TLD y al autoritativo, y devuelve la respuesta final al cliente (y la guarda en caché).",
   ["Eso describe a un servidor autoritativo.","Eso es DHCP.","No es su función."]],

  ["3.4","h","dns,dnssec",
   "What does DNSSEC provide?",
   "Signatures that prove DNS answers are authentic",
   ["Encryption of DNS queries so nobody can see them","Faster DNS lookups through signed caching","Automatic IP address assignment"],
   "DNSSEC firma los registros para comprobar que son auténticos y no se han alterado. No cifra las consultas.",
   ["El cifrado lo dan DoH o DoT.","No está pensado para acelerar las consultas.","Eso es DHCP."]],

  ["3.4","m","dns,doh",
   "Which technology encrypts DNS queries by sending them inside HTTPS?",
   "DoH (DNS over HTTPS)",
   ["DNSSEC","PTR records","Zone transfers"],
   "DoH (DNS over HTTPS) mete las consultas DNS en HTTPS, cifradas y en el puerto 443.",
   ["DNSSEC firma, pero no cifra.","PTR es un tipo de registro.","Las transferencias de zona copian zonas entre servidores."]],

  ["3.4","h","dns,dot",
   "Which port does DNS over TLS (DoT) use by default?",
   "TCP 853",
   ["UDP 53","TCP 443","UDP 123"],
   "DoT (DNS over TLS) usa un puerto propio, el TCP 853. DoH, en cambio, usa el 443.",
   ["UDP 53 es DNS normal, sin cifrar.","443 es el de DoH (HTTPS).","123 es NTP."]],

  ["3.4","m","dns,hosts-file",
   "A technician adds an entry to a PC's hosts file mapping 'intranet' to 10.1.1.50. What effect does it have?",
   "That PC resolves it locally, before asking DNS",
   ["Every PC in the company learns the mapping","The DNS server is updated automatically","The PC stops using DNS entirely"],
   "El archivo hosts es una resolución local y estática que el equipo consulta normalmente antes que DNS. Solo afecta a ese equipo.",
   ["Solo afecta al equipo donde se edita.","No actualiza el servidor DNS.","Los demás nombres siguen resolviéndose por DNS."]],

  ["3.4","m","dns,ttl,caching",
   "A website moved to a new IP address, but some users still reach the old server for a few hours. What is the MOST likely reason?",
   "The old record is cached until its TTL expires",
   ["DNS records never change once published","The users' switches are blocking the new IP","DHCP assigned them the old IP"],
   "Los resolvers y los equipos guardan en caché los registros durante su TTL (Time to Live). Hasta que caduca, siguen usando la IP antigua.",
   ["Los registros sí se pueden cambiar.","Los switches no filtran por IP de destino.","DHCP da la IP del cliente, no la del sitio web."]],

  ["3.4","h","dns,email",
   "Which DNS records are directly involved in delivering a domain's email and publishing its SPF anti-spoofing policy? (Choose TWO)",
   ["MX","TXT"],
   ["PTR","AAAA only","CNAME for the root domain"],
   "El MX indica adónde entregar el correo, y SPF se publica en un registro TXT.",
   ["PTR ayuda en algunas comprobaciones, pero no entrega correo ni publica SPF.","AAAA solo da una dirección IPv6.","Un CNAME en la raíz del dominio no se permite y no publica políticas."]],

  ["3.4","m","dns,mx",
   "A domain has two MX records with preference values 10 and 20. How do sending mail servers use them?",
   "They try 10 first and use 20 as a backup",
   ["They always use the higher value (20) first","They alternate randomly regardless of value","They ignore both and use the A record"],
   "En los MX, el número de preferencia más bajo tiene prioridad; el otro queda de respaldo.",
   ["Es al revés.","Solo se reparten al azar cuando los valores son iguales.","Si hay MX, se usan los MX."]],

  ["3.4","e","dns,doh",
   "Which port does DNS over HTTPS (DoH) use?",
   "TCP 443",
   ["UDP 53","TCP 853","UDP 514"],
   "DoH viaja como tráfico HTTPS normal, por el 443.",
   ["UDP 53 es DNS sin cifrar.","853 es DoT.","514 es Syslog."]],

  ["3.4","m","dns,zone-transfer",
   "What is a DNS zone transfer?",
   "Copying a zone from the primary to a secondary",
   ["Moving a website to a new IP address","Changing a domain's registrar","Sending DNS queries over HTTPS to a public resolver"],
   "Una transferencia de zona copia los registros de la zona primaria a los servidores secundarios. Se suele limitar a servidores autorizados.",
   ["Mover un sitio es cambiar un registro.","Cambiar de registrador es otro trámite.","Eso es DoH."]],

  ["3.4","h","dns,hierarchy",
   "When a resolver has nothing cached, which servers does it query first to find out who is responsible for the .com domain?",
   "The root name servers",
   ["The local DHCP server","The website's web server","The authoritative server for example.com"],
   "La resolución va de arriba abajo: raíz → servidores del TLD (.com) → servidor autoritativo del dominio.",
   ["DHCP no resuelve nombres.","El servidor web no es un servidor DNS.","A ese se llega al final, no al principio."]],

  ["3.4","m","dns,forwarder",
   "An internal DNS server sends queries for internet names that it cannot resolve to the ISP's DNS server. What is this configuration called?",
   "Forwarding (a DNS forwarder)",
   ["Zone transfer","Reverse lookup","DHCP relay"],
   "Un forwarder es el servidor al que el DNS interno reenvía las consultas que no puede resolver.",
   ["Una transferencia de zona copia zonas.","La búsqueda inversa resuelve IP a nombre.","El DHCP relay reenvía peticiones DHCP."]],

  ["3.4","h","ntp,stratum",
   "In NTP, what does a lower stratum number indicate?",
   "The server is closer to an authoritative reference clock",
   ["The server has a slower network link to its upstream peers","The time is less accurate","The server uses TCP instead of UDP"],
   "Stratum 0 es el reloj de referencia (atómico, GPS), stratum 1 está conectado directamente a él, y así sucesivamente. Cuanto menor, más cerca de la fuente.",
   ["No mide la velocidad del enlace.","Normalmente es más preciso, no menos.","No cambia el transporte: NTP usa UDP 123."]],

  ["3.4","m","ptp",
   "Which protocol provides sub-microsecond time synchronization for environments such as financial trading and industrial control?",
   "PTP (Precision Time Protocol)",
   ["NTP over a WAN","SNMP","DHCP"],
   "PTP (Precision Time Protocol, IEEE 1588) usa marcas de tiempo por hardware y logra una precisión mucho mayor que NTP.",
   ["NTP da precisión de milisegundos; no llega a submicrosegundos.","SNMP monitoriza equipos.","DHCP asigna IPs."]],

  ["3.4","h","nts",
   "What does Network Time Security (NTS) add to NTP?",
   "Authentication so clients can trust the time source",
   ["Encryption of all LAN traffic","Sub-microsecond accuracy on any network, even over the internet","Automatic DHCP configuration"],
   "NTS (Network Time Security) añade autenticación criptográfica a NTP para evitar que alguien suplante al servidor de hora.",
   ["Solo protege NTP, no todo el tráfico.","La precisión extrema es cosa de PTP.","No tiene relación con DHCP."]],

  ["3.4","m","ntp,security",
   "Why can incorrect time on servers cause authentication failures?",
   "Kerberos and certificate checks rely on synced clocks",
   ["Passwords expire when the clock is wrong","DHCP refuses clients with the wrong time","Switches block traffic with old timestamps"],
   "Kerberos rechaza los tickets si los relojes difieren demasiado (unos 5 minutos por defecto), y los certificados se validan por fechas.",
   ["La caducidad de contraseñas no depende de un desfase de minutos.","DHCP no comprueba la hora.","Los switches no filtran por marcas de tiempo."]],
];

export default q;
