import type { Raw } from '../types';

// 3.4 (+1) · 3.5 Network access and management methods (30) · 4.1 Basic network security concepts (50)
const q: Raw[] = [
  ["3.4","m","ipv6,ndp,slaac",
   "Which messages do IPv6 routers send so hosts can learn the network prefix and default router for SLAAC?",
   "Router advertisements (RA)",
   ["DHCPv4 offers","ARP replies from the router","Syslog messages from the router"],
   "Los routers IPv6 envían Router Advertisements (parte de NDP, que usa ICMPv6) con el prefijo y su propia dirección como gateway.",
   ["DHCPv4 es de IPv4.","IPv6 no usa ARP; usa NDP.","Syslog son mensajes de registro."]],

  ["3.5","e","vpn,site-to-site",
   "Two offices want their networks permanently connected over the internet through their edge firewalls, without users running any VPN software. What should be used?",
   "Site-to-site VPN",
   ["Client-to-site VPN","Clientless VPN","Console connection"],
   "Una VPN site-to-site une dos redes a través de sus firewalls o routers. Los usuarios no tienen que hacer nada.",
   ["La client-to-site necesita un cliente en cada equipo.","La clientless es para usuarios individuales desde el navegador.","La consola es acceso local para administrar un equipo."]],

  ["3.5","e","vpn,remote-access",
   "Employees working from home run software on their laptops to connect securely to the corporate network. What type of VPN is this?",
   "Client-to-site VPN",
   ["Site-to-site VPN","GRE tunnel without encryption","Out-of-band management"],
   "La VPN client-to-site (de acceso remoto) conecta un equipo individual a la red de la empresa mediante un cliente VPN.",
   ["La site-to-site une redes completas, no portátiles sueltos.","GRE sin cifrado no es seguro.","La gestión fuera de banda es para administrar equipos."]],

  ["3.5","m","vpn,clientless",
   "A contractor needs access to a few internal web applications from a shared kiosk where installing software is not allowed. Which option fits?",
   "Clientless VPN through a web browser portal",
   ["Site-to-site VPN","Full-tunnel IPsec client VPN on the contractor's laptop","Console cable to the core switch"],
   "Una VPN clientless se usa desde el navegador (con TLS), sin instalar nada. Normalmente da acceso a aplicaciones web concretas.",
   ["La site-to-site une redes.","Un cliente IPsec exige instalar software.","El cable de consola es para administrar equipos localmente."]],

  ["3.5","m","vpn,split-tunnel",
   "A remote user's VPN sends only traffic for corporate subnets through the tunnel, while web browsing goes directly to the internet. What is this?",
   "Split tunnel",
   ["Full tunnel","Site-to-site tunnel","Clientless portal"],
   "Con split tunnel solo lo corporativo va por la VPN; el resto sale directamente por la conexión de casa.",
   ["Con full tunnel todo iría por la VPN.","La site-to-site une redes.","El portal clientless se usa desde el navegador."]],

  ["3.5","m","vpn,full-tunnel",
   "Company policy requires that ALL traffic from remote laptops, including internet browsing, pass through corporate security inspection. Which VPN mode should be used?",
   "Full tunnel",
   ["Split tunnel","No VPN","Clientless access to email only"],
   "Con full tunnel todo el tráfico del portátil va a la empresa y pasa por sus firewalls y filtros.",
   ["Con split tunnel la navegación saltaría la inspección.","Sin VPN no hay inspección.","El acceso clientless solo cubre ciertas aplicaciones."]],

  ["3.5","h","vpn,split-tunnel,security",
   "What is a security concern of split tunneling?",
   "Internet traffic bypasses corporate security controls",
   ["It encrypts all traffic twice and slows the VPN for everyone","It blocks all corporate applications","It requires a site-to-site VPN"],
   "El equipo está a la vez en la red corporativa y en internet sin la protección de la empresa, lo que puede servir de puente para una amenaza.",
   ["No cifra dos veces.","Lo corporativo sí funciona.","Es un modo de la VPN de cliente."]],

  ["3.5","m","vpn,full-tunnel",
   "What is a common drawback of full-tunnel VPNs for remote workers?",
   "All internet traffic hairpins through HQ, adding load",
   ["Corporate resources cannot be reached","Traffic to the internet is not encrypted","It requires no authentication from the user"],
   "Toda la navegación da un rodeo por la sede: consume su ancho de banda y añade retardo.",
   ["Los recursos corporativos sí son accesibles.","Va cifrado.","Requiere autenticación."]],

  ["3.5","e","ssh,management",
   "Which protocol should administrators use for encrypted command-line management of switches and routers?",
   "SSH",
   ["Telnet","HTTP","TFTP"],
   "SSH (Secure Shell, TCP 22) da acceso a la línea de comandos cifrado.",
   ["Telnet va sin cifrar.","HTTP es web sin cifrar.","TFTP transfiere archivos sin seguridad."]],

  ["3.5","e","console,management",
   "A brand-new switch has no IP address configured. How does the technician perform its initial configuration?",
   "Through the console port with a console cable",
   ["Through SSH from the office","Through the web GUI over the internet using its default IP","Through an SNMP trap"],
   "Sin IP no se puede llegar por red: se usa el puerto de consola, conectado directamente al equipo.",
   ["SSH necesita que el switch tenga IP.","La interfaz web también necesita IP.","Un trap es un aviso, no un método de configuración."]],

  ["3.5","m","console,cables",
   "Which cable is traditionally used to connect a laptop to a network device's RJ45 console port?",
   "Rollover (console) cable",
   ["Crossover Ethernet cable","Coaxial cable with F-connectors","Single-mode fiber patch cord"],
   "El cable de consola (rollover) lleva los pines invertidos. Hoy se conecta al portátil con un adaptador USB a serie, o se usa un puerto de consola USB.",
   ["Un crossover es para Ethernet.","El coaxial no se usa para consola.","La fibra no se usa para consola."]],

  ["3.5","e","gui,management",
   "An administrator configures a firewall through a web page in a browser using HTTPS. Which access method is this?",
   "Graphical user interface (GUI)",
   ["Console","Command-line API only","Out-of-band modem"],
   "Configurar desde una página web es usar la GUI (Graphical User Interface) del equipo, idealmente por HTTPS.",
   ["La consola es acceso por cable y en modo texto.","Una API se usa desde programas, no con una página.","Un módem de gestión es otro método."]],

  ["3.5","m","api,automation",
   "An engineer needs to push the same VLAN change to 300 switches from a script. Which management method is BEST suited?",
   "The devices' API",
   ["Console cable to each switch","Manual GUI clicks","Telnet sessions one by one"],
   "Las APIs permiten que un programa configure muchos equipos de forma automática y repetible.",
   ["Ir switch por switch con consola llevaría días.","Hacer clic 300 veces es lento y propenso a errores.","Telnet no es seguro ni se automatiza bien."]],

  ["3.5","m","jump-box",
   "Administrators must first log in to a hardened, monitored server before they can connect to any network device. What is this server called?",
   "Jump box (jump host)",
   ["Honeypot","Proxy for guests","DHCP relay"],
   "Un jump box es el único punto de entrada controlado para administrar: se refuerza, se vigila y desde ahí se accede a los equipos.",
   ["Un honeypot es un señuelo para atacantes.","Un proxy para invitados sirve para navegar.","El DHCP relay reenvía peticiones DHCP."]],

  ["3.5","m","jump-box",
   "What is the main security benefit of requiring all device management to go through a jump box?",
   "One hardened, audited entry point for management",
   ["It removes the need for passwords on each managed device","It speeds up routing between VLANs","It replaces the perimeter firewall"],
   "Concentrar la administración en un punto permite endurecerlo, exigir MFA y registrar todo lo que se hace.",
   ["Sigue haciendo falta autenticarse.","No afecta al enrutamiento.","No sustituye al firewall."]],

  ["3.5","e","in-band",
   "An administrator manages switches over SSH across the same network that carries user traffic. What is this called?",
   "In-band management",
   ["Out-of-band management","Clientless VPN","Air-gapped management"],
   "La gestión en banda (in-band) usa la misma red de producción que los usuarios.",
   ["Fuera de banda usa un camino separado.","La VPN clientless es para usuarios remotos.","Aislado (air-gapped) significa sin conexión."]],

  ["3.5","m","out-of-band",
   "What is the main advantage of out-of-band management?",
   "Access even when the production network is down",
   ["It is always cheaper than in-band","It removes the need for authentication","It carries user traffic faster than in-band"],
   "La gestión fuera de banda (out-of-band) usa un camino independiente, como una red de gestión aparte o un servidor de consolas con módem o 4G. Funciona aunque la red principal esté caída.",
   ["Cuesta más, porque es otra red.","Sigue necesitando autenticación.","No transporta tráfico de usuarios."]],

  ["3.5","m","out-of-band",
   "A bad configuration change cut off all network access to a remote site's core switch. How can the engineer fix it without traveling?",
   "Use an out-of-band console server on a cellular link",
   ["SSH to the switch over the production network","Send an SNMP trap to the switch","Wait for DHCP to renew the switch's address"],
   "Con un servidor de consolas conectado por 4G (u otra vía independiente), se llega a la consola del switch aunque la red principal esté caída.",
   ["La red de producción es justo lo que está caído.","Los traps van del equipo al gestor, no al revés, y no reparan nada.","DHCP no arregla la configuración de un switch."]],

  ["3.5","h","console-server",
   "What does a console server (terminal server) in a network rack provide?",
   "Remote access to many devices' console ports",
   ["Wireless coverage for the data center","DHCP for all servers in the rack","Load balancing for web traffic"],
   "Un servidor de consolas se conecta a los puertos de consola de muchos equipos y permite acceder a ellos en remoto.",
   ["No da Wi-Fi.","No es un servidor DHCP.","No reparte tráfico web."]],

  ["3.5","m","management,security",
   "Why should Telnet and HTTP management be disabled on network devices?",
   "They send credentials in clear text",
   ["They are too fast for older devices","They cannot be used from a laptop","They require a console cable"],
   "Telnet y HTTP no cifran: un atacante que capture el tráfico ve el usuario y la contraseña. Se sustituyen por SSH y HTTPS.",
   ["La velocidad no es el problema.","Sí se pueden usar desde un portátil.","No usan cable de consola."]],

  ["3.5","m","ssh,keys",
   "What is an advantage of using SSH key-based authentication instead of passwords for device management?",
   "Keys resist guessing and can be revoked per admin",
   ["Keys do not require encryption","Keys also work over Telnet sessions","Keys remove the need for user accounts on network devices"],
   "Una clave SSH no se adivina por fuerza bruta como una contraseña débil, y se puede retirar a cada administrador por separado.",
   ["SSH sigue cifrando.","Telnet no usa claves.","Cada administrador sigue teniendo su cuenta."]],

  ["3.5","h","api,rest",
   "A controller's REST API is used for automation. What transport and data format does it MOST commonly use?",
   "HTTPS with JSON",
   ["Telnet with plain text","SNMP traps with MIBs","TFTP with binary images"],
   "Las APIs REST modernas funcionan sobre HTTPS e intercambian datos en JSON.",
   ["Telnet no se usa para APIs REST.","SNMP es otro protocolo de gestión, no REST.","TFTP transfiere archivos."]],

  ["3.5","h","out-of-band",
   "Which of the following are examples of out-of-band management? (Choose TWO)",
   ["A dedicated management network separate from production","A console server reachable through a cellular modem"],
   ["SSH over the production user VLAN","A GUI reached through the same internet link as users","SNMP polling across the production WAN"],
   "Es fuera de banda cuando el camino es independiente de la red de producción: una red de gestión aparte o un acceso por 4G/módem.",
   ["Si usa la VLAN de producción, es en banda.","Si comparte el enlace de los usuarios, es en banda.","Si va por la WAN de producción, es en banda."]],

  ["3.5","m","vpn,ssl-vpn",
   "Why are TLS-based (SSL) remote access VPNs often easier to use from hotels and airports than IPsec VPNs?",
   "They use TCP 443, which is rarely blocked",
   ["They need no authentication","They use UDP 69, which home routers allow","They do not encrypt traffic"],
   "Las VPN basadas en TLS usan el 443, igual que la web, así que casi ningún firewall las bloquea. IPsec usa puertos y protocolos que a veces se filtran.",
   ["Sí requieren autenticación.","El 69 es TFTP.","Sí cifran."]],

  ["3.5","m","management-vlan",
   "Why do many organizations place device management interfaces in a dedicated management VLAN?",
   "To isolate management traffic for authorized admins",
   ["To make user traffic faster on access ports","To avoid configuring IP addresses","To allow guests to manage switches"],
   "Una VLAN de gestión aparte permite limitar quién puede llegar a las interfaces de administración.",
   ["No acelera el tráfico de los usuarios.","Siguen necesitando IPs.","Los invitados nunca deben poder administrar."]],

  ["3.5","m","acl,management",
   "How can administrators ensure only the IT subnet can SSH into the routers?",
   "Apply an ACL permitting only the IT subnet",
   ["Change the routers' hostnames to hide them","Enable jumbo frames on the IT subnet","Use a longer console cable"],
   "Una ACL (Access Control List) aplicada al acceso de gestión permite solo las IPs autorizadas.",
   ["El nombre no restringe el acceso.","Las jumbo frames no tienen que ver.","El cable de consola es acceso local."]],

  ["3.5","m","vpn,mfa",
   "Which change BEST protects the remote access VPN against stolen passwords?",
   "Require MFA for VPN logins",
   ["Switch from full tunnel to split tunnel","Use Telnet for the VPN","Disable VPN logging to hide sessions"],
   "Con MFA, una contraseña robada no basta para entrar.",
   ["El modo de túnel no protege contra credenciales robadas.","Telnet no es un protocolo de VPN y no cifra.","Quitar los logs empeora la seguridad."]],

  ["3.5","m","vpn,ipsec",
   "Which protocol suite is MOST commonly used to build site-to-site VPNs between firewalls?",
   "IPsec",
   ["SNMP","DHCP","FTP"],
   "Las VPN site-to-site suelen montarse con IPsec entre los firewalls o routers de cada sede.",
   ["SNMP es monitorización.","DHCP asigna IPs.","FTP transfiere archivos."]],

  ["3.5","h","vpn,gre,ipsec",
   "Two sites need to run a dynamic routing protocol that uses multicast across their encrypted VPN. What is a common design?",
   "GRE over IPsec",
   ["Plain IPsec tunnel mode","Telnet sessions","Clientless VPN portal"],
   "GRE puede transportar multicast (como el de OSPF), pero no cifra. IPsec cifra, pero de forma básica no transporta multicast. Juntos resuelven las dos cosas.",
   ["IPsec a secas no transporta multicast de forma nativa.","Telnet no es una VPN.","Un portal clientless es para usuarios."]],

  ["3.5","e","console,physical-security",
   "Why must network equipment rooms be physically secured even if console ports require a password?",
   "Physical access allows password recovery or theft",
   ["Console ports are faster than SSH for attackers","Locked rooms improve Wi-Fi coverage","Physical security replaces all passwords"],
   "Con acceso físico se pueden usar procedimientos de recuperación de contraseña, robar o desconectar equipos.",
   ["La velocidad no es la cuestión.","No afecta al Wi-Fi.","La seguridad física complementa las contraseñas; no las sustituye."]],

  ["3.5","h","vpn,clientless",
   "What is a typical limitation of a clientless (browser-based) VPN compared with a full VPN client?",
   "Usually only web apps published on the portal",
   ["It cannot be encrypted with TLS","It works only on the same LAN","It requires a site-to-site tunnel on the user's side"],
   "El portal clientless da acceso a aplicaciones web publicadas, no a toda la red como un cliente VPN completo.",
   ["Va cifrado con TLS.","Precisamente se usa desde fuera de la LAN.","El usuario no necesita ningún túnel propio."]],

  ["4.1","e","encryption,in-transit",
   "Which of the following protects data in transit?",
   "TLS on a web session",
   ["Full-disk encryption on a laptop","A locked server rack","A database backup stored in a safe"],
   "Los datos en tránsito son los que viajan por la red. TLS los cifra mientras viajan.",
   ["El cifrado de disco protege los datos en reposo.","Un rack cerrado es seguridad física.","Una copia en una caja fuerte son datos en reposo."]],

  ["4.1","e","encryption,at-rest",
   "A lost laptop's data is still unreadable to the finder because the whole drive is encrypted. What does this protect?",
   "Data at rest",
   ["Data in transit","Data in use by the CPU only","Network availability"],
   "El cifrado de disco protege los datos almacenados (en reposo).",
   ["En tránsito se refiere a los datos que viajan por la red.","No se refiere a los datos en uso.","La disponibilidad es otro pilar de la seguridad."]],

  ["4.1","m","pki",
   "In a PKI, what is the role of a certificate authority (CA)?",
   "Issue and sign certificates binding keys to identities",
   ["Assign IP addresses to web servers","Store user passwords for web logins","Encrypt all traffic on the LAN between clients and servers"],
   "La CA (Certificate Authority) firma certificados que certifican que una clave pública pertenece a quien dice. La PKI (Public Key Infrastructure) es todo ese sistema.",
   ["Eso es DHCP.","Las contraseñas no las guarda la CA.","La CA no cifra el tráfico."]],

  ["4.1","m","certificates,self-signed",
   "Users see a browser warning when opening an internal web tool that uses a self-signed certificate. Why?",
   "The certificate was not issued by a CA the browser trusts",
   ["The site uses HTTP on port 80","The certificate uses encryption that is too strong for browsers","The server's clock is exactly correct"],
   "Un certificado autofirmado se lo firma el propio servidor. El navegador no puede comprobar quién es y avisa.",
   ["Con HTTP no habría certificado.","Un cifrado fuerte no causa avisos.","Tener la hora correcta no causa avisos."]],

  ["4.1","h","pki,asymmetric",
   "In public key cryptography, which key is used to decrypt data that was encrypted with a user's public key?",
   "The user's private key",
   ["The same public key","The CA's public key","Any other user's private key"],
   "Lo cifrado con la clave pública solo se descifra con la clave privada pareja, que solo tiene su dueño.",
   ["La pública no descifra lo que ella misma cifró.","La clave de la CA sirve para verificar certificados.","Cada clave privada es única de su dueño."]],

  ["4.1","m","certificates",
   "A website suddenly shows certificate errors for all users, although nothing was changed. What is a likely cause?",
   "The certificate has expired",
   ["The DNS server switched to IPv6","The switch port is in VLAN 1","The users' passwords expired"],
   "Los certificados tienen fecha de caducidad. Si nadie lo renueva, todos los navegadores empiezan a mostrar errores.",
   ["IPv6 no provoca errores de certificado.","La VLAN no afecta a los certificados.","Las contraseñas de los usuarios no están relacionadas."]],

  ["4.1","e","mfa,factors",
   "Which of the following is an example of 'something you have'?",
   "A hardware security token",
   ["A password","A fingerprint","Your mother's maiden name"],
   "Algo que tienes es un objeto físico: token, tarjeta inteligente, teléfono con app de códigos.",
   ["Una contraseña es algo que sabes.","La huella es algo que eres.","Es algo que sabes."]],

  ["4.1","e","mfa,factors",
   "Which authentication factor is a fingerprint scan?",
   "Something you are",
   ["Something you know","Something you have","Somewhere you are"],
   "La biometría (huella, cara, iris) es algo que eres.",
   ["Algo que sabes es una contraseña o un PIN.","Algo que tienes es un token o una tarjeta.","'Donde estás' es la ubicación."]],

  ["4.1","e","sso",
   "Employees log in once in the morning and can open email, HR and CRM applications without entering credentials again. What is this?",
   "Single sign-on (SSO)",
   ["Multifactor authentication","Role-based access control","Least privilege"],
   "SSO (Single Sign-On): una sola autenticación da acceso a varias aplicaciones.",
   ["MFA es pedir varios factores, no un login único.","RBAC asigna permisos por rol.","El mínimo privilegio limita permisos."]],

  ["4.1","h","saml,sso",
   "Which XML-based standard lets an identity provider tell a web application that a user has already authenticated, enabling SSO across organizations?",
   "SAML",
   ["TACACS+","SNMP","LDAP over UDP"],
   "SAML (Security Assertion Markup Language) intercambia 'aserciones' en XML entre el proveedor de identidad y la aplicación: es la base de mucho SSO web.",
   ["TACACS+ es para administrar equipos de red.","SNMP es monitorización.","LDAP consulta directorios; no es un estándar de SSO web."]],

  ["4.1","h","radius",
   "Which statement about RADIUS is correct?",
   "Central authentication over UDP; encrypts only the password",
   ["It uses TCP 49 and encrypts the entire payload","It is only used to manage Cisco routers","It resolves hostnames for authenticated clients on the network"],
   "RADIUS (Remote Authentication Dial-In User Service) centraliza la autenticación de acceso (Wi-Fi Enterprise, VPN, 802.1X). Usa UDP y solo cifra la contraseña.",
   ["Eso describe a TACACS+.","Se usa en muchos contextos de acceso.","Eso es DNS."]],

  ["4.1","h","tacacs",
   "Which statement about TACACS+ is correct?",
   "TCP 49, full payload encryption, separate AAA functions",
   ["It uses UDP and encrypts only the password","It is a wireless encryption standard for WPA3","It assigns IP addresses to VPN clients"],
   "TACACS+ (Terminal Access Controller Access-Control System Plus) cifra todo el mensaje y separa las tres A. Por eso es el preferido para administrar equipos de red.",
   ["Eso describe a RADIUS.","No es un cifrado Wi-Fi.","No asigna IPs."]],

  ["4.1","m","tacacs,device-admin",
   "A company wants to control which commands each network administrator may run on routers and log every command. Which protocol is BEST?",
   "TACACS+",
   ["RADIUS","SAML","SNMPv1"],
   "TACACS+ permite autorizar comando a comando y registrar cada uno, algo pensado para la administración de equipos.",
   ["RADIUS es más limitado para autorizar comandos individuales.","SAML es SSO web.","SNMPv1 es monitorización insegura."]],

  ["4.1","e","ldap",
   "Which protocol does a VPN appliance commonly use to query a directory service such as Active Directory to validate a user?",
   "LDAP",
   ["SMTP","TFTP","NTP"],
   "LDAP (Lightweight Directory Access Protocol) consulta directorios de usuarios. Lo ideal es usarlo cifrado (LDAPS).",
   ["SMTP es correo.","TFTP transfiere archivos.","NTP sincroniza la hora."]],

  ["4.1","m","totp",
   "An authenticator app shows a six-digit code that changes every 30 seconds and is required at login. What is this?",
   "Time-based one-time password (TOTP)",
   ["Static password","Self-signed certificate on the phone","Geofencing"],
   "Un TOTP (Time-based One-Time Password) es un código que cambia con el tiempo; sirve como 'algo que tienes' (el teléfono).",
   ["Una contraseña estática no cambia.","Un certificado autofirmado no genera códigos.","Geofencing se basa en la ubicación."]],

  ["4.1","e","least-privilege",
   "A help desk technician only needs to reset passwords, so they are given only that permission. Which principle is applied?",
   "Least privilege",
   ["Single sign-on","Defense by obscurity","Implicit trust"],
   "Mínimo privilegio: cada persona tiene solo los permisos imprescindibles para su trabajo.",
   ["SSO es un login único.","Ocultar cosas no es un principio de permisos.","La confianza implícita es lo contrario de un control."]],

  ["4.1","e","rbac",
   "Permissions are assigned to groups such as 'Network Admins' and 'Help Desk', and users get access by being placed in a group. What is this model?",
   "Role-based access control (RBAC)",
   ["Mandatory access control by clearance level","Discretionary access by file owners","Geofencing"],
   "En RBAC (Role-Based Access Control) los permisos van al rol y los usuarios heredan los del rol que tienen.",
   ["El control obligatorio usa etiquetas o niveles de clasificación.","El discrecional deja decidir al dueño de cada recurso.","Geofencing controla por ubicación."]],

  ["4.1","e","aaa",
   "What is the difference between authentication and authorization?",
   "Authentication: who you are; authorization: what you may do",
   ["They are the same thing with two different names","Authorization verifies identity and authentication grants permissions","Authentication logs what users did"],
   "Primero se comprueba quién eres (autenticación) y después qué puedes hacer (autorización).",
   ["Son pasos distintos.","Está al revés.","Registrar lo que se hizo es el accounting."]],

  ["4.1","m","aaa,accounting",
   "In AAA, what does accounting provide?",
   "A record of what users did and when",
   ["Verification of user identity","The list of permissions a user has","Encryption of passwords in transit"],
   "Accounting registra la actividad: quién entró, cuándo, qué hizo. Es clave para auditorías.",
   ["Eso es la autenticación.","Eso es la autorización.","No es cifrado."]],

  ["4.1","m","geofencing",
   "A company blocks logins to its cloud apps when the request comes from outside the countries where it operates. What is this?",
   "Geofencing",
   ["Port security","Least privilege","Honeypot"],
   "Geofencing aplica reglas según la ubicación geográfica (del usuario o del dispositivo).",
   ["Port security limita MACs en un puerto de switch.","El mínimo privilegio limita permisos, no ubicaciones.","Un honeypot es un señuelo."]],

  ["4.1","e","physical-security",
   "Which physical security control both deters intruders and provides evidence after an incident?",
   "Security cameras",
   ["Strong passwords","VLAN segmentation","Firewall rules"],
   "Las cámaras disuaden (se ven) y graban (dan pruebas).",
   ["Las contraseñas son un control lógico.","Las VLANs son lógicas.","Los firewalls son lógicos."]],

  ["4.1","m","physical-security,vestibule",
   "Which physical control uses two interlocking doors so only one person can pass at a time, preventing tailgating?",
   "Access control vestibule",
   ["Badge reader on one door only","Security camera","Cable lock"],
   "Un vestíbulo de control de acceso (mantrap) tiene dos puertas que no se abren a la vez: impide que alguien entre detrás de otra persona.",
   ["Una sola puerta con lector no evita que alguien se cuele detrás.","La cámara graba, pero no impide el paso.","Un candado de cable protege un portátil."]],

  ["4.1","e","physical-security",
   "Which control ensures only authorized staff can enter the network closet?",
   "A door lock with badge access",
   ["An SSID","A DHCP reservation","A syslog server"],
   "Una cerradura con tarjeta limita y registra quién entra en la sala.",
   ["El SSID es el nombre de la red Wi-Fi.","DHCP asigna IPs.","Syslog registra eventos de red, no abre puertas."]],

  ["4.1","e","deception,honeypot",
   "A security team deploys a fake server with attractive-looking data to lure attackers and study their methods. What is it?",
   "Honeypot",
   ["Jump box","Proxy server","Load balancer"],
   "Un honeypot es un señuelo: parece valioso, pero existe para atraer a los atacantes y observarlos.",
   ["El jump box es el punto de entrada de los administradores.","Un proxy intermedia peticiones.","Un balanceador reparte tráfico."]],

  ["4.1","m","deception,honeynet",
   "What is a honeynet?",
   "A network of decoys to attract and watch attackers",
   ["A wireless mesh of production APs","A VPN for honeybee researchers","A group of load-balanced web servers behind a firewall"],
   "Una honeynet es una red entera de señuelos, más realista que un único honeypot.",
   ["Una malla de APs es infraestructura real.","No tiene que ver con abejas.","Un grupo balanceado de servidores es producción."]],

  ["4.1","m","risk",
   "How is risk commonly described in security?",
   "Likelihood of a threat exploiting a weakness, times impact",
   ["Any software bug found in a production system by a scanner","A person attacking the network","A patch released by a vendor"],
   "Riesgo = probabilidad de que una amenaza aproveche una vulnerabilidad × el impacto que tendría.",
   ["Un fallo de software es una vulnerabilidad.","Una persona que ataca es una amenaza (actor).","Un parche es una medida de corrección."]],

  ["4.1","e","vulnerability",
   "A router runs firmware with a known flaw that allows remote code execution. What is the flaw called?",
   "A vulnerability",
   ["A threat actor","A risk assessment","An exploit kit"],
   "Una vulnerabilidad es una debilidad que podría aprovecharse.",
   ["El actor de amenaza es quien atacaría.","Una evaluación de riesgos es un análisis.","Un kit de exploits es la herramienta para aprovechar la debilidad."]],

  ["4.1","m","exploit",
   "Code written specifically to take advantage of a vulnerability is called:",
   "An exploit",
   ["A patch","A baseline","A threat assessment"],
   "Un exploit es el código o la técnica que aprovecha una vulnerabilidad concreta.",
   ["Un parche corrige la vulnerabilidad.","Una línea base describe lo normal.","Una evaluación de amenazas es un análisis."]],

  ["4.1","m","threat",
   "In security terminology, what is a threat?",
   "Anything or anyone that could cause harm",
   ["A weakness in software or configuration","A signed digital certificate","A firewall rule that is too permissive"],
   "Una amenaza es aquello que podría causar daño: un atacante, un empleado descontento, un incendio.",
   ["La debilidad es la vulnerabilidad.","Un certificado es un control.","Una regla de firewall es un control."]],

  ["4.1","e","cia,confidentiality",
   "Encrypting customer records so only authorized people can read them supports which part of the CIA triad?",
   "Confidentiality",
   ["Integrity","Availability","Accounting"],
   "Confidencialidad: que solo quien debe pueda leer la información.",
   ["Integridad es que no se modifique sin permiso.","Disponibilidad es que esté accesible cuando se necesita.","Accounting es parte de AAA, no de la tríada CIA."]],

  ["4.1","m","cia,integrity",
   "A file's hash is compared before and after transfer to confirm it was not altered. Which part of the CIA triad does this support?",
   "Integrity",
   ["Confidentiality","Availability","Authorization"],
   "Integridad: comprobar que los datos no han cambiado. Si el hash coincide, el archivo es idéntico.",
   ["El hash no oculta el contenido.","No afecta a la disponibilidad.","La autorización es de AAA."]],

  ["4.1","e","cia,availability",
   "Redundant links, backup power and DDoS protection mainly support which part of the CIA triad?",
   "Availability",
   ["Confidentiality","Integrity","Non-repudiation"],
   "Disponibilidad: que los sistemas funcionen cuando se necesitan.",
   ["No ocultan información.","No verifican que los datos no cambien.","El no repudio impide negar una acción; no es parte de la tríada."]],

  ["4.1","m","cia,integrity",
   "Which of the following help ensure data integrity? (Choose TWO)",
   ["Hashing","Digital signatures"],
   ["Redundant power supplies","Load balancing","Screen privacy filters"],
   "El hash detecta cambios y la firma digital además demuestra quién firmó.",
   ["Eso es disponibilidad.","Eso es disponibilidad.","Eso es confidencialidad física."]],

  ["4.1","e","compliance,pci-dss",
   "An online store processes credit card payments. Which standard governs how it must protect cardholder data?",
   "PCI DSS",
   ["GDPR only","802.1X","RFC 1918"],
   "PCI DSS (Payment Card Industry Data Security Standard) fija los requisitos para quien procesa, almacena o transmite datos de tarjetas.",
   ["GDPR protege datos personales de la UE en general, no específicamente las tarjetas.","802.1X es control de acceso a la red.","RFC 1918 define direcciones privadas."]],

  ["4.1","e","compliance,gdpr",
   "Which regulation protects the personal data and privacy of people in the European Union?",
   "GDPR",
   ["PCI DSS","SNMPv3","802.11h"],
   "El GDPR (General Data Protection Regulation, RGPD en español) regula el tratamiento de datos personales de personas en la UE.",
   ["PCI DSS trata de tarjetas de pago.","SNMPv3 es un protocolo.","802.11h es un estándar de Wi-Fi."]],

  ["4.1","m","compliance,data-locality",
   "A regulation requires that citizens' health data be stored only on servers located within that country. What concept is this?",
   "Data locality",
   ["Elasticity","Least privilege","Geofencing of Wi-Fi access"],
   "La localidad de los datos exige que se guarden físicamente en una jurisdicción concreta. Afecta a la elección de región en la nube.",
   ["La elasticidad es escalar recursos.","El mínimo privilegio trata de permisos.","Geofencing controla accesos por ubicación, no dónde se guardan los datos."]],

  ["4.1","m","audit,compliance",
   "What is the main purpose of a security audit?",
   "To verify compliance with policies and regulations",
   ["To install new firmware on audited devices","To increase network speed","To assign IP addresses to audited systems"],
   "Una auditoría comprueba que lo que se hace coincide con lo que exigen las políticas y las normas.",
   ["Instalar firmware es mantenimiento.","No busca velocidad.","Eso es DHCP."]],

  ["4.1","e","segmentation,iot",
   "A company installs smart thermostats and cameras. What is the recommended way to connect them?",
   "On a separate, restricted VLAN",
   ["On the same VLAN as the finance servers","Directly to the internet with public IPs","On the guest Wi-Fi with no rules"],
   "Los dispositivos IoT suelen ser poco seguros. Separarlos limita el daño si alguno se ve comprometido.",
   ["Mezclarlos con servidores críticos multiplica el riesgo.","Exponerlos a internet es muy peligroso.","Sin reglas, siguen sin estar controlados."]],

  ["4.1","m","segmentation,ics,scada",
   "Why should ICS/SCADA networks that control industrial equipment be strictly isolated from the corporate IT network?",
   "Legacy, hard-to-patch systems where attacks cause physical harm",
   ["They use too much bandwidth for shared links","They need public IP addresses","They only work with wireless sensors and gateways, not cables"],
   "Los sistemas OT (Operational Technology) suelen ser antiguos y difíciles de parchear, y un ataque puede tener consecuencias físicas. Se aíslan con mucho rigor.",
   ["El ancho de banda no es el motivo principal.","No necesitan IPs públicas; al contrario.","Suelen ser cableados."]],

  ["4.1","e","segmentation,guest",
   "Which firewall rule is MOST important for a guest network?",
   "Deny guest traffic to internal subnets",
   ["Allow guests to reach the file servers","Allow SSH from guests to switches","Disable internet access for guests"],
   "Lo esencial es que un invitado no pueda llegar a nada interno. Internet sí, lo corporativo no.",
   ["Eso expone datos internos.","Eso expone la administración de la red.","El objetivo de la red de invitados es darles internet."]],

  ["4.1","m","segmentation,byod",
   "Employees want to connect personal phones (BYOD) to the network. What is a good approach?",
   "Separate segment plus access controls such as NAC",
   ["Give them the same access as company laptops","Assign them static public IPs from the ISP","Connect them to the SCADA network"],
   "Los dispositivos personales no están gestionados por la empresa: se separan y se controla qué pueden hacer.",
   ["No tienen los controles de un equipo corporativo.","Las IPs públicas los expondrían.","Mezclarlos con OT es muy peligroso."]],

  ["4.1","m","iiot",
   "Sensors on a factory floor that report machine vibration and temperature to analytics systems are examples of:",
   "Industrial IoT (IIoT)",
   ["BYOD","Guest devices","SaaS"],
   "El IIoT (Industrial Internet of Things) son sensores y dispositivos conectados en entornos industriales.",
   ["BYOD son dispositivos personales.","No son equipos de invitados.","SaaS es software como servicio."]],

  ["4.1","m","encryption,in-transit",
   "Which of the following protect data in transit? (Choose TWO)",
   ["TLS","IPsec"],
   ["Full-disk encryption","Encrypted database files at rest","Locked filing cabinets"],
   "TLS e IPsec cifran los datos mientras viajan por la red.",
   ["El cifrado de disco protege datos en reposo.","Los archivos cifrados almacenados están en reposo.","Es seguridad física."]],

  ["4.1","m","hashing",
   "What is the key difference between hashing and encryption?",
   "Hashing is one-way; encryption is reversible with a key",
   ["Hashing is reversible with a key and encryption is not reversible","They are identical; both use keys","Hashing requires a certificate authority"],
   "Un hash no se puede 'deshacer': sirve para comprobar. El cifrado se descifra con la clave adecuada.",
   ["Es al revés.","Son distintos.","El hash no necesita una CA."]],

  ["4.1","h","certificates",
   "Which information is contained in a digital certificate?",
   "Public key, identity, issuing CA and validity dates",
   ["The subject's private key","The user's password, hashed","The list of all VLANs and subnets the server is allowed to use"],
   "El certificado contiene la clave pública, a quién pertenece, quién lo emitió y las fechas de validez. La clave privada nunca va dentro.",
   ["La clave privada debe quedarse con su dueño.","No contiene contraseñas.","No tiene nada que ver con VLANs."]],

  ["4.1","h","certificates,revocation",
   "A web server's private key was stolen. What should happen to its certificate before it expires?",
   "The CA should revoke it (CRL/OCSP)",
   ["Nothing; it will expire eventually","Its expiration date should be extended","It should be copied to more servers"],
   "Si se compromete la clave, se revoca el certificado. Los clientes lo comprueban con una CRL (Certificate Revocation List) o con OCSP.",
   ["Esperar deja al atacante usar el certificado mientras tanto.","Alargar la validez empeora el problema.","Copiarlo no soluciona el robo."]],

  ["4.1","m","defense-in-depth",
   "A company uses a firewall, IPS, endpoint protection, MFA and network segmentation together. Which principle does this represent?",
   "Defense in depth",
   ["Single point of failure","Implicit trust","Security through obscurity"],
   "Defensa en profundidad: varias capas de controles, para que si una falla actúen las demás.",
   ["Es justo lo contrario.","Confiar sin verificar no es una estrategia de seguridad.","Ocultar no sustituye a los controles reales."]],

  ["4.1","e","physical-security",
   "Which is the BEST way to protect patch panels and switches in a shared office area?",
   "Place them in a locked cabinet or room",
   ["Hide them behind a plant","Label them 'do not touch' in large, visible letters","Disable their LEDs"],
   "Un armario o una sala con llave impide el acceso físico no autorizado.",
   ["Ocultarlos no los protege.","Un cartel no detiene a nadie.","Apagar los LEDs no protege nada."]],

  ["4.1","e","mfa",
   "What is the main benefit of MFA?",
   "A stolen password alone is not enough",
   ["Users no longer need passwords","It makes logins faster for users","It encrypts the hard drive"],
   "Con MFA el atacante necesitaría además el segundo factor (el teléfono, el token, la huella).",
   ["Normalmente se sigue usando contraseña más otro factor.","Suele añadir un paso.","No cifra el disco."]],

  ["4.1","h","sso,risk",
   "What is a security risk of single sign-on, and how is it usually reduced?",
   "One stolen login unlocks many apps, so add MFA",
   ["SSO disables all logging, so it is paired with SNMP","SSO requires Telnet, so it is paired with SSH","SSO exposes MAC addresses, so it is paired with VLANs"],
   "Con SSO una sola credencial abre muchas puertas. Por eso se protege con MFA.",
   ["SSO no desactiva los logs.","SSO no usa Telnet.","SSO no expone direcciones MAC."]],
];

export default q;
