import type { Raw } from '../types';

// 4.2 Attacks (50) · 4.3 Security features and defense techniques (40)
const q: Raw[] = [
  ["4.2","e","attacks,dos",
   "An attacker floods a web server with requests from a single machine until legitimate users cannot reach it. What type of attack is this?",
   "Denial of service (DoS)",
   ["Phishing","ARP spoofing","Shoulder surfing"],
   "Un DoS (Denial of Service) busca dejar un servicio inaccesible saturándolo.",
   ["El phishing engaña a personas con mensajes.","ARP spoofing se hace pasar por otra IP en la red local.","Shoulder surfing es mirar por encima del hombro."]],

  ["4.2","e","attacks,ddos",
   "A website is overwhelmed by traffic coming from tens of thousands of compromised devices around the world. What is this?",
   "Distributed DoS (DDoS)",
   ["Denial of service from a single host","VLAN hopping","Dumpster diving"],
   "Un DDoS (Distributed DoS) usa muchos equipos a la vez, normalmente una botnet, lo que hace muy difícil bloquearlo por origen.",
   ["Aquí no es un solo equipo.","VLAN hopping es saltar entre VLANs.","Dumpster diving es buscar en la basura."]],

  ["4.2","m","attacks,botnet",
   "What is a botnet?",
   "Compromised devices controlled by an attacker",
   ["A group of honeypots run by researchers","A cluster of load-balanced servers","A VPN used by security teams"],
   "Una botnet es un ejército de equipos infectados (PCs, cámaras, routers) controlados a distancia, que se usa para DDoS, spam, etc.",
   ["Los honeypots son señuelos defensivos.","Un clúster de servidores es legítimo.","No es una VPN."]],

  ["4.2","h","attacks,ddos,mitigation",
   "A company's internet link is completely saturated by a large volumetric DDoS. Why is filtering on its own edge firewall usually not enough?",
   "The link is full before the firewall, so filter upstream",
   ["Firewalls cannot filter UDP traffic at all","DDoS traffic is always encrypted end to end, so it cannot be seen","The firewall must be rebooted first"],
   "Si el enlace llega saturado, da igual lo que descarte el firewall: el tubo ya está lleno. Hay que filtrar antes, en el ISP o en un servicio de limpieza (scrubbing).",
   ["Los firewalls filtran UDP.","No siempre va cifrado.","Reiniciar no resuelve la saturación."]],

  ["4.2","m","attacks,syn-flood",
   "An attacker sends thousands of TCP SYN packets without ever completing the handshake, filling the server's connection table. What attack is this?",
   "SYN flood",
   ["ARP poisoning","MAC flooding","DNS spoofing"],
   "En un SYN flood el atacante abre miles de conexiones a medias que el servidor espera en vano, hasta agotar sus recursos. Es un tipo de DoS.",
   ["ARP poisoning corrompe cachés ARP.","MAC flooding llena la tabla MAC de un switch.","DNS spoofing falsifica respuestas DNS."]],

  ["4.2","h","attacks,amplification",
   "Attackers send small DNS queries with the victim's IP as the spoofed source to open resolvers, which send much larger responses to the victim. What is this?",
   "Reflection/amplification DDoS",
   ["Evil twin","Tailgating","VLAN hopping"],
   "Las respuestas grandes se 'reflejan' hacia la víctima: por cada byte que envía, el atacante consigue que le lleguen muchos más.",
   ["El evil twin es un AP falso.","Tailgating es entrar detrás de alguien.","VLAN hopping es saltar de VLAN."]],

  ["4.2","h","attacks,vlan-hopping",
   "An attacker's device negotiates a trunk with a switch port that was left in dynamic/auto mode, gaining access to all VLANs. What is this?",
   "VLAN hopping by switch spoofing",
   ["MAC flooding of the switch table","DNS poisoning","Evil twin"],
   "Si el puerto negocia trunks automáticamente, el atacante se hace pasar por un switch y recibe tráfico de todas las VLANs.",
   ["MAC flooding llena la tabla MAC.","DNS poisoning corrompe DNS.","El evil twin es un AP falso."]],

  ["4.2","h","attacks,vlan-hopping,double-tagging",
   "Which attack sends frames with two 802.1Q tags, relying on the native VLAN, so the second switch forwards the frame into a different VLAN?",
   "Double-tagging VLAN hopping",
   ["SYN flood","ARP spoofing","Rogue DHCP"],
   "El primer switch quita la etiqueta exterior (la de la VLAN nativa) y el segundo lee la interior, así la trama acaba en otra VLAN.",
   ["Un SYN flood satura conexiones TCP.","ARP spoofing falsifica respuestas ARP.","Un DHCP falso reparte configuraciones malas."]],

  ["4.2","m","attacks,vlan-hopping,mitigation",
   "Which measures reduce the risk of VLAN hopping? ",
   "Disable auto-trunking; use an unused native VLAN",
   ["Enable Telnet on all switches","Put all users in VLAN 1, the default VLAN","Use hubs instead of switches at the access layer"],
   "Se configuran los puertos de acceso como tales, se desactiva la negociación de trunk y se usa una VLAN nativa sin usuarios.",
   ["Telnet no tiene relación y es inseguro.","La VLAN 1 por defecto facilita el ataque.","Los hubs empeorarían todo."]],

  ["4.2","m","attacks,mac-flooding",
   "An attacker sends thousands of frames with random source MAC addresses to fill a switch's MAC table, causing it to flood traffic out of all ports. What attack is this?",
   "MAC flooding",
   ["ARP poisoning","DNS spoofing","Evil twin"],
   "Con la tabla MAC llena, el switch no sabe dónde está cada equipo e inunda todo como un hub: el atacante puede capturar tráfico ajeno.",
   ["ARP poisoning corrompe cachés ARP.","DNS spoofing falsifica DNS.","El evil twin es un AP falso."]],

  ["4.2","m","attacks,mac-flooding,mitigation",
   "Which switch feature BEST prevents MAC flooding attacks?",
   "Port security with a MAC limit",
   ["Jumbo frames on access ports","Spanning Tree Protocol","A separate voice VLAN"],
   "Port security limita cuántas MACs puede aprender un puerto; si alguien envía miles, el puerto se bloquea.",
   ["Las jumbo frames no limitan MACs.","STP evita bucles, no inundaciones de MACs.","La voice VLAN separa la voz."]],

  ["4.2","m","attacks,arp-spoofing",
   "An attacker on the LAN sends forged ARP replies claiming that the default gateway's IP address belongs to the attacker's MAC address. What is the attacker doing?",
   "ARP spoofing",
   ["DNS poisoning","VLAN hopping","SYN flooding"],
   "ARP spoofing es enviar respuestas ARP falsas para hacerse pasar por otra IP (aquí, el gateway).",
   ["DNS poisoning afecta a la resolución de nombres.","VLAN hopping salta entre VLANs.","El SYN flood satura conexiones TCP."]],

  ["4.2","m","attacks,arp-poisoning",
   "After forged ARP messages, several PCs' ARP caches now map the gateway's IP to the attacker's MAC, so their traffic passes through the attacker. What is the corrupted state of those caches called?",
   "ARP poisoning",
   ["MAC flooding","DHCP starvation","Deauthentication"],
   "ARP poisoning es el resultado: las cachés ARP 'envenenadas' con asociaciones falsas. Se consigue mediante ARP spoofing y permite un ataque on-path.",
   ["MAC flooding llena la tabla del switch, no las cachés ARP de los PCs.","DHCP starvation agota las IPs de un servidor DHCP.","Deauth desconecta clientes Wi-Fi."]],

  ["4.2","m","attacks,arp,mitigation",
   "Which switch feature mitigates ARP spoofing by validating ARP packets against trusted IP-to-MAC bindings?",
   "Dynamic ARP Inspection (DAI)",
   ["PortFast","LACP","Channel bonding"],
   "DAI (Dynamic ARP Inspection) descarta los mensajes ARP que no coinciden con la tabla de asociaciones de DHCP snooping.",
   ["PortFast acelera el arranque de un puerto.","LACP agrega enlaces.","Channel bonding es de Wi-Fi."]],

  ["4.2","m","attacks,dns-poisoning",
   "An attacker inserts a false record into a DNS resolver's cache so users asking for the bank's site receive the attacker's IP. What attack is this?",
   "DNS cache poisoning",
   ["MAC flooding","ARP spoofing","Tailgating"],
   "DNS poisoning corrompe la caché de un resolver con registros falsos: todos los que le pregunten reciben la dirección del atacante.",
   ["MAC flooding es de switches.","ARP spoofing actúa en la red local con ARP, no con DNS.","Tailgating es acceso físico."]],

  ["4.2","m","attacks,dns-spoofing",
   "An on-path attacker answers a victim's DNS query with a forged response before the real server does, sending the victim to a fake site. What is this?",
   "DNS spoofing",
   ["VLAN hopping","Dumpster diving","Evil twin"],
   "DNS spoofing es falsificar la respuesta DNS para redirigir a la víctima.",
   ["VLAN hopping es de switches.","Dumpster diving es rebuscar en la basura.","El evil twin es un AP falso."]],

  ["4.2","h","attacks,dns,mitigation",
   "Which technology helps resolvers detect forged or tampered DNS records?",
   "DNSSEC",
   ["DHCP snooping","Port security","WPA3"],
   "DNSSEC firma los registros: el resolver puede comprobar que la respuesta es auténtica y descartar las falsas.",
   ["DHCP snooping protege contra servidores DHCP falsos.","Port security limita MACs.","WPA3 protege el Wi-Fi."]],

  ["4.2","m","attacks,rogue-dhcp",
   "Users suddenly receive a default gateway that belongs to an unknown device, and their traffic is being intercepted. What is the MOST likely cause?",
   "A rogue DHCP server",
   ["An expired certificate","A duplex mismatch","A hidden SSID"],
   "Un servidor DHCP no autorizado reparte configuraciones con su propia IP como gateway o DNS, y así se coloca en medio del tráfico.",
   ["Un certificado caducado da errores en HTTPS.","Un problema de dúplex causa lentitud.","Un SSID oculto no cambia los gateways."]],

  ["4.2","m","attacks,rogue-dhcp,mitigation",
   "Which switch feature blocks DHCP offers from unauthorized servers?",
   "DHCP snooping",
   ["BPDU guard","Jumbo frames","PoE"],
   "DHCP snooping solo permite respuestas DHCP en los puertos marcados como de confianza (los del servidor legítimo).",
   ["BPDU guard protege STP.","Las jumbo frames cambian el tamaño de trama.","PoE da electricidad."]],

  ["4.2","m","attacks,rogue-ap",
   "An employee plugs a cheap wireless router into an office network jack to get better Wi-Fi at their desk. What security problem does this create?",
   "A rogue access point",
   ["An evil twin","DNS poisoning","An unauthorized VLAN trunk"],
   "Un AP no autorizado conectado a la red interna abre una puerta inalámbrica sin los controles de la empresa.",
   ["Un evil twin imita la red corporativa, normalmente sin estar conectado a ella.","No afecta a DNS por sí mismo.","No crea un trunk."]],

  ["4.2","h","attacks,evil-twin,rogue-ap",
   "What is the key difference between a rogue AP and an evil twin?",
   "A rogue AP is plugged into the LAN; an evil twin fakes your SSID",
   ["They are the same thing with two names","An evil twin is always plugged into the corporate LAN by an employee","A rogue AP always uses the corporate SSID"],
   "El rogue AP es un AP no autorizado dentro de la red. El evil twin es un AP falso que copia el nombre de una red legítima para engañar a los usuarios.",
   ["Son distintos.","El evil twin suele estar fuera de la red de la empresa.","Un rogue AP puede tener cualquier SSID."]],

  ["4.2","h","attacks,deauthentication",
   "Users' Wi-Fi connections keep dropping, and a capture shows many forged deauthentication frames. What is the attacker likely trying to do?",
   "Kick clients off, e.g. toward an evil twin",
   ["Assign them new IP addresses","Update their firmware over the air","Increase their signal strength"],
   "El ataque de desautenticación fuerza la desconexión. Al reconectar, el atacante puede capturar el saludo o atraerlos a su AP falso.",
   ["No asigna IPs.","No actualiza nada.","No mejora la señal."]],

  ["4.2","e","attacks,on-path",
   "An attacker secretly positions themselves between two parties, intercepting and possibly altering their communication. What is this?",
   "On-path attack",
   ["Distributed denial of service","Dumpster diving","Brute force"],
   "En un ataque on-path el atacante se coloca en medio de la comunicación: lee y puede modificar lo que pasa.",
   ["Un DoS busca tumbar el servicio.","Dumpster diving es rebuscar en la basura.","La fuerza bruta prueba contraseñas."]],

  ["4.2","m","attacks,on-path",
   "Which of the following can let an attacker become on-path on a local network?",
   "ARP poisoning of the default gateway entry",
   ["A strong WPA3 passphrase","A correctly signed DNSSEC zone on the server","Disabling unused switch ports"],
   "Envenenando la entrada ARP del gateway, el tráfico de las víctimas pasa por el atacante.",
   ["WPA3 es una defensa.","DNSSEC es una defensa.","Deshabilitar puertos es una defensa."]],

  ["4.2","e","social-engineering,phishing",
   "Employees receive an email that looks like it is from IT, asking them to click a link and 'verify' their password. What is this?",
   "Phishing",
   ["Tailgating","Shoulder surfing","MAC flooding"],
   "El phishing usa mensajes falsos (sobre todo correos) para robar credenciales o instalar malware.",
   ["Tailgating es entrar detrás de alguien.","Shoulder surfing es mirar la pantalla ajena.","MAC flooding es un ataque a switches."]],

  ["4.2","m","social-engineering,spear-phishing",
   "An attacker researches a specific payroll employee and sends them a personalized email referencing their manager and a real project. What is this?",
   "Spear phishing",
   ["Generic spam","Vishing","Dumpster diving"],
   "El spear phishing es phishing dirigido a una persona o un grupo concreto, con información personalizada para ser más creíble.",
   ["El spam genérico no está personalizado.","El vishing es por teléfono.","Dumpster diving es rebuscar en la basura."]],

  ["4.2","e","social-engineering,vishing",
   "A caller pretending to be from the bank asks a user to read back a one-time code sent to their phone. What is this attack?",
   "Vishing",
   ["Smishing","Tailgating","Evil twin"],
   "El vishing (voice phishing) es phishing por llamada de voz.",
   ["El smishing es por SMS.","Tailgating es acceso físico.","El evil twin es un AP falso."]],

  ["4.2","e","social-engineering,smishing",
   "A user receives a text message claiming a package is held and asking them to pay a fee through a link. What is this?",
   "Smishing",
   ["Vishing","Whaling","Shoulder surfing"],
   "El smishing es phishing por SMS.",
   ["El vishing es por voz.","El whaling va dirigido a directivos.","Shoulder surfing es mirar por encima del hombro."]],

  ["4.2","m","social-engineering,whaling",
   "A phishing campaign specifically targets the company's CEO and CFO. What is this called?",
   "Whaling",
   ["Smishing","Tailgating","Pharming by DNS"],
   "El whaling es spear phishing dirigido a la 'ballena': los altos directivos.",
   ["El smishing es por SMS.","Tailgating es acceso físico.","El pharming redirige mediante DNS; no se define por la víctima."]],

  ["4.2","e","social-engineering,dumpster-diving",
   "An attacker searches a company's trash for printed network diagrams and password notes. What is this?",
   "Dumpster diving",
   ["Shoulder surfing","Phishing","MAC flooding"],
   "Dumpster diving es buscar información útil en la basura. Se evita triturando los documentos.",
   ["Shoulder surfing es mirar pantallas.","El phishing usa mensajes.","MAC flooding es un ataque a switches."]],

  ["4.2","e","social-engineering,shoulder-surfing",
   "Someone standing behind an employee at a coffee shop watches them type their VPN password. What is this?",
   "Shoulder surfing",
   ["Dumpster diving","Tailgating","Vishing"],
   "Shoulder surfing es espiar lo que alguien teclea o ve en la pantalla. Se mitiga con filtros de privacidad y atención al entorno.",
   ["Dumpster diving es rebuscar en la basura.","Tailgating es colarse detrás de alguien.","El vishing es por teléfono."]],

  ["4.2","e","social-engineering,tailgating",
   "An unauthorized person follows an employee through a badge-controlled door before it closes. What is this?",
   "Tailgating",
   ["Shoulder surfing","Phishing","Evil twin"],
   "Tailgating es entrar detrás de alguien autorizado sin pasar la tarjeta. Se evita con vestíbulos de control (mantraps) y formación.",
   ["Shoulder surfing es mirar pantallas.","El phishing es por mensajes.","El evil twin es un AP falso."]],

  ["4.2","m","social-engineering,pretexting",
   "An attacker calls the help desk, claims to be a traveling executive who lost access, and pressures the technician to reset the password immediately. What technique is this?",
   "Pretexting (impersonation)",
   ["MAC flooding","Tailgating","DNS poisoning"],
   "El atacante se inventa una historia creíble (el pretexto) y se hace pasar por otra persona para obtener algo. La defensa es verificar la identidad siempre.",
   ["MAC flooding es técnico, no social.","Tailgating es físico.","DNS poisoning es técnico."]],

  ["4.2","e","malware,ransomware",
   "Files on a file server are suddenly encrypted, and a note demands payment for the decryption key. What type of malware is this?",
   "Ransomware",
   ["Spyware","Adware","Worm without payload"],
   "El ransomware cifra los datos y pide un rescate. Las copias de seguridad aisladas son la defensa clave.",
   ["El spyware espía sin cifrar archivos.","El adware muestra publicidad.","Un gusano sin carga útil solo se propaga."]],

  ["4.2","e","malware,trojan",
   "A user downloads a 'free PDF converter' that works, but secretly opens a backdoor for an attacker. What type of malware is this?",
   "Trojan",
   ["Worm","Ransomware","Rootkit only"],
   "Un troyano se disfraza de programa legítimo y útil, pero lleva oculta una función maliciosa.",
   ["Un gusano se propaga solo por la red.","El ransomware cifra archivos.","Un rootkit se esconde en el sistema; lo que se describe es un programa disfrazado."]],

  ["4.2","m","malware,worm",
   "Malware spreads from computer to computer across the network by exploiting a vulnerability, without any user action. What is it?",
   "Worm",
   ["Virus","Trojan","Adware"],
   "Un gusano se replica solo a través de la red, sin que nadie abra nada.",
   ["Un virus necesita que alguien ejecute el archivo infectado.","Un troyano necesita que el usuario lo instale.","El adware muestra publicidad."]],

  ["4.2","m","malware,virus",
   "Which type of malware attaches itself to a legitimate file and spreads only when that file is run by a user?",
   "Virus",
   ["Worm","Botnet","Rootkit"],
   "Un virus se adhiere a otro archivo y necesita que alguien lo ejecute para propagarse.",
   ["El gusano se propaga solo.","Una botnet es una red de equipos infectados.","Un rootkit se esconde en lo profundo del sistema."]],

  ["4.2","m","malware,keylogger",
   "Malware secretly records every key a user types and sends it to an attacker. What is it?",
   "Keylogger (spyware)",
   ["Ransomware","Worm","DDoS agent"],
   "Un keylogger registra las pulsaciones del teclado para robar contraseñas y datos. Es un tipo de spyware.",
   ["El ransomware cifra archivos.","Un gusano se propaga; no se define por registrar teclas.","Un agente de DDoS ataca a terceros."]],

  ["4.2","h","malware,rootkit",
   "Which type of malware hides deep in the operating system, often at the kernel level, to conceal its presence from security tools?",
   "Rootkit",
   ["Adware","Phishing kit","Spam bot"],
   "Un rootkit se esconde en capas profundas del sistema (kernel, arranque) para no ser detectado. A menudo hay que reinstalar el sistema para eliminarlo.",
   ["El adware se ve a simple vista.","Un kit de phishing es para engañar a usuarios.","Un bot de spam envía correo; no se define por ocultarse en el kernel."]],

  ["4.2","m","attacks,passwords",
   "What is the difference between a brute-force attack and a dictionary attack on passwords?",
   "Brute force: every combination; dictionary: likely words",
   ["They are the same attack with two names","A dictionary attack tries every combination","Brute force only works against Wi-Fi passphrases, not accounts"],
   "La fuerza bruta prueba todas las combinaciones posibles. El diccionario prueba una lista de palabras y contraseñas comunes, así que es más rápido contra contraseñas débiles.",
   ["Son técnicas distintas.","Es al revés.","La fuerza bruta sirve contra cualquier contraseña."]],

  ["4.2","h","attacks,password-spraying",
   "An attacker tries the single password 'Spring2026!' against hundreds of different user accounts, slowly, to avoid lockouts. What is this?",
   "Password spraying",
   ["Brute force against one account","Shoulder surfing","ARP spoofing"],
   "En el password spraying se prueba una contraseña común contra muchas cuentas, para no activar el bloqueo por intentos en una sola.",
   ["La fuerza bruta clásica prueba muchas contraseñas contra una cuenta.","Shoulder surfing es mirar.","ARP spoofing es de red local."]],

  ["4.2","m","attacks,insider-threat",
   "A disgruntled network administrator copies customer data to a personal drive before resigning. What type of threat is this?",
   "Insider threat",
   ["DDoS","Evil twin","VLAN hopping"],
   "Una amenaza interna viene de alguien con acceso legítimo: empleados, excontratistas, socios.",
   ["Un DDoS es externo y masivo.","El evil twin es un AP falso.","VLAN hopping es un ataque técnico de red."]],

  ["4.2","m","attacks,zero-day",
   "Attackers exploit a vulnerability that the vendor does not yet know about and for which no patch exists. What is this called?",
   "Zero-day attack",
   ["Known vulnerability with an available patch","Configuration drift","Tabletop exercise"],
   "Un zero-day aprovecha una vulnerabilidad desconocida o sin parche: el fabricante lleva 'cero días' para corregirla.",
   ["Ahí ya habría un parche disponible.","La desviación de configuración es otro problema.","Un tabletop es un ejercicio de mesa."]],

  ["4.2","m","social-engineering,mitigation",
   "Which of the following are effective defenses against social engineering? (Choose TWO)",
   ["Security awareness training","Procedures to verify identity before resetting passwords"],
   ["Jumbo frames","Disabling STP","Using hubs"],
   "Contra el engaño a personas funcionan la formación y los procedimientos de verificación.",
   ["Las jumbo frames no protegen a las personas.","Quitar STP solo causaría bucles.","Los hubs empeoran la seguridad."]],

  ["4.2","h","attacks,layer2",
   "Which of the following are Layer 2 attacks? (Choose TWO)",
   ["MAC flooding","ARP spoofing"],
   ["DNS cache poisoning","Phishing","SQL injection"],
   "MAC flooding y ARP spoofing actúan en la red local, con MACs y ARP (capa 2).",
   ["DNS poisoning actúa en DNS, un servicio de capa de aplicación.","El phishing es ingeniería social.","La inyección SQL ataca aplicaciones."]],

  ["4.2","e","attacks,cia",
   "A successful DDoS attack mainly affects which part of the CIA triad?",
   "Availability",
   ["Confidentiality","Integrity","Authentication"],
   "Un DDoS impide usar el servicio: ataca la disponibilidad.",
   ["No roba datos.","No modifica datos.","La autenticación no es parte de la tríada CIA."]],

  ["4.2","m","attacks,cia,on-path",
   "An attacker using ARP poisoning reads and modifies traffic between users and the server. Which parts of the CIA triad are affected?",
   "Confidentiality and integrity",
   ["Only availability","Only accounting","None"],
   "Leer el tráfico rompe la confidencialidad y modificarlo rompe la integridad.",
   ["El servicio sigue funcionando.","Accounting no es parte de la tríada.","Afecta claramente a dos pilares."]],

  ["4.2","h","attacks,evil-twin,mitigation",
   "Which control BEST protects enterprise Wi-Fi users from connecting to an evil twin that copies the corporate SSID?",
   "Enterprise Wi-Fi with server certificate validation",
   ["Hiding the SSID from beacons","Using WEP with a long key","Increasing AP transmit power so the real AP always wins"],
   "Si los clientes comprueban el certificado del servidor RADIUS legítimo, un AP falso no puede hacerse pasar por la red corporativa.",
   ["El atacante también puede usar un SSID oculto.","WEP es inseguro.","Más potencia no evita la suplantación."]],

  ["4.2","m","attacks,rogue-ap,detection",
   "How can an organization detect rogue access points in its buildings?",
   "Wireless scans or a WIDS compared to the authorized AP list",
   ["By checking DNS logs only for new device names on the network","By disabling DHCP on every VLAN","By using jumbo frames on AP ports"],
   "Un WIDS (Wireless Intrusion Detection System) o un escaneo periódico encuentra los APs que no están en la lista autorizada.",
   ["DNS no revela APs.","Sin DHCP no funcionaría la red.","Las jumbo frames no tienen relación."]],

  ["4.3","e","hardening,ports",
   "What is a basic hardening step for switch ports that are not in use?",
   "Administratively disable them",
   ["Configure them as trunks","Enable PoE at maximum power","Assign them to the management VLAN"],
   "Un puerto sin usar y activo es una puerta abierta: se apaga (shutdown).",
   ["Un trunk abierto es aún más peligroso.","Dar PoE no protege nada.","Meterlos en la VLAN de gestión sería peligrosísimo."]],

  ["4.3","e","hardening,services",
   "Why should unnecessary services such as an unused web server or Telnet be disabled on network devices?",
   "Each one increases the attack surface",
   ["They use too much electricity","They block routing protocols","They prevent logging of other services"],
   "Cada servicio activo es algo más que atacar. Si no se usa, se desactiva.",
   ["El consumo no es el motivo.","No bloquean el enrutamiento.","No impiden registrar eventos."]],

  ["4.3","e","hardening,passwords",
   "A newly installed firewall still uses the vendor's default admin password. What should be done first?",
   "Change them to strong, unique credentials",
   ["Publish the password internally","Enable Telnet access for easier support","Leave it until the next audit"],
   "Las credenciales por defecto son públicas: cualquiera puede buscarlas en internet. Se cambian nada más instalar.",
   ["Difundirla no la hace segura.","Telnet además es inseguro.","Esperar deja el equipo expuesto."]],

  ["4.3","m","port-security",
   "What does switch port security do?",
   "Limits which and how many MACs can use a port",
   ["Encrypts traffic on the port","Assigns IP addresses to each port","Prevents spanning tree loops on access ports"],
   "Port security fija qué MACs y cuántas pueden usar un puerto y qué hacer si se viola la regla.",
   ["No cifra.","No asigna IPs.","Eso es STP."]],

  ["4.3","m","port-security",
   "A port configured with port security in shutdown mode detects an unauthorized MAC address. What happens?",
   "The port goes error-disabled",
   ["The port becomes a trunk","The whole switch reboots","The device receives a new IP"],
   "En modo shutdown, una violación deja el puerto en err-disabled hasta que un administrador lo rehabilita.",
   ["No se convierte en trunk.","El switch no se reinicia.","No cambia la IP del equipo."]],

  ["4.3","h","port-security,sticky",
   "Which port security option learns the MAC address of the first device connected and saves it as an allowed address?",
   "Sticky MAC learning",
   ["PortFast","Native VLAN","Jumbo frames"],
   "Con sticky MAC el switch aprende dinámicamente la MAC conectada y la guarda como permitida, sin escribirla a mano.",
   ["PortFast acelera el arranque.","La VLAN nativa es de los trunks.","Las jumbo frames son de tamaño de trama."]],

  ["4.3","m","nac,802.1x",
   "What does 802.1X provide on a wired network?",
   "Port-based access control: authenticate before traffic",
   ["Wireless encryption only, with no control over wired ports","Loop prevention between switches","Automatic IP address assignment"],
   "802.1X bloquea el puerto hasta que el equipo o el usuario se autentica (normalmente contra RADIUS).",
   ["También se usa en redes cableadas.","Eso es STP.","Eso es DHCP."]],

  ["4.3","e","nac,802.1x",
   "A company wants every PC plugged into an office jack to authenticate with the user's credentials before getting network access. What should be implemented?",
   "802.1X on the switch ports",
   ["Jumbo frames","A second default gateway","A hidden SSID"],
   "Con 802.1X el switch pide credenciales (o un certificado) antes de abrir el puerto.",
   ["Las jumbo frames no autentican.","Un gateway no controla el acceso al puerto.","El SSID es de Wi-Fi."]],

  ["4.3","m","mac-filtering",
   "Why is MAC filtering considered a weak security control on its own?",
   "MAC addresses can be easily observed and spoofed",
   ["MAC filtering encrypts too much traffic for the switch to handle","MACs change every hour","It blocks all devices"],
   "Las MACs viajan sin cifrar y se pueden copiar en cualquier equipo. El filtrado MAC ayuda, pero no basta.",
   ["No cifra nada.","Las MACs no cambian solas cada hora.","Solo bloquea las no permitidas."]],

  ["4.3","h","nac,posture",
   "A NAC system checks that a laptop has current antivirus and patches before granting full access; otherwise it places the laptop in a remediation VLAN. What is this?",
   "Posture assessment",
   ["Port mirroring","Geofencing","DNS filtering"],
   "La evaluación de postura (posture assessment) comprueba el estado de seguridad del equipo antes de dejarle entrar. Si no cumple, va a cuarentena.",
   ["Port mirroring copia tráfico.","Geofencing usa la ubicación.","El filtrado DNS bloquea dominios."]],

  ["4.3","m","key-management",
   "Which practice is part of good cryptographic key management?",
   "Rotate, store securely and revoke keys when unused",
   ["Sharing one key with every vendor","Writing keys in network diagrams so the team can find them","Never changing keys once created"],
   "Gestionar claves es generarlas bien, guardarlas seguras, rotarlas y revocarlas cuando dejan de ser necesarias.",
   ["Compartir una clave multiplica el riesgo.","Los diagramas no son sitio para claves.","Las claves deben rotarse."]],

  ["4.3","h","key-management,hsm",
   "Where should a certificate authority's private signing key ideally be stored?",
   "In a hardware security module (HSM)",
   ["In a shared network folder","In an email to the security team","On a sticky note in the server room"],
   "Un HSM (Hardware Security Module) guarda y usa las claves sin dejar que se extraigan.",
   ["Una carpeta compartida la expone.","El correo la expone.","En papel se puede robar o copiar."]],

  ["4.3","e","acl",
   "What does an access control list (ACL) on a router or firewall do?",
   "Permits or denies traffic by IP, protocol and port",
   ["Assigns VLANs to users as they log in","Stores backup configurations of the router","Measures Wi-Fi signal strength"],
   "Una ACL es una lista de reglas que permiten o deniegan tráfico según IPs, protocolos y puertos.",
   ["No asigna VLANs.","No guarda copias de configuración.","No mide Wi-Fi."]],

  ["4.3","m","acl,implicit-deny",
   "An ACL has only 'permit' statements for web and DNS traffic. What happens to SSH traffic that matches none of them?",
   "It is denied by the implicit deny at the end of the ACL",
   ["It is permitted because nothing blocks it","It is forwarded to the default gateway unfiltered","It is logged and always allowed"],
   "Las ACLs terminan con una denegación implícita: lo que no se permite expresamente, se bloquea.",
   ["El comportamiento por defecto es denegar.","La ACL filtra antes de reenviar.","No se permite por defecto."]],

  ["4.3","m","acl,order",
   "How does a router process the entries in an ACL?",
   "Top to bottom, stopping at the first entry that matches",
   ["It evaluates all entries and applies the most restrictive","Bottom to top, stopping at the first match","In random order to balance CPU load"],
   "Se evalúan de arriba abajo y se aplica la primera regla que coincide; las demás se ignoran. Por eso el orden importa.",
   ["No se evalúan todas.","Es de arriba abajo.","No es aleatorio."]],

  ["4.3","h","acl,order,troubleshooting",
   "An ACL's first line is 'permit ip any any' and its second line is 'deny tcp any host 10.1.1.5 eq 23'. Is Telnet to 10.1.1.5 blocked?",
   "No, the first line matches everything first",
   ["Yes, because deny statements always take priority","Yes, because Telnet is always blocked","It depends on the time of day the ACL was applied"],
   "Como se aplica la primera coincidencia, 'permit any any' lo deja pasar todo. Las denegaciones específicas deben ir antes.",
   ["No tienen prioridad; manda el orden.","Nada bloquea Telnet por defecto.","No hay condición horaria."]],

  ["4.3","e","url-filtering",
   "A company blocks access to specific websites by URL or category at its proxy. What is this?",
   "URL filtering",
   ["Port security","MAC filtering","DHCP snooping"],
   "El filtrado de URLs bloquea direcciones web o categorías concretas.",
   ["Port security limita MACs en un puerto.","El filtrado MAC controla dispositivos.","DHCP snooping bloquea servidores DHCP falsos."]],

  ["4.3","m","content-filtering",
   "A secure web gateway blocks executable file downloads and scans web pages for malicious scripts. What is this capability?",
   "Content filtering",
   ["Port aggregation","Band steering","Route summarization"],
   "El filtrado de contenido analiza lo que se descarga o se visita (tipos de archivo, scripts, malware), no solo la URL.",
   ["La agregación une enlaces.","Band steering es de Wi-Fi.","Resumir rutas es enrutamiento."]],

  ["4.3","e","zones",
   "In firewall zone design, which is typically considered an untrusted zone?",
   "The internet",
   ["The internal server VLAN","The management network","The data center core"],
   "Internet es la zona no confiable por excelencia; las redes internas son de confianza (en distintos grados).",
   ["Es una zona interna.","Es de las más protegidas.","Es interna y protegida."]],

  ["4.3","e","screened-subnet",
   "Where should a company place its public web server so internet users can reach it without gaining access to the internal network?",
   "In a screened subnet (DMZ)",
   ["On the internal user VLAN","On the management network","On the same switch port as the core router"],
   "La screened subnet (antes DMZ) es una zona intermedia para servicios públicos, separada de la red interna.",
   ["Exponerlo en la red de usuarios pondría todo en riesgo.","La red de gestión debe estar muy protegida.","No es un diseño de seguridad."]],

  ["4.3","m","screened-subnet,rules",
   "Which firewall rule set is MOST appropriate for a screened subnet hosting a web server?",
   "Internet to web server HTTPS only; restrict screened-to-internal",
   ["Allow all traffic between the screened subnet and the internal network","Block HTTPS from the internet to the screened subnet","Allow the internet to reach any internal host"],
   "Solo se abre lo necesario (HTTPS al servidor) y se limita mucho lo que la zona intermedia puede hacer hacia dentro.",
   ["Anularía la separación.","Así nadie podría ver la web.","Expondría toda la red."]],

  ["4.3","m","screened-subnet",
   "Why is it risky to host a public-facing web server directly on the internal LAN?",
   "A compromise puts the attacker inside the LAN",
   ["Web servers cannot use private IPs","The server would be too fast for internal users","Internal LANs cannot run HTTPS"],
   "Si comprometen un servidor público que está en la LAN, el atacante ya está dentro. En la screened subnet queda contenido.",
   ["Pueden usar IPs privadas con NAT.","La velocidad no es el problema.","HTTPS funciona en cualquier red."]],

  ["4.3","h","dhcp-snooping",
   "When configuring DHCP snooping, which switch ports should be marked as trusted?",
   "Only ports toward real DHCP servers",
   ["All access ports on the switch","Ports connected to user PCs","No ports at all; snooping trusts none"],
   "Solo los puertos hacia los servidores DHCP legítimos son de confianza. En el resto, las respuestas DHCP se bloquean.",
   ["Así cualquier PC podría ser un DHCP falso.","Los PCs no deben ofrecer DHCP.","Sin puertos de confianza no llegaría ninguna respuesta DHCP."]],

  ["4.3","h","private-vlans",
   "Hotel guests share one VLAN, but the hotel wants each room's device isolated from every other room while all can reach the gateway. Which feature does this?",
   "Private VLANs",
   ["LACP","Native VLAN","Voice VLAN"],
   "Las VLAN privadas dividen una VLAN en puertos aislados que solo pueden hablar con el puerto 'promiscuo' (el gateway).",
   ["LACP agrega enlaces.","La VLAN nativa es de los trunks.","La voice VLAN es para teléfonos."]],

  ["4.3","m","firewall,acl",
   "What advantage does a stateful firewall have over a basic stateless ACL?",
   "It tracks connections and allows return traffic",
   ["It does not need any rules","It works only at Layer 2","It cannot log traffic, so it is faster than a stateless ACL"],
   "El firewall stateful recuerda las conexiones; un ACL sin estado necesita reglas explícitas en ambos sentidos.",
   ["Sigue necesitando reglas.","Trabaja en capas 3 y 4 (o más).","Puede registrar tráfico."]],

  ["4.3","m","hardening",
   "Which of the following are device hardening steps? (Choose TWO)",
   ["Disable unused services","Change default passwords"],
   ["Enable Telnet for convenience","Use the SNMP community 'public'","Leave unused switch ports enabled"],
   "Quitar lo que sobra y cambiar las credenciales por defecto son pasos básicos de endurecimiento.",
   ["Telnet es inseguro.","'public' es un valor por defecto inseguro.","Los puertos sin usar deben apagarse."]],

  ["4.3","m","nac",
   "Which of the following are network access control methods at the switch port? (Choose TWO)",
   ["802.1X","Port security"],
   ["DNSSEC","Spanning Tree Protocol","Route summarization"],
   "802.1X y port security controlan quién puede usar un puerto.",
   ["DNSSEC protege DNS.","STP evita bucles.","Resumir rutas es enrutamiento."]],

  ["4.3","m","acl,logging",
   "Why add logging to an ACL's explicit deny rule?",
   "To record blocked attempts for review",
   ["To make the ACL permit the traffic","To speed up the router's lookups","To disable the implicit deny"],
   "Registrar lo bloqueado ayuda a detectar ataques y a entender por qué algo no funciona.",
   ["Registrar no cambia la acción.","Registrar consume algo de recursos; no acelera.","No desactiva la denegación implícita."]],

  ["4.3","h","egress-filtering",
   "A firewall blocks outbound packets whose source IP is not part of the company's own address space. What is this called?",
   "Egress filtering",
   ["Ingress filtering","Port mirroring","Band steering"],
   "El filtrado de salida (egress) impide que salga tráfico con IPs de origen falsas, por ejemplo desde un equipo infectado que participa en un DDoS.",
   ["Ingress filtra lo que entra.","Port mirroring copia tráfico.","Band steering es de Wi-Fi."]],

  ["4.3","h","ingress-filtering",
   "An edge router drops packets arriving from the internet with RFC 1918 private source addresses. What is this?",
   "Ingress filtering",
   ["Egress filtering","NAT overload","DHCP relay on the WAN"],
   "Desde internet no deberían llegar IPs privadas como origen: si llegan, están falsificadas y se descartan (ingress).",
   ["Egress es tráfico de salida.","NAT traduce direcciones.","El relay reenvía DHCP."]],

  ["4.3","m","allow-list",
   "A firewall policy permits only explicitly approved applications and blocks everything else. What approach is this?",
   "Allow list (default deny)",
   ["Deny list (default allow)","Implicit trust","Open policy"],
   "Con una lista de permitidos solo pasa lo aprobado. Es más seguro que bloquear solo lo que se sabe que es malo.",
   ["Una lista de bloqueados deja pasar todo lo demás.","La confianza implícita no es un control.","Una política abierta no protege."]],

  ["4.3","e","hardening,firmware",
   "Keeping network device firmware up to date is part of hardening because it:",
   "Fixes known vulnerabilities",
   ["Changes the VLAN numbering","Removes the need for ACLs","Increases cable length limits"],
   "Las actualizaciones corrigen vulnerabilidades conocidas.",
   ["No cambian las VLANs.","Las ACLs siguen siendo necesarias.","No cambian los límites de los cables."]],

  ["4.3","m","firewall,least-privilege",
   "When writing firewall rules for a new application server, what is the BEST approach?",
   "Allow only the sources, destinations and ports needed",
   ["Allow all ports from any source to simplify troubleshooting","Allow all traffic and review it next year","Disable the firewall for that server"],
   "Mínimo privilegio aplicado a la red: solo se abre lo que la aplicación necesita.",
   ["Abrirlo todo expone el servidor.","Revisarlo al año es demasiado tarde.","Quitar el firewall lo deja desprotegido."]],

  ["4.3","m","hardening,unused-ports",
   "Besides shutting down unused switch ports, what else is commonly done with them?",
   "Put them in an unused 'parking' VLAN",
   ["Assign them to the server VLAN","Configure them as trunks to the core","Give them the management IP"],
   "Si alguien reactivara un puerto por error, al estar en una VLAN aislada y sin uso, no tendría acceso a nada.",
   ["Dar acceso a los servidores sería peligroso.","Un trunk sería aún peor.","Los puertos de acceso no llevan IP de gestión."]],

  ["4.3","h","nac,802.1x,guest-vlan",
   "Some printers do not support 802.1X. How can a switch still give them limited access without disabling 802.1X on all ports?",
   "Use MAC authentication bypass or a restricted VLAN",
   ["Turn off 802.1X on the whole switch","Put the printers in the management VLAN","Give the printers public IP addresses"],
   "Los switches pueden usar la MAC como identificación de respaldo (MAB, MAC Authentication Bypass) o mandar a una VLAN limitada a quien no soporte 802.1X.",
   ["Quitar 802.1X en todo pierde la protección.","La VLAN de gestión no es para impresoras.","Las IPs públicas las expondrían."]],

  ["4.3","m","screened-subnet",
   "In a screened subnet design with two firewalls, where is the screened subnet located?",
   "Between the outer and the inner firewall",
   ["Inside the internal user VLAN","Outside both firewalls on the internet","On the management network behind both firewalls"],
   "La zona intermedia queda entre los dos firewalls: el externo filtra lo que llega de internet y el interno protege la red interna.",
   ["La red interna queda detrás del firewall interior.","Fuera de los firewalls no habría protección.","La red de gestión es otra zona."]],

  ["4.3","m","hardening,secure-protocols",
   "Which change hardens how administrators manage network devices?",
   "Switch to SSH, HTTPS and SNMPv3",
   ["Replace SSH with Telnet for compatibility","Use the same password on every device","Allow management from any IP"],
   "Usar protocolos cifrados en la administración impide que se capturen credenciales.",
   ["Telnet es inseguro.","Una contraseña común multiplica el riesgo.","Hay que limitar desde dónde se administra."]],

  ["4.3","h","acl,placement",
   "To stop unwanted traffic as early as possible, where should an ACL that filters by source, destination and port normally be placed?",
   "As close to the source of the traffic as possible",
   ["As close to the destination of the traffic as possible","Only on the internet router","On every switch in the network"],
   "Filtrar cerca del origen evita que el tráfico no deseado recorra la red para nada.",
   ["Cerca del destino gastaría recursos por el camino.","El router de internet no ve el tráfico interno.","Aplicarla en todas partes complica la gestión sin necesidad."]],

  ["4.3","e","firewall,default-deny",
   "What is the safest default policy for traffic entering a network from the internet?",
   "Deny by default; allow only what is needed",
   ["Allow all by default and block known threats","Allow everything during business hours","Allow everything from IPv6"],
   "Denegar por defecto es la base: solo pasa lo que se ha decidido permitir.",
   ["Permitirlo todo expone la red.","La hora no hace seguro el tráfico.","IPv6 no es más confiable."]],

  ["4.3","e","hardening,accounts",
   "During hardening, what should be done with vendor-created or unused accounts on network devices?",
   "Remove or disable them",
   ["Share them with all technicians","Give them administrator rights","Leave them for troubleshooting"],
   "Las cuentas que sobran son una vía de entrada: se eliminan o se desactivan.",
   ["Compartirlas elimina la trazabilidad.","Darles más permisos empeora el riesgo.","Dejarlas abiertas es un riesgo."]],
];

export default q;
