import type { Raw } from '../types';

// 4.2 (+1) · 5.1 Troubleshooting methodology (30) · 5.2 Cabling and physical interface issues (50)
const q: Raw[] = [
  ["4.2","h","attacks,dhcp-starvation",
   "An attacker sends thousands of DHCP requests with spoofed MAC addresses until the DHCP server has no addresses left. What is this attack?",
   "DHCP starvation",
   ["DNS poisoning","Evil twin","Shoulder surfing"],
   "La inanición DHCP (starvation) agota todas las IPs del servidor, de modo que los clientes legítimos no reciben ninguna. A menudo precede a un DHCP falso.",
   ["DNS poisoning corrompe DNS.","El evil twin es un AP falso.","Shoulder surfing es mirar por encima del hombro."]],

  ["5.1","e","methodology",
   "What is the FIRST step of the CompTIA troubleshooting methodology?",
   "Identify the problem",
   ["Establish a theory of probable cause","Implement the solution","Document findings"],
   "Siempre se empieza por identificar bien el problema: recoger información, preguntar y reproducirlo.",
   ["La teoría viene después, en el paso 2.","Implementar es el paso 5.","Documentar es el último paso (7)."]],

  ["5.1","e","methodology",
   "What is the LAST step of the troubleshooting methodology?",
   "Document findings, actions, outcomes and lessons learned",
   ["Verify full system functionality and implement preventive measures","Implement the solution or escalate as necessary","Test the theory to determine the cause"],
   "El paso 7 es documentar: qué pasó, qué se hizo, el resultado y lo aprendido.",
   ["Verificar es el paso 6.","Implementar es el paso 5.","Probar la teoría es el paso 3."]],

  ["5.1","m","methodology",
   "A technician's theory is confirmed: a failed power supply caused the outage. What is the NEXT step?",
   "Establish a plan of action and identify potential effects",
   ["Document findings, actions and outcomes","Question the users again about recent changes","Verify full system functionality and implement preventive measures"],
   "Tras confirmar la teoría (paso 3) viene el plan de acción (paso 4): cómo se arreglará y qué efectos puede tener.",
   ["Documentar es el final.","Preguntar a los usuarios forma parte del paso 1.","Verificar llega después de implementar."]],

  ["5.1","e","methodology",
   "After implementing a fix, what should the technician do next?",
   "Verify full functionality and add preventive measures",
   ["Establish a new theory of probable cause","Identify the problem again by questioning users","Close the ticket without testing"],
   "El paso 6 comprueba que todo funciona (no solo lo que se arregló) y aplica medidas para que no vuelva a pasar.",
   ["Una nueva teoría solo hace falta si la primera no se confirmó.","Identificar el problema es el paso 1.","Hay que verificar antes de cerrar."]],

  ["5.1","m","methodology",
   "A technician tests a theory, and the theory turns out to be wrong. What should they do?",
   "Establish a new theory or escalate",
   ["Implement the original fix anyway","Document the issue as resolved","Skip to verifying functionality"],
   "Si la teoría no se confirma, se vuelve al paso 2 con una nueva teoría, o se escala a quien pueda seguir.",
   ["Aplicar un arreglo basado en una teoría falsa no resuelve nada.","No está resuelto.","No hay nada que verificar todavía."]],

  ["5.1","m","methodology,identify",
   "Asking 'Has anything changed recently?' belongs to which step of the methodology?",
   "Identify the problem",
   ["Test the theory","Implement the solution","Document findings"],
   "Determinar si algo cambió forma parte del paso 1, junto con recoger información, preguntar a los usuarios e identificar los síntomas.",
   ["Probar la teoría es verificar una causa concreta.","Implementar es aplicar la solución.","Documentar es el cierre."]],

  ["5.1","e","methodology,identify",
   "Which activity is part of identifying the problem?",
   "Questioning users about the symptoms they see",
   ["Replacing the core switch","Writing the lessons-learned report for the team","Rolling back the change"],
   "Preguntar a los usuarios qué ven, desde cuándo y a quién afecta es parte del paso 1.",
   ["Cambiar equipos sería implementar, y sin diagnóstico.","El informe de lecciones aprendidas es el paso 7.","La marcha atrás es parte del plan o de la implementación."]],

  ["5.1","m","methodology,identify",
   "A user reports that printing fails 'sometimes'. The technician tries to print the same document from the user's PC. Which part of the methodology is this?",
   "Duplicating the problem",
   ["Implementing preventive measures","Escalating to a senior technician","Documenting outcomes and lessons learned"],
   "Reproducir el problema confirma los síntomas y es parte del paso 1.",
   ["Las medidas preventivas van en el paso 6.","Todavía no hay motivo para escalar.","Documentar es el final."]],

  ["5.1","m","methodology,identify",
   "A user reports slow Wi-Fi, a printer that is offline, and an email error, all at the same time. How should the technician approach them?",
   "Approach multiple problems individually",
   ["Assume one cause and fix only that","Replace the user's laptop","Ignore the smaller issues"],
   "La metodología pide tratar varios problemas por separado, aunque se sospeche una causa común, para no mezclar síntomas.",
   ["Asumir una sola causa sin comprobarlo lleva a errores.","Cambiar el portátil no está justificado.","Todos los problemas cuentan."]],

  ["5.1","m","methodology,theory",
   "When establishing a theory of probable cause, what does 'question the obvious' mean?",
   "Check simple causes first, like cables and power",
   ["Always assume the most complex cause","Ask the user the same question three times","Skip the theory step and replace hardware"],
   "Cuestionar lo obvio es no dar nada por sentado: comprobar primero lo más simple.",
   ["Es justo lo contrario.","No se trata de repetir preguntas.","La teoría es un paso obligatorio."]],

  ["5.1","m","methodology,theory",
   "While forming a theory, a technician decides to start testing at the network layer and then move up or down the OSI model based on the result. Which approach is this?",
   "Divide and conquer",
   ["Top-to-bottom","Bottom-to-top","Escalation"],
   "Divide y vencerás: se empieza por una capa intermedia (típicamente la 3) y, según el resultado, se sube o se baja.",
   ["Top-to-bottom empieza por la capa 7.","Bottom-to-top empieza por la capa 1.","Escalar es pasar el problema a otro nivel."]],

  ["5.1","m","methodology,plan",
   "Which step includes identifying the potential effects of the fix, such as downtime for other users?",
   "Establish a plan of action",
   ["Identify the problem","Test the theory","Document findings"],
   "El plan de acción (paso 4) define cómo se resolverá y qué impacto tendrá (cortes, riesgos, necesidad de una ventana de cambios).",
   ["El paso 1 se centra en entender el problema.","El paso 3 confirma la causa.","El paso 7 registra lo ocurrido."]],

  ["5.1","m","methodology,verify",
   "After replacing a failed switch, the technician also configures monitoring alerts for its power supplies. Which step includes this?",
   "Verify functionality and implement preventive measures",
   ["Identify the problem and gather information","Establish a theory of probable cause","Test the theory to determine the cause"],
   "Las medidas preventivas forman parte del paso 6, junto con la verificación completa.",
   ["El paso 1 es entender el problema.","El paso 2 es plantear causas.","El paso 3 es confirmarlas."]],

  ["5.1","e","methodology,document",
   "Why is the documentation step important?",
   "It helps solve future issues faster and spot patterns",
   ["It replaces the need to test fixes","It is only needed for hardware failures","It makes the fix take effect on all devices"],
   "Documentar crea una base de conocimiento: el próximo técnico que vea lo mismo sabrá qué hacer.",
   ["No sustituye a las pruebas.","Se documenta todo tipo de incidencias.","La documentación no aplica cambios."]],

  ["5.1","m","methodology,escalate",
   "The problem is in the ISP's equipment, which the technician has no access to. What should they do?",
   "Escalate to the ISP or the appropriate team",
   ["Keep testing new theories until one works locally","Replace the company's firewall","Close the ticket"],
   "Cuando la solución está fuera de tu alcance o autoridad, se escala (paso 5: implementar o escalar).",
   ["Seguir probando no arregla algo que no controlas.","El firewall no es el problema.","No está resuelto."]],

  ["5.1","m","methodology,verify",
   "A technician replaced a faulty patch cable and the user's link light is back on. What is the NEXT step?",
   "Verify the user can reach all needed resources",
   ["Close the ticket immediately","Establish a new theory of probable cause","Replace the switch as well to be safe"],
   "Que haya luz no garantiza que todo funcione: se verifica que el usuario llega a todo lo que necesita.",
   ["Cerrar sin verificar es arriesgado.","No hace falta otra teoría si ya funciona.","No hay motivo para cambiar el switch."]],

  ["5.1","m","methodology,plan",
   "The fix for an issue requires rebooting a core router during business hours. What should the technician do as part of the plan of action?",
   "Assess impact and schedule it via change management",
   ["Reboot it immediately without telling anyone about it","Skip the fix and close the ticket","Replace the router with a hub"],
   "El plan de acción tiene en cuenta el impacto y sigue la gestión de cambios (ventana, aprobación, aviso a los usuarios).",
   ["Reiniciar sin avisar provoca un corte general inesperado.","El problema seguiría ahí.","Un hub no enruta."]],

  ["5.1","m","methodology,identify",
   "A user insists nothing changed, but logs show their laptop installed a VPN client update last night. Which part of identifying the problem did the logs help with?",
   "Determining if anything changed",
   ["Implementing the solution","Documenting lessons learned","Escalating to the vendor"],
   "Los usuarios no siempre saben qué cambió; los logs ayudan a averiguarlo, que es parte del paso 1.",
   ["Aún no se ha implementado nada.","Documentar es el final.","Todavía no hay motivo para escalar."]],

  ["5.1","m","methodology,approaches",
   "Only one web application fails while the rest of the network works fine. Which troubleshooting approach is MOST efficient to start with?",
   "Top-to-bottom",
   ["Bottom-to-top","Replace all cabling","Divide and conquer starting at Layer 1"],
   "Si el problema es de una aplicación concreta y la red funciona, conviene empezar por arriba (capa 7) y bajar.",
   ["Empezar por los cables sería lento si el resto funciona.","No hay indicios de un problema de cableado.","Divide y vencerás empieza en el medio, no en la capa 1."]],

  ["5.1","h","methodology,order",
   "Which sequence correctly lists the first four troubleshooting steps?",
   "Identify the problem → Establish a theory → Test the theory → Establish a plan of action",
   ["Establish a theory → Identify the problem → Establish a plan → Test the theory","Identify the problem → Establish a plan → Test the theory → Establish a theory","Test the theory → Identify the problem → Establish a theory → Document"],
   "Los 7 pasos: 1) identificar · 2) teoría · 3) probarla · 4) plan de acción · 5) implementar o escalar · 6) verificar · 7) documentar.",
   ["No se puede teorizar antes de identificar.","El plan va después de confirmar la teoría.","No se puede probar sin una teoría."]],

  ["5.1","h","methodology,order",
   "In the seven-step troubleshooting methodology, which step number is 'Establish a plan of action to resolve the problem and identify potential effects'?",
   "Step 4",
   ["Step 2","Step 3","Step 6"],
   "1 identificar · 2 teoría · 3 probar · 4 plan de acción · 5 implementar o escalar · 6 verificar · 7 documentar.",
   ["El paso 2 es la teoría.","El paso 3 es probar la teoría.","El paso 6 es verificar."]],

  ["5.1","e","methodology,identify",
   "Which step includes gathering information from logs, users and monitoring tools?",
   "Identify the problem",
   ["Implement the solution","Verify full system functionality","Document findings"],
   "Recoger información es la base del paso 1.",
   ["Implementar es aplicar el arreglo.","Verificar es comprobar al final.","Documentar es registrar al final."]],

  ["5.1","m","methodology,test",
   "A technician immediately replaced a switch because 'it looked old', but the problem continued. Which step did they skip?",
   "Test the theory to determine the cause",
   ["Document findings","Question the obvious","Implement preventive measures on the network"],
   "Actuar sin confirmar la causa es saltarse el paso 3. Antes de cambiar nada hay que comprobar la teoría.",
   ["Documentar es posterior.","Cuestionar lo obvio es parte del paso 2.","Las medidas preventivas van después de arreglar."]],

  ["5.1","e","methodology,document",
   "The user confirms everything works after the fix. What is the remaining step?",
   "Document the findings and outcomes",
   ["Establish a new theory of probable cause","Identify the problem with the users again","Test the theory to determine the cause"],
   "Cuando todo está verificado, solo queda documentar.",
   ["Ya no hace falta otra teoría.","El problema ya está identificado.","La teoría ya está probada."]],

  ["5.1","m","methodology,plan",
   "Before applying a fix that changes VLAN assignments on 40 ports, the technician prepares a rollback procedure. Which step is this part of?",
   "Establish a plan of action",
   ["Identify the problem","Verify full system functionality","Document findings"],
   "Preparar cómo se hará y cómo deshacerlo es parte del plan de acción (paso 4).",
   ["El paso 1 es entender el problema.","Verificar va después de implementar.","Documentar es el cierre."]],

  ["5.1","m","methodology,identify",
   "Which of the following belong to the 'identify the problem' step? (Choose TWO)",
   ["Question users","Determine if anything has changed"],
   ["Implement the solution","Document lessons learned","Escalate to the vendor"],
   "Preguntar a los usuarios y averiguar si algo cambió son actividades del paso 1.",
   ["Es el paso 5.","Es el paso 7.","Escalar forma parte del paso 3 o del 5."]],

  ["5.1","h","methodology,theory",
   "Which of the following are part of establishing a theory of probable cause? (Choose TWO)",
   ["Question the obvious","Consider multiple approaches, such as top-to-bottom or divide and conquer"],
   ["Verify full system functionality","Document findings","Implement preventive measures"],
   "En el paso 2 se cuestiona lo obvio y se consideran distintos enfoques del modelo OSI.",
   ["Es el paso 6.","Es el paso 7.","Es parte del paso 6."]],

  ["5.1","m","methodology,verify",
   "After fixing a DNS issue for one department, why should the technician test from several departments too?",
   "To verify the fix did not break anything else",
   ["To create more tickets for the other departments","Because the methodology forbids testing with the original user","To avoid documentation of the fix"],
   "Verificar el sistema completo incluye comprobar que el cambio no ha afectado a otros.",
   ["El objetivo no es generar tickets.","Se prueba con el usuario original y con más.","La documentación sigue siendo obligatoria."]],

  ["5.1","m","methodology,escalate",
   "A junior technician finds that the fix requires changing firewall rules they are not authorized to modify. What should they do?",
   "Escalate to someone authorized to change it",
   ["Make the change anyway and document it later","Disable the firewall temporarily","Tell the user it cannot be fixed"],
   "Escalar es correcto cuando el arreglo está fuera de tus permisos.",
   ["Hacerlo sin autorización rompe la gestión de cambios.","Desactivar el firewall es muy peligroso.","Sí se puede arreglar, pero lo hace otra persona."]],

  ["5.2","m","cabling,fiber",
   "A technician connects two single-mode optics with a multimode patch cable, and the link shows errors or stays down. What is the problem?",
   "The wrong type of fiber cable",
   ["A duplex mismatch","A native VLAN mismatch","An expired certificate"],
   "Las ópticas monomodo necesitan fibra monomodo. Con un latiguillo multimodo, la señal no se transmite correctamente.",
   ["El dúplex es un ajuste Ethernet, no un problema de fibra.","La VLAN nativa no impide que el enlace se levante.","No hay certificados en juego."]],

  ["5.2","m","cabling,copper",
   "A 10GBASE-T link over a 70 m run keeps dropping to 1 Gbps and logging errors. The installed cable is Cat 5e. What is the likely cause?",
   "The cable category cannot do 10 Gbps at that length",
   ["The switch needs jumbo frames","DNS is misconfigured on the switch's management interface","The port is in the wrong VLAN"],
   "Cat 5e no está pensado para 10GBASE-T. Para 10 Gbps a 70 m hace falta al menos Cat 6a.",
   ["Las jumbo frames no afectan a la velocidad del enlace.","DNS no afecta al enlace físico.","La VLAN no cambia la velocidad."]],

  ["5.2","m","cabling,shielding",
   "A copper run passes next to heavy industrial machinery, and the link shows many errors. Besides rerouting, which cable choice helps?",
   "Properly grounded shielded twisted pair (STP)",
   ["Unshielded Cat 5e with tighter twists","A longer UTP cable routed the same way","A rollover cable with shielding"],
   "El cable apantallado (STP, Shielded Twisted Pair) protege frente a interferencias electromagnéticas, si está bien puesto a tierra. La fibra sería otra buena opción.",
   ["El UTP es el más sensible a la interferencia.","Más longitud añade atenuación.","El rollover es para consola."]],

  ["5.2","h","cabling,shielding",
   "Shielded cable was installed, but errors got worse. The installer did not ground the shield. Why can this be a problem?",
   "An ungrounded shield acts like an antenna",
   ["Shielded cable only works with fiber optics","Grounding lowers the link speed","STP cannot carry Ethernet signals at all"],
   "El blindaje debe conectarse a tierra; si no, en vez de proteger puede captar interferencias.",
   ["STP es cobre para Ethernet.","La tierra no reduce la velocidad.","STP lleva Ethernet sin problema."]],

  ["5.2","m","cabling,crosstalk",
   "What is crosstalk?",
   "Signal from one wire pair bleeding into an adjacent pair",
   ["Two switches using different VLANs","Signal weakening over distance","Radio interference from microwave ovens near the cable run"],
   "La diafonía (crosstalk) es la señal de un par que se 'cuela' en otro par cercano. El trenzado de los pares existe para reducirla.",
   ["No es un problema de VLANs.","Eso es la atenuación.","Eso es interferencia externa (EMI/RF)."]],

  ["5.2","h","cabling,next",
   "A cable certifier reports excessive NEXT (near-end crosstalk) at one end of a run. What is the MOST likely cause?",
   "Pairs untwisted too far at the termination",
   ["The cable is actually fiber optic","The switch has STP enabled","The DHCP scope is full on that VLAN"],
   "La diafonía en el extremo cercano suele aparecer cuando se destrenzan los pares demasiado al crimpar o al conectar en el patch panel.",
   ["La fibra no sufre diafonía eléctrica.","STP no causa diafonía.","DHCP no tiene relación con la señal."]],

  ["5.2","e","cabling,attenuation",
   "A copper Ethernet run of 130 m has intermittent errors. What is the MOST likely cause?",
   "Attenuation beyond the 100 m limit",
   ["DNS poisoning on the segment","A duplex setting of full","Too many VLANs on the link"],
   "Por encima de 100 m la señal se debilita demasiado (atenuación). Hay que acortar el tramo, añadir un switch intermedio o usar fibra.",
   ["DNS no afecta al medio físico.","Full duplex es lo correcto.","El número de VLANs no afecta a la señal."]],

  ["5.2","e","cabling,emi",
   "Network cables were run across a ceiling right next to fluorescent light ballasts, and users on that run see errors. What is the likely cause?",
   "Electromagnetic interference",
   ["Attenuation from a cable that is too short","DHCP exhaustion","A routing loop"],
   "Los balastos de fluorescentes, los motores y los cables eléctricos generan EMI (Electromagnetic Interference) que corrompe la señal del cobre.",
   ["Un cable corto no produce atenuación relevante.","DHCP no provoca errores de señal.","Un bucle de enrutamiento no se relaciona con la ubicación del cable."]],

  ["5.2","m","cabling,termination",
   "A newly terminated cable passes a basic continuity test but shows many errors under load. The jack was punched down with pairs untwisted several centimeters. What is the problem?",
   "Improper termination",
   ["Incorrect SSID","A wrong default gateway","Too short a lease time"],
   "Una terminación mal hecha (pares muy destrenzados, conectores mal crimpados) degrada la señal aunque haya continuidad.",
   ["El SSID es de Wi-Fi.","El gateway no causa errores físicos.","El préstamo DHCP no afecta a la señal."]],

  ["5.2","m","cabling,pinout",
   "One end of a patch cable is wired T568A and the other T568B. What kind of cable is this?",
   "A crossover cable",
   ["A straight-through cable","A rollover cable","A coaxial cable"],
   "Un extremo en T568A y el otro en T568B intercambia los pares de transmisión y recepción: es un cable cruzado (crossover).",
   ["El directo usa el mismo estándar en los dos extremos.","El rollover invierte todos los pines; es para consola.","El coaxial es otro tipo de cable."]],

  ["5.2","h","cabling,split-pair",
   "A cable tester shows correct pin-to-pin continuity, but the link has heavy errors. A certifier reports a split pair. What happened?",
   "Split pairs: wires from two pairs used as one pair",
   ["The cable is too short for the tester","The cable is fiber with copper ends","The switch port is administratively down"],
   "En un par partido (split pair) los pines conectan bien, pero los hilos de un 'par' vienen de pares trenzados distintos, así que se pierde la protección contra la diafonía.",
   ["Un cable corto no causa esto.","La fibra no tiene pares.","Un puerto apagado no generaría errores; simplemente no funcionaría."]],

  ["5.2","m","fiber,tx-rx",
   "A new duplex fiber link does not come up. Both optics and the cable type are correct. What should the technician check next?",
   "Whether TX and RX are swapped",
   ["Whether DNS is resolving the switch name","Whether the VLAN database exists","Whether the SSID is hidden"],
   "En fibra dúplex, la transmisión de un lado debe ir a la recepción del otro. Si están cruzadas al revés, no hay enlace; se intercambian en un extremo.",
   ["DNS no afecta a que el enlace se levante.","Las VLANs no impiden el enlace físico.","El SSID es de Wi-Fi."]],

  ["5.2","m","interface-counters,crc",
   "An interface shows a rapidly increasing CRC error count. What are the MOST likely causes?",
   "Bad cable, interference or duplex mismatch",
   ["An incorrect DNS server","A full DHCP scope on that VLAN's server","A missing default route"],
   "Los errores CRC indican tramas dañadas: cable roto o mal crimpado, interferencias o discrepancia de dúplex.",
   ["DNS no daña tramas.","DHCP no daña tramas.","Las rutas no dañan tramas."]],

  ["5.2","m","interface-counters,runts",
   "What are runts on a switch interface?",
   "Frames smaller than the 64-byte minimum",
   ["Frames larger than the MTU","Frames with 802.1Q VLAN tags","Frames sent to the broadcast address"],
   "Un runt es una trama demasiado pequeña (menos de 64 bytes). Suele deberse a colisiones, normalmente por un problema de dúplex.",
   ["Esos son los giants.","Las etiquetas VLAN son normales en los trunks.","Los broadcasts son tramas válidas."]],

  ["5.2","m","interface-counters,giants",
   "An interface logs many giants. What does this indicate?",
   "Oversized frames, often from an MTU mismatch",
   ["Frames smaller than 64 bytes","Too many VLANs on the trunk","An expired DHCP lease on a client connected to the port"],
   "Un giant es una trama mayor del máximo permitido (1518 bytes sin jumbo). Suele indicar que un lado usa jumbo frames y el otro no.",
   ["Esas son las runts.","El número de VLANs no produce giants.","DHCP no tiene relación."]],

  ["5.2","m","interface-counters,drops",
   "An uplink interface shows a growing number of output drops during business hours, but no CRC errors. What is the MOST likely cause?",
   "Congestion overflowing the output buffers",
   ["A bad cable on the uplink","A duplex mismatch with the upstream router","A wrong DNS record"],
   "Descartes de salida sin errores CRC indican saturación: llega más tráfico del que la interfaz puede enviar.",
   ["Un cable malo produciría errores CRC.","Un problema de dúplex produciría colisiones y CRC.","DNS no descarta tramas."]],

  ["5.2","m","port-status,err-disabled",
   "A user's port stopped working, and the switch shows it as 'err-disabled'. What could have caused this?",
   "A security feature, like port security, shut it",
   ["The DHCP lease on the PC expired","The DNS server went down","The user changed their domain password this morning"],
   "El estado err-disabled lo pone el switch automáticamente por una violación: port security, BPDU guard, errores de enlace…",
   ["DHCP no apaga puertos.","DNS no apaga puertos.","Cambiar la contraseña no afecta al puerto."]],

  ["5.2","e","port-status,admin-down",
   "A switch port shows 'administratively down'. What does this mean?",
   "An administrator disabled the port",
   ["The cable is broken or unplugged","The connected PC is powered off","The port detected a loop"],
   "'Administratively down' significa que alguien lo apagó a propósito por configuración.",
   ["Un cable roto daría 'down', no 'administratively down'.","Con el PC apagado se vería 'down/notconnect'.","Un bucle detectado llevaría a err-disabled o bloqueo por STP."]],

  ["5.2","h","port-status,suspended",
   "One member of an LACP bundle shows a 'suspended' state while the others are up. What is the MOST likely cause?",
   "Its settings do not match the other members",
   ["The DNS server is unreachable","The VLAN is missing from DHCP","The port has a new IP address assigned"],
   "Un miembro que no coincide con el resto (velocidad, dúplex, modo LACP) o que no recibe LACP del otro lado queda suspendido.",
   ["DNS no afecta a la agregación de enlaces.","DHCP no tiene relación con LACP.","Los puertos de capa 2 no llevan IP."]],

  ["5.2","m","port-status,err-disabled",
   "After fixing the cause of a port's err-disabled state, how is the port normally restored?",
   "Shut it and re-enable it, or use auto-recovery",
   ["Reboot every switch in the building to clear the state","Change the DNS server on the switch","Replace the patch panel"],
   "Una vez resuelta la causa, se hace shutdown y no shutdown en el puerto, o se deja que la recuperación automática lo levante.",
   ["No hace falta reiniciar nada.","DNS no tiene relación.","El patch panel no es el problema."]],

  ["5.2","m","poe,budget",
   "Several newly installed IP cameras stay dark, while earlier cameras on the same switch work. The switch logs power denial messages. What is the MOST likely cause?",
   "The switch's PoE power budget has been exceeded",
   ["The cameras are in the wrong DNS zone","The switch needs jumbo frames","STP is blocking the camera ports as a loop"],
   "El switch tiene un presupuesto total de PoE. Cuando se agota, deja de alimentar a los dispositivos nuevos.",
   ["DNS no da electricidad.","Las jumbo frames no afectan a la alimentación.","STP no deniega energía."]],

  ["5.2","h","poe,budget",
   "A PoE switch has a 370 W budget. It already powers 12 cameras drawing 25 W each. How many 30 W access points can still be added without exceeding the budget?",
   "2",
   ["3","5","12"],
   "12 × 25 = 300 W usados. Quedan 370 − 300 = 70 W. 70 / 30 = 2,33, así que caben 2 APs.",
   ["3 APs serían 90 W: se pasa del presupuesto.","5 APs serían 150 W.","12 APs serían 360 W."]],

  ["5.2","m","poe,standards",
   "Which PoE standard provides up to about 30 W per port (PoE+)?",
   "802.3at",
   ["802.3af","802.3bt","802.11ac"],
   "802.3af da hasta unos 15,4 W por puerto (PoE), 802.3at unos 30 W (PoE+) y 802.3bt 60–90 W (PoE++).",
   ["802.3af da unos 15,4 W.","802.3bt da 60–90 W.","802.11ac es Wi-Fi."]],

  ["5.2","m","poe,standards",
   "A new pan-tilt-zoom camera requires 802.3at (PoE+), but the switch port only supports 802.3af. What is likely to happen?",
   "It may not fully power on or lose motor features",
   ["It works at full power anyway using 802.3af","The switch upgrades itself to 802.3bt","The camera receives more power than it needs"],
   "Con menos potencia de la necesaria, el dispositivo no arranca o funciona limitado.",
   ["No puede recibir más de lo que da el puerto.","El switch no cambia su hardware solo.","Recibiría menos, no más."]],

  ["5.2","h","transceivers,mismatch",
   "A technician inserts a 1 Gbps SFP into a switch port that supports only 10 Gbps SFP+ optics. The link will not come up. What is the issue?",
   "The port does not support that speed",
   ["The VLAN on the port is wrong","DNS is down for the switch","The patch panel is not labeled"],
   "Si el puerto solo admite 10 Gbps, un SFP de 1 Gbps no funcionará ahí. Hay que usar la óptica que soporte el puerto.",
   ["La VLAN no impide que el enlace se levante.","DNS no tiene relación.","Las etiquetas no afectan al enlace."]],

  ["5.2","m","transceivers,signal",
   "A fiber link shows a low received signal level and intermittent errors, although the optics match. What should the technician do first?",
   "Inspect and clean the fiber connectors",
   ["Change the DNS server","Replace the switch's power supply unit","Disable spanning tree"],
   "La suciedad en los conectores es una de las causas más comunes de pérdida de señal en fibra. Primero se inspecciona y se limpia.",
   ["DNS no afecta a la potencia óptica.","La fuente no explica una señal óptica baja.","STP no afecta a la señal."]],

  ["5.2","m","fiber,bend-radius",
   "A fiber patch cord was tightly zip-tied around a sharp corner, and the link now shows high loss. What is the cause?",
   "Bend radius exceeded",
   ["The cable is too short for the run","A duplex mismatch","DHCP exhaustion"],
   "Doblar la fibra más de lo permitido deja escapar la luz (o rompe la fibra), y la pérdida aumenta.",
   ["La longitud corta no causa pérdida.","El dúplex no aplica aquí.","DHCP no tiene relación."]],

  ["5.2","m","fiber,distance",
   "A 10GBASE-SR link over multimode fiber is planned for 1.5 km. What problem is expected?",
   "Too long for short-range multimode optics",
   ["No problem, multimode has no distance limit","It will only work with Cat 6 copper instead","It will cause a routing loop"],
   "Las ópticas SR sobre multimodo llegan a cientos de metros. Para 1,5 km se necesitan ópticas monomodo (por ejemplo, LR).",
   ["Toda fibra tiene límites de distancia.","El cobre llega aún menos lejos.","No se relaciona con el enrutamiento."]],

  ["5.2","h","fiber,optical-power",
   "A light meter shows a received power of −30 dBm on a link whose optics need at least −20 dBm. What does this indicate?",
   "Too much loss: dirty connectors, splices or distance",
   ["The signal is too strong for the receiver to decode correctly","The link is perfect at that level","The switch has the wrong VLAN"],
   "−30 dBm es 10 dB más débil que el mínimo necesario: se está perdiendo demasiada luz por el camino.",
   ["Más negativo significa más débil, no más fuerte.","Está por debajo de la sensibilidad mínima.","La VLAN no afecta a la potencia óptica."]],

  ["5.2","m","cabling,auto-mdix",
   "Why can modern switches usually connect to each other with either a straight-through or a crossover cable?",
   "Auto-MDIX swaps transmit and receive automatically",
   ["All modern cables are fiber","Switches no longer use twisted pair between each other","STP rewires the ports internally"],
   "Auto-MDIX ajusta automáticamente los pares de transmisión y recepción, así que el tipo de cable ya no importa en la mayoría de equipos.",
   ["Mucho cableado sigue siendo cobre.","Siguen usando par trenzado.","STP no cambia el cableado."]],

  ["5.2","e","cabling,link-light",
   "A user's PC shows no link light, and the switch port shows no link either. Where should troubleshooting focus?",
   "The physical layer",
   ["DNS settings","The web browser","The user's password"],
   "Sin luz de enlace en ningún extremo, el problema es físico (capa 1).",
   ["DNS es mucho más arriba.","El navegador es capa 7.","La contraseña no afecta a la luz de enlace."]],

  ["5.2","h","interface-counters,late-collisions",
   "A switch port connected to a server shows late collisions increasing. What is the MOST likely cause?",
   "A duplex mismatch",
   ["A missing DNS record","An exhausted DHCP scope","An incorrect SSID"],
   "En full duplex no debería haber colisiones. Las colisiones tardías (late collisions) son el síntoma clásico de un lado en half y otro en full.",
   ["DNS no genera colisiones.","DHCP no genera colisiones.","El SSID es de Wi-Fi."]],

  ["5.2","m","interface-counters,crc",
   "Which of the following commonly cause CRC errors on a copper link? (Choose TWO)",
   ["A damaged or poorly terminated cable","Electromagnetic interference near the cable"],
   ["An incorrect DNS server","DHCP scope exhaustion","A missing MX record"],
   "El CRC detecta tramas dañadas en el medio físico: cable defectuoso o interferencias.",
   ["DNS no daña tramas.","DHCP no daña tramas.","Los registros de correo no afectan al enlace."]],

  ["5.2","m","port-status",
   "Which port states require an administrator to take action before the port will pass traffic again? (Choose TWO)",
   ["Administratively down","Error-disabled (without automatic recovery)"],
   ["Up/up","Forwarding","Connected"],
   "Un puerto apagado por configuración o en err-disabled (sin recuperación automática) no vuelve solo: alguien tiene que actuar.",
   ["Up/up ya funciona.","Forwarding ya reenvía.","Connected ya funciona."]],

  ["5.2","h","port-status,up-down",
   "A router serial interface shows 'up/down' (physical up, line protocol down). What does this suggest?",
   "Physical is fine, but Layer 2 fails (e.g. encapsulation)",
   ["The cable is unplugged at the far end","The interface was shut down by an administrator","Everything is working normally on the link"],
   "Estado físico arriba pero protocolo abajo: hay señal, pero la capa 2 no se entiende con el otro extremo (encapsulación distinta, keepalives, reloj).",
   ["Desenchufado daría down/down.","Apagado mostraría 'administratively down'.","Up/down no es un estado normal de trabajo."]],

  ["5.2","m","port-status,down-down",
   "An interface shows 'down/down'. Where is the problem MOST likely?",
   "At the physical layer, like a cable or far-end device",
   ["In the DNS configuration of the router","In the routing protocol's neighbor settings","In the web application on the server"],
   "Down/down indica que no hay señal física: cable, transceptor o el equipo del otro extremo.",
   ["DNS no bajaría la interfaz.","El enrutamiento no bajaría la interfaz física.","La aplicación no afecta a la interfaz."]],

  ["5.2","e","fiber,connectors",
   "A new switch has LC ports, but the available fiber patch cords have SC connectors on both ends. What is needed?",
   "LC-to-SC (or LC-to-LC) patch cords",
   ["A crossover copper cable","A rollover cable with adapters","A coaxial adapter for each port"],
   "Los conectores deben coincidir con los puertos. Hacen falta latiguillos con los extremos correctos (por ejemplo, LC-SC).",
   ["El cobre no se conecta a puertos de fibra.","El rollover es para consola.","El coaxial no tiene relación."]],

  ["5.2","m","cabling,copper",
   "A 10GBASE-T run of 90 m is planned. Which minimum cable category should be installed?",
   "Cat 6a",
   ["Cat 5e","Cat 6","Cat 3"],
   "Para 10 Gbps en 90 m hace falta Cat 6a (Cat 6 solo llega a unos 55 m a 10 Gbps).",
   ["Cat 5e no está pensado para 10 Gbps.","Cat 6 llega a unos 55 m a 10 Gbps.","Cat 3 es de telefonía."]],

  ["5.2","h","cabling,outdoor",
   "Why is fiber preferred over copper for a link between two separate buildings?",
   "It is immune to ground differences and lightning surges",
   ["Copper cannot carry Ethernet outdoors at all, even when shielded","Fiber is always cheaper to install","Copper requires wireless controllers"],
   "Entre edificios puede haber diferencias de potencial de tierra y sobretensiones por rayos. La fibra no conduce electricidad, así que evita esos riesgos (y además llega más lejos).",
   ["El cobre puede usarse en exterior con precauciones, pero es más arriesgado.","La fibra no siempre es más barata.","El cobre no necesita controladores inalámbricos."]],

  ["5.2","m","cabling,emi",
   "A data cable must cross a power cable in a ceiling. What is the recommended practice to reduce interference?",
   "Cross at 90 degrees and keep parallel runs apart",
   ["Tie them together tightly for neatness","Run them in the same conduit for the full length","Wrap the data cable around the power cable"],
   "Cruzarlos en ángulo recto y separar los tramos paralelos reduce el acoplamiento electromagnético.",
   ["Juntarlos aumenta la interferencia.","Ir en el mismo conducto aumenta la interferencia.","Enrollarlos es lo peor posible."]],

  ["5.2","m","cabling,console",
   "A technician mistakenly uses a rollover (console) cable to connect a PC's network card to a switch port. What happens?",
   "No link, because the pinout is wrong for Ethernet",
   ["It works normally at 10 Gbps once auto-MDIX adapts","It enables PoE on the port","It creates a trunk to the PC"],
   "El rollover invierte todos los pines y está pensado para la consola serie, no para Ethernet.",
   ["No funcionaría como Ethernet.","No habilita PoE.","No crea trunks."]],

  ["5.2","m","poe,power-cycling",
   "A wireless AP keeps rebooting every few minutes. It works fine when connected to a PoE injector with more power. What is the likely cause?",
   "The port is not supplying enough PoE power",
   ["The AP has the wrong SSID","The DNS server is slow to answer the AP","The AP's MAC address is duplicated"],
   "Si el AP pide más potencia de la que da el puerto (por su clase o por el presupuesto del switch), se reinicia al consumir más.",
   ["El SSID no provoca reinicios.","DNS no reinicia equipos.","Una MAC duplicada no causaría reinicios que desaparecen con otro inyector."]],

  ["5.2","h","transceivers,ddm",
   "Which transceiver feature lets a switch report optical transmit/receive power and temperature to help troubleshoot a fiber link?",
   "DDM/DOM diagnostics",
   ["Auto-MDIX","PortFast","Band steering on the optic"],
   "Muchos SFP incluyen DDM/DOM (Digital Diagnostics/Optical Monitoring), que informa de la potencia óptica, la temperatura y el voltaje.",
   ["Auto-MDIX es de cobre.","PortFast es de STP.","Band steering es de Wi-Fi."]],

  ["5.2","e","port,troubleshooting",
   "A user's connection fails. Moving the same cable to a different switch port fixes it. What does this suggest?",
   "The original switch port is faulty",
   ["The DNS server was down","The user's password expired","The VLAN database was deleted"],
   "Si el mismo cable funciona en otro puerto, el problema está en el puerto original.",
   ["DNS no depende del puerto.","La contraseña no depende del puerto.","Si se hubiera borrado la base de VLANs, afectaría a muchos puertos."]],

  ["5.2","e","cabling,termination",
   "A wall jack was punched down on the patch panel using the wrong color order. What is the likely result?",
   "Link failures or errors from a wrong pinout",
   ["The link becomes faster than its cable category is rated for","The user gets a public IP","The switch creates a new VLAN"],
   "Un orden de colores incorrecto provoca una asignación de pines equivocada: sin enlace o con errores.",
   ["No mejora nada.","No afecta al direccionamiento.","No crea VLANs."]],

  ["5.2","e","cabling,short",
   "A cable tester reports a short between two wires. What does this mean?",
   "Two conductors are touching each other",
   ["A wire is broken and not connected","The cable is too long","The cable is fiber, not copper"],
   "Un cortocircuito (short) indica que dos hilos se tocan. Suele deberse a un conector dañado o a un cable pisado.",
   ["Eso es un circuito abierto (open).","La longitud es otro tipo de fallo.","La fibra no tiene hilos eléctricos."]],

  ["5.2","e","cabling,open",
   "A cable tester reports an open on pair 3. What does this mean?",
   "A wire in that pair has no continuity",
   ["Two wires are touching","The pair is working perfectly","The cable is shielded on that pair"],
   "Un circuito abierto (open) es un hilo cortado o sin conectar: no hay continuidad.",
   ["Eso sería un cortocircuito.","El tester está indicando un fallo.","El apantallado no es un fallo."]],

  ["5.2","m","cabling,reversed-pair",
   "A cable tester shows that pin 1 on one end connects to pin 2 on the other, and pin 2 to pin 1. What is this fault?",
   "Reversed pair (reversal)",
   ["Short","Correct straight-through wiring","Split pair with correct pins"],
   "Los dos hilos de un mismo par están intercambiados: es un par invertido. Hay que volver a terminar el conector.",
   ["En un corto los hilos se tocan.","En un cable directo el pin 1 va al pin 1.","En un par partido los pines son correctos pero los pares están mezclados."]],

  ["5.2","m","cabling,copper",
   "A Cat 8 cable run of 50 m is installed for 40 Gbps between server rows. What problem should be expected?",
   "Too long: Cat 8 does 40 Gbps only to about 30 m",
   ["No problem; Cat 8 supports 100 m at 40 Gbps","Cat 8 only supports 100 Mbps","Cat 8 requires fiber connectors"],
   "Cat 8 está pensado para tramos cortos (hasta unos 30 m) dentro del centro de datos.",
   ["No llega a 100 m a 40 Gbps.","Cat 8 es mucho más rápido.","Usa conectores de cobre."]],
];

export default q;
