import type { Raw } from '../types';

// 5.1 (+1) · 5.2 (+1) · 5.3 Network services issues (55) · 5.4 Performance issues (45)
const q: Raw[] = [
  ["5.1","m","methodology,order",
   "In the troubleshooting methodology, which step is 'Implement the solution or escalate as necessary'?",
   "Step 5",
   ["Step 3","Step 4","Step 7"],
   "1 identificar · 2 teoría · 3 probar · 4 plan de acción · 5 implementar o escalar · 6 verificar · 7 documentar.",
   ["El paso 3 es probar la teoría.","El paso 4 es el plan de acción.","El paso 7 es documentar."]],

  ["5.2","m","interface,flapping",
   "A switch log shows an uplink going up and down every few seconds (interface flapping). What are the MOST likely causes?",
   "A faulty cable, optic or loose connection",
   ["An incorrect DNS server","A full DHCP scope on the uplink's VLAN","A wrong SSID on the uplink"],
   "Un enlace que sube y baja una y otra vez suele indicar un problema físico: cable dañado, conector suelto o transceptor que falla.",
   ["DNS no afecta al estado del enlace.","DHCP no afecta al estado del enlace.","El SSID es de Wi-Fi."]],

  ["5.3","m","stp,loop",
   "Right after a technician connects a second cable between two switches 'for redundancy', the network becomes almost unusable. STP had been disabled on both switches. What happened?",
   "A switching loop (broadcast storm)",
   ["A DNS server failure at that moment","A DHCP scope exhaustion","A duplex mismatch on a PC"],
   "Sin STP, dos cables entre switches forman un bucle: los broadcasts dan vueltas sin fin y saturan la red.",
   ["DNS no colapsa toda la red de golpe.","DHCP no provoca una tormenta.","Un PC no colapsaría toda la red."]],

  ["5.3","h","stp,root-bridge",
   "Traffic between two core switches is taking a slow path through an old access switch. Investigation shows the access switch is the STP root bridge. What is the BEST fix?",
   "Lower the core switch's bridge priority",
   ["Disable STP on all switches to free links","Raise the priority of the core switch to 65535","Remove all redundant links in the network"],
   "Si el root está en un mal sitio, el árbol entero queda mal. Se baja la prioridad del switch de core para que gane la elección.",
   ["Sin STP aparecerían bucles.","Una prioridad mayor lo hace perder la elección, no ganarla.","Quitar la redundancia elimina la protección frente a fallos."]],

  ["5.3","h","stp,root-bridge",
   "A new switch with default STP priority is added, and it unexpectedly becomes the root bridge. Why?",
   "Equal priorities, so the lowest MAC address won",
   ["It has the most ports of any switch","It was the last switch powered on","It has the highest management IP address"],
   "Con prioridades iguales desempata la MAC más baja. Por eso conviene fijar a mano la prioridad del root deseado.",
   ["El número de puertos no cuenta.","El orden de encendido no decide.","Las IPs no participan en STP."]],

  ["5.3","m","stp,port-states",
   "An engineer notices that one of two uplinks between an access switch and the distribution layer carries no traffic and shows as blocking. Is this a problem?",
   "No, STP blocks it to prevent a loop until needed",
   ["Yes, the port is broken and must be replaced","Yes, blocking means a duplex mismatch","Yes, it means the VLAN is missing on that link"],
   "Es el comportamiento normal de STP: uno de los caminos redundantes queda bloqueado como respaldo.",
   ["El puerto funciona; solo está bloqueado por diseño.","El bloqueo de STP no tiene relación con el dúplex.","No indica que falte una VLAN."]],

  ["5.3","h","stp,port-roles",
   "In RSTP, which port role is a backup path toward the root bridge that is ready to take over if the root port fails?",
   "Alternate port",
   ["Designated port","Edge port","Trunk port"],
   "El alternate port es un camino alternativo hacia el root, bloqueado mientras el root port funciona.",
   ["El designated reenvía hacia su segmento.","El edge port conecta equipos finales (PortFast).","Trunk es un tipo de puerto de VLAN, no un rol de STP."]],

  ["5.3","h","stp,port-roles",
   "On each network segment, which STP port role is responsible for forwarding traffic toward that segment?",
   "Designated port",
   ["Root port","Alternate port","Disabled port"],
   "En cada segmento hay un designated port que reenvía hacia él. El root port, en cambio, es el camino de cada switch hacia el root.",
   ["El root port apunta hacia el root bridge.","El alternate está bloqueado como respaldo.","El disabled está apagado."]],

  ["5.3","m","stp,portfast",
   "PCs using network boot (PXE) fail to boot because the switch port takes about 30 seconds to start forwarding. What should be changed?",
   "Enable PortFast on the access ports",
   ["Disable DHCP on the switch","Increase the DHCP lease time","Change the native VLAN on access ports"],
   "El arranque en red empieza antes de que STP termine sus estados de escucha y aprendizaje. PortFast pone el puerto en forwarding al momento.",
   ["Sin DHCP no hay arranque en red.","El tiempo de préstamo no afecta a la espera.","La VLAN nativa no cambia la espera de STP."]],

  ["5.3","e","vlan,incorrect-assignment",
   "A new employee's PC gets an IP address but cannot reach the accounting server that the rest of the team uses. Their port is in the guest VLAN. What is the problem?",
   "Wrong VLAN on the switch port",
   ["A duplex mismatch on the port","A broken DNS server","An expired certificate on the PC"],
   "El puerto está en la VLAN equivocada: el PC recibe IP de la red de invitados y las reglas le impiden llegar al servidor.",
   ["Un problema de dúplex no cambiaría de red al equipo.","DNS no explica una IP de otra subred.","Un certificado no explica esto."]],

  ["5.3","m","vlan,voice",
   "IP phones on a floor show 'no IP address', while the PCs plugged into them work. The switch ports have no voice VLAN configured. What should be fixed?",
   "Configure the voice VLAN on the access ports",
   ["Replace all the phones with new models","Change the PCs' DNS servers","Disable STP on the access ports"],
   "Sin voice VLAN, los teléfonos no llegan a la red de voz y su DHCP. Los PCs siguen en la de datos.",
   ["Los teléfonos no están averiados.","El DNS de los PCs no afecta a los teléfonos.","STP no tiene relación."]],

  ["5.3","e","vlan,incorrect-assignment",
   "Two PCs are configured in the same IP subnet but are plugged into switch ports in different VLANs. They cannot ping each other. Why?",
   "They are in different broadcast domains",
   ["Their MAC addresses are identical","The switch has too many ports","ICMP is only allowed in VLAN 1"],
   "Aunque tengan IPs de la misma subred, cada VLAN es una red separada: sus tramas no se ven.",
   ["No tienen la misma MAC.","El número de puertos no influye.","No existe esa restricción."]],

  ["5.3","m","acl,implicit-deny",
   "After a new ACL that permits only HTTP and HTTPS is applied to a server VLAN, users can no longer resolve names. Why?",
   "The implicit deny blocks DNS (port 53)",
   ["DNS only works over HTTPS","The DNS server needs a new IP","The ACL encrypts DNS so it fails"],
   "Todo lo que no se permite expresamente se deniega: la ACL también bloquea DNS.",
   ["DNS normal usa el 53.","La IP del servidor no cambió.","Las ACLs no cifran."]],

  ["5.3","h","acl,direction",
   "An ACL intended to block traffic from the guest VLAN to the servers was applied, but guest traffic still reaches the servers. The rules are correct. What is a likely mistake?",
   "Wrong interface or wrong direction",
   ["The ACL is too short to match guests","The guest VLAN has no DHCP","The servers use jumbo frames"],
   "Una ACL correcta en la interfaz o el sentido equivocados no filtra el tráfico que se quería.",
   ["La longitud no es el problema.","DHCP no afecta a la ACL.","Las jumbo frames no afectan al filtrado."]],

  ["5.3","h","acl,stateless",
   "A stateless ACL on a router permits outbound web requests, but pages never load. What is the MOST likely problem?",
   "Return traffic is not permitted (no state)",
   ["DNS is using TCP instead of UDP","The web server has too many users","The ACL is stateful and blocks replies"],
   "Una ACL sin estado no recuerda las conexiones: hay que permitir también las respuestas, o usar un firewall stateful.",
   ["DNS no explica que no carguen las páginas.","El problema está en el filtrado.","Si fuera stateful, dejaría pasar las respuestas."]],

  ["5.3","m","routing,missing-route",
   "Users in the main office cannot reach a new branch subnet, but can reach everything else. The router's table has no entry for the branch network. What is the problem?",
   "A missing route to the branch subnet",
   ["A duplex mismatch","A rogue DHCP server at the branch","An incorrect SSID"],
   "Sin una ruta hacia esa red (estática o aprendida por un protocolo dinámico), el router no sabe cómo llegar.",
   ["El dúplex no explica que falte una red concreta.","Un DHCP falso afectaría a las IPs de los clientes.","El SSID es de Wi-Fi."]],

  ["5.3","m","routing,default-route",
   "Internal subnets can reach each other, but nobody can reach the internet. The edge router has no default route. What should be added?",
   "A default route to the ISP",
   ["A DHCP reservation","A new VLAN for internet users","A PTR record for the router"],
   "Sin ruta por defecto, el router no sabe adónde enviar los destinos de internet.",
   ["DHCP no da rutas a los routers.","Una VLAN no da salida a internet.","Un PTR es un registro de DNS inverso."]],

  ["5.3","m","routing,next-hop",
   "A static route points to a next-hop address that is not on any of the router's connected networks. What is the MOST likely result?",
   "The route is not usable because the next hop is unreachable",
   ["The route becomes the default route","Traffic is load-balanced automatically","The router assigns the next-hop IP to itself so it can reach it"],
   "Si el siguiente salto no es alcanzable, el router no puede usar esa ruta y el tráfico no llega.",
   ["No se convierte en la ruta por defecto.","No hay reparto de carga.","El router no se asigna IPs ajenas."]],

  ["5.3","h","routing,loop",
   "A traceroute to a remote server shows the same two routers repeating until the trace ends with 'TTL expired'. What is the problem?",
   "A routing loop between those two routers",
   ["A DNS failure","A duplex mismatch","DHCP scope exhaustion on both routers"],
   "Cada router cree que el camino pasa por el otro: el paquete va y viene hasta que el TTL llega a 0.",
   ["DNS no produce saltos repetidos.","El dúplex no produce bucles de enrutamiento.","DHCP no afecta al enrutamiento."]],

  ["5.3","h","routing,asymmetric",
   "Traffic leaves a site through Firewall A but the replies return through Firewall B, and the connections are dropped. What is the likely issue?",
   "Asymmetric routing past a stateful firewall",
   ["A DNS poisoning attack","Jumbo frames enabled on the WAN interfaces","An incorrect SSID on the WAN"],
   "Con enrutamiento asimétrico la ida y la vuelta van por caminos distintos. Un firewall stateful descarta respuestas de conexiones que no vio empezar.",
   ["No hay indicios de un ataque de DNS.","Las jumbo frames no causan esto.","El SSID es de Wi-Fi."]],

  ["5.3","h","routing,longest-prefix",
   "All traffic to 10.50.0.0/16 should go to Router A, but traffic to 10.50.8.0/24 unexpectedly goes to Router B. What explains this?",
   "A more specific /24 route points to Router B",
   ["Router B has a higher IP address","Router A is running OSPF","The /16 route has a lower administrative distance"],
   "El prefijo más largo (/24) gana siempre sobre el más corto (/16), tenga la AD que tenga.",
   ["La IP del router no influye.","El protocolo no cambia la regla del prefijo más largo.","La AD solo desempata prefijos idénticos."]],

  ["5.3","m","dhcp,exhaustion",
   "On Monday morning, newly arriving laptops get 169.254.x.x addresses while those that connected earlier work fine. What is the MOST likely cause?",
   "The DHCP scope is exhausted",
   ["The DNS server is down","The default gateway is wrong","The switch is using jumbo frames"],
   "Si los primeros equipos obtienen IP y los siguientes caen en APIPA, se han agotado las direcciones del ámbito DHCP.",
   ["Sin DNS habría IP, pero no se resolverían nombres.","Un gateway erróneo no provoca APIPA.","Las jumbo frames no afectan a DHCP."]],

  ["5.3","m","dhcp,exhaustion",
   "Which actions help resolve DHCP address pool exhaustion?",
   "Enlarge the scope and shorten leases",
   ["Lengthen the lease time to 30 days","Disable DHCP and use APIPA","Add a second DNS server to the scope"],
   "Más direcciones disponibles y préstamos más cortos hacen que siempre haya IPs libres.",
   ["Préstamos más largos agravan el problema.","APIPA no permite salir de la red local.","DNS no afecta a la cantidad de IPs."]],

  ["5.3","e","gateway,incorrect",
   "A host can ping other hosts on its subnet but cannot reach any remote network. Its IP and mask are correct. What should be checked first?",
   "The default gateway setting",
   ["The monitor cable","The printer driver","The DNS MX record"],
   "Si lo local funciona y lo remoto no, lo primero es comprobar el gateway, que es la puerta de salida de la subred.",
   ["El monitor no afecta a la red.","El driver de impresora no tiene relación.","Un MX es para correo."]],

  ["5.3","m","gateway,incorrect",
   "A host is configured as 192.168.10.25/24 with a default gateway of 192.168.20.1. What is the problem?",
   "The gateway is outside the host's subnet",
   ["The host's IP address is a broadcast address","The mask should be /8 for private IPs","Nothing; this configuration is valid"],
   "El gateway tiene que estar en la misma subred que el equipo (192.168.10.x). 192.168.20.1 es otra red.",
   ["La .25 no es broadcast.","Cambiar a /8 no es la solución correcta.","No es una configuración válida."]],

  ["5.3","e","ip,duplicate",
   "A PC shows a warning about an IP address conflict and loses its connection intermittently. What is the problem?",
   "Another device has the same IP",
   ["The cable is too long","The SSID is hidden from the PC","The DNS TTL is too short"],
   "Una IP duplicada provoca cortes intermitentes: cada equipo 'se roba' la dirección según quién respondió al último ARP.",
   ["La longitud del cable no causa conflictos de IP.","El SSID no causa conflictos de IP.","El TTL de DNS no afecta."]],

  ["5.3","m","ip,duplicate",
   "How can a technician confirm which devices are fighting over a duplicate IP address?",
   "Check the ARP table for one IP with changing MACs",
   ["Check the SSID list near the PC","Run a cable certifier on both ports that report the conflict","Look at the DNS MX record"],
   "Si una IP aparece asociada a MACs distintas en la tabla ARP (o en los logs del switch), hay dos equipos usándola.",
   ["El SSID no muestra IPs duplicadas.","El certificador prueba cables.","El MX es de correo."]],

  ["5.3","h","ip,subnet-mask",
   "A host is configured as 10.1.1.50 with mask 255.255.255.128 (/25), but the network is actually 10.1.0.0/23. What is a likely symptom?",
   "It treats some local hosts as remote",
   ["The host cannot power on its NIC","The host gets a 169.254 address","Nothing, masks do not matter"],
   "Con una máscara más larga de la debida, el equipo cree que su red es más pequeña: envía al gateway lo que es local, o no puede llegar a parte de la red.",
   ["La máscara no afecta al encendido.","Una IP estática no cae en APIPA.","La máscara es crucial."]],

  ["5.3","h","ip,subnet-mask",
   "The network is 172.16.0.0/22, but one server was configured with a /24 mask. Which hosts will the server have trouble reaching directly?",
   "Hosts in 172.16.1.x, 172.16.2.x and 172.16.3.x",
   ["Only hosts in 172.16.0.x","Hosts on the internet only","No hosts at all, because the mask is ignored"],
   "Con /24 el servidor solo considera local 172.16.0.x. Los otros bloques del /22 los manda al gateway o no los alcanza, aunque en realidad son locales.",
   ["Esos sí los ve como locales.","El problema es local, no de internet.","Sí habrá problemas."]],

  ["5.3","e","dns,resolution",
   "A user can ping 8.8.8.8 but cannot open any website by name. What is the MOST likely problem?",
   "DNS resolution",
   ["The default gateway","The physical cable","The switch's VLAN"],
   "Si llega a una IP de internet, la red y el gateway funcionan. Que fallen los nombres apunta a DNS.",
   ["El ping a internet prueba que el gateway funciona.","El cable funciona, porque el ping llega.","La VLAN funciona, porque el ping llega."]],

  ["5.3","m","dns,misconfigured",
   "A workstation's DNS server is set to 192.168.1.200, which does not exist. What will the user experience?",
   "Names fail, but IP connectivity works",
   ["The PC gets an APIPA address","The link light turns off","Only printing fails on that PC"],
   "Con un DNS inexistente no se resuelven nombres, aunque la conectividad por IP funcione.",
   ["La IP del equipo no depende del DNS.","El enlace físico no depende del DNS.","Afecta a todo lo que use nombres."]],

  ["5.3","h","dhcp,relay",
   "A new VLAN 30 was created with its SVI and DHCP scope, but its clients receive 169.254.x.x addresses. Other VLANs work. What is MOST likely missing?",
   "A DHCP relay on the VLAN 30 SVI",
   ["A DNS server for VLAN 30","A trunk from VLAN 30 to the internet","A second DHCP scope for VLAN 10"],
   "El servidor DHCP está en otra red. Sin relay en la interfaz de la VLAN 30, los broadcasts DHCP no llegan al servidor.",
   ["DNS no da direcciones IP.","Un trunk a internet no tiene relación.","La VLAN 10 ya funciona."]],

  ["5.3","m","firewall,dns",
   "After a firewall rule change, users can browse by IP address but not by name. What did the change MOST likely block?",
   "Outbound DNS traffic on port 53",
   ["TCP 443","ICMP","Inbound SMB on port 445"],
   "Si los nombres no se resuelven pero las IPs funcionan, se ha bloqueado DNS (el 53).",
   ["Bloquear 443 impediría HTTPS también por IP.","Bloquear ICMP solo afecta al ping.","SMB es compartición de archivos."]],

  ["5.3","m","nat",
   "After switching to a new ISP, internal users have no internet access. The router's default route is correct, but the NAT rule still references the old public interface. What is the problem?",
   "NAT is not translating on the new interface",
   ["DHCP is exhausted on the LAN","The VLAN database is missing on the edge","STP is blocking the uplink"],
   "Sin NAT, las IPs privadas salen tal cual y nadie en internet puede responder.",
   ["DHCP no tiene relación con la traducción.","Las VLANs no están implicadas.","STP no es el problema."]],

  ["5.3","m","ip-config",
   "Which of the following are symptoms of an incorrect subnet mask on a host? (Choose TWO)",
   ["Some hosts on the local network cannot be reached directly","Traffic to local hosts is sent to the default gateway"],
   ["The link light turns off","The PC cannot boot","The monitor goes blank"],
   "Una máscara errónea hace que el equipo se equivoque al decidir qué es local y qué es remoto.",
   ["La máscara no afecta al enlace físico.","No afecta al arranque.","No afecta al monitor."]],

  ["5.3","m","apipa",
   "Which of the following could cause a Windows PC to receive a 169.254.x.x address? (Choose TWO)",
   ["The DHCP server is unreachable","The DHCP scope has no free addresses"],
   ["The DNS server is down","The default gateway is wrong","The browser cache is full"],
   "APIPA aparece cuando el equipo pide IP por DHCP y nadie le da una: servidor inalcanzable o sin direcciones libres.",
   ["DNS no asigna IPs.","El gateway viene en la oferta DHCP; no provoca APIPA.","La caché del navegador no tiene relación."]],

  ["5.3","h","routing,return-path",
   "A server is reachable from subnet A but not from subnet B, even though B's router has a route to the server. What should be checked on the server's side?",
   "The return path to subnet B, routes and ACLs",
   ["The server's monitor resolution","Whether subnet B uses jumbo frames","The SSID used by subnet A clients"],
   "La comunicación necesita ida y vuelta. Si falta la ruta de regreso o una ACL la bloquea, la respuesta nunca llega.",
   ["La pantalla no influye.","Las jumbo frames no explican esto.","El SSID no tiene relación."]],

  ["5.3","m","icmp,firewall",
   "A web server does not respond to ping, but its website loads normally. What is the MOST likely explanation?",
   "A firewall is blocking ICMP",
   ["The server is powered off","DNS is broken for the site","The cable is unplugged"],
   "Muchos firewalls bloquean ICMP. Que la web cargue demuestra que el servidor está encendido y alcanzable.",
   ["Si estuviera apagado, la web no cargaría.","Si DNS fallara, la web no cargaría por nombre.","Si estuviera desconectado, nada funcionaría."]],

  ["5.3","m","vlan,wireless",
   "Wireless clients on a newly installed AP receive IP addresses from the wrong subnet. The AP's switch port is an access port in VLAN 1. What should be changed?",
   "Put the AP's switch port in the correct VLAN or trunk",
   ["Change the AP's antenna to a directional one","Enable jumbo frames on the AP's switch port and uplink","Disable DHCP on the AP's VLAN"],
   "El AP pasa el tráfico a la VLAN de su puerto. Si el puerto está mal configurado, los clientes caen en la red equivocada.",
   ["La antena no afecta a la subred.","Las jumbo frames no afectan.","Sin DHCP los clientes no obtendrían IP."]],

  ["5.3","m","vlan,svi",
   "Hosts in VLAN 40 can reach each other but nothing outside their VLAN. The Layer 3 switch shows the VLAN 40 SVI as administratively down. What is the fix?",
   "Enable the VLAN 40 SVI (their gateway)",
   ["Replace all the host cables","Change the hosts' DNS server","Create a new DHCP scope for VLAN 10"],
   "La SVI es el gateway de la VLAN. Si está apagada, los hosts no pueden salir de su red.",
   ["Los cables funcionan: los hosts se ven entre ellos.","DNS no afecta a llegar a otras redes por IP.","La VLAN 10 no está implicada."]],

  ["5.3","h","stp,topology-change",
   "Users experience brief network slowdowns several times a day. Logs show frequent STP topology change notifications caused by a port that goes up and down constantly. What is the likely impact of those notifications?",
   "Switches flush MAC tables and flood",
   ["DNS records are deleted","DHCP scopes are reset","VLANs are removed and re-created"],
   "Cada cambio de topología hace que los switches vacíen sus tablas MAC: mientras las reaprenden, inundan tráfico. Hay que arreglar ese puerto inestable (o marcarlo como edge si es de un equipo final).",
   ["STP no toca DNS.","STP no toca DHCP.","STP no borra VLANs."]],

  ["5.3","m","dhcp,options",
   "After a DHCP change, every newly connected client gets the correct IP but cannot leave the subnet. Existing clients are fine. What is the MOST likely cause?",
   "The scope's gateway option is wrong",
   ["The switch ports failed","The DNS TTL is too short","STP was disabled on the access switch"],
   "Los clientes nuevos reciben la opción de gateway errónea; los antiguos aún conservan la correcta de su préstamo anterior.",
   ["Si los puertos fallaran, no tendrían IP.","El TTL de DNS no afecta a la salida de la subred.","Un problema de STP afectaría a todos por igual."]],

  ["5.3","m","hosts-file",
   "One user always reaches an old intranet server even though DNS returns the new address to everyone else. What should be checked on the user's PC?",
   "The local hosts file",
   ["The user's monitor cable","The switch PoE budget","The SSID in use"],
   "El archivo hosts se consulta normalmente antes que DNS. Una entrada antigua ahí gana a la respuesta correcta de DNS.",
   ["El cable del monitor no afecta.","PoE no tiene relación.","El SSID no tiene relación."]],

  ["5.3","m","dhcp,dns-option",
   "Users who connected today cannot resolve names, but users who connected last week can. Which DHCP setting was MOST likely changed incorrectly?",
   "The DNS server option in the scope",
   ["The lease time","The exclusion range","The scope's router (gateway) option"],
   "Los nuevos clientes recibieron un DNS erróneo; los antiguos aún usan el que les dio su préstamo anterior.",
   ["El tiempo de préstamo no afecta a los nombres.","Las exclusiones no afectan a DNS.","Un gateway erróneo impediría salir de la red, no solo resolver nombres."]],

  ["5.3","m","wired,vlan",
   "Wireless users on a floor work normally, but wired users on the same floor cannot reach the internal servers. What is the MOST likely area to investigate?",
   "The wired ports' switch config (VLAN or ACLs)",
   ["The Wi-Fi channel plan on that floor","The RADIUS server's certificate for 802.1X","The AP's antenna type"],
   "Si el Wi-Fi funciona y el cable no, el problema está en la parte cableada: VLAN de los puertos, trunk o ACLs.",
   ["El plan de canales solo afecta al Wi-Fi.","RADIUS no explica que falle solo la parte cableada.","La antena solo afecta al Wi-Fi."]],

  ["5.3","m","routing,traceroute",
   "A traceroute from a PC to a remote server stops responding right after the first hop, which is the default gateway. What does this suggest?",
   "The problem is at or beyond the gateway",
   ["The PC's cable is broken","The PC's IP address is wrong","The DNS server is down for the PC"],
   "Si el primer salto (el gateway) responde, la conexión local funciona. El fallo está en el gateway o más allá.",
   ["Si el cable estuviera roto, ni el gateway respondería.","Con una IP errónea normalmente no llegaría al gateway.","Traceroute a una IP no depende de DNS."]],

  ["5.3","h","routing,default-route",
   "Users in several VLANs can reach each other and the data center, but not the internet. Only the Layer 3 core switch routes between VLANs. What should be checked first on the core switch?",
   "Whether it has a default route pointing to the internet edge",
   ["Whether the users' PCs have monitors","Whether the Wi-Fi SSID is hidden","Whether the patch panels in every closet are labeled correctly"],
   "Si lo interno funciona y solo falla internet, lo primero es comprobar la ruta por defecto del equipo que enruta.",
   ["Los monitores no tienen relación.","El SSID no tiene relación.","Las etiquetas no afectan al enrutamiento."]],

  ["5.3","h","fhrp,duplicate",
   "Hosts lose connectivity intermittently. Two routers are both claiming the same virtual gateway IP as active because their FHRP settings do not match. What is the issue?",
   "An FHRP misconfiguration",
   ["A DNS poisoning attack on the hosts","A PoE budget problem on the switch","A cable category mismatch"],
   "Si los dos routers creen ser el activo, la VIP responde desde dos sitios y el tráfico se pierde de forma intermitente.",
   ["No es un problema de DNS.","PoE no tiene relación.","El cable no causa dos gateways activos."]],

  ["5.3","m","dhcp,overlap",
   "Two DHCP servers were accidentally configured with the same address range for one subnet. What problem will appear?",
   "Duplicate IP addresses assigned to different clients",
   ["Faster address assignment with no issues","All clients receive APIPA addresses from both servers","DNS stops working"],
   "Cada servidor reparte sin saber lo que dio el otro, así que acaban asignando la misma IP a dos equipos.",
   ["Hay conflictos.","Sí reciben IPs, pero duplicadas.","DNS no se ve afectado directamente."]],

  ["5.3","e","ip,static",
   "A user's laptop has a static IP from their home network (192.168.0.50) and cannot connect at the office, where the network is 10.20.0.0/16. What is the BEST fix?",
   "Set the laptop to use DHCP",
   ["Change the office network to 192.168.0.0","Replace the laptop's network card","Disable the office firewall"],
   "Con la configuración automática, el portátil recibe una IP válida en cada red a la que se conecta.",
   ["No se cambia toda la red por un portátil.","La tarjeta funciona bien.","El firewall no es el problema."]],

  ["5.3","m","gateway,invalid",
   "A host in 192.168.5.0/24 has its default gateway set to 192.168.5.0. What is wrong?",
   ".0 is the network address, not a usable host",
   ["Nothing; the network address is the gateway","The gateway must be 255.255.255.0","The gateway must be a public IP"],
   "La dirección de red (.0) no se puede asignar a ningún equipo. El gateway debe ser una IP de host válida, por ejemplo .1.",
   ["La dirección de red no puede ser el gateway.","Eso es una máscara, no una dirección.","El gateway es una IP local de la subred."]],

  ["5.3","m","internet,edge",
   "All hosts can ping their default gateway but none can ping 8.8.8.8. Where is the problem MOST likely?",
   "At the edge: default route, NAT or ISP link",
   ["On every host's network card","In the DNS server only, since names fail","In the access switch VLANs"],
   "Si todos llegan al gateway y nadie sale, el problema es común a todos y está en el borde: enlace del ISP, NAT o ruta por defecto.",
   ["No fallan todas las tarjetas a la vez.","El ping a una IP no depende de DNS.","Las VLANs funcionan, porque llegan al gateway."]],

  ["5.3","m","dns,public-resolver",
   "Laptops that were manually configured to use a public DNS resolver cannot resolve 'intranet.corp.local', while other PCs can. Why?",
   "Public resolvers do not know internal zones",
   ["Public DNS blocks all web traffic","The laptops' cables are too long","The intranet uses IPv6 only, not IPv4"],
   "Los nombres internos solo los conoce el DNS interno. Un resolver público de internet no puede responderlos.",
   ["El DNS público no bloquea tráfico.","El cable no afecta a la resolución.","No hay indicios de IPv6."]],

  ["5.4","m","performance,throughput",
   "What is the difference between bandwidth and throughput?",
   "Bandwidth is capacity; throughput is what actually gets through",
   ["They are always identical on wired links","Throughput is always higher than bandwidth on a healthy link","Bandwidth measures delay between two hosts"],
   "El ancho de banda es la capacidad teórica del enlace; el throughput es lo que realmente se consigue transferir.",
   ["El throughput suele ser menor.","No puede superar la capacidad.","El retardo es la latencia."]],

  ["5.4","e","performance,latency",
   "What does latency measure?",
   "The time data takes to reach its destination",
   ["The amount of data transferred per second","The variation in delay between packets of the same stream","The percentage of packets lost"],
   "La latencia es el retardo: cuánto tarda un paquete en llegar (o en ir y volver, si se mide el RTT).",
   ["Eso es el throughput.","Eso es el jitter.","Eso es la pérdida de paquetes."]],

  ["5.4","e","performance,jitter",
   "What is jitter?",
   "Variation in packet delay",
   ["Total data transferred","Lost packets","Signal strength variation"],
   "El jitter es la variación del retardo entre paquetes. La voz y el vídeo lo sufren mucho.",
   ["Eso es el volumen de datos.","Eso es la pérdida.","Eso es la intensidad de señal."]],

  ["5.4","e","performance,packet-loss",
   "VoIP calls have words missing and gaps in the audio. Which performance issue is MOST likely?",
   "Packet loss",
   ["Too much bandwidth","DNS misconfiguration","An incorrect SSID"],
   "La voz va por UDP y no se retransmite: un paquete perdido es un trozo de audio que falta.",
   ["Tener ancho de banda de sobra no causa cortes.","DNS no afecta a una llamada ya establecida.","El SSID no causa huecos en el audio."]],

  ["5.4","m","performance,congestion",
   "Every afternoon when backups run, users' applications become slow and interface utilization reaches 100%. What is the problem?",
   "Congestion on the link",
   ["A duplex mismatch","DNS poisoning","A wrong subnet mask"],
   "Cuando la demanda supera la capacidad, el tráfico se acumula en las colas: aumentan la latencia y la pérdida.",
   ["El dúplex no depende de la hora.","No hay indicios de ataque.","La máscara no provoca lentitud por horas."]],

  ["5.4","m","performance,bottleneck",
   "A server has a 10 Gbps NIC and the core is 40 Gbps, but the branch WAN link is 100 Mbps. Branch users see slow file downloads from the server. What is limiting them?",
   "The 100 Mbps WAN link",
   ["The server's 10 Gbps network card","The 40 Gbps core","The users' monitors"],
   "El rendimiento de extremo a extremo lo marca el enlace más lento del camino.",
   ["10 Gbps no es el límite aquí.","El core tiene capacidad de sobra.","El monitor no influye."]],

  ["5.4","h","performance,oversubscription",
   "An access switch has 48 users at 1 Gbps each and a single 1 Gbps uplink. What is the likely performance issue at peak times?",
   "Uplink oversubscription",
   ["Too many VLANs on the uplink","Jumbo frames on the uplink","PoE budget exhaustion"],
   "48 Gbps de demanda posible contra 1 Gbps de subida es una sobresuscripción de 48:1. En hora punta el uplink se satura.",
   ["El número de VLANs no limita el ancho de banda.","Las jumbo frames no causan esto.","PoE es energía, no ancho de banda."]],

  ["5.4","m","performance,qos",
   "A congested WAN link carries VoIP, video conferencing and bulk file transfers. What should be configured so calls stay clear?",
   "QoS prioritizing voice and video",
   ["Larger DHCP scopes","A new SSID for voice traffic only","Longer patch cables"],
   "QoS da prioridad al tráfico sensible (voz, vídeo) cuando hay congestión.",
   ["DHCP no prioriza tráfico.","Un SSID no prioriza tráfico cableado.","El cable no prioriza nada."]],

  ["5.4","m","performance,latency",
   "Which type of application is MOST affected by high latency?",
   "Real-time voice and video calls",
   ["Overnight bulk backups","Email delivery between servers","Software updates downloaded in the background"],
   "En una conversación en tiempo real, el retardo se nota enseguida. Los procesos en segundo plano lo toleran mejor.",
   ["Las copias nocturnas toleran bien el retardo.","El correo tolera el retardo.","Las descargas en segundo plano lo toleran."]],

  ["5.4","h","performance,jitter-buffer",
   "How do VoIP endpoints reduce the effect of jitter?",
   "They use a jitter buffer to smooth playback",
   ["They switch to TCP for reliability and retransmission","They increase the DHCP lease time","They disable encryption"],
   "El buffer de jitter guarda los paquetes unos milisegundos para reproducirlos a ritmo constante, a costa de añadir algo de retardo.",
   ["TCP añadiría más retardo.","DHCP no tiene relación.","El cifrado no causa jitter."]],

  ["5.4","h","performance,packet-loss,tcp",
   "Why does even small packet loss significantly reduce throughput for large TCP transfers?",
   "TCP retransmits and slows down after loss",
   ["TCP ignores lost packets and keeps sending","Packet loss increases bandwidth","UDP retransmits TCP packets"],
   "TCP interpreta la pérdida como congestión: reenvía lo perdido y baja su ritmo de envío.",
   ["TCP sí detecta y corrige la pérdida.","La pérdida no aumenta la capacidad.","UDP no retransmite nada."]],

  ["5.4","m","performance,contention",
   "Why does adding many clients to one AP reduce each client's throughput even with a strong signal?",
   "Clients share half-duplex airtime",
   ["Each client doubles the AP's bandwidth","Wi-Fi is full duplex for every client","More clients reduce interference"],
   "En Wi-Fi solo puede transmitir uno a la vez en cada canal: cuantos más clientes, menos tiempo de aire para cada uno.",
   ["No se suma capacidad.","Wi-Fi comparte el medio.","Más clientes significan más contención."]],

  ["5.4","m","performance,throughput",
   "A speed test between two PCs on a 1 Gbps link shows about 400 Mbps. What should the technician consider?",
   "Overhead, disk, CPU or other traffic limit it",
   ["The cable must be fiber for 1 Gbps","The link is running at 10 Gbps","Throughput always equals bandwidth"],
   "El throughput real depende de más cosas que el enlace: sobrecarga de los protocolos, disco, CPU y otros tráficos.",
   ["El cobre soporta 1 Gbps.","Es un enlace de 1 Gbps.","Rara vez son iguales."]],

  ["5.4","m","wireless,co-channel",
   "A survey shows five APs on channel 6 in the same area of the 2.4 GHz band. What is the likely performance problem?",
   "Co-channel interference",
   ["Too little DHCP scope for the APs","A duplex mismatch on the AP ports","Too many VLANs on the APs"],
   "Varios APs en el mismo canal y en la misma zona compiten por el medio. Hay que repartirlos entre 1, 6 y 11 o pasar a 5 GHz.",
   ["DHCP no afecta a la capacidad del canal.","El dúplex no aplica a Wi-Fi.","Las VLANs no afectan al canal."]],

  ["5.4","e","wireless,signal",
   "Users at the far end of an office see a weak Wi-Fi signal and slow speeds. What is the MOST likely cause?",
   "Distance and obstacles weaken signal",
   ["A DNS failure at that end","An incorrect subnet mask","A switching loop on the AP's switch"],
   "La señal se debilita con la distancia y con paredes, puertas y muebles. Menos señal significa menos velocidad.",
   ["DNS no depende de la distancia.","La máscara no depende de la distancia.","Un bucle afectaría a todos, no solo a los lejanos."]],

  ["5.4","h","wireless,rssi",
   "Which RSSI reading indicates the strongest, most usable Wi-Fi signal?",
   "−55 dBm",
   ["−70 dBm","−80 dBm","−90 dBm"],
   "El RSSI se mide en dBm negativos: cuanto más cerca de 0, más fuerte. −55 es una señal buena; −80 o −90 son muy débiles.",
   ["−70 es aceptable, pero más débil que −55.","−80 es débil.","−90 prácticamente no sirve."]],

  ["5.4","h","wireless,snr",
   "An AP shows a good signal of −60 dBm, but clients still perform poorly. The noise floor is −65 dBm. What is the issue?",
   "An SNR of 5 dB is far too low",
   ["The signal is too strong","The SSID name is too long","The DHCP lease is too short"],
   "Lo que importa es la diferencia entre la señal y el ruido (SNR, Signal-to-Noise Ratio). 5 dB es muy poco; se buscan 20–25 dB o más.",
   ["−60 dBm no es demasiado fuerte.","La longitud del SSID no importa.","DHCP no tiene relación."]],

  ["5.4","e","wireless,coverage",
   "A warehouse has areas where devices lose Wi-Fi completely. A survey confirms there is no usable signal there. What is the BEST fix?",
   "Add or move APs to cover dead zones",
   ["Hide the SSID in those areas of the warehouse","Switch the APs to WEP","Shorten the DHCP lease"],
   "Si no llega la señal, hay que acercar la cobertura: más APs o mejor ubicados, o antenas adecuadas.",
   ["Ocultar el SSID no amplía la cobertura.","WEP es inseguro y no mejora la señal.","DHCP no mejora la cobertura."]],

  ["5.4","m","wireless,disassociation",
   "Laptops repeatedly disconnect and reconnect to the same AP throughout the day. Which could cause client disassociation?",
   "Interference, weak signal, power saving or deauths",
   ["A correct WPA3 configuration","A properly sized DHCP scope","A labeled patch panel in the closet nearest the AP"],
   "Las desconexiones repetidas pueden venir de interferencias, señal débil, ahorro de energía del cliente o incluso un ataque de desautenticación.",
   ["Una configuración correcta no provoca desconexiones.","Un DHCP correcto no provoca desconexiones.","Las etiquetas no afectan al Wi-Fi."]],

  ["5.4","m","wireless,roaming",
   "Users lose their connection every time they walk from one wing to another. The APs in each wing use different SSIDs. What is the problem?",
   "APs with mismatched SSID or security settings",
   ["The users' laptops are too fast","DNS is not working in the other wing of the building","The switches are using STP"],
   "Con SSIDs distintos, el portátil tiene que cambiar de red al moverse. Para un roaming fluido, todos los APs deben anunciar la misma red.",
   ["La velocidad del portátil no importa.","DNS no causa cortes al moverse.","STP no afecta al roaming inalámbrico."]],

  ["5.4","h","wireless,sticky-client",
   "A laptop stays connected to a distant AP with a weak signal instead of moving to a much closer AP. What is this, and what can help?",
   "A sticky client; raise minimum data rates",
   ["A rogue DHCP server; enable DHCP snooping","A duplex mismatch; hard-code full duplex","DNS poisoning; enable DNSSEC"],
   "Un cliente 'pegajoso' no se cambia de AP. Subir las tasas mínimas o usar funciones de ayuda al roaming lo empuja hacia un AP más cercano.",
   ["No es un problema de DHCP.","El dúplex no aplica a Wi-Fi.","No es un problema de DNS."]],

  ["5.4","h","wireless,power",
   "APs are set to maximum transmit power. Users report poor performance and clients connecting to far-away APs. What is a likely fix?",
   "Reduce AP transmit power",
   ["Increase power further on all APs","Hide all SSIDs to reduce beacons","Disable 5 GHz on every AP"],
   "Demasiada potencia crea celdas enormes que se solapan: más interferencia y clientes enganchados a APs lejanos.",
   ["Más potencia empeora el problema.","Ocultar los SSID no cambia la cobertura.","5 GHz suele ayudar, no empeorar."]],

  ["5.4","m","wireless,density",
   "One AP in a lecture hall serves 150 students, and everyone reports slow Wi-Fi despite a strong signal. What is the BEST fix?",
   "Add APs based on user capacity",
   ["Increase the DHCP lease time","Use a hidden SSID for students","Replace WPA3 with WEP"],
   "Con buena señal pero muchos usuarios, el problema es la capacidad: hacen falta más APs para repartir a los clientes.",
   ["El tiempo de préstamo no aumenta la capacidad.","Ocultar el SSID no ayuda.","WEP es inseguro y no aporta capacidad."]],

  ["5.4","h","wireless,legacy",
   "Why can a few very old 802.11b clients slow down a 2.4 GHz network for everyone?",
   "Their low data rates hog airtime",
   ["They use 6 GHz and cause interference","They encrypt with WPA3","They disable QoS on the AP"],
   "Los clientes lentos ocupan el canal mucho más tiempo por cada trama, y el resto tiene que esperar.",
   ["802.11b es de 2.4 GHz.","802.11b no soporta WPA3.","No desactivan QoS."]],

  ["5.4","e","performance,latency",
   "Which common tool measures round-trip latency to a host?",
   "ping",
   ["nslookup","ipconfig /release","A toner probe"],
   "ping muestra el tiempo de ida y vuelta (RTT) de cada respuesta.",
   ["nslookup consulta DNS.","ipconfig /release libera la IP.","Un toner sirve para localizar cables."]],

  ["5.4","m","performance,packet-loss",
   "Continuous pings to the branch router show 8% of replies timing out only during business hours. What is the MOST likely cause?",
   "Peak-hour WAN congestion",
   ["A wrong subnet mask","A missing MX record for the branch","An incorrect SSID at the branch"],
   "Pérdida que aparece solo en horas punta apunta a saturación: las colas se llenan y se descartan paquetes.",
   ["Una máscara errónea fallaría siempre.","Un MX es para correo.","El SSID es de Wi-Fi."]],

  ["5.4","h","performance,voip",
   "Which jitter value is generally considered the upper limit for good VoIP quality?",
   "About 30 ms",
   ["About 300 ms","About 3 seconds","Jitter does not affect VoIP"],
   "Como referencia habitual para la voz: jitter por debajo de unos 30 ms, latencia de ida por debajo de unos 150 ms y pérdida por debajo del 1 %.",
   ["300 ms de jitter haría la voz inentendible.","3 segundos es inaceptable.","El jitter afecta mucho a la voz."]],

  ["5.4","m","performance,congestion",
   "Which of the following help resolve a congested WAN link? (Choose TWO)",
   ["Upgrade the link bandwidth","Apply QoS to prioritize critical traffic"],
   ["Disable STP","Use WEP","Shorten patch cables"],
   "Se puede aumentar la capacidad y/o priorizar lo importante.",
   ["STP no afecta a la WAN, y quitarlo causaría bucles.","WEP es de Wi-Fi e inseguro.","El cable no amplía la WAN."]],

  ["5.4","m","wireless,coverage",
   "Which of the following help fix insufficient wireless coverage? (Choose TWO)",
   ["Add access points","Relocate APs or use antennas better suited to the space"],
   ["Hide the SSID","Switch to WEP","Increase the DHCP lease time"],
   "La cobertura se mejora con más APs o colocándolos y orientándolos mejor.",
   ["Ocultar el SSID no amplía la señal.","WEP es inseguro.","DHCP no mejora la cobertura."]],

  ["5.4","m","performance,capacity",
   "A switch's ports are all 1 Gbps, but performance problems appear when many servers transfer at once. The switch's forwarding capacity is lower than the sum of its ports. What limits performance?",
   "The switch's backplane or forwarding rate",
   ["The DNS server configuration","The SSID of nearby APs","The rack diagram for the wiring closet"],
   "Si el switch no puede mover a la vez todo lo que llega por sus puertos, su capacidad de conmutación se convierte en el cuello de botella.",
   ["DNS no mueve tráfico.","El SSID es de Wi-Fi.","El diagrama es documentación."]],

  ["5.4","h","performance,microbursts",
   "Average utilization on a link is only 30%, yet the interface shows output drops. What could explain this?",
   "Microbursts that briefly exceed capacity",
   ["The cable is too short","DNS is too slow for the link speed","The VLAN ID is too high"],
   "Las medias de 5 minutos esconden picos de milisegundos que llenan los buffers y provocan descartes.",
   ["La longitud corta no causa descartes.","DNS no descarta tramas.","El número de VLAN no importa."]],

  ["5.4","h","performance,bufferbloat",
   "Latency rises from 20 ms to over 500 ms whenever a large upload runs, even though no packets are lost. What is a likely cause?",
   "Bufferbloat",
   ["Missing default route","Wrong subnet mask","Expired certificate"],
   "Buffers muy grandes guardan muchos paquetes en cola: no se pierden, pero esperan mucho, así que la latencia se dispara.",
   ["Sin ruta no habría conexión.","La máscara no depende de la carga.","Un certificado no afecta a la latencia."]],

  ["5.4","m","performance,bottleneck",
   "Users at a branch report that video training streams keep buffering, while email works fine. What should be checked first?",
   "The branch WAN link utilization",
   ["The branch's DNS MX record","The printer drivers on user PCs","The switch's rack position"],
   "El vídeo necesita un ancho de banda sostenido; si el enlace WAN está al límite, es el primer sospechoso.",
   ["El MX es de correo, y el correo funciona.","Los drivers de impresora no tienen relación.","La posición del rack no importa."]],

  ["5.4","m","performance,isp",
   "A branch's internet link is 500 Mbps down and 20 Mbps up. Users complain that video calls freeze when they share their screens. Why?",
   "The 20 Mbps upload is saturated",
   ["The download speed is too high","DNS is overloaded by video calls","The patch cables are Cat 6"],
   "Compartir pantalla y enviar vídeo consume subida. Con solo 20 Mbps de subida para toda la sede, se satura.",
   ["La bajada no es el problema.","DNS no afecta al vídeo en curso.","Cat 6 no es un problema."]],

  ["5.4","m","wireless,2.4ghz",
   "In a crowded apartment building, a user's 2.4 GHz-only laptop is very slow while 5 GHz devices perform well. Why?",
   "2.4 GHz has few clean channels and many neighbors",
   ["2.4 GHz has more channels than 5 GHz, so it is crowded","5 GHz is always congested","The laptop's cable is broken"],
   "2.4 GHz solo tiene 3 canales sin solapamiento y los comparten todos los vecinos. En 5 GHz hay muchos más canales.",
   ["Es al revés.","5 GHz suele estar menos congestionado.","El portátil está usando Wi-Fi, no cable."]],

  ["5.4","e","wireless,signal",
   "As a user walks away from an AP, what typically happens to their connection?",
   "The signal weakens and the data rate drops",
   ["The data rate increases","The IP address changes to a public address","The SSID changes automatically"],
   "Con menos señal, el cliente y el AP bajan a velocidades más lentas y robustas.",
   ["La velocidad baja, no sube.","La IP no cambia por la distancia.","El SSID no cambia."]],

  ["5.4","m","wireless,obstacles",
   "Signal is poor behind metal shelving and concrete walls in a warehouse. Why?",
   "Metal and concrete reflect and absorb RF",
   ["Metal amplifies Wi-Fi signals","Concrete improves roaming between APs","Obstacles only affect wired networks"],
   "El metal refleja la señal y el hormigón la absorbe: detrás de ellos queda mucha menos cobertura.",
   ["El metal no amplifica, refleja.","El hormigón empeora la señal.","Los obstáculos afectan al Wi-Fi."]],

  ["5.4","h","wireless,roaming",
   "VoIP calls on Wi-Fi drop briefly every time a user moves between APs using WPA2-Enterprise. Which feature reduces the reauthentication delay?",
   "Fast roaming (802.11r)",
   ["A hidden SSID","WEP encryption","Longer DHCP leases"],
   "802.11r permite que el cliente cambie de AP sin repetir la autenticación completa, lo que evita los cortes en las llamadas.",
   ["Ocultar el SSID no acelera el roaming.","WEP es inseguro.","Los préstamos DHCP no afectan al cambio de AP."]],

  ["5.4","m","performance,ping",
   "A continuous ping shows replies of 20 ms, 25 ms, 200 ms, 22 ms and 180 ms, with no timeouts. Which problem does this indicate?",
   "High jitter",
   ["Packet loss","A DNS failure","An incorrect gateway"],
   "No hay pérdidas, pero el retardo varía mucho de un paquete a otro: eso es jitter.",
   ["No hay tiempos agotados.","El ping a una IP no depende de DNS.","Con un gateway erróneo no habría respuestas."]],

  ["5.4","h","wireless,contention",
   "Which access method do Wi-Fi clients use to avoid transmitting at the same time on a shared channel?",
   "CSMA/CA (collision avoidance)",
   ["CSMA/CD (collision detection)","Token passing","STP"],
   "Wi-Fi usa CSMA/CA (Carrier Sense Multiple Access with Collision Avoidance): escucha antes de hablar y espera turnos para evitar colisiones.",
   ["CSMA/CD es del Ethernet antiguo en half duplex.","El paso de testigo es de tecnologías antiguas como Token Ring.","STP evita bucles en switches."]],

  ["5.4","m","wireless,interference",
   "An apartment user's Wi-Fi is slow at night, and a scan shows 15 neighboring networks on the same channels. What is the BEST action?",
   "Use a less crowded channel or 5/6 GHz",
   ["Increase the DHCP lease time","Hide the SSID from neighbors","Switch the router to WEP"],
   "Cambiar a un canal más libre o a una banda con más canales reduce la interferencia de las redes vecinas.",
   ["DHCP no reduce interferencias.","Ocultar el SSID no cambia el canal.","WEP es inseguro."]],

  ["5.4","m","performance,server-bottleneck",
   "Hundreds of users download files from one server with a single 1 Gbps NIC, and all downloads are slow while the network core is barely used. What is the bottleneck?",
   "The server's network interface",
   ["The core switches","The users' monitors","The DNS server"],
   "Si el core está libre pero el servidor tiene una sola tarjeta de 1 Gbps para cientos de usuarios, su interfaz es el cuello de botella.",
   ["El core está casi libre.","Los monitores no influyen.","DNS no limita las descargas."]],

  ["5.4","m","performance,cpu",
   "Pings to a router's interface show high, variable latency, and the router's CPU is at 99%. What is the likely cause of the delay?",
   "The overloaded router is slow to respond",
   ["The cable is too short","The SSID is hidden on the router's wireless side","DHCP leases are too long"],
   "Un router con la CPU al límite tarda en procesar y responder, así que aumenta la latencia.",
   ["La longitud corta no causa retardo.","El SSID no afecta a un router cableado.","DHCP no carga así la CPU."]],

  ["5.4","m","performance,jitter",
   "What commonly causes jitter on a busy network?",
   "Varying queuing delays as traffic levels change",
   ["A correctly configured QoS policy on the WAN edge","Using fiber instead of copper","A DHCP reservation"],
   "Cuando el tráfico sube y baja, las colas se llenan y se vacían, y cada paquete espera un tiempo distinto.",
   ["QoS bien configurado reduce el jitter.","La fibra no causa jitter.","DHCP no tiene relación."]],

  ["5.4","h","performance,voip,latency",
   "What is the commonly recommended maximum one-way latency for good VoIP call quality?",
   "About 150 ms",
   ["About 5 ms","About 1 second","About 5 seconds"],
   "Por encima de unos 150 ms de ida, las conversaciones empiezan a notarse retrasadas y los interlocutores se pisan.",
   ["5 ms es excelente, no el límite.","1 segundo es demasiado.","5 segundos es inutilizable."]],
];

export default q;
