import type { Raw } from '../types';

// 5.3 (+4) · 5.5 Tools and protocols to solve networking issues (60)
const q: Raw[] = [
  ["5.3","m","vlan,trunk,troubleshooting",
   "After a switch replacement, users in VLAN 20 on the new switch cannot reach VLAN 20 hosts elsewhere. The uplink trunk's allowed VLAN list was configured as 1-10. What is the fix?",
   "Add VLAN 20 to the trunk's allowed VLAN list",
   ["Change the users' DNS server","Enable jumbo frames on the access ports","Replace the users' patch cables"],
   "El trunk solo transporta las VLANs permitidas. Si la 20 no está en la lista, su tráfico no cruza.",
   ["DNS no impide que el tráfico cruce el trunk.","Las jumbo frames no tienen relación.","Los cables funcionan con el resto de VLANs."]],

  ["5.3","m","ip-config,moved-server",
   "A server with a static IP from the old server VLAN was moved to a switch port in the new server VLAN. Nobody can reach it. What is the problem?",
   "Its IP address and gateway still belong to the old VLAN's subnet",
   ["The server needs a longer cable","DNS records never need updating","The switch port must be a trunk to the internet for servers"],
   "Al cambiar de VLAN, el servidor cambia de red: su IP estática y su gateway deben actualizarse a la nueva subred (y también su registro DNS).",
   ["El cable no es el problema.","Precisamente el DNS también hay que actualizarlo.","No tiene nada que ver con un trunk."]],

  ["5.3","m","routing,default-route",
   "The edge router has a default route, but internet access fails. The route's next hop is the IP of an old ISP router that was removed. What should be done?",
   "Point the default route to the new ISP gateway",
   ["Delete all internal routes","Enable DHCP on the WAN interface of the edge router","Disable NAT on the WAN interface"],
   "Una ruta por defecto que apunta a un siguiente salto que ya no existe no sirve: hay que apuntarla al gateway actual del ISP.",
   ["Las rutas internas funcionan.","DHCP no corrige una ruta estática errónea por sí mismo.","Quitar NAT empeoraría la salida."]],

  ["5.3","m","monitoring,icmp",
   "The monitoring system reports a file server as down, but users can open its shares normally. A new ACL was recently applied to the server VLAN. What is the MOST likely explanation?",
   "The ACL blocks ICMP pings but allows SMB",
   ["The server is powered off","SMB uses ICMP for file transfers","The switch lost its VLAN database"],
   "Si los usuarios acceden y el ping falla, el servidor está vivo: la nueva ACL bloquea el ICMP que usa la monitorización.",
   ["Si estuviera apagado, nadie accedería.","SMB usa TCP 445, no ICMP.","Sin VLANs, los usuarios tampoco accederían."]],

  ["5.5","e","tools,ping",
   "Which command checks whether a host is reachable and measures round-trip time?",
   "ping",
   ["nslookup","netstat","arp"],
   "ping envía ICMP Echo Request y espera Echo Reply: dice si el host responde y cuánto tarda.",
   ["nslookup consulta DNS.","netstat muestra conexiones y puertos.","arp muestra la caché de IP a MAC."]],

  ["5.5","e","tools,traceroute",
   "Which tool shows each router hop along the path to a destination?",
   "traceroute / tracert",
   ["ipconfig","nslookup","netstat"],
   "traceroute lista cada salto del camino y cuánto tarda en responder cada uno.",
   ["ipconfig muestra la configuración IP local.","nslookup consulta DNS.","netstat muestra conexiones."]],

  ["5.5","e","tools,tracert",
   "What is the Windows command equivalent to the Linux traceroute command?",
   "tracert",
   ["trace","pathfinder","route print"],
   "En Windows es tracert; en Linux y macOS, traceroute.",
   ["trace no es el comando estándar de Windows.","pathfinder no existe como comando.","route print muestra la tabla de rutas."]],

  ["5.5","m","tools,traceroute",
   "A traceroute to a server shows replies for hops 1 through 5 and then only asterisks. What does this suggest?",
   "The issue is at or beyond the sixth hop",
   ["The local PC's patch cable is broken","DNS is not working on the PC","The first router is down"],
   "Los primeros saltos responden, así que el camino funciona hasta ahí. A partir de ahí hay un fallo o un equipo que no responde a las sondas.",
   ["Con el cable roto no respondería ni el salto 1.","Traceroute a una IP no depende de DNS.","El primer router respondió."]],

  ["5.5","e","tools,nslookup",
   "Which command is commonly used on Windows to query DNS and check what IP a hostname resolves to?",
   "nslookup",
   ["tracert","arp -a","ipconfig /release"],
   "nslookup pregunta a un servidor DNS y muestra la respuesta.",
   ["tracert muestra saltos.","arp -a muestra la caché ARP.","ipconfig /release libera la IP."]],

  ["5.5","m","tools,dig",
   "Which Linux tool provides detailed DNS query output, including flags, TTLs and the answering server?",
   "dig",
   ["ping","ifconfig","netstat"],
   "dig (Domain Information Groper) muestra las respuestas DNS con mucho detalle.",
   ["ping mide la alcanzabilidad.","ifconfig muestra interfaces.","netstat muestra conexiones."]],

  ["5.5","m","tools,dig",
   "Which command lists the mail servers for example.com on a Linux system?",
   "dig example.com MX",
   ["ping example.com MX","netstat example.com","arp example.com"],
   "Con dig se indica el tipo de registro. MX devuelve los servidores de correo del dominio.",
   ["ping no consulta tipos de registro.","netstat no consulta DNS.","arp no consulta DNS."]],

  ["5.5","e","tools,ipconfig",
   "Which Windows command shows a PC's IP address, subnet mask, gateway, DNS servers and MAC address?",
   "ipconfig /all",
   ["ping /all","tracert /all","netstat -r"],
   "ipconfig /all muestra toda la configuración IP de cada adaptador, incluida la MAC.",
   ["ping no tiene esa opción.","tracert no tiene esa opción.","netstat -r muestra la tabla de rutas."]],

  ["5.5","e","tools,ipconfig",
   "A Windows PC has an APIPA address. Which commands make it request a new DHCP lease?",
   "ipconfig /release, then /renew",
   ["ping 169.254.1.1 -t","nslookup /renew followed by ping","arp -d then tracert"],
   "/release libera la dirección actual y /renew pide una nueva al servidor DHCP.",
   ["ping no pide IPs.","nslookup es para DNS.","Borrar la caché ARP no pide IP."]],

  ["5.5","m","tools,ipconfig",
   "A website moved to a new IP, and a user's PC still uses the old one. Which Windows command clears the PC's DNS resolver cache?",
   "ipconfig /flushdns",
   ["ipconfig /renew","arp -a","netstat -an"],
   "/flushdns vacía la caché DNS local para que el equipo vuelva a preguntar.",
   ["/renew pide una IP nueva, no borra la caché DNS.","arp -a muestra la caché ARP.","netstat muestra conexiones."]],

  ["5.5","e","tools,linux",
   "Which Linux commands display a host's IP address configuration?",
   "ip addr or ifconfig",
   ["ipconfig /all","tracert","nslookup -all"],
   "En Linux se usa ip addr; ifconfig es el comando antiguo.",
   ["ipconfig es de Windows.","tracert es de Windows y muestra saltos.","nslookup consulta DNS."]],

  ["5.5","m","tools,linux,routing",
   "Which Linux command displays the host's routing table?",
   "ip route",
   ["ip addr","dig","arp -a"],
   "ip route muestra las rutas del equipo, incluida la ruta por defecto (el gateway).",
   ["ip addr muestra las direcciones.","dig consulta DNS.","arp -a muestra la caché ARP."]],

  ["5.5","e","tools,arp",
   "Which command shows the local ARP cache, mapping IP addresses to MAC addresses?",
   "arp -a",
   ["ping -a","netstat -an","nslookup"],
   "arp -a muestra qué MAC corresponde a cada IP conocida en la red local.",
   ["ping -a intenta resolver el nombre de la IP.","netstat -an muestra conexiones.","nslookup consulta DNS."]],

  ["5.5","e","tools,netstat",
   "Which command lists a host's active connections and listening ports?",
   "netstat",
   ["ipconfig","tracert","nslookup"],
   "netstat muestra las conexiones abiertas y los puertos en escucha del equipo.",
   ["ipconfig muestra la configuración IP.","tracert muestra saltos.","nslookup consulta DNS."]],

  ["5.5","m","tools,netstat",
   "A new web service does not respond. Which command confirms on the server itself whether anything is listening on TCP 443?",
   "netstat -an (look for LISTENING)",
   ["tracert localhost 443","nslookup localhost 443 (check the port)","arp -a (look for 443)"],
   "netstat -an muestra los puertos en escucha. Si el 443 no aparece, el servicio no está escuchando.",
   ["tracert no comprueba puertos locales.","nslookup es para DNS.","arp no tiene relación con puertos."]],

  ["5.5","m","tools,tcpdump",
   "Which command-line tool captures packets on a Linux interface?",
   "tcpdump",
   ["ipconfig","nslookup","tracert"],
   "tcpdump captura y muestra paquetes desde la consola. Sus capturas se pueden abrir después en Wireshark.",
   ["ipconfig es de Windows y no captura.","nslookup consulta DNS.","tracert muestra saltos."]],

  ["5.5","e","tools,protocol-analyzer",
   "Which tool decodes captured packets field by field so an engineer can see exactly what each protocol sent?",
   "Protocol analyzer",
   ["Toner probe","Cable tester","Light meter"],
   "Un analizador de protocolos muestra cada paquete decodificado capa por capa.",
   ["El toner localiza cables.","El cable tester prueba conductores.","El medidor de luz mide la potencia óptica."]],

  ["5.5","e","tools,nmap",
   "Which tool scans hosts to discover which ports are open and which services are running?",
   "Nmap",
   ["nslookup","ipconfig","tracert"],
   "Nmap descubre equipos, puertos abiertos y servicios en la red.",
   ["nslookup consulta DNS.","ipconfig muestra la configuración local.","tracert muestra saltos."]],

  ["5.5","m","tools,nmap",
   "Before going live, an administrator wants to verify that only TCP 22 and 443 are open on a new server. Which tool is BEST?",
   "Nmap port scan",
   ["ping","arp -a","A toner probe"],
   "Un escaneo de puertos con Nmap muestra exactamente qué puertos responden.",
   ["ping no revisa puertos TCP.","arp no revisa puertos.","El toner es para cables."]],

  ["5.5","m","tools,lldp",
   "A technician needs to find which switch and port a VoIP phone is connected to, without tracing the cable. Which protocol information helps?",
   "LLDP/CDP neighbor data",
   ["DNS PTR records","DHCP lease time","SMTP headers"],
   "LLDP y CDP anuncian quién está conectado a cada puerto: nombre del switch, puerto y tipo de dispositivo.",
   ["Un PTR da nombres, no puertos.","El tiempo de préstamo no ayuda.","SMTP es correo."]],

  ["5.5","m","tools,lldp,cdp",
   "What is the key difference between LLDP and CDP?",
   "LLDP is a vendor-neutral standard; CDP is Cisco proprietary",
   ["CDP works across routers on the internet, LLDP only locally","LLDP only works on wireless","They carry IP routes between routers"],
   "Los dos descubren vecinos directos. LLDP (IEEE 802.1AB) es estándar; CDP es de Cisco.",
   ["Ninguno cruza routers: solo ven vecinos directos.","LLDP funciona en redes cableadas.","No son protocolos de enrutamiento."]],

  ["5.5","e","tools,speed-test",
   "A branch reports slow internet. Which tool measures the actual upload and download throughput of the connection?",
   "Speed tester",
   ["Cable tester","Toner probe","arp -a"],
   "Un speed tester mide la velocidad real de subida y bajada.",
   ["El cable tester comprueba el cableado.","El toner localiza cables.","arp no mide velocidad."]],

  ["5.5","m","tools,speed-test,iperf",
   "An engineer runs a throughput test between a server in the data center and a laptop at a branch to measure the WAN link, not the internet. Which tool fits?",
   "A throughput tester such as iperf",
   ["nslookup with a timer","A visual fault locator","show vlan brief on the switch"],
   "Una herramienta cliente/servidor como iperf mide el rendimiento entre dos puntos concretos de tu propia red.",
   ["nslookup es DNS.","El VFL es para fibra.","show vlan muestra VLANs."]],

  ["5.5","e","tools,toner",
   "A technician must find which unlabeled cable in a bundle goes to a specific wall jack. Which tool helps?",
   "Toner and probe",
   ["Protocol analyzer","Speed tester","Nmap"],
   "Se conecta el generador de tono a la roseta y con la sonda se busca el cable que 'suena' en el armario.",
   ["El analizador trabaja con paquetes.","El speed tester mide velocidad.","Nmap escanea puertos."]],

  ["5.5","e","tools,cable-tester",
   "Which tool checks a copper cable for continuity, opens, shorts and correct pinout?",
   "Cable tester",
   ["Wi-Fi analyzer","Light meter","nslookup"],
   "Un cable tester verifica que cada hilo llega al pin correcto y que no hay cortes ni cortocircuitos.",
   ["El Wi-Fi analyzer es para redes inalámbricas.","El medidor de luz es para fibra.","nslookup es DNS."]],

  ["5.5","h","tools,cable-certifier",
   "What does a cable certifier do that a basic cable tester does not?",
   "Verifies the cable meets its category's specifications",
   ["Only checks that the cable is plugged in","Assigns IP addresses to the tested ports","Measures Wi-Fi signal along the cable run"],
   "El certificador mide parámetros eléctricos (diafonía, atenuación, pérdida de retorno) y confirma que el cable cumple su categoría, por ejemplo Cat 6a.",
   ["Eso es mucho menos de lo que hace.","No asigna IPs.","No mide Wi-Fi."]],

  ["5.5","m","tools,tap",
   "Which device is placed inline on a link to passively copy all traffic to a monitoring tool?",
   "Network TAP",
   ["Toner probe","Cable certifier","Light meter"],
   "Un TAP (Test Access Point) copia todo el tráfico del enlace hacia un analizador, sin interferir.",
   ["El toner localiza cables.","El certificador prueba cables.","El medidor de luz mide potencia óptica."]],

  ["5.5","e","tools,wifi-analyzer",
   "Which tool shows nearby wireless networks, their channels and signal strength?",
   "Wi-Fi analyzer",
   ["Cable tester","Toner probe","tracert"],
   "Un Wi-Fi analyzer muestra los SSID, los canales que usan, la intensidad de señal y los solapamientos.",
   ["El cable tester es para cobre.","El toner es para cables.","tracert muestra saltos IP."]],

  ["5.5","m","tools,vfl",
   "A fiber patch cord might be broken. Which simple tool shines a visible red light into the fiber to reveal breaks or sharp bends?",
   "Visual fault locator (VFL)",
   ["Toner probe","Multimeter","Wi-Fi analyzer"],
   "El VFL (Visual Fault Locator) inyecta luz roja visible: donde la fibra está rota o doblada, la luz se escapa y se ve.",
   ["El toner es para cobre.","El multímetro mide electricidad.","El Wi-Fi analyzer es para redes inalámbricas."]],

  ["5.5","h","tools,otdr",
   "A long outdoor fiber run is down. Which tool can determine how far along the cable the break is located?",
   "OTDR",
   ["Toner probe","Cable tester for copper","Speed tester"],
   "Un OTDR (Optical Time Domain Reflectometer) envía pulsos de luz y mide los reflejos para localizar a qué distancia está el fallo.",
   ["El toner es para cobre.","El cable tester de cobre no sirve para fibra.","El speed tester mide velocidad."]],

  ["5.5","m","tools,light-meter",
   "Which tool measures the optical power received on a fiber link to check whether loss is within limits?",
   "Optical power meter",
   ["Toner probe","Protocol analyzer","nslookup"],
   "El medidor de potencia óptica indica cuánta luz llega (en dBm) para compararlo con lo que necesita la óptica.",
   ["El toner es para cobre.","El analizador ve paquetes.","nslookup es DNS."]],

  ["5.5","h","tools,spectrum-analyzer",
   "Wi-Fi performance drops at certain times, but a Wi-Fi analyzer shows no other networks on the channel. Which tool can detect non-Wi-Fi interference such as microwaves or wireless cameras?",
   "Spectrum analyzer",
   ["Cable certifier","Toner probe","nslookup"],
   "El analizador de espectro ve toda la energía de radio en la banda, no solo las redes Wi-Fi. Así descubre microondas, cámaras u otros emisores.",
   ["El certificador es para cables.","El toner es para cables.","nslookup es DNS."]],

  ["5.5","m","tools,show-mac",
   "Which switch command shows which port a particular MAC address was learned on?",
   "show mac address-table",
   ["show route","show vlan","show power"],
   "La tabla MAC indica en qué puerto (y VLAN) se aprendió cada dirección MAC.",
   ["show route muestra las rutas.","show vlan muestra las VLANs y sus puertos.","show power muestra el consumo PoE."]],

  ["5.5","e","tools,show-route",
   "Which command displays a router's routing table?",
   "show route (show ip route)",
   ["show mac address-table","show vlan","show power"],
   "La tabla de rutas muestra las redes conocidas, cómo se aprendieron y el siguiente salto.",
   ["Ese comando muestra la tabla MAC.","Ese comando muestra las VLANs.","Ese comando muestra PoE."]],

  ["5.5","m","tools,show-interface",
   "Which command shows an interface's status, speed, duplex and error counters such as CRCs?",
   "show interface",
   ["show vlan","show arp","show route"],
   "show interface da el estado, la velocidad, el dúplex y los contadores de errores de cada puerto.",
   ["show vlan muestra las VLANs.","show arp muestra la tabla ARP.","show route muestra las rutas."]],

  ["5.5","e","tools,show-config",
   "Which command displays a device's current running configuration?",
   "show running-config",
   ["show power","show mac address-table","show arp"],
   "Muestra la configuración que el equipo está usando en ese momento.",
   ["show power muestra PoE.","Ese comando muestra la tabla MAC.","show arp muestra la tabla ARP."]],

  ["5.5","m","tools,show-arp",
   "On a router, which command shows the IP-to-MAC mappings it has learned for directly connected hosts?",
   "show arp",
   ["show vlan","show route","show power"],
   "show arp muestra la tabla ARP del router: qué MAC corresponde a cada IP de sus redes conectadas.",
   ["show vlan muestra las VLANs.","show route muestra las rutas.","show power muestra PoE."]],

  ["5.5","e","tools,show-vlan",
   "Which switch command lists the VLANs and the access ports assigned to each?",
   "show vlan",
   ["show route","show arp","show power"],
   "show vlan muestra las VLANs que existen y los puertos de acceso de cada una.",
   ["show route muestra las rutas.","show arp muestra la tabla ARP.","show power muestra PoE."]],

  ["5.5","m","tools,show-power",
   "Which switch command shows how much PoE power each port is drawing and the remaining power budget?",
   "show power (show power inline)",
   ["show vlan","show mac address-table","show route"],
   "show power muestra el consumo PoE por puerto y cuánto presupuesto queda.",
   ["show vlan no muestra energía.","La tabla MAC no muestra energía.","La tabla de rutas no muestra energía."]],

  ["5.5","m","tools,show-mac,scenario",
   "A technician knows a PC's MAC address and needs to find which switch port it uses. What should they do?",
   "Search show mac address-table for it",
   ["Run nslookup with the MAC","Check the DHCP lease time","Ping the MAC address from the switch"],
   "La tabla MAC del switch asocia cada MAC a un puerto.",
   ["nslookup no busca MACs.","El tiempo de préstamo no indica el puerto.","ping usa IPs, no MACs."]],

  ["5.5","m","tools,show-interface,scenario",
   "A server connection is slow, and a duplex mismatch is suspected. Which command confirms the negotiated speed and duplex on the switch side?",
   "show interface",
   ["show vlan","show arp","nslookup"],
   "show interface muestra la velocidad y el dúplex negociados, y los contadores de colisiones y errores que delatan el problema.",
   ["show vlan no muestra el dúplex.","show arp no muestra el dúplex.","nslookup es DNS."]],

  ["5.5","m","tools,show-power,scenario",
   "New cameras will not power on. Which command helps confirm whether the switch has run out of PoE budget?",
   "show power",
   ["show route","show vlan","tracert"],
   "show power muestra el presupuesto total, lo consumido y el estado de cada puerto PoE.",
   ["show route muestra las rutas.","show vlan muestra las VLANs.","tracert muestra saltos IP."]],

  ["5.5","e","tools,show-vlan,scenario",
   "A user's port may be in the wrong VLAN. Which command quickly shows the VLAN assignment of the access ports?",
   "show vlan",
   ["show power","show route","ping"],
   "show vlan muestra a qué VLAN pertenece cada puerto de acceso.",
   ["show power muestra PoE.","show route muestra las rutas.","ping no muestra VLANs."]],

  ["5.5","e","tools,ping,loopback",
   "What does a successful ping to 127.0.0.1 confirm?",
   "The local TCP/IP stack is working",
   ["The default gateway is reachable","DNS is working","The internet connection is up"],
   "El loopback no sale del equipo: solo prueba que la pila TCP/IP local funciona.",
   ["El gateway es otra dirección.","No usa DNS.","No sale a internet."]],

  ["5.5","m","tools,ping,methodology",
   "A user cannot reach the internet. After confirming the PC has a valid IP address, which ping test should come next?",
   "Ping the default gateway",
   ["Ping a server on another continent","Ping 255.255.255.255","Ping the user's own MAC address"],
   "Se avanza de cerca a lejos: si el gateway no responde, el problema es local; si responde, se sigue hacia fuera.",
   ["Saltar tan lejos no indica dónde está el fallo.","Es una dirección de broadcast.","ping no usa MACs."]],

  ["5.5","h","tools,traceroute,ttl",
   "How does traceroute discover each hop on the path?",
   "Increasing TTLs; each router replies ICMP Time Exceeded",
   ["It asks the DNS server for the path","It reads the switch MAC tables","It uses DHCP to request a route list from each router on the path"],
   "Con TTL 1 responde el primer router, con TTL 2 el segundo, y así sucesivamente: cada uno delata su posición.",
   ["DNS no conoce los caminos.","Las tablas MAC son locales de cada switch.","DHCP no da listas de rutas."]],

  ["5.5","h","tools,tcpdump",
   "Which tcpdump command captures only DNS traffic on interface eth0?",
   "tcpdump -i eth0 port 53",
   ["tcpdump -i eth0 port 80","tcpdump dns eth0 --all","tcpdump -r eth0 443"],
   "-i elige la interfaz y 'port 53' filtra el tráfico DNS.",
   ["El 80 es HTTP.","No es una sintaxis válida de tcpdump.","-r lee un archivo, y el 443 es HTTPS."]],

  ["5.5","h","tools,wireshark",
   "In Wireshark, an engineer wants to see only DNS packets in a large capture. What should they use?",
   "A display filter such as 'dns'",
   ["A cable tester","show vlan","A toner probe"],
   "Los filtros de visualización de Wireshark (por ejemplo, dns, http o ip.addr == 10.1.1.5) muestran solo lo que interesa.",
   ["El cable tester es hardware para cobre.","show vlan es un comando de switch.","El toner es para cables."]],

  ["5.5","h","tools,nmap",
   "Which Nmap capability attempts to identify the operating system of a remote host based on its responses?",
   "OS fingerprinting",
   ["DNS zone transfer","PoE budgeting","Channel bonding"],
   "Nmap puede estimar el sistema operativo analizando cómo responde el equipo a ciertos paquetes.",
   ["La transferencia de zona es de DNS.","PoE es energía.","Channel bonding es de Wi-Fi."]],

  ["5.5","m","tools,nmap,authorization",
   "Before running port scans against the company's servers, what should a technician obtain?",
   "Written authorization from the owner",
   ["A new IP address for the scanner","A longer patch cable to the core","The users' passwords"],
   "Escanear sin permiso puede violar políticas o leyes, y disparar alertas de seguridad. Siempre se pide autorización.",
   ["No hace falta una IP nueva.","El cable no tiene relación.","Nunca se piden las contraseñas de los usuarios."]],

  ["5.5","m","tools,dns",
   "Which of the following tools can be used to troubleshoot DNS resolution? (Choose TWO)",
   ["nslookup","dig"],
   ["Toner probe","Cable tester","show power"],
   "nslookup y dig consultan servidores DNS y muestran sus respuestas.",
   ["El toner es para cables.","El cable tester es para cables.","show power es PoE."]],

  ["5.5","m","tools,copper",
   "Which hardware tools are used to troubleshoot copper cabling? (Choose TWO)",
   ["Cable tester","Toner and probe"],
   ["Visual fault locator","OTDR","Wi-Fi analyzer"],
   "El cable tester comprueba el cable y el toner lo localiza.",
   ["El VFL es para fibra.","El OTDR es para fibra.","El Wi-Fi analyzer es para redes inalámbricas."]],

  ["5.5","m","tools,arp",
   "Which Windows command clears an entry from the ARP cache so the PC must relearn the MAC address?",
   "arp -d",
   ["arp -a","ipconfig /all","ping -t"],
   "arp -d elimina entradas de la caché ARP; arp -a solo las muestra.",
   ["arp -a solo muestra la caché.","ipconfig /all muestra la configuración.","ping -t hace un ping continuo."]],

  ["5.5","m","tools,loopback-plug",
   "A technician suspects a NIC or switch port is faulty. Which simple device loops the transmit pins back to the receive pins to test the port on its own?",
   "Loopback plug",
   ["Toner probe","Light meter","Wi-Fi analyzer"],
   "Un conector de loopback devuelve la señal al mismo puerto, así se prueba el puerto sin depender de otro equipo.",
   ["El toner localiza cables.","El medidor de luz mide potencia óptica.","El Wi-Fi analyzer es para redes inalámbricas."]],

  ["5.5","m","tools,speed-test",
   "A branch pays for 300 Mbps, but several speed tests at quiet times show about 90 Mbps. What is the reasonable next step?",
   "Contact the ISP with the test results",
   ["Replace all branch PCs with faster ones","Change the branch VLANs","Disable DNS"],
   "Si el enlace da mucho menos de lo contratado incluso sin carga, hay que escalar al ISP con los datos de las pruebas.",
   ["Los PCs no limitan el enlace de la sede.","Las VLANs no limitan el ISP.","Quitar DNS rompería la navegación."]],

  ["5.5","m","tools,wifi-analyzer",
   "Before configuring a new AP in a crowded office, how should a technician choose its channel?",
   "Use a Wi-Fi analyzer to find the least congested channel",
   ["Pick channel 6 every time","Use the same channel as the neighbors so clients can roam","Choose a channel based on the SSID name"],
   "El analizador muestra qué canales están ocupados y con qué intensidad, para elegir el más libre.",
   ["El 6 puede estar saturado.","Coincidir con los vecinos causa interferencia.","El nombre no tiene relación con el canal."]],

  ["5.5","m","tools,protocol-analyzer,tcp",
   "Users report slow file transfers. A protocol analyzer shows many TCP retransmissions and duplicate ACKs. What does this indicate?",
   "Packet loss somewhere on the path",
   ["The DNS server is fast","The link is underused by the clients","The files are too small"],
   "Retransmisiones y ACKs duplicados indican que se pierden segmentos por el camino.",
   ["DNS no tiene relación.","No indica que el enlace esté infrautilizado.","El tamaño de los archivos no causa retransmisiones."]],

  ["5.5","h","tools,linux,neighbor",
   "Which Linux command shows the IPv4 ARP / IPv6 neighbor cache?",
   "ip neigh",
   ["ip route","dig","ifconfig -r"],
   "ip neigh muestra la tabla de vecinos (ARP en IPv4, NDP en IPv6).",
   ["ip route muestra las rutas.","dig es DNS.","ifconfig no tiene esa opción."]],

  ["5.5","m","tools,netstat,security",
   "A workstation behaves strangely, and the technician suspects malware. Which command helps reveal unexpected connections to unknown external IPs?",
   "netstat -an",
   ["ipconfig /release","nslookup localhost","arp -d"],
   "netstat -an lista todas las conexiones abiertas; se ven conexiones raras hacia IPs desconocidas.",
   ["Liberar la IP no muestra conexiones.","nslookup no muestra conexiones.","arp -d borra la caché ARP."]],

  ["5.5","m","tools,traceroute",
   "In a traceroute output, one hop shows '* * *' but the following hops respond normally. What does this usually mean?",
   "That router forwards traffic but ignores probes",
   ["The path is completely broken at that hop","The destination server is down","DNS failed for that hop's name"],
   "Si los saltos posteriores responden, el tráfico pasa por ese router: simplemente no contesta a las sondas.",
   ["Si estuviera roto, los siguientes no responderían.","El destino responde al final.","traceroute a una IP no depende de DNS."]],
];

export default q;
